# SSMD and Matching Analysis of CDPHE vs Highest r.grf Choices

In [1]:
import copy
import functools
import glob
import pickle
import scipy
import sklearn
import warnings

warnings.filterwarnings('ignore')

import itertools
import graphviz as gr
import numpy as np
import os
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm


from matplotlib import style
from matplotlib import pyplot as plt
from pprint import pprint
from scipy import stats, special

from sklearn import datasets, mixture
from sklearn.covariance import EmpiricalCovariance
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler

from tqdm import tqdm

from urllib.request import urlopen
import json
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)

import plotly.express as px
import plotly.figure_factory as ff

%matplotlib inline

style.use("fivethirtyeight")
pd.set_option("display.max_columns", 6)

np.random.seed(0)
pd.set_option('display.max_columns', None)

### Set Directories

In [2]:
DATA_FOLDER = "../data"
FIGURES_FOLDER = "../figures"
OUTPUT_FOLDER = "../output"
NURSE_CORRECTION_FOLDER = os.path.join(DATA_FOLDER,"Case Study COVID County Matching Databases")

### Import County Fips master

In [3]:
county_fips_master_df = pd.read_csv(os.path.join(OUTPUT_FOLDER,"county_fips_master.csv"))
county_fips_master_df = county_fips_master_df[county_fips_master_df["state_abbr"]=="CO"]
county_fips_master_df.head()

,fips,county_name,state_abbr,state_name,long_name,sumlev,region,division,state,county,crosswalk,region_name,division_name
245,8001,Adams County,CO,Colorado,Adams County CO,50.0,4.0,8.0,8.0,1.0,4-8-8-1,West,Mountain
246,8003,Alamosa County,CO,Colorado,Alamosa County CO,50.0,4.0,8.0,8.0,3.0,4-8-8-3,West,Mountain
247,8005,Arapahoe County,CO,Colorado,Arapahoe County CO,50.0,4.0,8.0,8.0,5.0,4-8-8-5,West,Mountain
248,8007,Archuleta County,CO,Colorado,Archuleta County CO,50.0,4.0,8.0,8.0,7.0,4-8-8-7,West,Mountain
249,8009,Baca County,CO,Colorado,Baca County CO,50.0,4.0,8.0,8.0,9.0,4-8-8-9,West,Mountain

### Import Nursing Homes and Correctional Facilitiy Files

In [4]:
nursing_ts_df = pd.read_csv(os.path.join(NURSE_CORRECTION_FOLDER,"ReplicationData_TimeSeries_CO.csv"))
nursing_ts_df.head()

,Date,PROVNUM,PROVNAME,CITY,COUNTY,Case,ever_had_case,first_week,case_count_outbreak,case_count_CMS,Case_a,ever_had_case_a,first_week_a,homes_this,homes_last,homes_two,connections_this,connections_last,connections_two,homes_this_a,homes_last_a,homes_two_a,connections_this_a,connections_last_a,connections_two_a,OOS_homes,OOS_connections
0,19apr2020 00:00:00,065001,LOWRY HILLS CARE AND REHABILITATION,AURORA,Arapahoe County,1,1,19apr2020 00:00:00,4,0,1,1,19apr2020 00:00:00,1,0,0,2,0,0,1,0,0,2,0,0,0,0
1,19apr2020 00:00:00,065009,ST PAUL HEALTH CENTER,DENVER,Denver County,0,0,26apr2020 00:00:00,0,0,0,0,26apr2020 00:00:00,2,0,0,2,0,0,2,0,0,2,0,0,0,0
2,19apr2020 00:00:00,065015,MOUNTAIN VISTA HEALTH CENTER,WHEAT RIDGE,Jefferson County,1,1,19apr2020 00:00:00,5,0,1,1,19apr2020 00:00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19apr2020 00:00:00,065034,AMBERWOOD COURT REHABILITATION AND CARE COMMUNITY,DENVER,Denver County,1,1,19apr2020 00:00:00,10,0,1,1,19apr2020 00:00:00,4,0,0,9,0,0,4,0,0,9,0,0,0,0
4,19apr2020 00:00:00,065052,MESA VISTA OF BOULDER,BOULDER,Boulder County,1,1,19apr2020 00:00:00,15,0,1,1,19apr2020 00:00:00,1,0,0,1,0,0,1,0,0,1,0,0,1,1

In [5]:
nursing_cross_df = pd.read_csv(os.path.join(NURSE_CORRECTION_FOLDER,"ReplicationData_CrossSection.csv"))
nursing_cross_df = nursing_cross_df[nursing_cross_df["providerstate"]=="CO"].sort_values(by="Provider_ID")
nursing_cross_df.head()

,weekending,Provider_ID,providername,provideraddress,providercity,providerstate,providerzipcode,submitteddata,passedqualityassurancecheck,residentsweeklyadmissionscovid19,residentstotaladmissionscovid19,residentsweeklyconfirmedcovid19,CMS_ResidentsTotalConfirmed,residentsweeklysuspectedcovid19,residentstotalsuspectedcovid19,residentsweeklyalldeaths,residentstotalalldeaths,residentsweeklycovid19deaths,residentstotalcovid19deaths,numberofallbeds,totalnumberofoccupiedbeds,residentaccesstotestinginfacilit,laboratorytypeisstatehealthdept,laboratorytypeisprivatelab,laboratorytypeisother,staffweeklyconfirmedcovid19,stafftotalconfirmedcovid19,staffweeklysuspectedcovid19,stafftotalsuspectedcovid19,staffweeklycovid19deaths,stafftotalcovid19deaths,shortageofnursingstaff,shortageofclinicalstaff,shortageofaides,shortageofotherstaff,anycurrentsupplyofn95masks,oneweeksupplyofn95masks,anycurrentsupplyofsurgicalmasks,oneweeksupplyofsurgicalmasks,anycurrentsupplyofeyeprotection,oneweeksupplyofeyeprotection,anycurrentsupplyofgowns,oneweeksupplyofgowns,anycurrentsupplyofgloves,oneweeksupplyofgloves,anycurrentsupplyofhandsanitizer,oneweeksupplyofhandsanitizer,ventilatordependentunit,numberofventilatorsinfacility,numberofventilatorsinuseforcovid,anycurrentsupplyofventilatorsupp,oneweeksupplyofventilatorsupplie,totalresidentconfirmedcovid19cas,totalresidentcovid19deathsper100,totalresidentscovid19deathsasape,Building_ID,_ID,cleaned_address,phone,county_ssa,county_name,ownership,bedcert,restot,certification,inhosp,lbn,participation_date,ccrc_facil,sffstatus,abuse_icon,oldsurvey,chow_last_12mos,resfamcouncil,sprinkler_status,overall_rating,overall_rating_fn,survey_rating,survey_rating_fn,quality_rating,quality_rating_fn,ls_quality_rating,ls_quality_rating_fn,ss_quality_rating,ss_quality_rating_fn,staffing_rating,staffing_rating_fn,rn_staffing_rating,rn_staffing_rating_fn,staffing_flag,pt_staffing_flag,aidhrd,vochrd,rnhrd,totlichrd,tothrd,pthrd,cm_aide,cm_lpn,cm_rn,cm_total,adj_aide,adj_lpn,adj_rn,adj_total,weighted_all_cycles_score,incident_cnt,cmplnt_cnt,fine_cnt,fine_tot,payden_cnt,tot_penlty_cnt,State_Long,lat,lng,accuracy_check,Hand_Searched,building_match,building_match_convex,OSM_Building_Good,gisjoin,Links_Degree,Links_Strength,PrEigenVector1,degree_weeks_1_5,eigenvector_weeks_1_5,strength_weeks_1_5,weight_nghbr_degree_weeks_1_5,strength_days_weeks_1_5,degree_weeks_7_11,eigenvector_weeks_7_11,strength_weeks_7_11,weight_nghbr_degree_weeks_7_11,strength_days_weeks_7_11,degree_weeks_1_11,eigenvector_weeks_1_11,strength_weeks_1_11,weight_nghbr_degree_weeks_1_11,strength_days_weeks_1_11,FillIn,degree_cases,expsuminfectviol,count,shareblack,highblackshare,sharedual,highmedicaid,Unmatch,State_ResidentsPositive,May31_residents_deaths_state,May31_staff_pos_state,May31_staff_deaths_state,May31_datereport_state,May31_state,countyfipsstate,countyfipscounty,rstate,rcounty,FIPScode,codeurban2013,urban,forprofit,forprofit_ind,HasViolations,QualityAssuranceCheck,SurgicalMasks_OneWeekSupply,HandSanitizer_OneWeekSupply,HypArcSin_StateCases,CMS_ConfirmedPlusSuspected,HypArcSin_CMSCases,CMS_ConfirmedPlusSusp_01,State_ResidentsPositive_0_1,ratingdum1,ratingdum2,ratingdum3,ratingdum4,ratingdum5
1857,5/31/2020,06A088,LITTLE SISTERS OF THE POOR - MULLEN HOME,3629 W 29TH AVE,DENVER,CO,80211,Y,Y,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.0,37.0,Y,N,Y,N,0.0,0.0,0.0,0.0,0.0,0.0,N,N,N,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,0.0,0.0,NaN,Colorado_1926991,1889,"3629 W 29th Ave, Denver, CO 80211, USA",3034337221,150,Denver,Non profit - Corporation,42,40.500000,Medicaid,N,Legal Business Name Not Available,1975-05-01,N,NaN,N,N,N,Resident,Yes,5.0,NaN,5.0,NaN,3.0,NaN,3.0,NaN,NaN,2.0,5.0,NaN,5.0,NaN,NaN,NaN,3.39179,0.37251,1.28863,1.66114,5.05294,0.00000,1.69276,0.62319,0.27806,2.59401,4.16437,0.44947,1.74431,6.24633,8.000,0,0,0,0,0,0,Colorado,39.759281,-105.03612,ROOFTOP,0,0,0,1,G08003100003036,0.0,0.0,0.000000e+00,0,0.0,0,0.0,0,0,0.0,0,0.0,0,0,1.210000e-17,0,0.0,0,0,0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,CO,8.0,31.0,8.0,31.0,8031.0,1.0,1.0,Non,0,1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1875,5/31/2020,06A171,GOOD SAMARITAN SOCIETY SIMLA,320 PUEBLO AVE,SIMLA,CO,80835,Y,Y,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,27.0,Y,Y,N,N,0.0,0.0,0.0,0.0,0.0,0.0,N,N,N,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,0.0,0.0,NaN,Colorado_1133429,1806,"320 Pueblo Ave, Simla, CO 80835, USA",7195412269,190,Elbert,Non profit - Corporation,30,25.200001,Medicaid,N,Legal Business Name Not Available,1991-05-01,N,NaN,N,N,N,Resident,Yes,4.0,NaN,2.0,NaN,5.0,NaN,5.0,NaN,NaN,2.0,4.0,NaN,5.0,NaN,NaN,NaN,1.97220,0.20151,1.05657,1.25808,3.23028,0.00000,1.95508,0.60315,0.27076,2.82899,2.09654,0.25122,1.46875,3.66152,82.667,2,0,0,0,0,0,Colorado,39.141476,-104.08384,ROOFTOP,0,0,0,1,G08003909611002,NaN,NaN,NaN,0,0.0,0,0.0,0,0,0.0,0,0.0,0,0,0.000000e+00,0,0.0,0,1,0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,CO,8.0,39.0,8.0,39.0,8039.0,2.0,1.0,Non,0,1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1789,5/31/2020,06A172,"PARK FOREST CARE CENTER, INC.",7045 STUART ST,WESTMINSTER,CO,80030,Y,Y,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,87.0,Y,N,Y,N,0.0,0.0,0.0,0.0,0.0,0.0,N,N,N,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,0.0,0.0,NaN,Colorado_705108,1972,"7045 Stuart St, Westminster, CO 80030, USA",3034277045,0,Adams,For profit - Corporation,103,91.300003,Medicaid,N,Legal Business Name Not Available,1991-03-01,N,NaN,Y,N,N,Resident,Yes,3.0,NaN,2.0,NaN,3.0,NaN,3.0,NaN,NaN,2.0,4.0,NaN,4.0,NaN,NaN,NaN,1.76025,0.65711,0.59772,1.25483,3.01508,0.01134,1.55882,0.59721,0.26190,2.41793,2.34690,0.82737,0.85901,3.99862,88.333,0,6,0,0,0,0,Colorado,39.825001,-105.04346,ROOFTOP,0,1,1,1,G08000100096073,9.0,9.0,5.898085e-11,0,0.0,0,0.0,0,0,0.0,0,0.0,0,0,1.210000e-17,0,0.0,0,0,0,3.0,6.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,CO,8.0,1.0,8.0,1.0,8001.0,2.0,1.0,For,1,1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1993,5/31/2020,06A173,SEDGWICK COUNTY MEMORIAL NURSING HOME,901 CEDAR ST,JULESBURG,CO,80737,Y,Y,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,32.0,31.0,Y,N,Y,N,0.0,0.0,0.0,0.0,0.0,0.0,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,0.0,0.0,NaN,Colorado_1721446,1872,"901 Cedar St, Julesburg, CO 80737, USA",9704636163,570,Sedgwick,Government - County,32,29.799999,Medicaid,N,Legal Business Name Not Available,1991-06-01,N,NaN,N,N,N,Resident,Yes,1.0,NaN,2.0,NaN,1.0,NaN,1.0,NaN,NaN,2.0,1.0,12.0,1.0,12.0,NaN,NaN,2.54653,0.96139,0.22438,1.18577,3.73230,0.00345,1.74547,0.57910,0.23784,2.56242,3.03216,1.24832,0.35508,4.67067,51.667,0,1,0,0,0,0,Colorado,40.993534,-102.26916,ROOFTOP,0,0,0,1,G08011509683002,0.0,0.0,2.418332e-17,0,0.0,0,0.0,0,0,0.0,0,0.0,0,0,1.210000e-17,0,0.0,0,0,0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,CO,8.0,115.0,8.0,115.0,8115.0,6.0,0.0,Gov,0,0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1822,5/31/2020,06A175,WALSH HEALTHCARE CENTER,150 N NEVADA ST,WALSH,CO,81090,Y,Y,0.0,0.0,0.0,0.0,0.0,0.0,2.0,7.0,0.0,0.0,30.0,19.0,Y,Y,Y,Y,0.0,0.0,0.0,2.0,0.0,0.0,Y,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,0.0,0.0,NaN,Colorado_199145,1901,"150 N Nevada St, Walsh, CO 81090, USA",7193245262,40,Baca,Government - Hospital district,30,20.799999,Medicaid,N,Legal Business Name Not Available,1991-07-01,N,NaN,N,N,N,Resident,Yes,4.0,NaN,5.0,NaN,3.0,NaN,3.0,NaN,NaN,2.0,1.0,12.0,1.0,12.0,NaN,NaN,3.30712,1.36830,0.63537,2.00367,5.31079,0.00000,2.04703,0.62451,0.26723,2.93878,3.35769,1.64750,0.89488,5.79489,14.000,0,0,0,0,0,0,Colorado,37.384636,-102.28057,ROOFTOP,0,1,1,1,G08000909646001,0.0,0.0,0.000000e+00,0,0.0,0,0.0,0,1,0.0,1,2.0,2,1,8.900000e-18,1,2.0,2,0,0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,CO,8.0,9.0,8.0,9.0,8009.0,6.0,0.0,Gov,0,0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [6]:
prisons_df = pd.read_csv(os.path.join(NURSE_CORRECTION_FOLDER,"facilities.csv"))
prisons_df = prisons_df[prisons_df["facility_state"]=="Colorado"]
#prisons_df["total_inmate_cases"] = prisons_df["total_inmate_cases"].fillna(prisons_df["total_inmate_deaths"])
#prisons_df["max_inmate_population_2020"] = prisons_df["max_inmate_population_2020"].fillna(prisons_df["total_inmate_cases"])
#prisons_df["latest_inmate_population"] = prisons_df["latest_inmate_population"].fillna(prisons_df["max_inmate_population_2020"])
prisons_df.head()

,nyt_id,facility_name,facility_type,facility_city,facility_county,facility_county_fips,facility_state,facility_lng,facility_lat,latest_inmate_population,max_inmate_population_2020,total_inmate_cases,total_inmate_deaths,total_officer_cases,total_officer_deaths,note
158,84EB1D78,Arkansas Valley Correctional Facility,State prison,Ordway,Crowley,8025,Colorado,-103.839378,38.189140,1012.0,NaN,961,4,99,0.0,NaN
159,A2A88844,Arrowhead Correctional Center,State prison,Cañon City,Fremont,8043,Colorado,-105.156106,38.434831,352.0,528.0,360,1,52,0.0,NaN
160,03079583,Bent County Correctional Facility,State prison,Las Animas,Bent,8011,Colorado,-103.205579,38.065192,1264.0,NaN,1091,2,95,2.0,NaN
161,5057D4F9,Buena Vista Correctional Facility,State prison,Buena Vista,Chaffee,8015,Colorado,-106.117628,38.822007,892.0,1129.0,523,1,89,0.0,NaN
162,5E8ED28B,Centennial Correctional Facility,State prison,Cañon City,Fremont,8043,Colorado,-105.160995,38.422731,700.0,886.0,151,0,102,0.0,NaN

In [7]:
nursing_cross_df[nursing_cross_df["Provider_ID"] == ("065001")]

Empty DataFrame
Columns: [weekending, Provider_ID, providername, provideraddress, providercity, providerstate, providerzipcode, submitteddata, passedqualityassurancecheck, residentsweeklyadmissionscovid19, residentstotaladmissionscovid19, residentsweeklyconfirmedcovid19, CMS_ResidentsTotalConfirmed, residentsweeklysuspectedcovid19, residentstotalsuspectedcovid19, residentsweeklyalldeaths, residentstotalalldeaths, residentsweeklycovid19deaths, residentstotalcovid19deaths, numberofallbeds, totalnumberofoccupiedbeds, residentaccesstotestinginfacilit, laboratorytypeisstatehealthdept, laboratorytypeisprivatelab, laboratorytypeisother, staffweeklyconfirmedcovid19, stafftotalconfirmedcovid19, staffweeklysuspectedcovid19, stafftotalsuspectedcovid19, staffweeklycovid19deaths, stafftotalcovid19deaths, shortageofnursingstaff, shortageofclinicalstaff, shortageofaides, shortageofotherstaff, anycurrentsupplyofn95masks, oneweeksupplyofn95masks, anycurrentsupplyofsurgicalmasks, oneweeksupplyofsurgicalmasks, anycurrentsupplyofeyeprotection, oneweeksupplyofeyeprotection, anycurrentsupplyofgowns, oneweeksupplyofgowns, anycurrentsupplyofgloves, oneweeksupplyofgloves, anycurrentsupplyofhandsanitizer, oneweeksupplyofhandsanitizer, ventilatordependentunit, numberofventilatorsinfacility, numberofventilatorsinuseforcovid, anycurrentsupplyofventilatorsupp, oneweeksupplyofventilatorsupplie, totalresidentconfirmedcovid19cas, totalresidentcovid19deathsper100, totalresidentscovid19deathsasape, Building_ID, _ID, cleaned_address, phone, county_ssa, county_name, ownership, bedcert, restot, certification, inhosp, lbn, participation_date, ccrc_facil, sffstatus, abuse_icon, oldsurvey, chow_last_12mos, resfamcouncil, sprinkler_status, overall_rating, overall_rating_fn, survey_rating, survey_rating_fn, quality_rating, quality_rating_fn, ls_quality_rating, ls_quality_rating_fn, ss_quality_rating, ss_quality_rating_fn, staffing_rating, staffing_rating_fn, rn_staffing_rating, rn_staffing_rating_fn, staffing_flag, pt_staffing_flag, aidhrd, vochrd, rnhrd, totlichrd, tothrd, pthrd, cm_aide, cm_lpn, cm_rn, ...]
Index: []

In [8]:
nursing_CO_df = pd.merge(left=nursing_ts_df, right=nursing_cross_df, how="left", left_on="PROVNAME", right_on="providername")
#nursing_CO_df["numberofallbeds"] = nursing_CO_df["numberofallbeds"].fillna(nursing_CO_df["totalnumberofoccupiedbeds"])
nursing_CO_df

,Date,PROVNUM,PROVNAME,CITY,COUNTY,Case,ever_had_case,first_week,case_count_outbreak,case_count_CMS,Case_a,ever_had_case_a,first_week_a,homes_this,homes_last,homes_two,connections_this,connections_last,connections_two,homes_this_a,homes_last_a,homes_two_a,connections_this_a,connections_last_a,connections_two_a,OOS_homes,OOS_connections,weekending,Provider_ID,providername,provideraddress,providercity,providerstate,providerzipcode,submitteddata,passedqualityassurancecheck,residentsweeklyadmissionscovid19,residentstotaladmissionscovid19,residentsweeklyconfirmedcovid19,CMS_ResidentsTotalConfirmed,residentsweeklysuspectedcovid19,residentstotalsuspectedcovid19,residentsweeklyalldeaths,residentstotalalldeaths,residentsweeklycovid19deaths,residentstotalcovid19deaths,numberofallbeds,totalnumberofoccupiedbeds,residentaccesstotestinginfacilit,laboratorytypeisstatehealthdept,laboratorytypeisprivatelab,laboratorytypeisother,staffweeklyconfirmedcovid19,stafftotalconfirmedcovid19,staffweeklysuspectedcovid19,stafftotalsuspectedcovid19,staffweeklycovid19deaths,stafftotalcovid19deaths,shortageofnursingstaff,shortageofclinicalstaff,shortageofaides,shortageofotherstaff,anycurrentsupplyofn95masks,oneweeksupplyofn95masks,anycurrentsupplyofsurgicalmasks,oneweeksupplyofsurgicalmasks,anycurrentsupplyofeyeprotection,oneweeksupplyofeyeprotection,anycurrentsupplyofgowns,oneweeksupplyofgowns,anycurrentsupplyofgloves,oneweeksupplyofgloves,anycurrentsupplyofhandsanitizer,oneweeksupplyofhandsanitizer,ventilatordependentunit,numberofventilatorsinfacility,numberofventilatorsinuseforcovid,anycurrentsupplyofventilatorsupp,oneweeksupplyofventilatorsupplie,totalresidentconfirmedcovid19cas,totalresidentcovid19deathsper100,totalresidentscovid19deathsasape,Building_ID,_ID,cleaned_address,phone,county_ssa,county_name,ownership,bedcert,restot,certification,inhosp,lbn,participation_date,ccrc_facil,sffstatus,abuse_icon,oldsurvey,chow_last_12mos,resfamcouncil,sprinkler_status,overall_rating,overall_rating_fn,survey_rating,survey_rating_fn,quality_rating,quality_rating_fn,ls_quality_rating,ls_quality_rating_fn,ss_quality_rating,ss_quality_rating_fn,staffing_rating,staffing_rating_fn,rn_staffing_rating,rn_staffing_rating_fn,staffing_flag,pt_staffing_flag,aidhrd,vochrd,rnhrd,totlichrd,tothrd,pthrd,cm_aide,cm_lpn,cm_rn,cm_total,adj_aide,adj_lpn,adj_rn,adj_total,weighted_all_cycles_score,incident_cnt,cmplnt_cnt,fine_cnt,fine_tot,payden_cnt,tot_penlty_cnt,State_Long,lat,lng,accuracy_check,Hand_Searched,building_match,building_match_convex,OSM_Building_Good,gisjoin,Links_Degree,Links_Strength,PrEigenVector1,degree_weeks_1_5,eigenvector_weeks_1_5,strength_weeks_1_5,weight_nghbr_degree_weeks_1_5,strength_days_weeks_1_5,degree_weeks_7_11,eigenvector_weeks_7_11,strength_weeks_7_11,weight_nghbr_degree_weeks_7_11,strength_days_weeks_7_11,degree_weeks_1_11,eigenvector_weeks_1_11,strength_weeks_1_11,weight_nghbr_degree_weeks_1_11,strength_days_weeks_1_11,FillIn,degree_cases,expsuminfectviol,count,shareblack,highblackshare,sharedual,highmedicaid,Unmatch,State_ResidentsPositive,May31_residents_deaths_state,May31_staff_pos_state,May31_staff_deaths_state,May31_datereport_state,May31_state,countyfipsstate,countyfipscounty,rstate,rcounty,FIPScode,codeurban2013,urban,forprofit,forprofit_ind,HasViolations,QualityAssuranceCheck,SurgicalMasks_OneWeekSupply,HandSanitizer_OneWeekSupply,HypArcSin_StateCases,CMS_ConfirmedPlusSuspected,HypArcSin_CMSCases,CMS_ConfirmedPlusSusp_01,State_ResidentsPositive_0_1,ratingdum1,ratingdum2,ratingdum3,ratingdum4,ratingdum5
0,19apr2020 00:00:00,065001,LOWRY HILLS CARE AND REHABILITATION,AURORA,Arapahoe County,1,1,19apr2020 00:00:00,4,0,1,1,19apr2020 00:00:00,1,0,0,2,0,0,1,0,0,2,0,0,0,0,5/31/2020,65001,LOWRY HILLS CARE AND REHABILITATION,10201 E THIRD AVE,AURORA,CO,80010.0,Y,Y,0.0,2.0,0.0,7.0,1.0,16.0,0.0,4.0,0.0,3.0,102.0,62.0,Y,Y,Y,N,0.0,6.0,2.0,20.0,0.0,0.0,N,N,N,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,112.90000,48.400002,42.900002,Colorado_607866,1958.0,"10201 E 3rd Ave, Aurora, CO 80010, USA",3.033643e+09,0.0,Adams,For profit - Corporation,108.0,77.300003,Medicare and Medicaid,N,SWEETWATER AURORA OPCO LLC,1968-09-19,N,SFF Candidate,Y,N,N,Resident,Yes,1.0,NaN,1.0,NaN,2.0,NaN,3.0,NaN,1.0,NaN,3.0,NaN,3.0,NaN,NaN,NaN,1.67186,0.58307,0.56687,1.14994,2.82180,0.06861,1.88075,0.65816,0.29222,2.83114,1.84750,0.66615,0.73014,3.19608,378.000,0.0,15.0,0.0,0.0,2.0,2.0,Colorado,39.720669,-104.86890,ROOFTOP,0.0,1.0,1.0,1.0,G08000500072012,1.0,2.0,2.051249e-12,2.0,0.079673,3.0,6.333334,28.0,1.0,0.000751,1.0,5.00,14.0,2.0,8.057516e-02,3.0,15.333333,49.0,0.0,45.0,3.0,5.0,0.289474,1.0,0.605263,1.0,0.0,9.0,2.0,15.0,NaN,5/27/20,CO,8.0,5.0,8.0,5.0,8005.0,2.0,1.0,For,1.0,1.0,1.0,1.0,1.0,2.893444,23.0,3.829114,1.0,1.0,1.0,0.0,0.0,0.0,0.0
1,19apr2020 00:00:00,065009,ST PAUL HEALTH CENTER,DENVER,Denver County,0,0,26apr2020 00:00:00,0,0,0,0,26apr2020 00:00:00,2,0,0,2,0,0,2,0,0,2,0,0,0,0,5/31/2020,65009,ST PAUL HEALTH CENTER,1667 ST PAUL ST,DENVER,CO,80206.0,Y,Y,0.0,2.0,0.0,5.0,1.0,11.0,0.0,1.0,0.0,1.0,150.0,97.0,Y,Y,Y,N,0.0,3.0,1.0,11.0,0.0,0.0,N,N,N,N,Y,N,Y,N,Y,N,Y,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,51.50000,10.300000,20.000000,Colorado_686348,1971.0,"1667 St Paul St, Denver, CO 80206, USA",3.033992e+09,150.0,Denver,For profit - Corporation,150.0,125.300000,Medicare and Medicaid,N,ST. PAUL HEALTH CENTER LTD,1980-06-01,N,NaN,N,N,N,Resident,Yes,2.0,NaN,1.0,NaN,5.0,NaN,5.0,NaN,5.0,NaN,4.0,NaN,4.0,NaN,NaN,NaN,2.66827,0.61239,0.70897,1.32136,3.98963,0.03215,1.84415,0.66190,0.29632,2.80237,3.00711,0.69569,0.90054,4.56520,130.000,0.0,23.0,0.0,0.0,0.0,0.0,Colorado,39.743099,-104.95157,ROOFTOP,0.0,1.0,1.0,1.0,G08003100037012,12.0,12.0,4.495367e-11,2.0,0.125687,2.0,5.500000,33.0,1.0,0.000359,1.0,4.00,6.0,2.0,6.759609e-02,2.0,11.000000,41.0,0.0,17.0,1.0,5.0,0.217742,0.0,0.500000,0.0,0.0,8.0,1.0,10.0,NaN,5/27/20,CO,8.0,31.0,8.0,31.0,8031.0,1.0,1.0,For,1.0,1.0,1.0,0.0,1.0,2.776472,16.0,3.466711,1.0,1.0,0.0,1.0,0.0,0.0,0.0
2,19apr2020 00:00:00,065015,MOUNTAIN VISTA HEALTH CENTER,WHEAT RIDGE,Jefferson County,1,1,19apr2020 00:00:00,5,0,1,1,19apr2020 00:00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5/31/2020,65015,MOUNTAIN VISTA HEALTH CENTER,4800 TABOR ST,WHEAT RIDGE,CO,80033.0,N,NaN,0.0,0.0,0.0,31.0,0.0,3.0,0.0,24.0,0.0,22.0,168.0,87.0,NaN,NaN,NaN,NaN,0.0,14.0,0.0,11.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,356.29999,252.899990,71.000000,Colorado_944984,1999.0,"4800 Tabor St, Wheat Ridge, CO 80033, USA",3.034214e+09,290.0,Jefferson,Non profit - Corporation,168.0,130.500000,Medicare and Medicaid,N,BAPTIST HOME ASSOCIATION OF THE ROCKY MOUNTAIN...,1967-01-01,Y,NaN,N,N,N,Resident,Yes,2.0,NaN,1.0,NaN,5.0,NaN,5.0,NaN,5.0,NaN,4.0,NaN,4.0,NaN,NaN,NaN,1.96054,0.73961,0.78457,1.52418,3.48472,0.03793,2.04885,0.65843,0.28720,2.99447,1.98876,0.84465,1.02820,3.73164,96.667,0.0,6.0,3.0,169579.0,0.0,3.0,Colorado,39.785484,-105.13000,ROOFTOP,0.0,1.0,1.0,1.0,G08005900104024,23.0,30.0,5.586522e-10,4.0,0.558123,4.0,6.750000,9.0,4.0,0.012736,4.0,3.75,10.0,9.0,3.258204e-01,10.0,11.200000,44.0,0.0,31.0,3.0,5.0,0.000000,0.0,NaN,0.0,0.0,80.0,27.0,34.0,NaN,5/27/20,CO,8.0,59.0,8.0,59.0,8059.0,2.0,1.0,Non,0.0,1.0,NaN,NaN,NaN,5.075213,34.0,4.219724,1.0,1.0,0.0,1.0,0.0,0.0,0.0
3,19apr2020 00:00:00,065034,AMBERWOOD COURT REHABILITATION AND CARE COMMUNITY,DENVER,Denver County,1,1,19apr2020 00:00:00,10,0,1,1,19apr2020 00:00:00,4,0,0,9,0,0,4,0,0,9,0,0,0,0,5/31/2020,65034,AMBERWOOD COURT REHABILITATION AND CARE COMMUNITY,4686 E ASBURY CIR,DENVER,CO,80222.0,Y,Y,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,85.0,61.0,Y,Y,Y,N,0.0,0.0,0.0,0.0,0.0,0.0,N,N,N,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,0.00000,32.799999,NaN,Colorado_288167,1923.0,"4686 E Asbury Cir, Denver, CO 80222, USA",3.037562e+09,150.0,Denver,For profit - Corporation,33.0,82.199997,Medicare and Medicaid,N,CONIFER CARE COMMUNITIES A LLC,1967-01-01,N,NaN,N,N,N,Resident,Yes,4.0,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,NaN,NaN,NaN,2.09986,0.44510,0.90885,1.35395,3.45382,0.05005,1.92785,0.73159,0.36590,3.02534,2.26377,0.45748,0.93490,3.66081,24.000,0.0,3.0,0.0,0.0,0.0,0.0,Colorado,39.679920,-104.93245,ROOFTOP,0.0,1.0,1.0,1.0,G08003100051042,12.0,16.0,6.196611e-11,5.0,0.522918,10.0,5.700000,155.0,4.0,0.001411,4.0,4.25,68.0,9.0,2.551117e-01,15.0,9.666667,330.0,0.0,123.0,2.0,5.0,0.267327,1.0,0.633663,1.0,0.0,26.0,15.0,16.0,NaN,5/27/20,CO,8.0,31.0,8.0,31.0,8031.0,1.0,1.0,For,1.0,1.0,1.0,1.0,1.0,3.951613,0.0,0.000000,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,19apr2020 00:00:00,065052,MESA VISTA OF BOULDER,BOULDER,Boulder County,1,1,19apr2020 00:00:00,15,0,1,1,19apr2020 00:00:00,1,0,0,1,0,0,1,0,0,1,0,0,1,1,5/31/2020,65052,MESA VISTA OF BOULDER,2121 MESA DR,BOULDER,CO,80304.0,Y,Y,0.0,0.0,0.0,6.0,0.0,0.0,0.0,4.0,0.0,4.0,162.0,132.0,Y,Y,Y,N,0.0,76.0,0.0,0.0,0.0,0.0,N,N,N,N,N,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,45.50000,30.299999,66.699997,Colorado_775967,1977.0,"2121 Mesa Dr, Boulder, CO 80304, USA",3.034424e+09,60.0,Boulder,For profit - Corporation,162.0,146.500000,Medicare and Medicaid,N,BUCKEYE M LLC,1967-01-01,N,NaN,Y,N,N,Resident,Yes,3.0,NaN,2.0,NaN,3.0,NaN,4.0,NaN,3.0,NaN,4.0,NaN,4.0,NaN,NaN,NaN,1.91121,0.59642,0.57479,1.17122,3.08243,0.03715,1.67451,0.63457,0.27578,2.58486,2.37212,0.70673,0.78448,3.82392,46.667,0.0,12.0,1.0,197059.0,0.0,1.0,Colorado,40.025284,-105.26945,ROOFTOP,0.0,1.0,1.0,1.0,G08001300121022,4.0,4.0,6.793851e-10,3.0,0.376251,3.0,6.333334,19.0,0.0,0.000000,0.0,0.00,0.0,5.0,1.485357e-01,5.0,10.000000,45.0,0.0,85.0,1.0,5.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,CO,8.0,13.0,8.0,13.0,8013.0,3.0,1.0,For,1.0,1.0,1.0,1.0,1.0,0.000000,6.0,2.491780,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4535,30aug2020 00:00:00,06A175,WALSH HEALTHCARE CENTER,WALSH,Baca County,0,0,NaN,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5/31/2020,06A175,WALSH HEALTHCARE CENTER,150 N NEVADA ST,WALSH,CO,81090.0,Y,Y,0.0,0.0,0.0,0.0,0.0,0.0,2.0,7.0,0.0,0.0,30.0,19.0,Y,Y,Y,Y,0.0,0.0,0.0,2.0,0.0,0.0,Y,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,0.00000,0.000000,NaN,Colorado_199145,1901.0,"150 N Nevada St, Walsh, CO 81090, USA",7.193245e+09,40.0,Baca,Government - Hospital district,30.0,20.799999,Medicaid,N,Legal Business Name Not Available,1991-07-01,N,NaN,N,N,N,Resident,Yes,4.0,NaN,5.0,NaN,3.0,NaN,3.0,NaN,NaN,2.0,1.0,12.0,1.0,12.0,NaN,NaN,3.30712,1.36830,0.63537,2.00367,5.31079,0.00000,2.04703,0.62451,0.26723,2.93878,3.35769,1.64750,0.89488,5.79489,14.000,0.0,0.0,0.0,0.0,0.0,0.0,Colorado,37.384636,-102.28057,ROOFTOP,0.0,1.0,1.0,1.0,G08000909646001,0.0,0.0,0.000000e+00,0.0,0.000000,0.0,0.000000,0.0,1.0,0.000000,1.0,2.00,2.0,1.0,8.900000e-18,1.0,2.000000,2.0,0.0,0.0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,CO,8.0,9.0,8.0,9.0,8009.0,6.0,0.0,Gov,0.0,0.0,1.0,1.0,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4536,30aug2020 00:00:00,06A185,SOUTHEAST COLORADO HOSPITAL LTC CENTER,SPRINGFIELD,Baca County,0,0,NaN,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5/31/2020,06A185,SOUTHEAST COLORADO HOSPITAL LTC CENTER,373 EAST 10TH AVE,SPRINGFIELD,CO,81073.0,Y,Y,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,56.0,47.0,Y,Y,Y,N,0.0,0.0,0.0,0.0,0.0,0.0,N,N,N,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,0.00000,0.000000,NaN,Colorado_1580117,1858.0,"373 E 10th Ave, Springfield, CO 81073, USA",7.195235e+09,40.0,Baca,Government - Hospital district,56.0,49.599998,Medicaid,Y,Legal Business Name Not Available,1991-12-01,N,NaN,N,N,N,Resident,Yes,1.0,NaN,3.0,NaN,1.0,NaN,1.0,NaN,NaN,2.0,1.0,12.0,1.0,12.0,NaN,NaN,3.62085,1.02597,0.45748,1.48345,5.10430,0.01075,2.01851,0.63606,0.28041,2.93498,3.72817,1.21288,0.61407,5.57680,46.000,0.0,3.0,0.0,0.0,0.0,0.0,Colorado,37.404411,-102.61295,ROOFTOP,0.0,1.0,1.0,1.0,G08000909647001,0.0,0.0,0.000000e+00,0.0,0.000000,0.0,0.000000,0.0,2.0,0.000000,2.0,1.00,6.0,2.0,2.380000e-18,2.0,1.000000,6.0,0.0,0.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,CO,8.0,9.0,8.0,9.0,8009.0,6.0,0.0,Gov,0.0,1.0,1.0,1.0,1.0,0.000000,0.0,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4537,30aug2020 00:00:00,06A190,SPANISH PEAKS VETERANS COMMUNITY LIVING CENTER,WALSENBURG,Huerfano County,0,0,NaN,0,0,0,1,24may2020 00:00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5/31/2020,06A190,SPANISH PEAKS VETERANS COMMUNITY LIVING CENTER,23500 US HIGHWAY 160,WALSENBURG,CO,81089.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colorado_1662658,1867.0,"23500 US-160, Walsenburg, CO 81089, USA",7.197385e+09,270.0,Huerfano,Government - Hospital district,120.0,88.000000,Medicaid,N,Legal Business Name Not Available,1997-12-31,N,NaN,N,N,N,Resident,Yes,3.0,NaN,2.0,NaN,4.0,NaN,4.0,NaN,NaN,2.0,5.0,NaN,5.0,NaN,NaN,NaN,2.94177,0.57338,0.99300,1.56638,4.50815,0.00000,2.14290,0.63224,0.27457,3.04971,2.85314,0.68194,1.36122,4.74017,62.667,0.0,6.0,0.0,0.0,0.0,0.0,Colorado,37.600346,-104.83176,ROOFTOP,0.0,1.0,1.0,1.0,G08005509609002,1.0,1.0,5.569111e-09,0.0,0.000000,0.0,0.000000,0.0,1.0,0.000000,1.0,2.00,4.0,1.0,8.260000e-18,1.0,2.000000,4.0,0.0,0.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,55.0,8.0,55.0,8055.0,6.0,0.0,Gov,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0
4538,30aug2020 00:00:00,06A192,CHEYENNE MANOR,CHEYENNE WELLS,Cheyenne County,0,0,NaN,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5/31/2020,06A192,CHEYENNE MANOR,561 W 1ST ST N,CHEYENNE WELLS,CO,80810.0,Y,Y,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0,23.0,Y,N,Y,N,0.0,0.0,3.0,3.0,0.0,0.0,N,N,Y,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,0.00000,0.000000,NaN,Colorado_1981766,1898.0,"561 W 1st St N, Cheyenne Wells, CO 80810, USA",7.197676e+09,80.0,Cheyenne,Government - Hospital district,38.0,19.299999,Medicaid,N,Legal Business Name Not Available,1999-12-10,N,NaN,N,N,N,Resident,Yes,5.0,NaN,5.0,NaN,5.0,NaN,5.0,NaN,NaN,2.0,5.0,NaN,5.0,NaN,NaN,NaN,3.10726,0.56399,0.83326,1.39726,4.50451,0.00000,2.01029,0.64314,0.25394,2.90738,3.21243,0.65940,1.23502,4.96820,1.333,0.0,0.0,0.0,0.0,0.0,0.0,Colorado,38.825687,-102.35146,ROOFTOP,0.0,0.0,1.0,1.0,G08001709606001,0.0,0.0,0.000000e+00,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.00,0.0,0.0,1.210000e-17,0.0,0.000000,0.0,0.0,0.0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,CO,8.0,17.0,8.0,17.0,8017.0,6.0,0.0,Gov,0.0,0.0,1.0,1.0,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4539,30aug2020 00:00:00,06A196,NAMASTE ALZHEIMER CENTER,COLORADO SPRINGS,El Paso County,0,0,NaN,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5/31/2020,06A196,NAMASTE ALZHEIMER CENTER,2 PENROSE BLVD,COLORADO SPRINGS,CO,80906.0,Y,Y,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64.0,59.0,Y,N,Y,N,0.0,0.0,0.0,0.0,0.0,0.0,N,N,N,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,0.00000,0.000000,NaN,Colorado_1302884,1829.0,"2 Penrose Blvd, Colorado Springs, CO 80906, USA",7.194424e+09,200.0,El Paso,Non profit - Corporation,64.0,61.400002,Medicaid,N,Legal Business Name Not Available,2003-05-29,N,NaN,Y,N,N,Family,Yes,2.0,NaN,1.0,NaN,5.0,NaN,5.0,NaN,NaN,2.0,4.0,NaN,4.0,NaN,NaN,NaN,2.60434,0.25308,0.65155,0.90462,3.50897,0.00000,2.01156,0.58379,0.24957,2.84492,2.69079,0.32597,0.98264,3.95514,100.000,0.0,12.0,0.0,0.0,0.0,0.0,Colorado,38.787113,-104.85735,ROOFTOP,0.0,1.0,1.0,1.0,G08004100031004,1.0,1.0,3.226811e-14,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.00,0.0,0.0,1.210000e-17,0.0,0.000000,0.0,0.0,0.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,CO,8.0,41.0,8.0,41.0,8041.0,3.0,1.0,Non,0.0,1.0,1.0,1.0,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [9]:
nursing_CO_df.columns

Index(['Date', 'PROVNUM', 'PROVNAME', 'CITY', 'COUNTY', 'Case',
       'ever_had_case', 'first_week', 'case_count_outbreak', 'case_count_CMS',
       ...
       'HypArcSin_StateCases', 'CMS_ConfirmedPlusSuspected',
       'HypArcSin_CMSCases', 'CMS_ConfirmedPlusSusp_01',
       'State_ResidentsPositive_0_1', 'ratingdum1', 'ratingdum2', 'ratingdum3',
       'ratingdum4', 'ratingdum5'],
      dtype='object', length=204)

I'm currently imputing total number of beds of each nursing home with total number of occupied beds (if the former is missing).

Same thing for prisons, I'm imputing:

latest_inmate_pop <- max_inmate_pop_2020 <- total_inmate_cases <- total_inmate_deaths

Even then, there will still be counties where there are no data for nursing homes or prisons. I will be treating those counties as having 0 beds and 0 inmates

### Generate Feature Data used for Matching Analysis

In [10]:
nursing_col_keep = ["COUNTY", 'PROVNUM', 'PROVNAME',"numberofallbeds"]
nursing_CO_use_df = nursing_CO_df[nursing_col_keep]
nursing_CO_use_df = pd.merge(left=county_fips_master_df[["fips","county_name"]],right=nursing_CO_use_df,how="left",left_on="county_name",right_on="COUNTY")
nursing_CO_use_df = nursing_CO_use_df.drop(["county_name"],axis=1)
nursing_CO_use_df = nursing_CO_use_df.drop_duplicates().dropna(subset="numberofallbeds")
nursing_CO_use_df

,fips,COUNTY,PROVNUM,PROVNAME,numberofallbeds
0,8001,Adams County,065108,"VILLAS AT SUNNY ACRES, THE",160.0
1,8001,Adams County,065120,CLEAR CREEK CARE CENTER,100.0
2,8001,Adams County,065193,ALPINE LIVING CENTER,101.0
3,8001,Adams County,065196,AVAMERE TRANSITIONAL CARE AND REHAB-MALLEY,162.0
4,8001,Adams County,065238,ELMS HAVEN CENTER,242.0
...,...,...,...,...,...
4343,8123,Weld County,065368,LIFE CARE CENTER OF GREELEY,104.0
4344,8123,Weld County,065397,"GRACE POINTE CONT CARE SR CAMPUS, SKILLED NURSING",53.0
4345,8123,Weld County,065410,COLUMBINE COMMONS HEALTH AND REHAB LLC,30.0
4518,8125,Yuma County,065263,YUMA LIFE CARE CENTER,32.0
4519,8125,Yuma County,065316,HILLCREST CARE CENTER,69.0

In [11]:
nursing_CO_use_df["fips"].unique().shape

(44,)

In [12]:
prisons_col_use = ["nyt_id","facility_name","facility_county_fips","max_inmate_population_2020"]
prisons_use_df = prisons_df[prisons_col_use]
prisons_use_df.head()

,nyt_id,facility_name,facility_county_fips,max_inmate_population_2020
158,84EB1D78,Arkansas Valley Correctional Facility,8025,NaN
159,A2A88844,Arrowhead Correctional Center,8043,528.0
160,03079583,Bent County Correctional Facility,8011,NaN
161,5057D4F9,Buena Vista Correctional Facility,8015,1129.0
162,5E8ED28B,Centennial Correctional Facility,8043,886.0

### Get County Level Features

In [13]:
county_features_df = pd.read_csv(os.path.join(DATA_FOLDER, "county_features.csv"))
colorado_county_features_df = county_features_df[county_features_df["STATE"]=="COLORADO"]

colorado_county_features_df["FIPS"] = colorado_county_features_df["FIPS"].astype(int)
relevant_cols = ["E_TOTPOP", "E_AGE17", "E_AGE65", "E_POV"]
colorado_county_features_df[relevant_cols] = colorado_county_features_df[relevant_cols].astype(int)

for f in relevant_cols[1:]:
    colorado_county_features_df[f+"_PERCENTAGE"] = 100*colorado_county_features_df[f]/colorado_county_features_df["E_TOTPOP"]

features_to_keep = ["FIPS", "COUNTY", "STATE", "LAT", "LON", "AREA_SQMI", "E_TOTPOP", "E_AGE17", "E_AGE65", "E_POV"] + [f+"_PERCENTAGE" for f in relevant_cols[1:]]

colorado_county_features_df = colorado_county_features_df[features_to_keep]

colorado_county_features_df["E_TOTPOP_RANK"] = colorado_county_features_df["E_TOTPOP"].rank(ascending=False)

colorado_county_features_df

,FIPS,COUNTY,STATE,LAT,LON,AREA_SQMI,E_TOTPOP,E_AGE17,E_AGE65,E_POV,E_AGE17_PERCENTAGE,E_AGE65_PERCENTAGE,E_POV_PERCENTAGE,E_TOTPOP_RANK
244,8001,Adams,COLORADO,39.874325,-104.331872,1166.256942,497115,135444,49181,56588,27.246009,9.893284,11.383282,5.0
245,8003,Alamosa,COLORADO,37.568442,-105.788041,722.576715,16444,3932,2113,3635,23.911457,12.849672,22.105327,31.0
246,8005,Arapahoe,COLORADO,39.644554,-104.331706,797.930917,636671,153460,78627,56802,24.103501,12.349707,8.921719,3.0
247,8007,Archuleta,COLORADO,37.202395,-107.050863,1350.086257,12908,2209,3168,1370,17.113418,24.542919,10.613573,35.0
248,8009,Baca,COLORADO,37.309780,-102.543741,2554.991586,3563,739,923,661,20.740949,25.905136,18.551782,56.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,8117,Summit,COLORADO,39.621023,-106.137555,608.338717,30429,5031,3601,3075,16.533570,11.834106,10.105491,18.0
304,8119,Teller,COLORADO,38.869976,-105.187365,557.042574,24113,4368,4875,1980,18.114710,20.217310,8.211338,24.0
305,8121,Washington,COLORADO,39.965790,-103.209744,2518.082648,4840,1108,944,480,22.892562,19.504132,9.917355,51.0
306,8123,Weld,COLORADO,40.555961,-104.383666,3986.025890,295123,78590,34304,30574,26.629575,11.623628,10.359748,9.0
307,8125,Yuma,COLORADO,40.000770,-102.421649,2364.397328,10069,2701,1829,1438,26.824908,18.164664,14.281458,38.0

### Tally the total number of inmates and nusing home beds per county

In [14]:
beds_per_county_df = nursing_CO_use_df.groupby(["fips"])["numberofallbeds"].agg(num_beds='sum', count_homes='count').reset_index(level=0)
inmates_per_county_df = prisons_use_df.groupby("facility_county_fips")["max_inmate_population_2020"].agg(num_inmates='sum', count_facilities='count').reset_index(level=0)
feature_match_df = pd.merge(left=beds_per_county_df, right=inmates_per_county_df, left_on="fips", right_on="facility_county_fips", how="outer")
feature_match_df = feature_match_df.drop(["facility_county_fips"],axis=1)
feature_match_df = feature_match_df.fillna(0)
feature_match_df = feature_match_df.astype(np.int64)
feature_match_df = pd.merge(left=feature_match_df, right=colorado_county_features_df, how="inner",left_on="fips",right_on="FIPS")
# Write to output folder
#feature_match_df.to_csv(os.path.join(OUTPUT_FOLDER,"feature_match.csv"),index=False)
#feature_match_df_rank = feature_match_df.copy()
#feature_match_df_rank[["num_beds","num_inmates"]] = feature_match_df_rank[["num_beds","num_inmates"]].rank(method="dense",ascending=False)
#feature_match_df_rank

In [15]:
feature_match_df

,fips,num_beds,count_homes,num_inmates,count_facilities,FIPS,COUNTY,STATE,LAT,LON,AREA_SQMI,E_TOTPOP,E_AGE17,E_AGE65,E_POV,E_AGE17_PERCENTAGE,E_AGE65_PERCENTAGE,E_POV_PERCENTAGE,E_TOTPOP_RANK
0,8001,1671,14,0,0,8001,Adams,COLORADO,39.874325,-104.331872,1166.256942,497115,135444,49181,56588,27.246009,9.893284,11.383282,5.0
1,8003,123,2,0,0,8003,Alamosa,COLORADO,37.568442,-105.788041,722.576715,16444,3932,2113,3635,23.911457,12.849672,22.105327,31.0
2,8005,1996,18,0,0,8005,Arapahoe,COLORADO,39.644554,-104.331706,797.930917,636671,153460,78627,56802,24.103501,12.349707,8.921719,3.0
3,8007,60,1,0,0,8007,Archuleta,COLORADO,37.202395,-107.050863,1350.086257,12908,2209,3168,1370,17.113418,24.542919,10.613573,35.0
4,8009,86,2,0,0,8009,Baca,COLORADO,37.309780,-102.543741,2554.991586,3563,739,923,661,20.740949,25.905136,18.551782,56.0
5,8011,56,1,0,0,8011,Bent,COLORADO,37.931891,-103.077584,1512.846146,5809,894,1005,912,15.389912,17.300740,15.699776,48.0
6,8013,1078,11,0,0,8013,Boulder,COLORADO,40.094970,-105.397691,726.369908,321030,62925,42068,38546,19.600972,13.104071,12.006978,8.0
7,8014,200,1,0,0,8014,Broomfield,COLORADO,39.953593,-105.050787,33.003534,66120,15692,8499,3296,23.732607,12.853902,4.984876,12.0
8,8015,98,1,1129,1,8015,Chaffee,COLORADO,38.738223,-106.316683,1013.407978,19164,2979,4670,1807,15.544771,24.368608,9.429138,26.0
9,8017,38,1,0,0,8017,Cheyenne,COLORADO,38.835646,-102.601791,1778.275373,2039,692,245,228,33.938205,12.015694,11.181952,58.0
10,8021,60,1,0,0,8021,Conejos,COLORADO,37.213406,-106.176447,1287.436098,8142,2210,1466,1813,27.143208,18.005404,22.267256,40.0
11,8025,37,1,1681,1,8025,Crowley,COLORADO,38.306180,-103.772736,787.427181,5630,717,724,1261,12.735346,12.859680,22.397869,49.0
12,8029,185,3,0,0,8029,Delta,COLORADO,38.861595,-107.864892,1142.126464,30346,6176,7499,5145,20.351941,24.711659,16.954459,19.0
13,8031,2203,23,826,1,8031,Denver,COLORADO,39.761850,-104.881105,153.292030,693417,139801,78751,93728,20.161173,11.356947,13.516830,1.0
14,8035,606,7,0,0,8035,Douglas,COLORADO,39.325414,-104.925987,840.249704,328614,89484,35801,11333,27.230733,10.894545,3.448727,7.0
15,8037,0,1,0,0,8037,Eagle,COLORADO,39.626992,-106.695169,1684.470957,54357,12118,5482,3793,22.293357,10.085178,6.977942,15.0
16,8039,30,1,0,0,8039,Elbert,COLORADO,39.315157,-104.114076,1850.835533,25162,5514,3689,1110,21.913997,14.660997,4.411414,22.0
17,8041,1849,21,0,0,8041,El Paso,COLORADO,38.827383,-104.527472,2126.844422,688153,168985,83244,72948,24.556312,12.096728,10.600550,2.0
18,8043,444,6,8037,8,8043,Fremont,COLORADO,38.455170,-105.424958,1533.081455,47002,7757,9807,5547,16.503553,20.865070,11.801625,16.0
19,8045,283,4,0,0,8045,Garfield,COLORADO,39.599352,-107.909780,2947.543401,58538,15028,7034,4662,25.672213,12.016126,7.964058,13.0
20,8051,50,1,0,0,8051,Gunnison,COLORADO,38.670499,-107.056880,3239.140212,16537,2929,2044,2084,17.711798,12.360162,12.602044,30.0
21,8059,2308,23,1127,1,8059,Jefferson,COLORADO,39.579511,-105.245462,764.289433,570427,115926,88707,41438,20.322671,15.550982,7.264383,4.0
22,8063,40,1,0,0,8063,Kit Carson,COLORADO,39.305340,-102.603023,2160.820615,7635,1791,1378,705,23.457760,18.048461,9.233792,42.0
23,8067,173,2,0,0,8067,La Plata,COLORADO,37.287367,-107.839718,1689.783902,55101,10565,8634,4609,19.173881,15.669407,8.364639,14.0
24,8069,1327,15,0,0,8069,Larimer,COLORADO,40.658093,-105.486764,2595.766922,338161,67812,49587,39489,20.053170,14.663725,11.677574,6.0
25,8071,119,1,0,0,8071,Las Animas,COLORADO,37.318831,-104.044110,4772.936003,14179,2547,3253,2426,17.963185,22.942380,17.109810,33.0
26,8073,35,1,0,0,8073,Lincoln,COLORADO,38.993740,-103.507555,2577.678218,5548,1110,951,475,20.007210,17.141312,8.561644,50.0
27,8075,147,2,2041,1,8075,Logan,COLORADO,40.728091,-103.090464,1838.597644,21689,4637,3647,3117,21.379501,16.814975,14.371340,25.0
28,8077,610,7,0,0,8077,Mesa,COLORADO,39.019524,-108.460571,3328.932559,149998,33006,26902,22978,22.004293,17.934906,15.318871,11.0
29,8081,58,1,0,0,8081,Moffat,COLORADO,40.610864,-108.217154,4743.241381,13060,3381,1816,1796,25.888208,13.905054,13.751914,34.0
30,8083,161,2,0,0,8083,Montezuma,COLORADO,37.338025,-108.595786,2029.327837,25909,5799,5353,4140,22.382184,20.660774,15.979003,21.0
31,8085,247,3,0,0,8085,Montrose,COLORADO,38.407507,-108.266282,2240.945104,41268,9090,9249,6812,22.026752,22.412038,16.506736,17.0
32,8087,323,3,0,0,8087,Morgan,COLORADO,40.263159,-103.812210,1280.484701,28257,7419,4320,2787,26.255441,15.288247,9.863043,20.0
33,8089,101,1,0,0,8089,Otero,COLORADO,37.884170,-103.721260,1261.945207,18325,4289,3616,4421,23.405184,19.732606,24.125512,27.0
34,8095,0,1,0,0,8095,Phillips,COLORADO,40.594712,-102.345105,687.927576,4318,1109,793,282,25.683187,18.364984,6.530801,54.0
35,8099,105,2,0,0,8099,Prowers,COLORADO,37.958181,-102.392161,1638.396294,12052,3031,2066,2218,25.149353,17.142383,18.403584,36.0
36,8101,1019,9,558,2,8101,Pueblo,COLORADO,38.170658,-104.489892,2386.078246,164685,37702,29234,30467,22.893403,17.751465,18.500167,10.0
37,8103,30,1,0,0,8103,Rio Blanco,COLORADO,39.972622,-108.200716,3220.969078,6465,1663,935,701,25.723125,14.462490,10.843001,46.0
38,8105,180,3,0,0,8105,Rio Grande,COLORADO,37.485853,-106.453128,911.955973,11351,2659,2143,1890,23.425249,18.879394,16.650515,37.0
39,8107,66,1,0,0,8107,Routt,COLORADO,40.483664,-106.987702,2362.018663,24874,4626,3459,2640,18.597733,13.906087,10.613492,23.0
40,8115,32,1,0,0,8115,Sedgwick,COLORADO,40.871568,-102.355358,548.040565,2350,539,608,390,22.936170,25.872340,16.595745,57.0
41,8119,139,2,0,0,8119,Teller,COLORADO,38.869976,-105.187365,557.042574,24113,4368,4875,1980,18.114710,20.217310,8.211338,24.0
42,8123,756,8,0,0,8123,Weld,COLORADO,40.555961,-104.383666,3986.025890,295123,78590,34304,30574,26.629575,11.623628,10.359748,9.0
43,8125,101,2,0,0,8125,Yuma,COLORADO,40.000770,-102.421649,2364.397328,10069,2701,1829,1438,26.824908,18.164664,14.281458,38.0

In [16]:
feature_match_df

,fips,num_beds,count_homes,num_inmates,count_facilities,FIPS,COUNTY,STATE,LAT,LON,AREA_SQMI,E_TOTPOP,E_AGE17,E_AGE65,E_POV,E_AGE17_PERCENTAGE,E_AGE65_PERCENTAGE,E_POV_PERCENTAGE,E_TOTPOP_RANK
0,8001,1671,14,0,0,8001,Adams,COLORADO,39.874325,-104.331872,1166.256942,497115,135444,49181,56588,27.246009,9.893284,11.383282,5.0
1,8003,123,2,0,0,8003,Alamosa,COLORADO,37.568442,-105.788041,722.576715,16444,3932,2113,3635,23.911457,12.849672,22.105327,31.0
2,8005,1996,18,0,0,8005,Arapahoe,COLORADO,39.644554,-104.331706,797.930917,636671,153460,78627,56802,24.103501,12.349707,8.921719,3.0
3,8007,60,1,0,0,8007,Archuleta,COLORADO,37.202395,-107.050863,1350.086257,12908,2209,3168,1370,17.113418,24.542919,10.613573,35.0
4,8009,86,2,0,0,8009,Baca,COLORADO,37.309780,-102.543741,2554.991586,3563,739,923,661,20.740949,25.905136,18.551782,56.0
5,8011,56,1,0,0,8011,Bent,COLORADO,37.931891,-103.077584,1512.846146,5809,894,1005,912,15.389912,17.300740,15.699776,48.0
6,8013,1078,11,0,0,8013,Boulder,COLORADO,40.094970,-105.397691,726.369908,321030,62925,42068,38546,19.600972,13.104071,12.006978,8.0
7,8014,200,1,0,0,8014,Broomfield,COLORADO,39.953593,-105.050787,33.003534,66120,15692,8499,3296,23.732607,12.853902,4.984876,12.0
8,8015,98,1,1129,1,8015,Chaffee,COLORADO,38.738223,-106.316683,1013.407978,19164,2979,4670,1807,15.544771,24.368608,9.429138,26.0
9,8017,38,1,0,0,8017,Cheyenne,COLORADO,38.835646,-102.601791,1778.275373,2039,692,245,228,33.938205,12.015694,11.181952,58.0
10,8021,60,1,0,0,8021,Conejos,COLORADO,37.213406,-106.176447,1287.436098,8142,2210,1466,1813,27.143208,18.005404,22.267256,40.0
11,8025,37,1,1681,1,8025,Crowley,COLORADO,38.306180,-103.772736,787.427181,5630,717,724,1261,12.735346,12.859680,22.397869,49.0
12,8029,185,3,0,0,8029,Delta,COLORADO,38.861595,-107.864892,1142.126464,30346,6176,7499,5145,20.351941,24.711659,16.954459,19.0
13,8031,2203,23,826,1,8031,Denver,COLORADO,39.761850,-104.881105,153.292030,693417,139801,78751,93728,20.161173,11.356947,13.516830,1.0
14,8035,606,7,0,0,8035,Douglas,COLORADO,39.325414,-104.925987,840.249704,328614,89484,35801,11333,27.230733,10.894545,3.448727,7.0
15,8037,0,1,0,0,8037,Eagle,COLORADO,39.626992,-106.695169,1684.470957,54357,12118,5482,3793,22.293357,10.085178,6.977942,15.0
16,8039,30,1,0,0,8039,Elbert,COLORADO,39.315157,-104.114076,1850.835533,25162,5514,3689,1110,21.913997,14.660997,4.411414,22.0
17,8041,1849,21,0,0,8041,El Paso,COLORADO,38.827383,-104.527472,2126.844422,688153,168985,83244,72948,24.556312,12.096728,10.600550,2.0
18,8043,444,6,8037,8,8043,Fremont,COLORADO,38.455170,-105.424958,1533.081455,47002,7757,9807,5547,16.503553,20.865070,11.801625,16.0
19,8045,283,4,0,0,8045,Garfield,COLORADO,39.599352,-107.909780,2947.543401,58538,15028,7034,4662,25.672213,12.016126,7.964058,13.0
20,8051,50,1,0,0,8051,Gunnison,COLORADO,38.670499,-107.056880,3239.140212,16537,2929,2044,2084,17.711798,12.360162,12.602044,30.0
21,8059,2308,23,1127,1,8059,Jefferson,COLORADO,39.579511,-105.245462,764.289433,570427,115926,88707,41438,20.322671,15.550982,7.264383,4.0
22,8063,40,1,0,0,8063,Kit Carson,COLORADO,39.305340,-102.603023,2160.820615,7635,1791,1378,705,23.457760,18.048461,9.233792,42.0
23,8067,173,2,0,0,8067,La Plata,COLORADO,37.287367,-107.839718,1689.783902,55101,10565,8634,4609,19.173881,15.669407,8.364639,14.0
24,8069,1327,15,0,0,8069,Larimer,COLORADO,40.658093,-105.486764,2595.766922,338161,67812,49587,39489,20.053170,14.663725,11.677574,6.0
25,8071,119,1,0,0,8071,Las Animas,COLORADO,37.318831,-104.044110,4772.936003,14179,2547,3253,2426,17.963185,22.942380,17.109810,33.0
26,8073,35,1,0,0,8073,Lincoln,COLORADO,38.993740,-103.507555,2577.678218,5548,1110,951,475,20.007210,17.141312,8.561644,50.0
27,8075,147,2,2041,1,8075,Logan,COLORADO,40.728091,-103.090464,1838.597644,21689,4637,3647,3117,21.379501,16.814975,14.371340,25.0
28,8077,610,7,0,0,8077,Mesa,COLORADO,39.019524,-108.460571,3328.932559,149998,33006,26902,22978,22.004293,17.934906,15.318871,11.0
29,8081,58,1,0,0,8081,Moffat,COLORADO,40.610864,-108.217154,4743.241381,13060,3381,1816,1796,25.888208,13.905054,13.751914,34.0
30,8083,161,2,0,0,8083,Montezuma,COLORADO,37.338025,-108.595786,2029.327837,25909,5799,5353,4140,22.382184,20.660774,15.979003,21.0
31,8085,247,3,0,0,8085,Montrose,COLORADO,38.407507,-108.266282,2240.945104,41268,9090,9249,6812,22.026752,22.412038,16.506736,17.0
32,8087,323,3,0,0,8087,Morgan,COLORADO,40.263159,-103.812210,1280.484701,28257,7419,4320,2787,26.255441,15.288247,9.863043,20.0
33,8089,101,1,0,0,8089,Otero,COLORADO,37.884170,-103.721260,1261.945207,18325,4289,3616,4421,23.405184,19.732606,24.125512,27.0
34,8095,0,1,0,0,8095,Phillips,COLORADO,40.594712,-102.345105,687.927576,4318,1109,793,282,25.683187,18.364984,6.530801,54.0
35,8099,105,2,0,0,8099,Prowers,COLORADO,37.958181,-102.392161,1638.396294,12052,3031,2066,2218,25.149353,17.142383,18.403584,36.0
36,8101,1019,9,558,2,8101,Pueblo,COLORADO,38.170658,-104.489892,2386.078246,164685,37702,29234,30467,22.893403,17.751465,18.500167,10.0
37,8103,30,1,0,0,8103,Rio Blanco,COLORADO,39.972622,-108.200716,3220.969078,6465,1663,935,701,25.723125,14.462490,10.843001,46.0
38,8105,180,3,0,0,8105,Rio Grande,COLORADO,37.485853,-106.453128,911.955973,11351,2659,2143,1890,23.425249,18.879394,16.650515,37.0
39,8107,66,1,0,0,8107,Routt,COLORADO,40.483664,-106.987702,2362.018663,24874,4626,3459,2640,18.597733,13.906087,10.613492,23.0
40,8115,32,1,0,0,8115,Sedgwick,COLORADO,40.871568,-102.355358,548.040565,2350,539,608,390,22.936170,25.872340,16.595745,57.0
41,8119,139,2,0,0,8119,Teller,COLORADO,38.869976,-105.187365,557.042574,24113,4368,4875,1980,18.114710,20.217310,8.211338,24.0
42,8123,756,8,0,0,8123,Weld,COLORADO,40.555961,-104.383666,3986.025890,295123,78590,34304,30574,26.629575,11.623628,10.359748,9.0
43,8125,101,2,0,0,8125,Yuma,COLORADO,40.000770,-102.421649,2364.397328,10069,2701,1829,1438,26.824908,18.164664,14.281458,38.0

### Split Choices into CDPHE (x) and TLGRF (y)

In [17]:
feature_choice_cols = ["date.y","fips","county"]
# Merge CDPHE choice with feature_match_df
compare_choices_df = pd.read_csv(os.path.join(OUTPUT_FOLDER,"case_study_decision_space.csv"))

alg_feature_dict = {}

for method in ["exp","logistic"]:
    alg_choices_df = compare_choices_df[feature_choice_cols + ["chosen_by_CDPHE"]]
    alg_choices_df = alg_choices_df[alg_choices_df["chosen_by_CDPHE"] == 1]
    alg_choices_df = pd.merge(left=alg_choices_df,right=feature_match_df,how="inner",on="fips")
    alg_choices_df = alg_choices_df.fillna(0)
    alg_feature_dict["CDPHE_{}".format(method)] = alg_choices_df
    for n in range(1,10):
        TLGRF_N = "TLGRF{}".format(n)
        alg_choices_df = compare_choices_df[feature_choice_cols + ["chosen_by_{}_{}".format(TLGRF_N,method)]]
        alg_choices_df = alg_choices_df[alg_choices_df["chosen_by_{}_{}".format(TLGRF_N,method)] == 1]
        alg_choices_df = pd.merge(left=alg_choices_df,right=feature_match_df,how="inner",on="fips")
        alg_choices_df = alg_choices_df.fillna(0)
        alg_feature_dict[TLGRF_N + "_{}".format(method)] = alg_choices_df

In [18]:
alg_feature_dict

{'CDPHE_exp':         date.y  fips     county  chosen_by_CDPHE  num_beds  count_homes  \
 0   2020-04-08  8051   Gunnison                1        50            1
 1   2020-07-22  8051   Gunnison                1        50            1
 2   2021-01-20  8051   Gunnison                1        50            1
 3   2021-04-25  8051   Gunnison                1        50            1
 4   2021-06-15  8051   Gunnison                1        50            1
 ..         ...   ...        ...              ...       ...          ...
 78  2021-05-11  8021    Conejos                1        60            1
 79  2020-12-21  8039     Elbert                1        30            1
 80  2021-02-07  8017   Cheyenne                1        38            1
 81  2021-06-23  8013    Boulder                1      1078           11
 82  2021-06-27  8059  Jefferson                1      2308           23

     num_inmates  count_facilities  FIPS     COUNTY     STATE        LAT  \
 0             0                 0  8051   Gunnison  COLORADO  38.670499
 1             0                 0  8051   Gunnison  COLORADO  38.670499
 2             0                 0  8051   Gunnison  COLORADO  38.670499
 3             0                 0  8051   Gunnison  COLORADO  38.670499
 4             0                 0  8051   Gunnison  COLORADO  38.670499
 ..          ...               ...   ...        ...       ...        ...
 78            0                 0  8021    Conejos  COLORADO  37.213406
 79            0                 0  8039     Elbert  COLORADO  39.315157
 80            0                 0  8017   Cheyenne  COLORADO  38.835646
 81            0                 0  8013    Boulder  COLORADO  40.094970
 82         1127                 1  8059  Jefferson  COLORADO  39.579511

            LON    AREA_SQMI  E_TOTPOP  E_AGE17  E_AGE65  E_POV  \
 0  -107.056880  3239.140212     16537     2929     2044   2084
 1  -107.056880  3239.140212     16537     2929     2044   2084
 2  -107.056880  3239.140212     16537     2929     2044   2084
 3  -107.056880  3239.140212     16537     2929     2044   2084
 4  -107.056880  3239.140212     16537     2929     2044   2084
 ..         ...          ...       ...      ...      ...    ...
 78 -106.176447  1287.436098      8142     2210     1466   1813
 79 -104.114076  1850.835533     25162     5514     3689   1110
 80 -102.601791  1778.275373      2039      692      245    228
 81 -105.397691   726.369908    321030    62925    42068  38546
 82 -105.245462   764.289433    570427   115926    88707  41438

     E_AGE17_PERCENTAGE  E_AGE65_PERCENTAGE  E_POV_PERCENTAGE  E_TOTPOP_RANK
 0            17.711798           12.360162         12.602044           30.0
 1            17.711798           12.360162         12.602044           30.0
 2            17.711798           12.360162         12.602044           30.0
 3            17.711798           12.360162         12.602044           30.0
 4            17.711798           12.360162         12.602044           30.0
 ..                 ...                 ...               ...            ...
 78           27.143208           18.005404         22.267256           40.0
 79           21.913997           14.660997          4.411414           22.0
 80           33.938205           12.015694         11.181952           58.0
 81           19.600972           13.104071         12.006978            8.0
 82           20.322671           15.550982          7.264383            4.0

 [83 rows x 22 columns],
 'TLGRF1_exp':         date.y  fips     county  chosen_by_TLGRF1_exp  num_beds  count_homes  \
 0   2020-04-08  8077       Mesa                     1       610            7
 1   2020-04-27  8075      Logan                     1       147            2
 2   2020-05-05  8003    Alamosa                     1       123            2
 3   2020-05-07  8083  Montezuma                     1       161            2
 4   2020-09-27  8083  Montezuma                     1       161            2
 ..         ...   ...        ...                   ...       ...          ...
 64  2021-04-13  8115   Sedgwick                     1        32            1
 65  2021-05-02  8115   Sedgwick                     1        32            1
 66  2021-05-09  8115   Sedgwick                     1        32            1
 67  2021-04-03  8081     Moffat                     1        58            1
 68  2021-06-06  8081     Moffat                     1        58            1

     num_inmates  count_facilities  FIPS     COUNTY     STATE        LAT  \
 0             0                 0  8077       Mesa  COLORADO  39.019524
 1          2041                 1  8075      Logan  COLORADO  40.728091
 2             0                 0  8003    Alamosa  COLORADO  37.568442
 3             0                 0  8083  Montezuma  COLORADO  37.338025
 4             0                 0  8083  Montezuma  COLORADO  37.338025
 ..          ...               ...   ...        ...       ...        ...
 64            0                 0  8115   Sedgwick  COLORADO  40.871568
 65            0                 0  8115   Sedgwick  COLORADO  40.871568
 66            0                 0  8115   Sedgwick  COLORADO  40.871568
 67            0                 0  8081     Moffat  COLORADO  40.610864
 68            0                 0  8081     Moffat  COLORADO  40.610864

            LON    AREA_SQMI  E_TOTPOP  E_AGE17  E_AGE65  E_POV  \
 0  -108.460571  3328.932559    149998    33006    26902  22978
 1  -103.090464  1838.597644     21689     4637     3647   3117
 2  -105.788041   722.576715     16444     3932     2113   3635
 3  -108.595786  2029.327837     25909     5799     5353   4140
 4  -108.595786  2029.327837     25909     5799     5353   4140
 ..         ...          ...       ...      ...      ...    ...
 64 -102.355358   548.040565      2350      539      608    390
 65 -102.355358   548.040565      2350      539      608    390
 66 -102.355358   548.040565      2350      539      608    390
 67 -108.217154  4743.241381     13060     3381     1816   1796
 68 -108.217154  4743.241381     13060     3381     1816   1796

     E_AGE17_PERCENTAGE  E_AGE65_PERCENTAGE  E_POV_PERCENTAGE  E_TOTPOP_RANK
 0            22.004293           17.934906         15.318871           11.0
 1            21.379501           16.814975         14.371340           25.0
 2            23.911457           12.849672         22.105327           31.0
 3            22.382184           20.660774         15.979003           21.0
 4            22.382184           20.660774         15.979003           21.0
 ..                 ...                 ...               ...            ...
 64           22.936170           25.872340         16.595745           57.0
 65           22.936170           25.872340         16.595745           57.0
 66           22.936170           25.872340         16.595745           57.0
 67           25.888208           13.905054         13.751914           34.0
 68           25.888208           13.905054         13.751914           34.0

 [69 rows x 22 columns],
 'TLGRF2_exp':         date.y  fips      county  chosen_by_TLGRF2_exp  num_beds  count_homes  \
 0   2020-04-08  8014  Broomfield                     1       200            1
 1   2020-04-20  8029       Delta                     1       185            3
 2   2020-05-05  8007   Archuleta                     1        60            1
 3   2020-05-07  8007   Archuleta                     1        60            1
 4   2020-11-23  8007   Archuleta                     1        60            1
 ..         ...   ...         ...                   ...       ...          ...
 68  2021-04-21  8095    Phillips                     1         0            1
 69  2021-02-15  8011        Bent                     1        56            1
 70  2021-04-18  8099     Prowers                     1       105            2
 71  2021-05-02  8009        Baca                     1        86            2
 72  2021-05-09  8009        Baca                     1        86            2

     num_inmates  count_facilities  FIPS      COUNTY     STATE        LAT  \
 0             0                 0  8014  Broomfield  COLORADO  39.953593
 1             0                 0  8029       Delta  COLORADO  38.861595
 2             0                 0  8007   Archuleta  COLORADO  37.202395
 3             0                 0  8007   Archuleta  COLORADO  37.202395
 4             0                 0  8007   Archuleta  COLORADO  37.202395
 ..          ...               ...   ...         ...       ...        ...
 68            0                 0  8095    Phillips  COLORADO  40.594712
 69            0                 0  8011        Bent  COLORADO  37.931891
 70            0                 0  8099     Prowers  COLORADO  37.958181
 71            0                 0  8009        Baca  COLORADO  37.309780
 72            0                 0  8009        Baca  COLORADO  37.309780

            LON    AREA_SQMI  E_TOTPOP  E_AGE17  E_AGE65  E_POV  \
 0  -105.050787    33.003534     66120    15692     8499   3296
 1  -107.864892  1142.126464     30346     6176     7499   5145
 2  -107.050863  1350.086257     12908     2209     3168   1370
 3  -107.050863  1350.086257     12908     2209     3168   1370
 4  -107.050863  1350.086257     12908     2209     3168   1370
 ..         ...          ...       ...      ...      ...    ...
 68 -102.345105   687.927576      4318     1109      793    282
 69 -103.077584  1512.846146      5809      894     1005    912
 70 -102.392161  1638.396294     12052     3031     2066   2218
 71 -102.543741  2554.991586      3563      739      923    661
 72 -102.543741  2554.991586      3563      739      923    661

     E_AGE17_PERCENTAGE  E_AGE65_PERCENTAGE  E_POV_PERCENTAGE  E_TOTPOP_RANK
 0            23.732607           12.853902          4.984876           12.0
 1            20.351941           24.711659         16.954459           19.0
 2            17.113418           24.542919         10.613573           35.0
 3            17.113418           24.542919         10.613573           35.0
 4            17.113418           24.542919         10.613573           35.0
 ..                 ...                 ...               ...            ...
 68           25.683187           18.364984          6.530801           54.0
 69           15.389912           17.300740         15.699776           48.0
 70           25.149353           17.142383         18.403584           36.0
 71           20.740949           25.905136         18.551782           56.0
 72           20.740949           25.905136         18.551782           56.0

 [73 rows x 22 columns],
 'TLGRF3_exp':         date.y  fips      county  chosen_by_TLGRF3_exp  num_beds  count_homes  \
 0   2020-04-27  8071  Las Animas                     1       119            1
 1   2020-07-12  8071  Las Animas                     1       119            1
 2   2020-11-29  8071  Las Animas                     1       119            1
 3   2020-12-27  8071  Las Animas                     1       119            1
 4   2021-04-13  8071  Las Animas                     1       119            1
 ..         ...   ...         ...                   ...       ...          ...
 69  2021-04-20  8099     Prowers                     1       105            2
 70  2021-04-25  8021     Conejos                     1        60            1
 71  2021-05-03  8021     Conejos                     1        60            1
 72  2021-05-09  8021     Conejos                     1        60            1
 73  2021-05-11  8021     Conejos                     1        60            1

     num_inmates  count_facilities  FIPS      COUNTY     STATE        LAT  \
 0             0                 0  8071  Las Animas  COLORADO  37.318831
 1             0                 0  8071  Las Animas  COLORADO  37.318831
 2             0                 0  8071  Las Animas  COLORADO  37.318831
 3             0                 0  8071  Las Animas  COLORADO  37.318831
 4             0                 0  8071  Las Animas  COLORADO  37.318831
 ..          ...               ...   ...         ...       ...        ...
 69            0                 0  8099     Prowers  COLORADO  37.958181
 70            0                 0  8021     Conejos  COLORADO  37.213406
 71            0                 0  8021     Conejos  COLORADO  37.213406
 72            0                 0  8021     Conejos  COLORADO  37.213406
 73            0                 0  8021     Conejos  COLORADO  37.213406

            LON    AREA_SQMI  E_TOTPOP  E_AGE17  E_AGE65  E_POV  \
 0  -104.044110  4772.936003     14179     2547     3253   2426
 1  -104.044110  4772.936003     14179     2547     3253   2426
 2  -104.044110  4772.936003     14179     2547     3253   2426
 3  -104.044110  4772.936003     14179     2547     3253   2426
 4  -104.044110  4772.936003     14179     2547     3253   2426
 ..         ...          ...       ...      ...      ...    ...
 69 -102.392161  1638.396294     12052     3031     2066   2218
 70 -106.176447  1287.436098      8142     2210     1466   1813
 71 -106.176447  1287.436098      8142     2210     1466   1813
 72 -106.176447  1287.436098      8142     2210     1466   1813
 73 -106.176447  1287.436098      8142     2210     1466   1813

     E_AGE17_PERCENTAGE  E_AGE65_PERCENTAGE  E_POV_PERCENTAGE  E_TOTPOP_RANK
 0            17.963185           22.942380         17.109810           33.0
 1            17.963185           22.942380         17.109810           33.0
 2            17.963185           22.942380         17.109810           33.0
 3            17.963185           22.942380         17.109810           33.0
 4            17.963185           22.942380         17.109810           33.0
 ..                 ...                 ...               ...            ...
 69           25.149353           17.142383         18.403584           36.0
 70           27.143208           18.005404         22.267256           40.0
 71           27.143208           18.005404         22.267256           40.0
 72           27.143208           18.005404         22.267256           40.0
 73           27.143208           18.005404         22.267256           40.0

 [74 rows x 22 columns],
 'TLGRF4_exp':         date.y  fips    county  chosen_by_TLGRF4_exp  num_beds  count_homes  \
 0   2020-04-08  8039    Elbert                     1        30            1
 1   2020-07-12  8039    Elbert                     1        30            1
 2   2020-07-15  8039    Elbert                     1        30            1
 3   2020-07-22  8039    Elbert                     1        30            1
 4   2020-07-23  8039    Elbert                     1        30            1
 ..         ...   ...       ...                   ...       ...          ...
 72  2021-03-02  8009      Baca                     1        86            2
 73  2021-03-07  8009      Baca                     1        86            2
 74  2021-06-23  8009      Baca                     1        86            2
 75  2021-04-21  8043   Fremont                     1       444            6
 76  2021-05-03  8115  Sedgwick                     1        32            1

     num_inmates  count_facilities  FIPS    COUNTY     STATE        LAT  \
 0             0                 0  8039    Elbert  COLORADO  39.315157
 1             0                 0  8039    Elbert  COLORADO  39.315157
 2             0                 0  8039    Elbert  COLORADO  39.315157
 3             0                 0  8039    Elbert  COLORADO  39.315157
 4             0                 0  8039    Elbert  COLORADO  39.315157
 ..          ...               ...   ...       ...       ...        ...
 72            0                 0  8009      Baca  COLORADO  37.309780
 73            0                 0  8009      Baca  COLORADO  37.309780
 74            0                 0  8009      Baca  COLORADO  37.309780
 75         8037                 8  8043   Fremont  COLORADO  38.455170
 76            0                 0  8115  Sedgwick  COLORADO  40.871568

            LON    AREA_SQMI  E_TOTPOP  E_AGE17  E_AGE65  E_POV  \
 0  -104.114076  1850.835533     25162     5514     3689   1110
 1  -104.114076  1850.835533     25162     5514     3689   1110
 2  -104.114076  1850.835533     25162     5514     3689   1110
 3  -104.114076  1850.835533     25162     5514     3689   1110
 4  -104.114076  1850.835533     25162     5514     3689   1110
 ..         ...          ...       ...      ...      ...    ...
 72 -102.543741  2554.991586      3563      739      923    661
 73 -102.543741  2554.991586      3563      739      923    661
 74 -102.543741  2554.991586      3563      739      923    661
 75 -105.424958  1533.081455     47002     7757     9807   5547
 76 -102.355358   548.040565      2350      539      608    390

     E_AGE17_PERCENTAGE  E_AGE65_PERCENTAGE  E_POV_PERCENTAGE  E_TOTPOP_RANK
 0            21.913997           14.660997          4.411414           22.0
 1            21.913997           14.660997          4.411414           22.0
 2            21.913997           14.660997          4.411414           22.0
 3            21.913997           14.660997          4.411414           22.0
 4            21.913997           14.660997          4.411414           22.0
 ..                 ...                 ...               ...            ...
 72           20.740949           25.905136         18.551782           56.0
 73           20.740949           25.905136         18.551782           56.0
 74           20.740949           25.905136         18.551782           56.0
 75           16.503553           20.865070         11.801625           16.0
 76           22.936170           25.872340         16.595745           57.0

 [77 rows x 22 columns],
 'TLGRF5_exp':         date.y  fips      county  chosen_by_TLGRF5_exp  num_beds  count_homes  \
 0   2020-04-08  8045    Garfield                     1       283            4
 1   2020-04-20  8039      Elbert                     1        30            1
 2   2020-09-16  8039      Elbert                     1        30            1
 3   2020-11-23  8039      Elbert                     1        30            1
 4   2021-03-08  8039      Elbert                     1        30            1
 ..         ...   ...         ...                   ...       ...          ...
 78  2021-01-20  8017    Cheyenne                     1        38            1
 79  2021-01-26  8017    Cheyenne                     1        38            1
 80  2021-03-02  8075       Logan                     1       147            2
 81  2021-05-11  8105  Rio Grande                     1       180            3
 82  2021-06-03  8105  Rio Grande                     1       180            3

     num_inmates  count_facilities  FIPS      COUNTY     STATE        LAT  \
 0             0                 0  8045    Garfield  COLORADO  39.599352
 1             0                 0  8039      Elbert  COLORADO  39.315157
 2             0                 0  8039      Elbert  COLORADO  39.315157
 3             0                 0  8039      Elbert  COLORADO  39.315157
 4             0                 0  8039      Elbert  COLORADO  39.315157
 ..          ...               ...   ...         ...       ...        ...
 78            0                 0  8017    Cheyenne  COLORADO  38.835646
 79            0                 0  8017    Cheyenne  COLORADO  38.835646
 80         2041                 1  8075       Logan  COLORADO  40.728091
 81            0                 0  8105  Rio Grande  COLORADO  37.485853
 82            0                 0  8105  Rio Grande  COLORADO  37.485853

            LON    AREA_SQMI  E_TOTPOP  E_AGE17  E_AGE65  E_POV  \
 0  -107.909780  2947.543401     58538    15028     7034   4662
 1  -104.114076  1850.835533     25162     5514     3689   1110
 2  -104.114076  1850.835533     25162     5514     3689   1110
 3  -104.114076  1850.835533     25162     5514     3689   1110
 4  -104.114076  1850.835533     25162     5514     3689   1110

In [19]:
alg_rankings_dict = {}
columns_to_use = ["num_beds","num_inmates","E_TOTPOP","E_TOTPOP_RANK"]
for alg in alg_feature_dict.keys():
    int_df = alg_feature_dict[alg][columns_to_use]
    int_df["num_beds_RANK"] = int_df["num_beds"].rank(method="dense",ascending=False)
    int_df["num_inmates_RANK"] = int_df["num_inmates"].rank(method="dense",ascending=False)
    
    alg_rankings_dict[alg] = int_df

In [20]:
alg_rankings_dict

{'CDPHE_exp':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0         50            0     16537           30.0           22.0
 1         50            0     16537           30.0           22.0
 2         50            0     16537           30.0           22.0
 3         50            0     16537           30.0           22.0
 4         50            0     16537           30.0           22.0
 ..       ...          ...       ...            ...            ...
 78        60            0      8142           40.0           19.0
 79        30            0     25162           22.0           27.0
 80        38            0      2039           58.0           23.0
 81      1078            0    321030            8.0            2.0
 82      2308         1127    570427            4.0            1.0

     num_inmates_RANK
 0                6.0
 1                6.0
 2                6.0
 3                6.0
 4                6.0
 ..               ...
 78               6.0
 79               6.0
 80               6.0
 81               6.0
 82               5.0

 [83 rows x 6 columns],
 'TLGRF1_exp':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0        610            0    149998           11.0            1.0
 1        147         2041     21689           25.0            5.0
 2        123            0     16444           31.0            6.0
 3        161            0     25909           21.0            4.0
 4        161            0     25909           21.0            4.0
 ..       ...          ...       ...            ...            ...
 64        32            0      2350           57.0           19.0
 65        32            0      2350           57.0           19.0
 66        32            0      2350           57.0           19.0
 67        58            0     13060           34.0           12.0
 68        58            0     13060           34.0           12.0

     num_inmates_RANK
 0                4.0
 1                1.0
 2                4.0
 3                4.0
 4                4.0
 ..               ...
 64               4.0
 65               4.0
 66               4.0
 67               4.0
 68               4.0

 [69 rows x 6 columns],
 'TLGRF2_exp':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0        200            0     66120           12.0            3.0
 1        185            0     30346           19.0            4.0
 2         60            0     12908           35.0           16.0
 3         60            0     12908           35.0           16.0
 4         60            0     12908           35.0           16.0
 ..       ...          ...       ...            ...            ...
 68         0            0      4318           54.0           26.0
 69        56            0      5809           48.0           18.0
 70       105            0     12052           36.0           11.0
 71        86            0      3563           56.0           14.0
 72        86            0      3563           56.0           14.0

     num_inmates_RANK
 0                3.0
 1                3.0
 2                3.0
 3                3.0
 4                3.0
 ..               ...
 68               3.0
 69               3.0
 70               3.0
 71               3.0
 72               3.0

 [73 rows x 6 columns],
 'TLGRF3_exp':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0        119            0     14179           33.0           10.0
 1        119            0     14179           33.0           10.0
 2        119            0     14179           33.0           10.0
 3        119            0     14179           33.0           10.0
 4        119            0     14179           33.0           10.0
 ..       ...          ...       ...            ...            ...
 69       105            0     12052           36.0           11.0
 70        60            0      8142           40.0           14.0
 71        60            0      8142           40.0           14.0
 72        60            0      8142           40.0           14.0
 73        60            0      8142           40.0           14.0

     num_inmates_RANK
 0                3.0
 1                3.0
 2                3.0
 3                3.0
 4                3.0
 ..               ...
 69               3.0
 70               3.0
 71               3.0
 72               3.0
 73               3.0

 [74 rows x 6 columns],
 'TLGRF4_exp':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0         30            0     25162           22.0           24.0
 1         30            0     25162           22.0           24.0
 2         30            0     25162           22.0           24.0
 3         30            0     25162           22.0           24.0
 4         30            0     25162           22.0           24.0
 ..       ...          ...       ...            ...            ...
 72        86            0      3563           56.0           13.0
 73        86            0      3563           56.0           13.0
 74        86            0      3563           56.0           13.0
 75       444         8037     47002           16.0            1.0
 76        32            0      2350           57.0           23.0

     num_inmates_RANK
 0                4.0
 1                4.0
 2                4.0
 3                4.0
 4                4.0
 ..               ...
 72               4.0
 73               4.0
 74               4.0
 75               1.0
 76               4.0

 [77 rows x 6 columns],
 'TLGRF5_exp':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0        283            0     58538           13.0            4.0
 1         30            0     25162           22.0           28.0
 2         30            0     25162           22.0           28.0
 3         30            0     25162           22.0           28.0
 4         30            0     25162           22.0           28.0
 ..       ...          ...       ...            ...            ...
 78        38            0      2039           58.0           24.0
 79        38            0      2039           58.0           24.0
 80       147         2041     21689           25.0           10.0
 81       180            0     11351           37.0            7.0
 82       180            0     11351           37.0            7.0

     num_inmates_RANK
 0                5.0
 1                5.0
 2                5.0
 3                5.0
 4                5.0
 ..               ...
 78               5.0
 79               5.0
 80               2.0
 81               5.0
 82               5.0

 [83 rows x 6 columns],
 'TLGRF6_exp':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0          0            0     54357           15.0           22.0
 1          0            0     54357           15.0           22.0
 2         40            0      7635           42.0           17.0
 3         40            0      7635           42.0           17.0
 4         40            0      7635           42.0           17.0
 ..       ...          ...       ...            ...            ...
 80        58            0     13060           34.0           14.0
 81        58            0     13060           34.0           14.0
 82        60            0     12908           35.0           13.0
 83        60            0     12908           35.0           13.0
 84        60            0     12908           35.0           13.0

     num_inmates_RANK
 0                5.0
 1                5.0
 2                5.0
 3                5.0
 4                5.0
 ..               ...
 80               5.0
 81               5.0
 82               5.0
 83               5.0
 84               5.0

 [85 rows x 6 columns],
 'TLGRF7_exp':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0         50            0     16537           30.0           18.0
 1         50            0     16537           30.0           18.0
 2         50            0     16537           30.0           18.0
 3         50            0     16537           30.0           18.0
 4         50            0     16537           30.0           18.0
 ..       ...          ...       ...            ...            ...
 91        56            0      5809           48.0           17.0
 92        56            0      5809           48.0           17.0
 93        56            0      5809           48.0           17.0
 94        86            0      3563           56.0           13.0
 95       101            0     18325           27.0           12.0

     num_inmates_RANK
 0                4.0
 1                4.0
 2                4.0
 3                4.0
 4                4.0
 ..               ...
 91               4.0
 92               4.0
 93               4.0
 94               4.0
 95               4.0

 [96 rows x 6 columns],
 'TLGRF8_exp':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0          0            0      4318           54.0           20.0
 1          0            0      4318           54.0           20.0
 2          0            0      4318           54.0           20.0
 3         30            0     25162           22.0           19.0
 4         30            0     25162           22.0           19.0
 ..       ...          ...       ...            ...            ...
 64        58            0     13060           34.0           13.0
 65       147         2041     21689           25.0            7.0
 66        56            0      5809           48.0           14.0
 67        56            0      5809           48.0           14.0
 68        30            0      6465           46.0           19.0

     num_inmates_RANK
 0                4.0
 1                4.0
 2                4.0
 3                4.0
 4                4.0
 ..               ...
 64               4.0
 65               2.0
 66               4.0
 67               4.0
 68               4.0

 [69 rows x 6 columns],
 'TLGRF9_exp':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0         60            0     12908           35.0           16.0
 1         60            0     12908           35.0           16.0
 2         40            0      7635           42.0           20.0
 3         40            0      7635           42.0           20.0
 4         40            0      7635           42.0           20.0
 ..       ...          ...       ...            ...            ...
 82       147         2041     21689           25.0            9.0
 83       147         2041     21689           25.0            9.0
 84        37         1681      5630           49.0           21.0
 85        35            0      5548           50.0           22.0
 86       200            0     66120           12.0            5.0

     num_inmates_RANK
 0                5.0
 1                5.0
 2                5.0
 3                5.0
 4                5.0
 ..               ...
 82               2.0
 83               2.0
 84               3.0
 85               5.0
 86               5.0

 [87 rows x 6 columns],
 'CDPHE_logistic':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0         50            0     16537           30.0           22.0
 1         50            0     16537           30.0           22.0
 2         50            0     16537           30.0           22.0
 3         50            0     16537           30.0           22.0
 4         50            0     16537           30.0           22.0
 ..       ...          ...       ...            ...            ...
 78        60            0      8142           40.0           19.0
 79        30            0     25162           22.0           27.0
 80        38            0      2039           58.0           23.0
 81      1078            0    321030            8.0            2.0
 82      2308         1127    570427            4.0            1.0

     num_inmates_RANK
 0                6.0
 1                6.0
 2                6.0
 3                6.0
 4                6.0
 ..               ...
 78               6.0
 79               6.0
 80               6.0
 81               6.0
 82               5.0

 [83 rows x 6 columns],
 'TLGRF1_logistic':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0          0            0     54357           15.0           21.0
 1          0            0     54357           15.0           21.0
 2          0            0     54357           15.0           21.0
 3          0            0     54357           15.0           21.0
 4        185            0     30346           19.0            6.0
 ..       ...          ...       ...            ...            ...
 89        58            0     13060           34.0           15.0
 90        58            0     13060           34.0           15.0
 91        58            0     13060           34.0           15.0
 92        58            0     13060           34.0           15.0
 93        58            0     13060           34.0           15.0

     num_inmates_RANK
 0                5.0
 1                5.0
 2                5.0
 3                5.0
 4                5.0
 ..               ...
 89               5.0
 90               5.0
 91               5.0
 92               5.0
 93               5.0

 [94 rows x 6 columns],
 'TLGRF2_logistic':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0        610            0    149998           11.0            1.0
 1        610            0    149998           11.0            1.0
 2        610            0    149998           11.0            1.0
 3         30            0     25162           22.0           25.0
 4         30            0     25162           22.0           25.0
 ..       ...          ...       ...            ...            ...
 89        60            0      8142           40.0           17.0
 90        58            0     13060           34.0           18.0
 91        58            0     13060           34.0           18.0
 92        58            0     13060           34.0           18.0
 93        32            0      2350           57.0           24.0

     num_inmates_RANK
 0                5.0
 1                5.0
 2                5.0
 3                5.0
 4                5.0
 ..               ...
 89               5.0
 90               5.0
 91               5.0
 92               5.0
 93               5.0

 [94 rows x 6 columns],
 'TLGRF3_logistic':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0        200            0     66120           12.0            4.0
 1        139            0     24113           24.0            9.0
 2        123            0     16444           31.0           10.0
 3        123            0     16444           31.0           10.0
 4        161            0     25909           21.0            7.0
 ..       ...          ...       ...            ...            ...
 83        58            0     13060           34.0           17.0
 84        58            0     13060           34.0           17.0
 85        86            0      3563           56.0           14.0
 86        32            0      2350           57.0           22.0
 87        40            0      7635           42.0           20.0

     num_inmates_RANK
 0                5.0
 1                5.0
 2                5.0
 3                5.0
 4                5.0
 ..               ...
 83               5.0
 84               5.0
 85               5.0
 86               5.0
 87               5.0

 [88 rows x 6 columns],
 'TLGRF4_logistic':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0        283            0     58538           13.0            4.0
 1        185            0     30346           19.0            7.0
 2         40            0      7635           42.0           20.0
 3         40            0      7635           42.0           20.0
 4         40            0      7635           42.0           20.0
 ..       ...          ...       ...            ...            ...
 77       101            0     18325           27.0           13.0
 78       101            0     18325           27.0           13.0
 79       105            0     12052           36.0           12.0
 80       200            0     66120           12.0            6.0
 81         0            0     54357           15.0           24.0

     num_inmates_RANK
 0                3.0
 1                3.0
 2                3.0
 3                3.0
 4                3.0
 ..               ...
 77               3.0
 78               3.0
 79               3.0
 80               3.0
 81               3.0

 [82 rows x 6 columns],
 'TLGRF5_logistic':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0         50            0     16537           30.0           16.0
 1         50            0     16537           30.0           16.0
 2         50            0     16537           30.0           16.0
 3         40            0      7635           42.0           17.0
 4         40            0      7635           42.0           17.0
 ..       ...          ...       ...            ...            ...
 77        86            0      3563           56.0           12.0
 78       101            0     10069           38.0           10.0
 79        56            0      5809           48.0           15.0
 80        56            0      5809           48.0           15.0
 81        32            0      2350           57.0           20.0

     num_inmates_RANK
 0                4.0
 1                4.0
 2                4.0
 3                4.0
 4                4.0
 ..               ...
 77               4.0
 78               4.0
 79               4.0
 80               4.0
 81               4.0

 [82 rows x 6 columns],
 'TLGRF6_logistic':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0        147         2041     21689           25.0            9.0
 1         40            0      7635           42.0           21.0
 2         40            0      7635           42.0           21.0
 3         40            0      7635           42.0           21.0
 4         40            0      7635           42.0           21.0
 ..       ...          ...       ...            ...            ...
 74        86            0      3563           56.0           15.0
 75        86            0      3563           56.0           15.0
 76        86            0      3563           56.0           15.0
 77        86            0      3563           56.0           15.0
 78        98         1129     19164           26.0           14.0

     num_inmates_RANK
 0                2.0
 1                4.0
 2                4.0
 3                4.0
 4                4.0
 ..               ...
 74               4.0
 75               4.0
 76               4.0
 77               4.0
 78               3.0

 [79 rows x 6 columns],
 'TLGRF7_logistic':     num_beds  num_inmates  E_TOTPOP  E_TOTPOP_RANK  num_beds_RANK  \
 0         30            0     25162           22.0           20.0
 1         30            0     25162           22.0           20.0
 2         30            0     25162           22.0           20.0
 3         30            0     25162           22.0           20.0
 4         30            0     25162           22.0           20.0
 ..       ...          ...       ...            ...            ...
 63        35            0      5548           50.0           18.0
 64        35            0      5548           50.0           18.0
 65       323            0     28257           20.0            2.0
 66        30            0      6465           46.0           20.0
 67        30            0      6465           46.0           20.0

     num_inmates_RANK
 0                2.0
 1                2.0
 2                2.0
 3                2.0
 4                2.0
 ..               ...
 63               2.0
 64               2.0
 65               2.0
 66               2.0

In [21]:
alg_mean_rankings_dict = {}
alg_median_rankings_dict = {}
for alg in alg_rankings_dict.keys():
    alg_mean_rankings_dict[alg] = alg_rankings_dict[alg].mean()
    alg_median_rankings_dict[alg] = alg_rankings_dict[alg].median()

In [22]:
alg_mean_rankings_dict

{'CDPHE_exp': num_beds              158.867470
 num_inmates           589.843373
 E_TOTPOP            33324.120482
 E_TOTPOP_RANK          30.397590
 num_beds_RANK          15.831325
 num_inmates_RANK        5.397590
 dtype: float64,
 'TLGRF1_exp': num_beds               75.811594
 num_inmates           176.115942
 E_TOTPOP            12595.463768
 E_TOTPOP_RANK          41.637681
 num_beds_RANK          12.971014
 num_inmates_RANK        3.797101
 dtype: float64,
 'TLGRF2_exp': num_beds               81.958904
 num_inmates           123.041096
 E_TOTPOP            15444.753425
 E_TOTPOP_RANK          37.205479
 num_beds_RANK          16.561644
 num_inmates_RANK        2.863014
 dtype: float64,
 'TLGRF3_exp': num_beds               91.500000
 num_inmates           154.040541
 E_TOTPOP            16694.878378
 E_TOTPOP_RANK          36.581081
 num_beds_RANK          14.743243
 num_inmates_RANK        2.945946
 dtype: float64,
 'TLGRF4_exp': num_beds               86.272727
 num_inmates           155.532468
 E_TOTPOP            15788.675325
 E_TOTPOP_RANK          35.935065
 num_beds_RANK          14.922078
 num_inmates_RANK        3.909091
 dtype: float64,
 'TLGRF5_exp': num_beds              114.457831
 num_inmates           382.795181
 E_TOTPOP            23337.373494
 E_TOTPOP_RANK          32.289157
 num_beds_RANK          18.036145
 num_inmates_RANK        4.746988
 dtype: float64,
 'TLGRF6_exp': num_beds               98.529412
 num_inmates           450.635294
 E_TOTPOP            21921.329412
 E_TOTPOP_RANK          33.000000
 num_beds_RANK          13.905882
 num_inmates_RANK        4.658824
 dtype: float64,
 'TLGRF7_exp': num_beds              112.489583
 num_inmates           157.510417
 E_TOTPOP            22279.125000
 E_TOTPOP_RANK          32.125000
 num_beds_RANK          12.614583
 num_inmates_RANK        3.916667
 dtype: float64,
 'TLGRF8_exp': num_beds              121.376812
 num_inmates           311.260870
 E_TOTPOP            19339.985507
 E_TOTPOP_RANK          33.188406
 num_beds_RANK          10.449275
 num_inmates_RANK        3.855072
 dtype: float64,
 'TLGRF9_exp': num_beds              109.459770
 num_inmates           276.954023
 E_TOTPOP            21170.126437
 E_TOTPOP_RANK          30.896552
 num_beds_RANK          14.609195
 num_inmates_RANK        4.793103
 dtype: float64,
 'CDPHE_logistic': num_beds              158.867470
 num_inmates           589.843373
 E_TOTPOP            33324.120482
 E_TOTPOP_RANK          30.397590
 num_beds_RANK          15.831325
 num_inmates_RANK        5.397590
 dtype: float64,
 'TLGRF1_logistic': num_beds              127.521277
 num_inmates           507.138298
 E_TOTPOP            30771.925532
 E_TOTPOP_RANK          25.893617
 num_beds_RANK          12.106383
 num_inmates_RANK        4.585106
 dtype: float64,
 'TLGRF2_logistic': num_beds              119.053191
 num_inmates           256.414894
 E_TOTPOP            27173.563830
 E_TOTPOP_RANK          29.276596
 num_beds_RANK          15.510638
 num_inmates_RANK        4.755319
 dtype: float64,
 'TLGRF3_logistic': num_beds              102.443182
 num_inmates           184.659091
 E_TOTPOP            21399.681818
 E_TOTPOP_RANK          30.238636
 num_beds_RANK          14.159091
 num_inmates_RANK        4.840909
 dtype: float64,
 'TLGRF4_logistic': num_beds              110.231707
 num_inmates           321.573171
 E_TOTPOP            19997.500000
 E_TOTPOP_RANK          33.475610
 num_beds_RANK          15.256098
 num_inmates_RANK        2.902439
 dtype: float64,
 'TLGRF5_logistic': num_beds              128.231707
 num_inmates           446.817073
 E_TOTPOP            21374.341463
 E_TOTPOP_RANK          34.365854
 num_beds_RANK          12.451220
 num_inmates_RANK        3.792683
 dtype: float64,
 'TLGRF6_logistic': num_beds               98.417722
 num_inmates           141.860759
 E_TOTPOP            17483.202532
 E_TOTPOP_RANK          35.670886
 num_beds_RANK          15.936709
 num_inmates_RANK        3.924051
 dtype: float64,
 'TLGRF7_logistic': num_beds               91.088235
 num_inmates           236.382353
 E_TOTPOP            17175.897059
 E_TOTPOP_RANK          34.485294
 num_beds_RANK          12.176471
 num_inmates_RANK        1.970588
 dtype: float64,
 'TLGRF8_logistic': num_beds               88.507937
 num_inmates            53.365079
 E_TOTPOP            14216.936508
 E_TOTPOP_RANK          38.190476
 num_beds_RANK          12.539683
 num_inmates_RANK        1.968254
 dtype: float64,
 'TLGRF9_logistic': num_beds               95.558824
 num_inmates           434.029412
 E_TOTPOP            14861.161765
 E_TOTPOP_RANK          39.720588
 num_beds_RANK          12.529412
 num_inmates_RANK        3.808824
 dtype: float64}

In [23]:
alg_mean_rankings_df = pd.DataFrame()
alg_median_rankings_df = pd.DataFrame()
for alg in alg_mean_rankings_dict.keys():
    alg_mean_rankings_df = alg_mean_rankings_df.append(alg_mean_rankings_dict[alg], ignore_index=True)
    alg_median_rankings_df = alg_median_rankings_df.append(alg_median_rankings_dict[alg], ignore_index=True)
alg_mean_rankings_df["algorithm"] = alg_mean_rankings_dict.keys()
alg_median_rankings_df["algorithm"] = alg_median_rankings_dict.keys()

alg_mean_rankings_df = alg_mean_rankings_df[["algorithm"]+list(alg_mean_rankings_df.columns[:-1])]
alg_median_rankings_df = alg_median_rankings_df[["algorithm"]+list(alg_median_rankings_df.columns[:-1])]

confusion_CDPHE_TLGRF = pd.read_csv(os.path.join(OUTPUT_FOLDER,"confusion_CDPHE_TLGRF.csv"))
alg_mean_rankings_df = pd.merge(left=alg_mean_rankings_df,right=confusion_CDPHE_TLGRF[["algorithm","PPV","NPV"]],how="inner",on="algorithm")
alg_median_rankings_df = pd.merge(left=alg_median_rankings_df,right=confusion_CDPHE_TLGRF[["algorithm","PPV","NPV"]],how="inner",on="algorithm")


alg_mean_rankings_df.to_csv(os.path.join(OUTPUT_FOLDER,"alg_mean_rankings_df.csv"),index=False)
alg_median_rankings_df.to_csv(os.path.join(OUTPUT_FOLDER,"alg_median_rankings_df.csv"),index=False)

In [24]:
alg_mean_rankings_df

,algorithm,num_beds,num_inmates,E_TOTPOP,E_TOTPOP_RANK,num_beds_RANK,num_inmates_RANK,PPV,NPV
0,CDPHE_exp,158.867470,589.843373,33324.120482,30.397590,15.831325,5.397590,0.153846,0.950942
1,TLGRF1_exp,75.811594,176.115942,12595.463768,41.637681,12.971014,3.797101,0.136752,0.949950
2,TLGRF2_exp,81.958904,123.041096,15444.753425,37.205479,16.561644,2.863014,0.128205,0.949455
3,TLGRF3_exp,91.500000,154.040541,16694.878378,36.581081,14.743243,2.945946,0.102564,0.947968
4,TLGRF4_exp,86.272727,155.532468,15788.675325,35.935065,14.922078,3.909091,0.076923,0.946482
5,TLGRF5_exp,114.457831,382.795181,23337.373494,32.289157,18.036145,4.746988,0.059829,0.945491
6,TLGRF6_exp,98.529412,450.635294,21921.329412,33.000000,13.905882,4.658824,0.059829,0.945491
7,TLGRF7_exp,112.489583,157.510417,22279.125000,32.125000,12.614583,3.916667,0.051282,0.944995
8,TLGRF8_exp,121.376812,311.260870,19339.985507,33.188406,10.449275,3.855072,0.051282,0.944995
9,TLGRF9_exp,109.459770,276.954023,21170.126437,30.896552,14.609195,4.793103,0.025641,0.943508
10,CDPHE_logistic,158.867470,589.843373,33324.120482,30.397590,15.831325,5.397590,0.170940,0.951933
11,TLGRF1_logistic,127.521277,507.138298,30771.925532,25.893617,12.106383,4.585106,0.512821,0.971754
12,TLGRF2_logistic,119.053191,256.414894,27173.563830,29.276596,15.510638,4.755319,0.179487,0.952428
13,TLGRF3_logistic,102.443182,184.659091,21399.681818,30.238636,14.159091,4.840909,0.094017,0.947473
14,TLGRF4_logistic,110.231707,321.573171,19997.500000,33.475610,15.256098,2.902439,0.085470,0.946977
15,TLGRF5_logistic,128.231707,446.817073,21374.341463,34.365854,12.451220,3.792683,0.051282,0.944995
16,TLGRF6_logistic,98.417722,141.860759,17483.202532,35.670886,15.936709,3.924051,0.017094,0.943013
17,TLGRF7_logistic,91.088235,236.382353,17175.897059,34.485294,12.176471,1.970588,0.025641,0.943508
18,TLGRF8_logistic,88.507937,53.365079,14216.936508,38.190476,12.539683,1.968254,0.008547,0.942517
19,TLGRF9_logistic,95.558824,434.029412,14861.161765,39.720588,12.529412,3.808824,0.025641,0.943508

In [25]:
alg_feature_dict["CDPHE_logistic"].head()

,date.y,fips,county,chosen_by_CDPHE,num_beds,count_homes,num_inmates,count_facilities,FIPS,COUNTY,STATE,LAT,LON,AREA_SQMI,E_TOTPOP,E_AGE17,E_AGE65,E_POV,E_AGE17_PERCENTAGE,E_AGE65_PERCENTAGE,E_POV_PERCENTAGE,E_TOTPOP_RANK
0,2020-04-08,8051,Gunnison,1,50,1,0,0,8051,Gunnison,COLORADO,38.670499,-107.05688,3239.140212,16537,2929,2044,2084,17.711798,12.360162,12.602044,30.0
1,2020-07-22,8051,Gunnison,1,50,1,0,0,8051,Gunnison,COLORADO,38.670499,-107.05688,3239.140212,16537,2929,2044,2084,17.711798,12.360162,12.602044,30.0
2,2021-01-20,8051,Gunnison,1,50,1,0,0,8051,Gunnison,COLORADO,38.670499,-107.05688,3239.140212,16537,2929,2044,2084,17.711798,12.360162,12.602044,30.0
3,2021-04-25,8051,Gunnison,1,50,1,0,0,8051,Gunnison,COLORADO,38.670499,-107.05688,3239.140212,16537,2929,2044,2084,17.711798,12.360162,12.602044,30.0
4,2021-06-15,8051,Gunnison,1,50,1,0,0,8051,Gunnison,COLORADO,38.670499,-107.05688,3239.140212,16537,2929,2044,2084,17.711798,12.360162,12.602044,30.0

In [26]:
alg_feature_dict["TLGRF1_logistic"].head()

,date.y,fips,county,chosen_by_TLGRF1_logistic,num_beds,count_homes,num_inmates,count_facilities,FIPS,COUNTY,STATE,LAT,LON,AREA_SQMI,E_TOTPOP,E_AGE17,E_AGE65,E_POV,E_AGE17_PERCENTAGE,E_AGE65_PERCENTAGE,E_POV_PERCENTAGE,E_TOTPOP_RANK
0,2020-04-08,8037,Eagle,1,0,1,0,0,8037,Eagle,COLORADO,39.626992,-106.695169,1684.470957,54357,12118,5482,3793,22.293357,10.085178,6.977942,15.0
1,2020-07-15,8037,Eagle,1,0,1,0,0,8037,Eagle,COLORADO,39.626992,-106.695169,1684.470957,54357,12118,5482,3793,22.293357,10.085178,6.977942,15.0
2,2021-01-18,8037,Eagle,1,0,1,0,0,8037,Eagle,COLORADO,39.626992,-106.695169,1684.470957,54357,12118,5482,3793,22.293357,10.085178,6.977942,15.0
3,2021-01-26,8037,Eagle,1,0,1,0,0,8037,Eagle,COLORADO,39.626992,-106.695169,1684.470957,54357,12118,5482,3793,22.293357,10.085178,6.977942,15.0
4,2020-04-20,8029,Delta,1,185,3,0,0,8029,Delta,COLORADO,38.861595,-107.864892,1142.126464,30346,6176,7499,5145,20.351941,24.711659,16.954459,19.0

In [27]:
feature_cols = ["num_beds","num_inmates","E_TOTPOP"]
CDPHE_choice = alg_feature_dict["CDPHE_logistic"]
TLGRF1_logistic_choice = alg_feature_dict["TLGRF1_logistic"]
#print("1 sided t-test of CDPHE against TLGRF1_logistic")
for feature in feature_cols:
    tstat, pvalue = scipy.stats.ttest_ind(a=CDPHE_choice[feature], b=TLGRF1_logistic_choice[feature],equal_var=False)
    print("For {}, t-statistic is {}, pvalue is {}".format(feature,tstat,pvalue))

For num_beds, t-statistic is 0.9345124664521997, pvalue is 0.3521515534519438
For num_inmates, t-statistic is 0.3339051388372595, pvalue is 0.7388853661726668
For E_TOTPOP, t-statistic is 0.30826805328597223, pvalue is 0.7585173361515981

In [28]:
CDPHE_choice["num_beds"].mean(), CDPHE_choice["num_beds"].var()**0.5

(158.86746987951807, 284.7508868948837)

In [29]:
rankings_df.mean()

rankings_data = {"Mean Total Nursing Home Beds": [rankings_df.mean()["total_beds_x"],rankings_df.mean()["total_beds_y"]]}
rankings_data["Mean Total Inmate Capacity"] = [rankings_df.mean()["total_inmates_x"],rankings_df.mean()["total_inmates_y"]]
rankings_data["Mean Total County Population"] = [rankings_df.mean()["POP_RANK_x"],rankings_df.mean()["POP_RANK_y"]]

rankings_table = pd.DataFrame.from_dict(rankings_data, orient="index")
rankings_table = rankings_table.rename(columns={0:"CDPHE", 1:"TLGRF"})
rankings_table.index.rename(name="Rank",inplace=True)
# Write to CSV
rankings_table.to_csv(os.path.join(OUTPUT_FOLDER,"rankings_table.csv"))
# Write to xtable
with open(os.path.join(OUTPUT_FOLDER,"rankings_table.tex"),"w") as tf:
    tf.write(rankings_table.to_latex())

rankings_table

NameError: name 'rankings_df' is not defined

In [ ]:
rankings_table.to_latex()

In [ ]:
CDPHE_not_TLGRF = list(set(CDPHE_choice_df["fips"]) - set(CDPHE_choice_df["fips"]).intersection(set(TLGRF_choice_df["fips"])))
CDPHE_choice_df[CDPHE_choice_df["fips"].isin(CDPHE_not_TLGRF)]

In [ ]:
for feature in X_vector_cols:
    Y_vector = TLGRF_choice_df[feature] - CDPHE_choice_df[feature]
    Y_bar = Y_vector.mean
    cov = EmpiricalCovariance().fit(np.array([Y_vector]))
    Tsquare = abs(len(Y_vector)*(Ybar.T@np.linalg.inv(cov.covariance_)@Ybar))
    print("For feature {}, T2 statistic is {}".format(feature,Tsquare))

In [ ]:
cov = EmpiricalCovariance().fit(Y_vector)
Ybar = Y_vector.mean()
cov.covariance_, Ybar

In [ ]:
Tsquare = len(Y_vector)*(Ybar.T@np.linalg.inv(cov.covariance_)@Ybar)
abs(Tsquare)

In [ ]:
cov.mahalanobis(Y_vector)