In [11]:
list.of.packages <- c("ggplot2", "Rcpp", "grf", "caret", "mltools", "rpart", "minpack.lm", "doParallel", "rattle", "anytime","rlist")
list.of.packages <- c(list.of.packages, "zoo", "dtw", "foreach", "evaluate","rlist","data.table","plyr","dplyr")


new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, lib='/home/zwang937/local/R_libs', repos="http://cran.us.r-project.org", dependencies = TRUE, INSTALL_opts = '--no-lock')


lapply(list.of.packages, require, character.only = TRUE)

Loading required package: ggplot2

Loading required package: Rcpp

Loading required package: caret

Loading required package: lattice

Loading required package: mltools

Loading required package: rpart

Loading required package: minpack.lm

Loading required package: doParallel

Loading required package: foreach

Loading required package: iterators

Loading required package: parallel

Loading required package: rattle

Loading required package: tibble

Loading required package: bitops

Rattle: A free graphical interface for data science with R.
Version 5.5.1 Copyright (c) 2006-2021 Togaware Pty Ltd.
Type 'rattle()' to shake, rattle, and roll your data.

Loading required package: anytime

Loading required package: rlist

Loading required package: zoo


Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric


Loading required package: dtw

Loading required package: proxy


Attaching package: ‘proxy’


The following objects are masked from ‘package:stats’:

    as.dist, dist


The following object is masked from ‘package:base’:

    as.matrix


Loaded dtw v1.22-3. See ?dtw for help, citation("dtw") for use in publication.


Loading required package: evaluate

Loading required package: data.table

Loading required package: plyr

Loading required package: dplyr


Attaching package: ‘dplyr’


The following objects are masked from ‘package:plyr’:

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize


The following objects are masked from ‘package:data.table’:

    between, first, last


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[[1]]
[1] TRUE

[[2]]
[1] TRUE

[[3]]
[1] TRUE

[[4]]
[1] TRUE

[[5]]
[1] TRUE

[[6]]
[1] TRUE

[[7]]
[1] TRUE

[[8]]
[1] TRUE

[[9]]
[1] TRUE

[[10]]
[1] TRUE

[[11]]
[1] TRUE

[[12]]
[1] TRUE

[[13]]
[1] TRUE

[[14]]
[1] TRUE

[[15]]
[1] TRUE

[[16]]
[1] TRUE

[[17]]
[1] TRUE

[[18]]
[1] TRUE

[[19]]
[1] TRUE

In [13]:
GRF_RDS_directory <- "./classical_grf_results/classical_grf_windowsize=2_numtrees=200"
GRF_object_fname <- "grf_stateforest_cutoff=999.rds"

GRF_object_fpath <- file.path(GRF_RDS_directory, GRF_object_fname)


GRF_object <- readRDS(GRF_object_fpath)

In [14]:
length(unique(GRF_object$X.orig$fips))

[1] 2422

In [15]:
GRF_object$X.orig

     fips  log_rolled_cases.y LAT      LON        AREA_SQMI   E_TOTPOP E_HU
1    1001  4.752358           32.53224 -86.64644   594.4435    55200    23315
2    1001  4.752358           32.53224 -86.64644   594.4435    55200    23315
3    1003  5.906529           30.65922 -87.74607  1589.7930   208107   111945
4    1003  5.906529           30.65922 -87.74607  1589.7930   208107   111945
5    1005  3.547151           31.87025 -85.40510   885.0016    25782    11937
6    1005  3.547151           31.87025 -85.40510   885.0016    25782    11937
7    1007  3.983679           33.01589 -87.12715   622.4611    22527     9161
8    1007  3.983679           33.01589 -87.12715   622.4611    22527     9161
9    1009  5.759803           33.97736 -86.56644   644.8305    57645    24222
10   1009  5.759803           33.97736 -86.56644   644.8305    57645    24222
11   1013  3.332205           31.75167 -86.68197   776.8382    20025    10026
12   1013  3.332205           31.75167 -86.68197   776.8382    20025    10026
13   1015  7.236134           33.77052 -85.82791   605.8673   115098    53682
14   1015  7.236134           33.77052 -85.82791   605.8673   115098    53682
15   1017  3.784190           32.91550 -85.39403   596.5606    33826    16981
16   1017  3.784190           32.91550 -85.39403   596.5606    33826    16981
17   1019  3.862232           34.06952 -85.65424   553.5248    25853    16531
18   1019  3.862232           34.06952 -85.65424   553.5248    25853    16531
19   1021  4.429115           32.85405 -86.72661   692.8512    43930    19586
20   1021  4.429115           32.85405 -86.72661   692.8512    43930    19586
21   1025  3.295837           31.68552 -87.81862  1238.4199    24387    12741
22   1025  3.295837           31.68552 -87.81862  1238.4199    24387    12741
23   1027  3.103946           33.27040 -85.86352   603.9608    13378     6802
24   1027  3.103946           33.27040 -85.86352   603.9608    13378     6802
25   1029  3.263576           33.67196 -85.51613   560.1042    14938     6806
26   1029  3.263576           33.67196 -85.51613   560.1042    14938     6806
27   1031  4.404976           31.40226 -85.98960   678.9858    51288    23088
28   1031  4.404976           31.40226 -85.98960   678.9858    51288    23088
29   1033  4.823732           34.70311 -87.80146   592.7447    54495    26466
30   1033  4.823732           34.70311 -87.80146   592.7447    54495    26466
⋮    ⋮     ⋮                  ⋮        ⋮          ⋮           ⋮        ⋮
4815 56013  5.159876          43.05483 -108.60894  9183.58620   40076   17983
4816 56013  5.159876          43.05483 -108.60894  9183.58620   40076   17983
4817 56015  3.575551          42.08946 -104.35354  2225.61217   13438    6031
4818 56015  3.575551          42.08946 -104.35354  2225.61217   13438    6031
4819 56019  3.071370          44.04405 -106.58854  4154.15021    8515    4618
4820 56019  3.071370          44.04405 -106.58854  4154.15021    8515    4618
4821 56021  5.363302          41.29283 -104.66039  2685.86256   97692   42922
4822 56021  5.363302          41.29283 -104.66039  2685.86256   97692   42922
4823 56023  3.996889          42.22999 -110.68296  4075.33508   19011    9319
4824 56023  3.996889          42.22999 -110.68296  4075.33508   19011    9319
4825 56025  5.549632          42.97765 -106.76822  5340.52241   80610   36703
4826 56025  5.549632          42.97765 -106.76822  5340.52241   80610   36703
4827 56029  3.964886          44.49239 -109.59360  6939.03584   29121   14324
4828 56029  3.964886          44.49239 -109.59360  6939.03584   29121   14324
4829 56033  4.512428          44.78137 -106.88121  2523.36001   30012   14779
4830 56033  4.512428          44.78137 -106.88121  2523.36001   30012   14779
4831 56035  3.844050          42.76793 -109.91617  4886.47950    9951    5989
4832 56035  3.844050          42.76793 -109.91617  4886.47950    9951    5989
4833 56037  3.122994          41.66033 -108.87568 10426.97573   44117   19628
4834 56037  3.122994          41.66033 -108.87568 10426.97573   44117   19628
4835 56039  4.941642          44.04866 -110.42609  3996.84462   23059   13680
4836 56039  4.941642          44.04866 -110.42609  3996.84462   23059   13680
4837 56041  3.806662          41.28473 -110.55895  2081.71981   20609    8972
4838 56041  3.806662          41.28473 -110.55895  2081.71981   20609    8972
4839 78010  4.718499          17.74600  -64.70330          NA      NA      NA
4840 78010  4.718499          17.74600  -64.70330          NA      NA      NA
4841 78030  4.183140          18.33333  -64.91667          NA      NA      NA
4842 78030  4.183140          18.33333  -64.91667          NA      NA      NA
4843 99999 10.663559          40.65857  -73.95064    57.51865 1632480  855716
4844 99999 10.663559          40.65857  -73.95064    57.51865 1632480  855716
     E_HH   E_POV  E_UNEMP ⋯ Variant...XBB Variant...XBB.1.16 Variant...XBB.1.5
1    21115   8422  1065    ⋯ 0.002586835   0                  0
2    21115   8422  1065    ⋯ 0.002586835   0                  0
3    78622  21653  4343    ⋯ 0.002586835   0                  0
4    78622  21653  4343    ⋯ 0.002586835   0                  0
5     9186   6597   918    ⋯ 0.002586835   0                  0
6     9186   6597   918    ⋯ 0.002586835   0                  0
7     6840   2863   658    ⋯ 0.002586835   0                  0
8     6840   2863   658    ⋯ 0.002586835   0                  0
9    20600   8220   909    ⋯ 0.002586835   0                  0
10   20600   8220   909    ⋯ 0.002586835   0                  0
11    6708   4640   567    ⋯ 0.002586835   0                  0
12    6708   4640   567    ⋯ 0.002586835   0                  0
13   45033  20819  4628    ⋯ 0.002586835   0                  0
14   45033  20819  4628    ⋯ 0.002586835   0                  0
15   13516   5531   773    ⋯ 0.002586835   0                  0
16   13516   5531   773    ⋯ 0.002586835   0                  0
17   10606   3827   581    ⋯ 0.002586835   0                  0
18   10606   3827   581    ⋯ 0.002586835   0                  0
19   16751   8034  1336    ⋯ 0.002586835   0                  0
20   16751   8034  1336    ⋯ 0.002586835   0                  0
21    9358   6088  1283    ⋯ 0.002586835   0                  0
22    9358   6088  1283    ⋯ 0.002586835   0                  0
23    5236   2405   378    ⋯ 0.002586835   0                  0
24    5236   2405   378    ⋯ 0.002586835   0                  0
25    5726   2719   458    ⋯ 0.002586835   0                  0
26    5726   2719   458    ⋯ 0.002586835   0                  0
27   19789   7604  1371    ⋯ 0.002586835   0                  0
28   19789   7604  1371    ⋯ 0.002586835   0                  0
29   21799   8785  1397    ⋯ 0.002586835   0                  0
30   21799   8785  1397    ⋯ 0.002586835   0                  0
⋮    ⋮      ⋮      ⋮       ⋱ ⋮             ⋮                  ⋮
4815  15003   5352  1174   ⋯ 0.001847094   0                  0
4816  15003   5352  1174   ⋯ 0.001847094   0                  0
4817   5209   1485   463   ⋯ 0.001847094   0                  0
4818   5209   1485   463   ⋯ 0.001847094   0                  0
4819   3828    960   181   ⋯ 0.001847094   0                  0
4820   3828    960   181   ⋯ 0.001847094   0                  0
4821  39179   9540  2628   ⋯ 0.001847094   0                  0
4822  39179   9540  2628   ⋯ 0.001847094   0                  0
4823   7075   1710   424   ⋯ 0.001847094   0                  0
4824   7075   1710   424   ⋯ 0.001847094   0                  0
4825  32851   7568  1998   ⋯ 0.001847094   0                  0
4826  32851   7568  1998   ⋯ 0.001847094   0                  0
4827  11977   2180   508   ⋯ 0.001847094   0                  0
4828  11977   2180   508   ⋯ 0.001847094   0                  0
4829  13159   1797   416   ⋯ 0.001847094   0                  0
4830  13159   1797   416   ⋯ 0.001847094   0                  0
4831   3275    828   195   ⋯ 0.001847094   0                  0
4832   3275    828   195   ⋯ 0.001847094   0                  0
4833  15871   5237  1213   ⋯ 0.001847094   0                  0
4834  15871   5237  1213   ⋯ 0.001847094   0                  0
4835   9158   1619   210   ⋯ 0.001847094   0                  0
4836   9158   1619   210   ⋯ 0.001847094   0                  0
4837   7735   2552   614   ⋯ 0.001847094   0                  0
4838   7735   2552   614   ⋯ 0.001847094   0                  0
4839     NA     NA    NA   ⋯ 0.001185921   0                  0
4840     NA     NA    NA   ⋯ 0.001185921   0                  0
4841     NA     NA    NA   ⋯ 0.001185921   0                  0
4842     NA     NA    NA   ⋯ 0.001185921   0                  0
4843 758133 295165 70250   ⋯ 0.001185921   0                  0
4844 758133 295165 70250   ⋯ 0.001185921   0                  0
     Variant...XBB.1.5.1 Variant...XBB.1.9.1 Variant...XBB.1.9.2
1    0                   0                   0
2    0                   0                   0
3    0                   0                   0
4    0                   0                   0
5    0                   0                   0
6    0                   0                   0
7    0                   0                   0
8    0                   0                   0
9    0                   0                   0
10   0                   0                   0
11   0                   0                   0
12   0                   0                   0
13   0                   0                   0
14   0                   0                   0
15   0                   0                   0
16   0                   0                   0
17   0                   0                   0
18   0                   0                   0
19   0                   0                   0
20   0                   0                   0
21   0                   0                   0
22   0                   0                   0
23   0                   0                   0
24   0                   0                   0
25   0                   0                   0
26   0                   0                   0
27   0                   0                   0
28   0                   0                   0
29   0                   0                   0
30   0                   0                   0
⋮    ⋮                   ⋮                   ⋮
4815 0                   0                   0
4816 0                   0                   0
4817 0                   0                   0
4818 0                   0                   0
4819 0                   0                   0
4820 0                   0                   0
4821 0                   0                   0
4822 0                   0                   0
4823 0                   0                   0
4824 0                   0                   0
4825 0                   0                   0
4826 0                   0                   0
4827 0                   0                   0
4828 0                   0                   0
4829 0                   0                   0
4830 0                   0                   0
4831 0                   0                   0
4832 0                   0                   0
4833 0                   0                   0
4834 0                   0                   0
4835 0                   0                   0
4836 0                   0                   0
4837 0                   0                   0
4838 0                   0                   0
4839 0                   0                   0
4840 0                   0                   0
4841 0                   0                   0
4842 0                   0                   0
4843 0                   0                   0
4844 0                   0                   0
     Variant...XBB.2.3 cutoff t0.lm        r.lm
1    0                 999    1.143848e+03 -3.258434e-02
2    0                 999    1.143848e+03 -3.258434e-02
3    0                 999    1.128284e+03 -4.533580e-02
4    0                 999    1.128284e+03 -4.533580e-02
5    0                 999    1.103961e+03 -3.347593e-02
6    0                 999    1.103961e+03 -3.347593e-02
7    0                 999    1.111217e+03 -3.518631e-02
8    0                 999    1.111217e+03 -3.518631e-02
9    0                 999    8.982348e+02  5.773356e-02
10   0                 999    8.982348e+02  5.773356e-02
11   0                 999    1.032591e+03 -9.633111e-02
12   0                 999    1.032591e+03 -9.633111e-02
13   0                 999    1.106531e+03 -6.667364e-02
14   0                 999    1.106531e+03 -6.667364e-02
15   0                 999    1.093223e+03 -3.974033e-02
16   0                 999    1.093223e+03 -3.974033e-02
17   0                 999    1.112978e+03 -3.359094e-02
18   0                 999    1.112978e+03 -3.359094e-02
19   0                 999    1.113948e+03 -3.819909e-02
20   0                 999    1.113948e+03 -3.819909e-02
21   0                 999    1.052964e+03 -5.996346e-02
22   0                 999    1.052964e+03 -5.996346e-02
23   0                 999    4.942298e+15 -6.280370e-16
24   0                 999    4.942298e+15 -6.280370e-16
25   0                 999    1.195442e+03 -1.652930e-02
26   0                 999    1.195442e+03 -1.652930e-02
27   0                 999    1.416469e+03 -1.052641e-02
28   0                 999    1.416469e+03 -1.052641e-02
29   0                 999    9.980000e+02  0.000000e+00
30   0                 999    9.980000e+02  0.000000e+00
⋮    ⋮                 ⋮      ⋮            ⋮
4815 0                 999     733.3497     0.019496962
4816 0                 999     733.3497     0.019496962
4817 0                 999     847.2380     0.023716527
4818 0                 999     847.2380     0.023716527
4819 0                 999     880.5268     0.026145280
4820 0                 999     880.5268     0.026145280
4821 0                 999     266.8877     0.007335811
4822 0                 999     266.8877     0.007335811
4823 0                 999     778.4626     0.018205964
4824 0                 999     778.4626     0.018205964
4825 0                 999    1582.8289    -0.009489326
4826 0                 999    1582.8289    -0.009489326
4827 0                 999    1288.6217    -0.013642776
4828 0                 999    1288.6217    -0.013642776
4829 0                 999    1126.5910    -0.035091320
4830 0                 999    1126.5910    -0.035091320
4831 0                 999     917.5305     0.047770276
4832 0                 999     917.5305     0.047770276
4833 0                 999    1031.8828    -0.092170460
4834 0                 999    1031.8828    -0.092170460
4835 0                 999    1174.8810    -0.027937668
4836 0                 999    1174.8810    -0.027937668
4837 0                 999    1071.0238    -0.052129065
4838 0                 999    1071.0238    -0.052129065
4839 0                 999    1098.3807    -0.047006042
4840 0                 999    1098.3807    -0.047006042
4841 0                 999    1170.4510    -0.024256978
4842 0                 999    1170.4510    -0.024256978
4843 0                 999    1632.1677    -0.016815044
4844 0                 999    1632.1677    -0.016815044

In [17]:
BLOCK_FOLDER <- "../../data/block_windowsize=2"
BLOCK_999_fname <- "block_999.csv"

BLOCK_999_fpath <- file.path(BLOCK_FOLDER, BLOCK_999_fname)

block_999 <- readr::read_csv(BLOCK_999_fpath)

Rows: 4844 Columns: 480
── Column specification ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr    (2): county, state
dbl  (438): fips, State_FIPS_Code, log_rolled_cases.x, shifted_time, log_rol...
lgl   (39): death, deathConfirmed, deathIncrease, deathProbable, hospitalize...
date   (1): datetime

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [18]:
block_999

     fips  county        state          datetime   State_FIPS_Code
1    1001  Autauga       Alabama        2022-10-15 1
2    1001  Autauga       Alabama        2022-10-16 1
3    1003  Baldwin       Alabama        2022-10-15 1
4    1003  Baldwin       Alabama        2022-10-16 1
5    1005  Barbour       Alabama        2022-10-15 1
6    1005  Barbour       Alabama        2022-10-16 1
7    1007  Bibb          Alabama        2022-10-16 1
8    1007  Bibb          Alabama        2022-10-15 1
9    1009  Blount        Alabama        2022-10-16 1
10   1009  Blount        Alabama        2022-10-15 1
11   1013  Butler        Alabama        2022-10-15 1
12   1013  Butler        Alabama        2022-10-16 1
13   1015  Calhoun       Alabama        2022-10-15 1
14   1015  Calhoun       Alabama        2022-10-16 1
15   1017  Chambers      Alabama        2022-10-16 1
16   1017  Chambers      Alabama        2022-10-15 1
17   1019  Cherokee      Alabama        2022-10-15 1
18   1019  Cherokee      Alabama        2022-10-16 1
19   1021  Chilton       Alabama        2022-10-16 1
20   1021  Chilton       Alabama        2022-10-15 1
21   1025  Clarke        Alabama        2022-10-16 1
22   1025  Clarke        Alabama        2022-10-15 1
23   1027  Clay          Alabama        2022-10-15 1
24   1027  Clay          Alabama        2022-10-16 1
25   1029  Cleburne      Alabama        2022-10-16 1
26   1029  Cleburne      Alabama        2022-10-15 1
27   1031  Coffee        Alabama        2022-10-16 1
28   1031  Coffee        Alabama        2022-10-15 1
29   1033  Colbert       Alabama        2022-10-15 1
30   1033  Colbert       Alabama        2022-10-16 1
⋮    ⋮     ⋮             ⋮              ⋮          ⋮
4815 56013 Fremont       Wyoming        2022-10-15 56
4816 56013 Fremont       Wyoming        2022-10-16 56
4817 56015 Goshen        Wyoming        2022-10-16 56
4818 56015 Goshen        Wyoming        2022-10-15 56
4819 56019 Johnson       Wyoming        2022-10-15 56
4820 56019 Johnson       Wyoming        2022-10-16 56
4821 56021 Laramie       Wyoming        2022-10-15 56
4822 56021 Laramie       Wyoming        2022-10-16 56
4823 56023 Lincoln       Wyoming        2022-10-16 56
4824 56023 Lincoln       Wyoming        2022-10-15 56
4825 56025 Natrona       Wyoming        2022-10-15 56
4826 56025 Natrona       Wyoming        2022-10-16 56
4827 56029 Park          Wyoming        2022-10-16 56
4828 56029 Park          Wyoming        2022-10-15 56
4829 56033 Sheridan      Wyoming        2022-10-16 56
4830 56033 Sheridan      Wyoming        2022-10-15 56
4831 56035 Sublette      Wyoming        2022-10-16 56
4832 56035 Sublette      Wyoming        2022-10-15 56
4833 56037 Sweetwater    Wyoming        2022-10-16 56
4834 56037 Sweetwater    Wyoming        2022-10-15 56
4835 56039 Teton         Wyoming        2022-10-16 56
4836 56039 Teton         Wyoming        2022-10-15 56
4837 56041 Uinta         Wyoming        2022-10-16 56
4838 56041 Uinta         Wyoming        2022-10-15 56
4839 78010 St. Croix     Virgin Islands 2022-10-15 NA
4840 78010 St. Croix     Virgin Islands 2022-10-16 NA
4841 78030 St. Thomas    Virgin Islands 2022-10-16 NA
4842 78030 St. Thomas    Virgin Islands 2022-10-15 NA
4843 99999 New York City New York       2022-10-15 36
4844 99999 New York City New York       2022-10-16 36
     log_rolled_cases.x shifted_time log_rolled_cases.y LAT      LON        ⋯
1    4.752358           0            4.752358           32.53224 -86.64644  ⋯
2    4.719774           1            4.752358           32.53224 -86.64644  ⋯
3    5.906529           0            5.906529           30.65922 -87.74607  ⋯
4    5.861193           1            5.906529           30.65922 -87.74607  ⋯
5    3.547151           0            3.547151           31.87025 -85.40510  ⋯
6    3.513675           1            3.547151           31.87025 -85.40510  ⋯
7    3.948493           1            3.983679           33.01589 -87.12715  ⋯
8    3.983679           0            3.983679           33.01589 -87.12715  ⋯
9    5.817536           1            5.759803           33.97736 -86.56644  ⋯
10   5.759803           0            5.759803           33.97736 -86.56644  ⋯
11   3.332205           0            3.332205           31.75167 -86.68197  ⋯
12   3.235873           1            3.332205           31.75167 -86.68197  ⋯
13   7.236134           0            7.236134           33.77052 -85.82791  ⋯
14   7.169460           1            7.236134           33.77052 -85.82791  ⋯
15   3.744449           1            3.784190           32.91550 -85.39403  ⋯
16   3.784190           0            3.784190           32.91550 -85.39403  ⋯
17   3.862232           0            3.862232           34.06952 -85.65424  ⋯
18   3.828641           1            3.862232           34.06952 -85.65424  ⋯
19   4.390916           1            4.429115           32.85405 -86.72661  ⋯
20   4.429115           0            4.429115           32.85405 -86.72661  ⋯
21   3.235873           1            3.295837           31.68552 -87.81862  ⋯
22   3.295837           0            3.295837           31.68552 -87.81862  ⋯
23   3.103946           0            3.103946           33.27040 -85.86352  ⋯
24   3.103946           1            3.103946           33.27040 -85.86352  ⋯
25   3.247047           1            3.263576           33.67196 -85.51613  ⋯
26   3.263576           0            3.263576           33.67196 -85.51613  ⋯
27   4.394449           1            4.404976           31.40226 -85.98960  ⋯
28   4.404976           0            4.404976           31.40226 -85.98960  ⋯
29   4.823732           0            4.823732           34.70311 -87.80146  ⋯
30   4.823732           1            4.823732           34.70311 -87.80146  ⋯
⋮    ⋮                  ⋮            ⋮                  ⋮        ⋮          ⋱
4815  5.159876          0             5.159876          43.05483 -108.60894 ⋯
4816  5.179373          1             5.159876          43.05483 -108.60894 ⋯
4817  3.599267          1             3.575551          42.08946 -104.35354 ⋯
4818  3.575551          0             3.575551          42.08946 -104.35354 ⋯
4819  3.071370          0             3.071370          44.04405 -106.58854 ⋯
4820  3.097515          1             3.071370          44.04405 -106.58854 ⋯
4821  5.363302          0             5.363302          41.29283 -104.66039 ⋯
4822  5.370638          1             5.363302          41.29283 -104.66039 ⋯
4823  4.015095          1             3.996889          42.22999 -110.68296 ⋯
4824  3.996889          0             3.996889          42.22999 -110.68296 ⋯
4825  5.549632          0             5.549632          42.97765 -106.76822 ⋯
4826  5.540142          1             5.549632          42.97765 -106.76822 ⋯
4827  3.951244          1             3.964886          44.49239 -109.59360 ⋯
4828  3.964886          0             3.964886          44.49239 -109.59360 ⋯
4829  4.477337          1             4.512428          44.78137 -106.88121 ⋯
4830  4.512428          0             4.512428          44.78137 -106.88121 ⋯
4831  3.891820          1             3.844050          42.76793 -109.91617 ⋯
4832  3.844050          0             3.844050          42.76793 -109.91617 ⋯
4833  3.030824          1             3.122994          41.66033 -108.87568 ⋯
4834  3.122994          0             3.122994          41.66033 -108.87568 ⋯
4835  4.913705          1             4.941642          44.04866 -110.42609 ⋯
4836  4.941642          0             4.941642          44.04866 -110.42609 ⋯
4837  3.754533          1             3.806662          41.28473 -110.55895 ⋯
4838  3.806662          0             3.806662          41.28473 -110.55895 ⋯
4839  4.718499          0             4.718499          17.74600  -64.70330 ⋯
4840  4.671493          1             4.718499          17.74600  -64.70330 ⋯
4841  4.158883          1             4.183140          18.33333  -64.91667 ⋯
4842  4.183140          0             4.183140          18.33333  -64.91667 ⋯
4843 10.663559          0            10.663559          40.65857  -73.95064 ⋯
4844 10.646744          1            10.663559          40.65857  -73.95064 ⋯
     Variant % XBB.1.16 Variant % XBB.1.5 Variant % XBB.1.5.1
1    0                  0                 0
2    0                  0                 0
3    0                  0                 0
4    0                  0                 0
5    0                  0                 0
6    0                  0                 0
7    0                  0                 0
8    0                  0                 0
9    0                  0                 0
10   0                  0                 0
11   0                  0                 0
12   0                  0                 0
13   0                  0                 0
14   0                  0                 0
15   0                  0                 0
16   0                  0                 0
17   0                  0                 0
18   0                  0                 0
19   0                  0                 0
20   0                  0                 0
21   0                  0                 0
22   0                  0                 0
23   0                  0                 0
24   0                  0                 0
25   0                  0                 0
26   0                  0                 0
27   0                  0                 0
28   0                  0                 0
29   0                  0                 0
30   0                  0                 0
⋮    ⋮                  ⋮                 ⋮
4815 0                  0                 0
4816 0                  0                 0
4817 0                  0                 0
4818 0                  0                 0
4819 0                  0                 0
4820 0                  0                 0
4821 0                  0                 0
4822 0                  0                 0
4823 0                  0                 0
4824 0                  0                 0
4825 0                  0                 0
4826 0                  0                 0
4827 0                  0                 0
4828 0                  0                 0
4829 0                  0                 0
4830 0                  0                 0
4831 0                  0                 0
4832 0                  0                 0
4833 0                  0                 0
4834 0                  0                 0
4835 0                  0                 0
4836 0                  0                 0
4837 0                  0                 0
4838 0                  0                 0
4839 0                  0                 0
4840 0                  0                 0
4841 0                  0                 0
4842 0                  0                 0
4843 0                  0                 0
4844 0                  0                 0
     Variant % XBB.1.9.1 Variant % XBB.1.9.2 Variant % XBB.2.3 cutoff
1    0                   0                   0                 999
2    0                   0                   0                 999
3    0                   0                   0                 999
4    0                   0                   0                 999
5    0                   0                   0                 999
6    0                   0                   0                 999
7    0                   0                   0                 999
8    0                   0                   0                 999
9    0                   0                   0                 999
10   0                   0                   0                 999
11   0                   0                   0                 999
12   0                   0                   0                 999
13   0                   0                   0                 999
14   0                   0                   0                 999
15   0                   0                   0                 999
16   0                   0                   0                 999
17   0                   0                   0                 999
18   0                   0                   0                 999
19   0                   0                   0                 999
20   0                   0                   0                 999
21   0                   0                   0                 999
22   0                   0                   0                 999
23   0                   0                   0                 999
24   0                   0                   0                 999
25   0                   0                   0                 999
26   0                   0                   0                 999
27   0                   0                   0                 999
28   0                   0                   0                 999
29   0                   0                   0                 999
30   0                   0                   0                 999
⋮    ⋮                   ⋮                   ⋮                 ⋮
4815 0                   0                   0                 999
4816 0                   0                   0                 999
4817 0                   0                   0                 999
4818 0                   0                   0                 999
4819 0                   0                   0                 999
4820 0                   0                   0                 999
4821 0                   0                   0                 999
4822 0                   0                   0                 999
4823 0                   0                   0                 999
4824 0                   0                   0                 999
4825 0                   0                   0                 999
4826 0                   0                   0                 999
4827 0                   0                   0                 999
4828 0                   0                   0                 999
4829 0                   0                   0                 999
4830 0                   0                   0                 999
4831 0                   0                   0                 999
4832 0                   0                   0                 999
4833 0                   0                   0                 999
4834 0                   0                   0                 999
4835 0                   0                   0                 999
4836 0                   0                   0                 999
4837 0                   0                   0                 999
4838 0                   0                   0                 999
4839 0                   0                   0                 999
4840 0                   0                   0                 999
4841 0                   0                   0                 999
4842 0                   0                   0                 999
4843 0                   0                   0                 999
4844 0                   0                   0                 999
     t0.lm        r.lm          shifted_log_rolled_cases
1    1.143848e+03 -3.258434e-02  0.00000000
2    1.143848e+03 -3.258434e-02 -0.03258434
3    1.128284e+03 -4.533580e-02  0.00000000
4    1.128284e+03 -4.533580e-02 -0.04533580
5    1.103961e+03 -3.347593e-02  0.00000000
6    1.103961e+03 -3.347593e-02 -0.03347593
7    1.111217e+03 -3.518631e-02 -0.03518631
8    1.111217e+03 -3.518631e-02  0.00000000
9    8.982348e+02  5.773356e-02  0.05773356
10   8.982348e+02  5.773356e-02  0.00000000
11   1.032591e+03 -9.633111e-02  0.00000000
12   1.032591e+03 -9.633111e-02 -0.09633111
13   1.106531e+03 -6.667364e-02  0.00000000
14   1.106531e+03 -6.667364e-02 -0.06667364
15   1.093223e+03 -3.974033e-02 -0.03974033
16   1.093223e+03 -3.974033e-02  0.00000000
17   1.112978e+03 -3.359094e-02  0.00000000
18   1.112978e+03 -3.359094e-02 -0.03359094
19   1.113948e+03 -3.819909e-02 -0.03819909
20   1.113948e+03 -3.819909e-02  0.00000000
21   1.052964e+03 -5.996346e-02 -0.05996346
22   1.052964e+03 -5.996346e-02  0.00000000
23   4.942298e+15 -6.280370e-16  0.00000000
24   4.942298e+15 -6.280370e-16  0.00000000
25   1.195442e+03 -1.652930e-02 -0.01652930
26   1.195442e+03 -1.652930e-02  0.00000000
27   1.416469e+03 -1.052641e-02 -0.01052641
28   1.416469e+03 -1.052641e-02  0.00000000
29   9.980000e+02  0.000000e+00  0.00000000
30   9.980000e+02  0.000000e+00  0.00000000
⋮    ⋮            ⋮             ⋮
4815  733.3497     0.019496962   0.000000000
4816  733.3497     0.019496962   0.019496962
4817  847.2380     0.023716527   0.023716527
4818  847.2380     0.023716527   0.000000000
4819  880.5268     0.026145280   0.000000000
4820  880.5268     0.026145280   0.026145280
4821  266.8877     0.007335811   0.000000000
4822  266.8877     0.007335811   0.007335811
4823  778.4626     0.018205964   0.018205964
4824  778.4626     0.018205964   0.000000000
4825 1582.8289    -0.009489326   0.000000000
4826 1582.8289    -0.009489326  -0.009489326
4827 1288.6217    -0.013642776  -0.013642776
4828 1288.6217    -0.013642776   0.000000000
4829 1126.5910    -0.035091320  -0.035091320
4830 1126.5910    -0.035091320   0.000000000
4831  917.5305     0.047770276   0.047770276
4832  917.5305     0.047770276   0.000000000
4833 1031.8828    -0.092170460  -0.092170460
4834 1031.8828    -0.092170460   0.000000000
4835 1174.8810    -0.027937668  -0.027937668
4836 1174.8810    -0.027937668   0.000000000
4837 1071.0238    -0.052129065  -0.052129065
4838 1071.0238    -0.052129065   0.000000000
4839 1098.3807    -0.047006042   0.000000000
4840 1098.3807    -0.047006042  -0.047006042
4841 1170.4510    -0.024256978  -0.024256978
4842 1170.4510    -0.024256978   0.000000000
4843 1632.1677    -0.016815044   0.000000000
4844 1632.1677    -0.016815044  -0.016815044

In [20]:
grf::importance(GRF_object)

ERROR: Error: 'importance' is not an exported object from 'namespace:grf'

In [21]:
grf::variable_importance(GRF_object)

      [,1]
 [1,] 0.0009986533
 [2,] 0.0018873961
 [3,] 0.0605068020
 [4,] 0.0012327418
 [5,] 0.0006319457
 [6,] 0.0006657688
 [7,] 0.0017541005
 [8,] 0.0007645648
 [9,] 0.0007334151
[10,] 0.0028608908
[11,] 0.0003017348
[12,] 0.0010059973
[13,] 0.0005981226
[14,] 0.0012427593
[15,] 0.0023395320
[16,] 0.0011021197
[17,] 0.0006346192
[18,] 0.0010947757
[19,] 0.0016664191
[20,] 0.0011677690
[21,] 0.0007307416
[22,] 0.0022692122
[23,] 0.0006684423
[24,] 0.0005981226
[25,] 0.0005669729
[26,] 0.0006969185
[27,] 0.0003667076
[28,] 0.0004681770
[29,] 0.0002705851
[30,] 0.0004708505
[31,] ⋮
[32,] 4.928064e-03
[33,] 3.985043e-03
[34,] 1.326191e-04
[35,] 3.546018e-03
[36,] 3.640341e-04
[37,] 1.664422e-04
[38,] 4.457890e-03
[39,] 4.728475e-04
[40,] 3.746284e-03
[41,] 2.002654e-04
[42,] 1.143287e-03
[43,] 3.667076e-04
[44,] 3.579841e-03
[45,] 2.340885e-04
[46,] 3.382314e-05
[47,] 0.000000e+00
[48,] 7.692353e-04
[49,] 0.000000e+00
[50,] 0.000000e+00
[51,] 0.000000e+00
[52,] 1.208260e-03
[53,] 0.000000e+00
[54,] 0.000000e+00
[55,] 0.000000e+00
[56,] 0.000000e+00
[57,] 0.000000e+00
[58,] 0.000000e+00
[59,] 0.000000e+00
[60,] 7.956866e-02
[61,] 6.605838e-02

In [22]:
names(GRF_object$X.orig)

  [1] "fips"
  [2] "log_rolled_cases.y"
  [3] "LAT"
  [4] "LON"
  [5] "AREA_SQMI"
  [6] "E_TOTPOP"
  [7] "E_HU"
  [8] "E_HH"
  [9] "E_POV"
 [10] "E_UNEMP"
 [11] "E_PCI"
 [12] "E_NOHSDP"
 [13] "E_AGE65"
 [14] "E_AGE17"
 [15] "E_DISABL"
 [16] "E_SNGPNT"
 [17] "E_MINRTY"
 [18] "E_LIMENG"
 [19] "E_MUNIT"
 [20] "E_MOBILE"
 [21] "E_CROWD"
 [22] "E_NOVEH"
 [23] "E_GROUPQ"
 [24] "EP_POV"
 [25] "MP_POV"
 [26] "EP_UNEMP"
 [27] "MP_UNEMP"
 [28] "EP_PCI"
 [29] "MP_PCI"
 [30] "EP_NOHSDP"
 [31] "MP_NOHSDP"
 [32] "EP_AGE65"
 [33] "MP_AGE65"
 [34] "EP_AGE17"
 [35] "MP_AGE17"
 [36] "EP_DISABL"
 [37] "MP_DISABL"
 [38] "EP_SNGPNT"
 [39] "MP_SNGPNT"
 [40] "EP_MINRTY"
 [41] "MP_MINRTY"
 [42] "EP_LIMENG"
 [43] "MP_LIMENG"
 [44] "EP_MUNIT"
 [45] "MP_MUNIT"
 [46] "EP_MOBILE"
 [47] "MP_MOBILE"
 [48] "EP_CROWD"
 [49] "MP_CROWD"
 [50] "EP_NOVEH"
 [51] "MP_NOVEH"
 [52] "EP_GROUPQ"
 [53] "MP_GROUPQ"
 [54] "EPL_POV"
 [55] "EPL_UNEMP"
 [56] "EPL_PCI"
 [57] "EPL_NOHSDP"
 [58] "SPL_THEME1"
 [59] "RPL_THEME1"
 [60] "EPL_AGE65"
 [61] "EPL_AGE17"
 [62] "EPL_DISABL"
 [63] "EPL_SNGPNT"
 [64] "SPL_THEME2"
 [65] "RPL_THEME2"
 [66] "EPL_MINRTY"
 [67] "EPL_LIMENG"
 [68] "SPL_THEME3"
 [69] "RPL_THEME3"
 [70] "EPL_MUNIT"
 [71] "EPL_MOBILE"
 [72] "EPL_CROWD"
 [73] "EPL_NOVEH"
 [74] "EPL_GROUPQ"
 [75] "SPL_THEME4"
 [76] "RPL_THEME4"
 [77] "SPL_THEMES"
 [78] "RPL_THEMES"
 [79] "F_POV"
 [80] "F_UNEMP"
 [81] "F_PCI"
 [82] "F_NOHSDP"
 [83] "F_THEME1"
 [84] "F_AGE65"
 [85] "F_AGE17"
 [86] "F_DISABL"
 [87] "F_SNGPNT"
 [88] "F_THEME2"
 [89] "F_MINRTY"
 [90] "F_LIMENG"
 [91] "F_THEME3"
 [92] "F_MUNIT"
 [93] "F_MOBILE"
 [94] "F_CROWD"
 [95] "F_NOVEH"
 [96] "F_GROUPQ"
 [97] "F_THEME4"
 [98] "F_TOTAL"
 [99] "E_UNINSUR"
[100] "EP_UNINSUR"
[101] "MP_UNINSUR"
[102] "E_DAYPOP"
[103] "State_of_emergency_issued"
[104] "State_of_emergency_lifted"
[105] "Date_closed_K.12_public_schools"
[106] "Closed_day_cares"
[107] "Reopen_day_cares"
[108] "Date_banned_visitors_to_nursing_homes"
[109] "Stay_at_home._shelter_in_place"
[110] "Stay_at_home_order._issued_but_did_not_specifically_restrict_movement_of_the_general_public"
[111] "End.relax_stay_at_home.shelter_in_place"
[112] "Closed_other_non.essential_businesses"
[113] "Closed_businesses_overnight"
[114] "Began_to_reopen_businesses"
[115] "Religious_gatherings_exempt_without_clear_social_distance_mandate."
[116] "Face_mask_mandate_in_public_spaces"
[117] "Face_mask_mandate_x2"
[118] "Face_mask_mandate_enforced_by_fines"
[119] "Face_mask_mandate_enforced_by_criminal_charge.citation"
[120] "No_legal_enforcement_of_face_mask_mandate"
[121] "Face_mask_mandate_for_employees_of_public.facing_businesses"
[122] "Ended_face_mask_mandate"
[123] "Ended_face_mask_mandate_x2"
[124] "Attempted_to_prevent_local_governments_from_implementing_face_mask_orders"
[125] "Banned_local_mask_mandates"
[126] "Liquor_stores_remained_open"
[127] "Allowed_restaurants_to_sell_takeout_alcohol"
[128] "Allowed_restaurants_to_deliver_alcohol"
[129] "Firearm_sellers_remained_open"
[130] "Cannabis_dispensaries_considered_essential_business"
[131] "Closed_restaurants_except_take_out"
[132] "Reopen_restaurants"
[133] "Initially_reopen_restaurants_for_outdoor_dining_only"
[134] "Closed_gyms"
[135] "Reopened_gyms"
[136] "Closed_movie_theaters"
[137] "Reopened_movie_theaters"
[138] "Closed_Bars"
[139] "Reopen_bars"
[140] "Reopened_hair_salons.barber_shops"
[141] "Reopened_religious_gatherings"
[142] "Reopened_other_non.essential_retail"
[143] "Allowed_businesses_to_reopen_overnight"
[144] "Began_to_reclose_bars"
[145] "Closed_bars_.x2."
[146] "Closed_movie_theaters_.x2."
[147] "Closed_hair_salons.barber_shops_.x2."
[148] "Closed_gyms_.x2."
[149] "Closed_restaurants_.x2."
[150] "Reopened_restaurants_.x2."
[151] "Reopened_bars_.x2."
[152] "Reopened_gyms_.x2."
[153] "Reopened_hair_salons.barber_shops_.x2."
[154] "Reopened_movie_theaters_.x2."
[155] "Closed_bars_.x3."
[156] "Closed_restaurants_.x3."
[157] "Reopened_bars_.x3."
[158] "Reopened_restaurants_.x3."
[159] "Mandate_quarantine_for_those_entering_the_state_from_specific_settings"
[160] "Mandate_quarantine_for_all_individuals_entering_the_state"
[161] "Date_all_mandated_quarantines_ended"
[162] "Date_vaccine_allocation_plan_last_updated"
[163] "Vaccine_allocation_phase._Frontline_Healthcare_Workers"
[164] "Vaccine_allocation_phase._Healthcare_Service_Workers"
[165] "Vaccine_allocation_phase._Home_Healthcare_Workers"
[166] "Vaccine_allocation_phase._Additional_Healthcare_Workers"
[167] "Vaccine_allocation_phase._Long.term_Care_Residents"
[168] "Vaccine_allocation_phase._EMS_Providers"
[169] "Vaccine_allocation_phase._Firefighters"
[170] "Vaccine_allocation_phase._Law_Enforcement_._Public_Safety_Personnel"
[171] "Vaccine_allocation_phase._Correctional_Staff"
[172] "Vaccine_allocation_phase._People_who_are_Incarcerated"
[173] "Vaccine_allocation_phase._Residents_of_Homeless_Shelters"
[174] "Vaccine_allocation_phase._Adults_Ages_75."
[175] "Vaccine_allocation_phase._Adults_Ages_65."
[176] "Vaccine_allocation_phase._Adults_w._High.Risk_Medical_Conditions"
[177] "Vaccine_allocation_phase._Pre.K.12_School_Employees"
[178] "Vaccine_allocation_phase._Higher_Education_Employees"
[179] "Vaccine_allocation_phase._Public_Transit_Workers"
[180] "Vaccine_allocation_phase._Food_Supply_Workers"
[181] "Vaccine_allocation_phase._Grocery_Store_Workers"
[182] "Vaccine_allocation_phase._Frontline_Essential_Workers"
[183] "Vaccine_allocation_phase._Additional_Essential_Workers"
[184] "Vaccine_allocation_phase._General_Public"
[185] "Date_adults_ages_80._became_eligible_for_COVID.19_vaccination"
[186] "Date_adults_ages_75._became_eligible_for_COVID.19_vaccination"
[187] "Date_adults_ages_70._became_eligible_for_COVID.19_vaccination"
[188] "Date_adults_ages_65._became_eligible_for_COVID.19_vaccination"
[189] "Date_adults_ages_60._became_eligible_for_COVID.19_vaccination"
[190] "Date_adults_ages_55._became_eligible_for_COVID.19_vaccination"
[191] "Date_adults_ages_50._became_eligible_for_COVID.19_vaccination"
[192] "Date_adults_ages_45._became_eligible_for_COVID.19_vaccination"
[193] "Date_adults_ages_40._became_eligible_for_COVID.19_vaccination"
[194] "Date_adults_ages_30._became_eligible_for_COVID.19_vaccination"
[195] "Date_K.12_school_employees_became_eligible_for_COVID.19_vaccination"
[196] "Date_grocery_store_workers_became_eligible_for_COVID.19_vaccination"
[197] "Date_incarcerated_people_became_eligible_for_COVID.19_vaccination"
[198] "Date_general_public_became_eligible_for_COVID.19_vaccination"
[199] "Adults_ages_65._prioritized_ahead_of_essential_workers"
[200] "Prioritization_by_race.ethnicity"
[201] "Proof_of_work_eligibility_requirement_for_vaccination"
[202] "Proof_of_age_eligibility_requirement_for_vaccination"
[203] "Proof_of_residency_requirement_for_vaccination"
[204] "Penalty_for_failure_to_comply_with_vaccine_distribution_requirements"
[205] "Expanded_scope_of_practice_of_certain_health_providers_to_administer_vaccines"
[206] "First_overall_eviction_moratorium_start"
[207] "First_overall_eviction_moratorium_end"
[208] "Second_overall_eviction_moratorium_start"
[209] "Second_overall_eviction_moratorium_end"
[210] "Third_overall_eviction_moratorium_start"
[211] "Third_overall_eviction_moratorium_end"
[212] "First_eviction_initiation_ban_start"
[213] "First_eviction_initiation_ban_end"
[214] "Second_Eviction_Initiation_Ban_Start"
[215] "Second_Eviction_Initiation_Ban_End"
[216] "First_eviction_hearing_ban_start"
[217] "First_eviction_hearing_ban_end"
[218] "Second_Eviction_Hearing_Ban_Start"
[219] "Second_Eviction_Hearing_Ban_End"
[220] "First_eviction_enforcement_ban_start"
[221] "First_eviction_enforcement_ban_end"
[222] "Second_Eviction_Enforcement_Ban_Start"
[223] "Second_Eviction_Enforcement_Ban_End"
[224] "COVID.19_hardship_limitation_start"
[225] "COVID.19_hardship_limitation_end"
[226] "Second_COVID.19_hardship_limitation_start"
[227] "Second_COVID.19_hardship_limitation_end"
[228] "Non.payment_limitation_start"
[229] "Non.payment_limitation_end"
[230] "Second_non.payment_limitation_start"
[231] "Second_non.payment_limitation_end"
[232] "CARES_Act_pleading_start"
[233] "CARES_Act_pleading_end"
[234] "CDC_moratorium_start"
[235] "CDC_moratorium_end"
[236] "Late_Fee_Ban_Start"
[237] "Late_Fee_Ban_End"
[238] "Second_Late_Fee_Ban_Start"
[239] "Second_Late_Fee_Ban_End"
[240] "Utilities_shutoff_moratorium_start"
[241] "Utilities_shutoff_moratorium_expiration"
[242] "Second_utilities_shutoff_moratorium_start"
[243] "Utilities_reconnection_start"
[244] "Utilities_reconnection_end"
[245] "SNAP_Waiver_._Emergency_Allotments_to_Current_SNAP_Households"
[246] "SNAP_Waiver_._Pandemic_EBT_during_school_year_2019.2020"
[247] "SNAP_Waiver_._Pandemic_EBT_during_school_year_2020.2021"
[248] "SNAP_Waiver_._Pandemic_EBT_during_summer_2021"
[249] "SNAP_Waiver_._Temporary_Suspension_of_Claims_Collection"
[250] "X2020_Q1_SNAP_ABAWD_Time_Limit_Waiver"
[251] "Modify_Medicaid_requirements_with_1135_waivers_.date_of_CMS_approval."
[252] "Reopened_ACA_enrollment_using_a_special_enrollment_period"
[253] "State_previously_allowed_audio.only_telehealth"
[254] "Allow_audio.only_telehealth"
[255] "Allow.expand_Medicaid_telehealth_coverage"
[256] "State_had_CHIP_premium_non.payment_lock.out_period_as_of_January_2019"
[257] "Suspend_CHIP_premium_non.payment_lock.outs"
[258] "Report_COVID.19_testing_by_race.ethnicity"
[259] "Report_COVID.19_cases_by_race.ethnicity"
[260] "Report_COVID.19_hospitalizations_by_race"
[261] "Report_COVID.19_deaths_by_race.ethnicity"
[262] "Report_COVID.19_vaccinations_by_race.ethnicity"
[263] "Report_Indigenous_COVID.19_testing"
[264] "Report_Indigenous_COVID.19_cases"
[265] "Report_Indigenous_COVID.19_hospitalizations"
[266] "Report_Indigenous_COVID.19_deaths"
[267] "Report_Indigenous_COVID.19_vaccinations"
[268] "Stopped_personal_visitation_in_state_prisons"
[269] "Stopped_legal_visitation_in_state_prisons"
[270] "Resumed_visitation_in_state_prisons"
[271] "Stopped_visitation_in_state_prisons_x2"
[272] "Resumed_visitation_in_state_prisons_x2"
[273] "Does_not_charge_copays_for_incarcerated_individuals"
[274] "Waived_COVID.respiratory_illness.related_copays_during_pandemic_for_incarcerated_individuals"
[275] "Waived_all_copays_during_pandemic_for_incarcerated_individuals"
[276] "Did_not_waive_copays_for_incarcerated_individuals"
[277] "Suspended_elective_medical_procedures"
[278] "Resumed_elective_medical_procedures"
[279] "No_order_to_suspend_elective_medical_procedures_but_did_release_guidance_or_orders_to_resume"
[280] "Suspended_elective_medical_procedures_x2"
[281] "Resumed_elective_medical_procedures_x2"
[282] "No_state_unemployment_waiting_period_prior_to_pandemic._or_date_waiting_period_waived_not_found"
[283] "Waived_one_week_waiting_period_for_unemployment_insurance"
[284] "Reinstated_one_week_waiting_period_for_unemployment_insurance"
[285] "Waived_work_search_requirement_for_unemployment_insurance"
[286] "Reinstated_work_search_requirement_for_UI"
[287] "Expanded_eligibility_of_unemployment_insurance_to_anyone_who_is_quarantined_and.or_taking_care_of_someone_who_is_quarantined"
[288] "Expanded_eligibility_to_high.risk_individuals_in_preventative_quarantine"
[289] "Expanded_eligibility_of_unemployment_insurance_to_those_who_have_lost_childcare.school_closures"
[290] "Extended_the_amount_of_time_an_individual_can_be_on_unemployment_insurance"
[291] "Weekly_unemployment_insurance_maximum_amount_.dollars."
[292] "Weekly_unemployment_insurance_maximum_amount_with_extra_stimulus_.through_July_31._2020._.dollars."
[293] "January_2020_unemployment_insurance_maximum_duration_.weeks."
[294] "July_2020_unemployment_insurance_maximum_duration_.weeks."
[295] "X2021_unemployment_insurance_maximum_duration_.weeks."
[296] "Extended_Benefits_program_activated"
[297] "Extended_Benefits_program_deactivated"
[298] "Extended_Benefits_program_activated_x2"
[299] "Total_Unemployment_Rate_at_Extended_Benefits_program_shutoff"
[300] "Total_Unemployment_Rate_relative_to_prior_year_..."
[301] "Total_Unemployment_Rate_relative_to_second_prior_year_..."
[302] "X20.week_Extended_Benefits_program_activated"
[303] "X20.week_Extended_Benefits_program_deactivated"
[304] "X20.week_Extended_Benefits_program_activated_x2"
[305] "Stopped_participating_in_pandemic.related_federal_unemployment_benefit_programs"
[306] "Minimum_total_earnings_required_in_the_base_period_to_qualify_for_UI"
[307] "Number_of_calendar_quarters_with_earnings_in_the_base_period_needed_to_qualify_for_UI"
[308] "Minimum_total_earnings_required_outside_the_highest_earning_calendar_quarter_of_the_base_period_to_qualify_for_UI"
[309] "Require_earnings_in_the_last_two_calendar_quarters_of_the_base_period_in_order_to_qualify_for_UI"
[310] "Earnings_in_base_period_required_to_receive_a_.300_weekly_benefit_amount_for_UI"
[311] "Taxable_Wage_Amount"
[312] "Minimum_Tax_Rate_..."
[313] "Maximum_Tax_Rate_..."
[314] "Average_Benefit_Amount_.August."
[315] "OSHA.approved_state_plan"
[316] "State_department_in_charge_of_enforcing_programs"
[317] "Aerosol_transmissable_diseases_standards"
[318] "Air_or_ventilation_standards"
[319] "Paid_sick_leave_prior_to_pandemic"
[320] "Paid_sick_leave_expansion_during_pandemic"
[321] "COVID.19_anti.retaliation_rules"
[322] "COVID.19_business_liability_protections"
[323] "COVID.19_liability_protections_for_healthcare_providers"
[324] "Branch_of_government_implementing_COVID.19_liability_rules"
[325] "COVID.19_workers._compensation_expansion"
[326] "Types_of_workers_eligible_for_workers._compensation_expansion"
[327] "Data_reporting_required_for_medical_treatment"
[328] "Minimum_number_of_work_days_missed_by_workers_to_require_data_reporting"
[329] "Occupational_injuries._illnesses._and_fatalities_reporting_prior_to_pandemic"
[330] "Made_Effort_to_Limit_Abortion_Access"
[331] "Use_of_telemedicine.telephone_evaluations_to_initiate_buprenorphine_prescribing"
[332] "Patients_can_receive_14.28_take.home_doses_of_opioid_medication"
[333] "Home_delivery_of_take.home_medication_by_opioid_treatment_programs"
[334] "Use_of_telemedicine_for_schedule_II.V_prescriptions"
[335] "Exceptions_to_emergency_oral_prescriptions"
[336] "Waive_requirement_to_obtain_separate_DEA_registration_to_dispense_outside_home_state"
[337] "Medicaid_Expansion"
[338] "Population_density_per_square_miles"
[339] "Population_2018"
[340] "Square_Miles"
[341] "Number_Homeless_.2019."
[342] "Percent_Unemployed_.2018."
[343] "Percent_living_under_the_federal_poverty_line_.2018."
[344] "Percent_at_risk_for_serious_illness_due_to_COVID"
[345] "All.cause_deaths_2018"
[346] "Mental_health_professionals_per_100.000_population_in_2019"
[347] "Were_there_casino.s._in_State._.Land_and_Non.Land_based."
[348] "State_has_at_least_one_Indian.Alaska_Native_reservation"
[349] "COVID.19_is_not_an_acceptable_reason_to_request_application_for_mail.in_ballot_unless_sick_or_exposed_.as_of_September_16._2020."
[350] "Witness_or_notary_signature_required_for_mail.in_ballot_.as_of_September_1._2020."
[351] "Permanent_mail.in_ballot_system"
[352] "Automatic_mail.in_ballot_system_in_response_to_COVID.19_.0.1.2_2_being_conditional._see_notes_for_details."
[353] "Automatic_applications_sent_for_mail.in_ballots_in_response_to_COVID.19_.0.1.2_2_being_conditional._see_notes_for_details."
[354] "Last_date_of_receipt_of_mail.in_ballot_request_for_the_general_election_.by_mail_or_online."
[355] "Closed_casinos"
[356] "Reopened_casinos"
[357] "Closed_casinos_.x2."
[358] "Reopened_casinos_.x2."
[359] "Mention_of_tribal_casinos"
[360] "Jan_1_2019_Minimum_Wage"
[361] "Mar_29_2019_Minimum_Wage"
[362] "Jul_1_2019_Minimum_Wage"
[363] "Oct_1_2019_Minimum_Wage"
[364] "Jan_1_2020_Minimum_Wage"
[365] "Jul_1_2020_Minimum_Wage"
[366] "Sep_1_2020_Minimum_Wage"
[367] "Oct_1_2020_Minimum_Wage"
[368] "X2020_Minimum_Wage_for_Tipped_Workers"
[369] "X2021_Minimum_Wage"
[370] "Different_Minimum_Wage_for_Smaller_Businesses"
[371] "death"
[372] "deathConfirmed"
[373] "deathIncrease"
[374] "deathProbable"
[375] "hospitalized"
[376] "hospitalizedCumulative"
[377] "hospitalizedCurrently"
[378] "hospitalizedIncrease"
[379] "inIcuCumulative"
[380] "inIcuCurrently"
[381] "negative"
[382] "negativeIncrease"
[383] "negativeTestsAntibody"
[384] "negativeTestsPeopleAntibody"
[385] "negativeTestsViral"
[386] "onVentilatorCumulative"
[387] "onVentilatorCurrently"
[388] "positive"
[389] "positiveCasesViral"
[390] "positiveIncrease"
[391] "positiveScore"
[392] "positiveTestsAntibody"
[393] "positiveTestsAntigen"
[394] "positiveTestsPeopleAntibody"
[395] "positiveTestsPeopleAntigen"
[396] "positiveTestsViral"
[397] "recovered"
[398] "totalTestEncountersViral"
[399] "totalTestEncountersViralIncrease"
[400] "totalTestResults"
[401] "totalTestResultsIncrease"
[402] "totalTestsAntibody"
[403] "totalTestsAntigen"
[404] "totalTestsPeopleAntibody"
[405] "totalTestsPeopleAntigen"
[406] "totalTestsPeopleViral"
[407] "totalTestsPeopleViralIncrease"
[408] "totalTestsViral"
[409] "totalTestsViralIncrease"
[410] "metrics.testPositivityRatio"
[411] "metrics.vaccinationsInitiatedRatio"
[412] "metrics.vaccinationsCompletedRatio"
[413] "hhs_region"
[414] "Variant...A.2.5"
[415] "Variant...AY.1"
[416] "Variant...AY.2"
[417] "Variant...AY.3"
[418] "Variant...B.1"
[419] "Variant...B.1.1"
[420] "Variant...B.1.1.194"
[421] "Variant...B.1.1.519"
[422] "Variant...B.1.1.529"
[423] "Variant...B.1.1.7"
[424] "Variant...B.1.2"
[425] "Variant...B.1.234"
[426] "Variant...B.1.243"
[427] "Variant...B.1.351"
[428] "Variant...B.1.427"
[429] "Variant...B.1.429"
[430] "Variant...B.1.525"
[431] "Variant...B.1.526"
[432] "Variant...B.1.526.1"
[433] "Variant...B.1.526.2"
[434] "Variant...B.1.596"
[435] "Variant...B.1.617"
[436] "Variant...B.1.617.1"
[437] "Variant...B.1.617.2"
[438] "Variant...B.1.617.3"
[439] "Variant...B.1.621"
[440] "Variant...B.1.621.1"
[441] "Variant...B.1.626"
[442] "Variant...B.1.628"
[443] "Variant...B.1.637"
[444] "Variant...BA.1.1"
[445] "Variant...BA.2"
[446] "Variant...BA.2.12.1"
[447] "Variant...BA.2.75"
[448] "Variant...BA.2.75.2"
[449] "Variant...BA.4"
[450] "Variant...BA.4.6"
[451] "Variant...BA.5"
[452] "Variant...BA.5.2.6"
[453] "Variant...BF.11"
[454] "Variant...BF.7"
[455] "Variant...BN.1"
[456] "Variant...BQ.1"
[457] "Variant...BQ.1.1"
[458] "Variant...CH.1.1"
[459] "Variant...FD.2"
[460] "Variant...Other"
[461] "Variant...P.1"
[462] "Variant...P.2"
[463] "Variant...R.1"
[464] "Variant...XBB"
[465] "Variant...XBB.1.16"
[466] "Variant...XBB.1.5"
[467] "Variant...XBB.1.5.1"
[468] "Variant...XBB.1.9.1"
[469] "Variant...XBB.1.9.2"
[470] "Variant...XBB.2.3"
[471] "cutoff"
[472] "t0.lm"
[473] "r.lm"

In [24]:
rev(names(GRF_object$X.orig)[order(grf::variable_importance(GRF_object))])

  [1] "t0.lm"
  [2] "r.lm"
  [3] "LAT"
  [4] "Date_adults_ages_65._became_eligible_for_COVID.19_vaccination"
  [5] "Average_Benefit_Amount_.August."
  [6] "Closed_movie_theaters"
  [7] "Weekly_unemployment_insurance_maximum_amount_.dollars."
  [8] "Closed_other_non.essential_businesses"
  [9] "Weekly_unemployment_insurance_maximum_amount_with_extra_stimulus_.through_July_31._2020._.dollars."
 [10] "Earnings_in_base_period_required_to_receive_a_.300_weekly_benefit_amount_for_UI"
 [11] "Closed_gyms"
 [12] "Closed_restaurants_except_take_out"
 [13] "First_overall_eviction_moratorium_start"
 [14] "Date_adults_ages_70._became_eligible_for_COVID.19_vaccination"
 [15] "Date_adults_ages_80._became_eligible_for_COVID.19_vaccination"
 [16] "Vaccine_allocation_phase._Correctional_Staff"
 [17] "Percent_living_under_the_federal_poverty_line_.2018."
 [18] "Reopened_gyms"
 [19] "Percent_Unemployed_.2018."
 [20] "Date_adults_ages_75._became_eligible_for_COVID.19_vaccination"
 [21] "Mental_health_professionals_per_100.000_population_in_2019"
 [22] "Date_adults_ages_50._became_eligible_for_COVID.19_vaccination"
 [23] "SNAP_Waiver_._Pandemic_EBT_during_school_year_2019.2020"
 [24] "Reopened_casinos"
 [25] "Total_Unemployment_Rate_at_Extended_Benefits_program_shutoff"
 [26] "Date_adults_ages_40._became_eligible_for_COVID.19_vaccination"
 [27] "Reopened_hair_salons.barber_shops"
 [28] "Exceptions_to_emergency_oral_prescriptions"
 [29] "Reopen_bars"
 [30] "Mandate_quarantine_for_all_individuals_entering_the_state"
 [31] "July_2020_unemployment_insurance_maximum_duration_.weeks."
 [32] "January_2020_unemployment_insurance_maximum_duration_.weeks."
 [33] "Stopped_participating_in_pandemic.related_federal_unemployment_benefit_programs"
 [34] "Closed_Bars"
 [35] "Vaccine_allocation_phase._Public_Transit_Workers"
 [36] "Variant...BA.1.1"
 [37] "Date_banned_visitors_to_nursing_homes"
 [38] "Date_K.12_school_employees_became_eligible_for_COVID.19_vaccination"
 [39] "Variant...BA.4.6"
 [40] "Medicaid_Expansion"
 [41] "Variant...BA.2"
 [42] "RPL_THEME3"
 [43] "Variant...BA.5.2.6"
 [44] "State_of_emergency_issued"
 [45] "OSHA.approved_state_plan"
 [46] "Variant...BQ.1"
 [47] "Variant...BA.2.75"
 [48] "Reopen_restaurants"
 [49] "E_UNEMP"
 [50] "Total_Unemployment_Rate_relative_to_prior_year_..."
 [51] "E_DISABL"
 [52] "Date_adults_ages_30._became_eligible_for_COVID.19_vaccination"
 [53] "Maximum_Tax_Rate_..."
 [54] "E_NOVEH"
 [55] "X2021_unemployment_insurance_maximum_duration_.weeks."
 [56] "Suspended_elective_medical_procedures"
 [57] "Percent_at_risk_for_serious_illness_due_to_COVID"
 [58] "log_rolled_cases.y"
 [59] "RPL_THEMES"
 [60] "EPL_NOHSDP"
 [61] "E_HU"
 [62] "First_eviction_enforcement_ban_start"
 [63] "All.cause_deaths_2018"
 [64] "E_MUNIT"
 [65] "Vaccine_allocation_phase._Frontline_Essential_Workers"
 [66] "E_DAYPOP"
 [67] "EPL_MINRTY"
 [68] "Reopened_bars_.x2."
 [69] "metrics.testPositivityRatio"
 [70] "Modify_Medicaid_requirements_with_1135_waivers_.date_of_CMS_approval."
 [71] "Non.payment_limitation_start"
 [72] "SNAP_Waiver_._Emergency_Allotments_to_Current_SNAP_Households"
 [73] "Vaccine_allocation_phase._Food_Supply_Workers"
 [74] "metrics.vaccinationsCompletedRatio"
 [75] "Minimum_total_earnings_required_outside_the_highest_earning_calendar_quarter_of_the_base_period_to_qualify_for_UI"
 [76] "SPL_THEME1"
 [77] "RPL_THEME1"
 [78] "E_AGE17"
 [79] "LON"
 [80] "Variant...XBB"
 [81] "X2020_Q1_SNAP_ABAWD_Time_Limit_Waiver"
 [82] "EPL_PCI"
 [83] "E_MOBILE"
 [84] "Variant...BF.7"
 [85] "First_eviction_initiation_ban_start"
 [86] "Date_general_public_became_eligible_for_COVID.19_vaccination"
 [87] "MP_AGE17"
 [88] "EPL_MOBILE"
 [89] "E_SNGPNT"
 [90] "SPL_THEMES"
 [91] "E_LIMENG"
 [92] "Resumed_elective_medical_procedures_x2"
 [93] "Utilities_shutoff_moratorium_start"
 [94] "COVID.19_hardship_limitation_end"
 [95] "Face_mask_mandate_in_public_spaces"
 [96] "EPL_AGE17"
 [97] "MP_NOHSDP"
 [98] "CARES_Act_pleading_end"
 [99] "Reopened_movie_theaters"
[100] "Stay_at_home._shelter_in_place"
[101] "E_NOHSDP"
[102] "fips"
[103] "Jan_1_2019_Minimum_Wage"
[104] "Vaccine_allocation_phase._Higher_Education_Employees"
[105] "Report_Indigenous_COVID.19_hospitalizations"
[106] "EP_GROUPQ"
[107] "Vaccine_allocation_phase._Firefighters"
[108] "Closed_bars_.x2."
[109] "Minimum_total_earnings_required_in_the_base_period_to_qualify_for_UI"
[110] "Total_Unemployment_Rate_relative_to_second_prior_year_..."
[111] "metrics.vaccinationsInitiatedRatio"
[112] "EP_UNINSUR"
[113] "COVID.19_hardship_limitation_start"
[114] "Allowed_businesses_to_reopen_overnight"
[115] "MP_CROWD"
[116] "Variant...Other"
[117] "E_HH"
[118] "Reopened_other_non.essential_retail"
[119] "EPL_UNEMP"
[120] "MP_MOBILE"
[121] "Number_Homeless_.2019."
[122] "Allow.expand_Medicaid_telehealth_coverage"
[123] "MP_UNINSUR"
[124] "MP_NOVEH"
[125] "E_POV"
[126] "EP_MINRTY"
[127] "E_CROWD"
[128] "EP_AGE17"
[129] "EPL_NOVEH"
[130] "EP_UNEMP"
[131] "Date_adults_ages_60._became_eligible_for_COVID.19_vaccination"
[132] "EPL_DISABL"
[133] "EP_MOBILE"
[134] "Adults_ages_65._prioritized_ahead_of_essential_workers"
[135] "E_GROUPQ"
[136] "RPL_THEME2"
[137] "EPL_POV"
[138] "EP_SNGPNT"
[139] "E_TOTPOP"
[140] "Date_grocery_store_workers_became_eligible_for_COVID.19_vaccination"
[141] "SPL_THEME4"
[142] "EP_DISABL"
[143] "SPL_THEME2"
[144] "Vaccine_allocation_phase._Residents_of_Homeless_Shelters"
[145] "E_MINRTY"
[146] "Date_vaccine_allocation_plan_last_updated"
[147] "AREA_SQMI"
[148] "Date_adults_ages_55._became_eligible_for_COVID.19_vaccination"
[149] "Stopped_visitation_in_state_prisons_x2"
[150] "Began_to_reopen_businesses"
[151] "EPL_LIMENG"
[152] "EP_POV"
[153] "E_AGE65"
[154] "Mar_29_2019_Minimum_Wage"
[155] "Made_Effort_to_Limit_Abortion_Access"
[156] "EPL_GROUPQ"
[157] "E_UNINSUR"
[158] "MP_POV"
[159] "MP_LIMENG"
[160] "Population_density_per_square_miles"
[161] "Resumed_visitation_in_state_prisons"
[162] "Jul_1_2020_Minimum_Wage"
[163] "MP_MUNIT"
[164] "First_overall_eviction_moratorium_end"
[165] "End.relax_stay_at_home.shelter_in_place"
[166] "EP_MUNIT"
[167] "MP_DISABL"
[168] "MP_GROUPQ"
[169] "EPL_SNGPNT"
[170] "Variant...BA.5"
[171] "Non.payment_limitation_end"
[172] "Vaccine_allocation_phase._Grocery_Store_Workers"
[173] "EP_NOHSDP"
[174] "EPL_MUNIT"
[175] "MP_SNGPNT"
[176] "EP_PCI"
[177] "CDC_moratorium_start"
[178] "Attempted_to_prevent_local_governments_from_implementing_face_mask_orders"
[179] "Stay_at_home_order._issued_but_did_not_specifically_restrict_movement_of_the_general_public"
[180] "EP_AGE65"
[181] "Extended_Benefits_program_deactivated"
[182] "RPL_THEME4"
[183] "EP_NOVEH"
[184] "Population_2018"
[185] "EP_LIMENG"
[186] "Variant...BN.1"
[187] "EPL_CROWD"
[188] "MP_UNEMP"
[189] "Variant...BA.2.75.2"
[190] "Face_mask_mandate_for_employees_of_public.facing_businesses"
[191] "X2020_Minimum_Wage_for_Tipped_Workers"
[192] "Waived_one_week_waiting_period_for_unemployment_insurance"
[193] "SPL_THEME3"
[194] "Taxable_Wage_Amount"
[195] "E_PCI"
[196] "Allowed_restaurants_to_deliver_alcohol"
[197] "First_eviction_initiation_ban_end"
[198] "Mandate_quarantine_for_those_entering_the_state_from_specific_settings"
[199] "EP_CROWD"
[200] "MP_PCI"
[201] "Date_incarcerated_people_became_eligible_for_COVID.19_vaccination"
[202] "Allowed_restaurants_to_sell_takeout_alcohol"
[203] "F_GROUPQ"
[204] "Variant...BQ.1.1"
[205] "First_eviction_enforcement_ban_end"
[206] "EPL_AGE65"
[207] "X2021_Minimum_Wage"
[208] "Extended_Benefits_program_activated"
[209] "Stopped_personal_visitation_in_state_prisons"
[210] "SNAP_Waiver_._Temporary_Suspension_of_Claims_Collection"
[211] "First_eviction_hearing_ban_end"
[212] "Began_to_reclose_bars"
[213] "Reopened_religious_gatherings"
[214] "Banned_local_mask_mandates"
[215] "F_THEME1"
[216] "Variant...BF.11"
[217] "Utilities_shutoff_moratorium_expiration"
[218] "F_THEME4"
[219] "MP_MINRTY"
[220] "MP_AGE65"
[221] "Variant...B.1.1.529"
[222] "hhs_region"
[223] "Jul_1_2019_Minimum_Wage"
[224] "COVID.19_workers._compensation_expansion"
[225] "Stopped_legal_visitation_in_state_prisons"
[226] "Vaccine_allocation_phase._Law_Enforcement_._Public_Safety_Personnel"
[227] "Initially_reopen_restaurants_for_outdoor_dining_only"
[228] "Variant...BA.4"
[229] "Suspended_elective_medical_procedures_x2"
[230] "Resumed_elective_medical_procedures"
[231] "Late_Fee_Ban_Start"
[232] "F_TOTAL"
[233] "Variant...BA.2.12.1"
[234] "Different_Minimum_Wage_for_Smaller_Businesses"
[235] "Minimum_number_of_work_days_missed_by_workers_to_require_data_reporting"
[236] "Data_reporting_required_for_medical_treatment"
[237] "Date_all_mandated_quarantines_ended"
[238] "Reopened_restaurants_.x2."
[239] "Date_closed_K.12_public_schools"
[240] "F_THEME3"
[241] "Sep_1_2020_Minimum_Wage"
[242] "Minimum_Tax_Rate_..."
[243] "First_eviction_hearing_ban_start"
[244] "Date_adults_ages_45._became_eligible_for_COVID.19_vaccination"
[245] "Face_mask_mandate_enforced_by_criminal_charge.citation"
[246] "Oct_1_2019_Minimum_Wage"
[247] "Automatic_applications_sent_for_mail.in_ballots_in_response_to_COVID.19_.0.1.2_2_being_conditional._see_notes_for_details."
[248] "Witness_or_notary_signature_required_for_mail.in_ballot_.as_of_September_1._2020."
[249] "Were_there_casino.s._in_State._.Land_and_Non.Land_based."
[250] "Extended_the_amount_of_time_an_individual_can_be_on_unemployment_insurance"
[251] "Expanded_eligibility_of_unemployment_insurance_to_those_who_have_lost_childcare.school_closures"
[252] "Expanded_eligibility_to_high.risk_individuals_in_preventative_quarantine"
[253] "Late_Fee_Ban_End"
[254] "Second_Eviction_Enforcement_Ban_End"
[255] "Second_Eviction_Hearing_Ban_End"
[256] "Second_Eviction_Hearing_Ban_Start"
[257] "Penalty_for_failure_to_comply_with_vaccine_distribution_requirements"
[258] "Vaccine_allocation_phase._Additional_Essential_Workers"
[259] "Closed_restaurants_.x2."
[260] "Cannabis_dispensaries_considered_essential_business"
[261] "Ended_face_mask_mandate"
[262] "Mention_of_tribal_casinos"
[263] "Square_Miles"
[264] "Proof_of_residency_requirement_for_vaccination"
[265] "Variant...CH.1.1"
[266] "Oct_1_2020_Minimum_Wage"
[267] "Closed_casinos"
[268] "Last_date_of_receipt_of_mail.in_ballot_request_for_the_general_election_.by_mail_or_online."
[269] "State_has_at_least_one_Indian.Alaska_Native_reservation"
[270] "Expanded_eligibility_of_unemployment_insurance_to_anyone_who_is_quarantined_and.or_taking_care_of_someone_who_is_quarantined"
[271] "Reinstated_work_search_requirement_for_UI"
[272] "Does_not_charge_copays_for_incarcerated_individuals"
[273] "SNAP_Waiver_._Pandemic_EBT_during_school_year_2020.2021"
[274] "Second_utilities_shutoff_moratorium_start"
[275] "Second_Late_Fee_Ban_Start"
[276] "CARES_Act_pleading_start"
[277] "Vaccine_allocation_phase._Adults_w._High.Risk_Medical_Conditions"
[278] "Closed_businesses_overnight"
[279] "Closed_day_cares"
[280] "State_of_emergency_lifted"
[281] "F_MOBILE"
[282] "F_MINRTY"
[283] "F_THEME2"
[284] "cutoff"
[285] "Variant...XBB.2.3"
[286] "Variant...XBB.1.9.2"
[287] "Variant...XBB.1.9.1"
[288] "Variant...XBB.1.5.1"
[289] "Variant...XBB.1.5"
[290] "Variant...XBB.1.16"
[291] "Variant...R.1"
[292] "Variant...P.2"
[293] "Variant...P.1"
[294] "Variant...FD.2"
[295] "Variant...B.1.637"
[296] "Variant...B.1.628"
[297] "Variant...B.1.626"
[298] "Variant...B.1.621.1"
[299] "Variant...B.1.621"
[300] "Variant...B.1.617.3"
[301] "Variant...B.1.617.2"
[302] "Variant...B.1.617.1"
[303] "Variant...B.1.617"
[304] "Variant...B.1.596"
[305] "Variant...B.1.526.2"
[306] "Variant...B.1.526.1"
[307] "Variant...B.1.526"
[308] "Variant...B.1.525"
[309] "Variant...B.1.429"
[310] "Variant...B.1.427"
[311] "Variant...B.1.351"
[312] "Variant...B.1.243"
[313] "Variant...B.1.234"
[314] "Variant...B.1.2"
[315] "Variant...B.1.1.7"
[316] "Variant...B.1.1.519"
[317] "Variant...B.1.1.194"
[318] "Variant...B.1.1"
[319] "Variant...B.1"
[320] "Variant...AY.3"
[321] "Variant...AY.2"
[322] "Variant...AY.1"
[323] "Variant...A.2.5"
[324] "totalTestsViralIncrease"
[325] "totalTestsViral"
[326] "totalTestsPeopleViralIncrease"
[327] "totalTestsPeopleViral"
[328] "totalTestsPeopleAntigen"
[329] "totalTestsPeopleAntibody"
[330] "totalTestsAntigen"
[331] "totalTestsAntibody"
[332] "totalTestResultsIncrease"
[333] "totalTestResults"
[334] "totalTestEncountersViralIncrease"
[335] "totalTestEncountersViral"
[336] "recovered"
[337] "positiveTestsViral"
[338] "positiveTestsPeopleAntigen"
[339] "positiveTestsPeopleAntibody"
[340] "positiveTestsAntigen"
[341] "positiveTestsAntibody"
[342] "positiveScore"
[343] "positiveIncrease"
[344] "positiveCasesViral"
[345] "positive"
[346] "onVentilatorCurrently"
[347] "onVentilatorCumulative"
[348] "negativeTestsViral"
[349] "negativeTestsPeopleAntibody"
[350] "negativeTestsAntibody"
[351] "negativeIncrease"
[352] "negative"
[353] "inIcuCurrently"
[354] "inIcuCumulative"
[355] "hospitalizedIncrease"
[356] "hospitalizedCurrently"
[357] "hospitalizedCumulative"
[358] "hospitalized"
[359] "deathProbable"
[360] "deathIncrease"
[361] "deathConfirmed"
[362] "death"
[363] "Jan_1_2020_Minimum_Wage"
[364] "Reopened_casinos_.x2."
[365] "Closed_casinos_.x2."
[366] "Automatic_mail.in_ballot_system_in_response_to_COVID.19_.0.1.2_2_being_conditional._see_notes_for_details."
[367] "Permanent_mail.in_ballot_system"
[368] "COVID.19_is_not_an_acceptable_reason_to_request_application_for_mail.in_ballot_unless_sick_or_exposed_.as_of_September_16._2020."
[369] "Waive_requirement_to_obtain_separate_DEA_registration_to_dispense_outside_home_state"
[370] "Use_of_telemedicine_for_schedule_II.V_prescriptions"
[371] "Home_delivery_of_take.home_medication_by_opioid_treatment_programs"
[372] "Patients_can_receive_14.28_take.home_doses_of_opioid_medication"
[373] "Use_of_telemedicine.telephone_evaluations_to_initiate_buprenorphine_prescribing"
[374] "Occupational_injuries._illnesses._and_fatalities_reporting_prior_to_pandemic"
[375] "Types_of_workers_eligible_for_workers._compensation_expansion"
[376] "Branch_of_government_implementing_COVID.19_liability_rules"
[377] "COVID.19_liability_protections_for_healthcare_providers"
[378] "COVID.19_business_liability_protections"
[379] "COVID.19_anti.retaliation_rules"
[380] "Paid_sick_leave_expansion_during_pandemic"
[381] "Paid_sick_leave_prior_to_pandemic"
[382] "Air_or_ventilation_standards"
[383] "Aerosol_transmissable_diseases_standards"
[384] "State_department_in_charge_of_enforcing_programs"
[385] "Require_earnings_in_the_last_two_calendar_quarters_of_the_base_period_in_order_to_qualify_for_UI"
[386] "Number_of_calendar_quarters_with_earnings_in_the_base_period_needed_to_qualify_for_UI"
[387] "X20.week_Extended_Benefits_program_activated_x2"
[388] "X20.week_Extended_Benefits_program_deactivated"
[389] "X20.week_Extended_Benefits_program_activated"
[390] "Extended_Benefits_program_activated_x2"
[391] "Waived_work_search_requirement_for_unemployment_insurance"
[392] "Reinstated_one_week_waiting_period_for_unemployment_insurance"
[393] "No_state_unemployment_waiting_period_prior_to_pandemic._or_date_waiting_period_waived_not_found"
[394] "No_order_to_suspend_elective_medical_procedures_but_did_release_guidance_or_orders_to_resume"
[395] "Did_not_waive_copays_for_incarcerated_individuals"
[396] "Waived_all_copays_during_pandemic_for_incarcerated_individuals"
[397] "Waived_COVID.respiratory_illness.related_copays_during_pandemic_for_incarcerated_individuals"
[398] "Resumed_visitation_in_state_prisons_x2"
[399] "Report_Indigenous_COVID.19_vaccinations"
[400] "Report_Indigenous_COVID.19_deaths"
[401] "Report_Indigenous_COVID.19_cases"
[402] "Report_Indigenous_COVID.19_testing"
[403] "Report_COVID.19_vaccinations_by_race.ethnicity"
[404] "Report_COVID.19_deaths_by_race.ethnicity"
[405] "Report_COVID.19_hospitalizations_by_race"
[406] "Report_COVID.19_cases_by_race.ethnicity"
[407] "Report_COVID.19_testing_by_race.ethnicity"
[408] "Suspend_CHIP_premium_non.payment_lock.outs"
[409] "State_had_CHIP_premium_non.payment_lock.out_period_as_of_January_2019"
[410] "Allow_audio.only_telehealth"
[411] "State_previously_allowed_audio.only_telehealth"
[412] "Reopened_ACA_enrollment_using_a_special_enrollment_period"
[413] "SNAP_Waiver_._Pandemic_EBT_during_summer_2021"
[414] "Utilities_reconnection_end"
[415] "Utilities_reconnection_start"
[416] "Second_Late_Fee_Ban_End"
[417] "CDC_moratorium_end"
[418] "Second_non.payment_limitation_end"
[419] "Second_non.payment_limitation_start"
[420] "Second_COVID.19_hardship_limitation_end"
[421] "Second_COVID.19_hardship_limitation_start"
[422] "Second_Eviction_Enforcement_Ban_Start"
[423] "Second_Eviction_Initiation_Ban_End"
[424] "Second_Eviction_Initiation_Ban_Start"
[425] "Third_overall_eviction_moratorium_end"
[426] "Third_overall_eviction_moratorium_start"
[427] "Second_overall_eviction_moratorium_end"
[428] "Second_overall_eviction_moratorium_start"
[429] "Expanded_scope_of_practice_of_certain_health_providers_to_administer_vaccines"
[430] "Proof_of_age_eligibility_requirement_for_vaccination"
[431] "Proof_of_work_eligibility_requirement_for_vaccination"
[432] "Prioritization_by_race.ethnicity"
[433] "Vaccine_allocation_phase._General_Public"
[434] "Vaccine_allocation_phase._Pre.K.12_School_Employees"
[435] "Vaccine_allocation_phase._Adults_Ages_65."
[436] "Vaccine_allocation_phase._Adults_Ages_75."
[437] "Vaccine_allocation_phase._People_who_are_Incarcerated"
[438] "Vaccine_allocation_phase._EMS_Providers"
[439] "Vaccine_allocation_phase._Long.term_Care_Residents"
[440] "Vaccine_allocation_phase._Additional_Healthcare_Workers"
[441] "Vaccine_allocation_phase._Home_Healthcare_Workers"
[442] "Vaccine_allocation_phase._Healthcare_Service_Workers"
[443] "Vaccine_allocation_phase._Frontline_Healthcare_Workers"
[444] "Reopened_restaurants_.x3."
[445] "Reopened_bars_.x3."
[446] "Closed_restaurants_.x3."
[447] "Closed_bars_.x3."
[448] "Reopened_movie_theaters_.x2."
[449] "Reopened_hair_salons.barber_shops_.x2."
[450] "Reopened_gyms_.x2."
[451] "Closed_gyms_.x2."
[452] "Closed_hair_salons.barber_shops_.x2."
[453] "Closed_movie_theaters_.x2."
[454] "Firearm_sellers_remained_open"
[455] "Liquor_stores_remained_open"
[456] "Ended_face_mask_mandate_x2"
[457] "No_legal_enforcement_of_face_mask_mandate"
[458] "Face_mask_mandate_enforced_by_fines"
[459] "Face_mask_mandate_x2"
[460] "Religious_gatherings_exempt_without_clear_social_distance_mandate."
[461] "Reopen_day_cares"
[462] "F_NOVEH"
[463] "F_CROWD"
[464] "F_MUNIT"
[465] "F_LIMENG"
[466] "F_SNGPNT"
[467] "F_DISABL"
[468] "F_AGE17"
[469] "F_AGE65"
[470] "F_NOHSDP"
[471] "F_PCI"
[472] "F_UNEMP"
[473] "F_POV"

In [25]:
GRF_object$X.orig$Date_adults_ages_65._became_eligible_for_COVID.19_vaccination

   [1] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
  [19] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
  [37] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
  [55] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
  [73] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
  [91] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
 [109] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 644 644 644 644
 [127] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
 [145] 644 644 644 644 644 644 644 644 644 644 644 644 636 636 636 636 636 636
 [163] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
 [181] 636 636 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
 [199] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
 [217] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
 [235] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
 [253] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
 [271] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
 [289] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
 [307] 601 601 601 601 601 601 642 642 642 642 642 642 642 642 642 642 642 642
 [325] 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642
 [343] 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642
 [361] 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642
 [379] 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642
 [397] 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642 642
 [415] 642 642 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591
 [433] 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591
 [451] 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591
 [469] 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591 591
 [487] 591 591 591 591 591 591 613 613 613 613 613 613 613 613 613 613 613 613
 [505] 613 613 613 613 636 636 636 636 636 636 644 644 663 663 663 663 663 663
 [523] 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663
 [541] 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663
 [559] 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663
 [577] 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663
 [595] 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663
 [613] 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663 663
 [631] 663 663 663 663 663 663 663 663 651 651 651 651 651 651 651 651 651 651
 [649] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
 [667] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
 [685] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
 [703] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
 [721] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
 [739] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
 [757] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
 [775] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
 [793] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 581 581
 [811] 581 581 581 581 581 581 623 623 623 623 623 623 623 623 623 623 623 623
 [829] 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623
 [847] 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623
 [865] 623 623 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630
 [883] 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630
 [901] 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630
 [919] 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630
 [937] 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630
 [955] 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630
 [973] 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630
 [991] 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630
[1009] 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630
[1027] 630 630 630 630 630 630 630 630 630 630 630 630 601 601 601 601 601 601
[1045] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
[1063] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
[1081] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
[1099] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
[1117] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
[1135] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
[1153] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
[1171] 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601 601
[1189] 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623
[1207] 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623
[1225] 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623
[1243] 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623
[1261] 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623
[1279] 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623
[1297] 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623 623
[1315] 623 623 623 623 623 623 623 623 623 623 623 623 623 623 634 634 634 634
[1333] 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634
[1351] 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634
[1369] 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634
[1387] 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634
[1405] 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634 634
[1423] 634 634 634 634 634 634 634 634 634 634 595 595 595 595 595 595 595 595
[1441] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[1459] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[1477] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[1495] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[1513] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[1531] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[1549] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[1567] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[1585] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[1603] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[1621] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[1639] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[1657] 595 595 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
[1675] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
[1693] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
[1711] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
[1729] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
[1747] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
[1765] 616 616 593 593 593 593 593 593 593 593 593 593 593 593 593 593 593 593
[1783] 593 593 593 593 593 593 593 593 593 593 593 593 593 593 593 593 630 630
[1801] 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630
[1819] 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630 630
[1837] 630 630 630 630 630 630 630 630 630 630 574 574 574 574 574 574 574 574
[1855] 574 574 574 574 574 574 574 574 574 574 574 574 574 574 574 574 574 574
[1873] 574 574 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[1891] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[1909] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[1927] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[1945] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[1963] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[1981] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[1999] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2017] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 636 636 636 636
[2035] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[2053] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[2071] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[2089] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[2107] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[2125] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[2143] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[2161] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[2179] 636 636 636 636 636 636 636 636 649 649 649 649 649 649 649 649 649 649
[2197] 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649
[2215] 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649
[2233] 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649
[2251] 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649
[2269] 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649
[2287] 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649
[2305] 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 649 637 637
[2323] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637
[2341] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637
[2359] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637
[2377] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637
[2395] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637
[2413] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637
[2431] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637
[2449] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637
[2467] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637
[2485] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637
[2503] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 588 588 588 588
[2521] 588 588 588 588 588 588 588 588 588 588 588 588 588 588 588 588 588 588
[2539] 588 588 588 588 588 588 588 588 588 588 588 588 588 588 588 588 588 588
[2557] 588 588 588 588 588 588 588 588 588 588 588 588 588 588 588 588 635 635
[2575] 635 635 635 635 635 635 635 635 635 635 635 635 635 635 635 635 635 635
[2593] 635 635 635 635 635 635 635 635 635 635 635 635 635 635 635 635 635 635
[2611] 635 635 635 635 635 635 635 635 602 602 602 602 602 602 602 602 602 602
[2629] 602 602 602 602 602 602 602 602 602 602 602 602 629 629 629 629 629 629
[2647] 629 629 629 629 629 629 629 629 629 629 629 629 629 629 641 641 641 641
[2665] 641 641 641 641 641 641 641 641 641 641 641 641 641 641 641 641 641 641
[2683] 641 641 641 641 641 641 641 641 641 641 641 641 641 641 641 641 641 641
[2701] 641 641 577 577 577 577 577 577 577 577 577 577 577 577 577 577 577 577
[2719] 577 577 577 577 577 577 577 577 577 577 577 577 577 577 577 577 577 577
[2737] 577 577 577 577 577 577 577 577 577 577 577 577 644 644 644 644 644 644
[2755] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2773] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2791] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2809] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2827] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2845] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2863] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2881] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2899] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2917] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2935] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2953] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2971] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[2989] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[3007] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[3025] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[3043] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 643 643 643 643
[3061] 643 643 643 643 643 643 643 643 643 643 643 643 643 643 643 643 643 643
[3079] 643 643 643 643 643 643 643 643 643 643 643 643 643 643 643 643 643 643
[3097] 643 643 643 643 643 643 643 643 643 643 636 636 636 636 636 636 636 636
[3115] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3133] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3151] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3169] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3187] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3205] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3223] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3241] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3259] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3277] 636 636 636 636 636 636 651 651 651 651 651 651 651 651 651 651 651 651
[3295] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
[3313] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
[3331] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
[3349] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
[3367] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
[3385] 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651 651
[3403] 651 651 651 651 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[3421] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[3439] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[3457] 595 595 595 595 595 595 595 595 595 595 636 636 636 636 636 636 636 636
[3475] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3493] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3511] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3529] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3547] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3565] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636 636
[3583] 636 636 636 636 636 636 636 636 636 636 636 636 636 636 602 602 602 602
[3601] 602 602 602 602 602 602 616 616 616 616 616 616 616 616 616 616 616 616
[3619] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
[3637] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
[3655] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
[3673] 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616 616
[3691] 616 616 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602
[3709] 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602
[3727] 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602
[3745] 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602
[3763] 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602
[3781] 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602
[3799] 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602
[3817] 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602
[3835] 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602
[3853] 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602
[3871] 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602
[3889] 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602 602
[3907] 602 602 602 602 602 602 602 602 602 602 602 602 658 658 658 658 658 658
[3925] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[3943] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[3961] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[3979] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[3997] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[4015] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[4033] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[4051] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[4069] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[4087] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[4105] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[4123] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[4141] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[4159] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[4177] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658
[4195] 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 658 606 606
[4213] 606 606 606 606 606 606 606 606 606 606 606 606 606 606 606 606 606 606
[4231] 606 606 606 606 606 606 606 606 606 606 606 606 606 606 606 606 595 595
[4249] 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595 595
[4267] 595 595 595 595 595 595 644 644 644 644 644 644 644 644 644 644 644 644
[4285] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[4303] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[4321] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[4339] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[4357] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[4375] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[4393] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[4411] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[4429] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[4447] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[4465] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644 644
[4483] 644 644 644 644 644 644 644 644 644 644 644 644 644 644 637 637 637 637
[4501] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637
[4519] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637
[4537] 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637 637

In [28]:
rev(sort(grf::variable_importance(GRF_object)))

  [1] 7.956866e-02 6.605838e-02 6.050680e-02 5.141346e-02 4.220397e-02
  [6] 3.956715e-02 3.900085e-02 3.551713e-02 3.503962e-02 3.140215e-02
 [11] 3.105190e-02 3.101808e-02 2.714452e-02 2.342472e-02 2.157984e-02
 [16] 2.086556e-02 1.562642e-02 1.369853e-02 1.309841e-02 1.221769e-02
 [21] 1.031429e-02 9.212168e-03 9.178345e-03 9.045726e-03 8.596684e-03
 [26] 8.507906e-03 8.058864e-03 8.001235e-03 6.032857e-03 6.006378e-03
 [31] 5.972555e-03 5.094506e-03 5.087162e-03 5.019516e-03 4.961887e-03
 [36] 4.928064e-03 4.645464e-03 4.590509e-03 4.457890e-03 4.050015e-03
 [41] 3.985043e-03 3.915399e-03 3.746284e-03 3.678637e-03 3.610991e-03
 [46] 3.579841e-03 3.546018e-03 3.304586e-03 2.860891e-03 2.725598e-03
 [51] 2.339532e-03 2.320397e-03 2.317723e-03 2.269212e-03 2.228945e-03
 [56] 2.185104e-03 2.055159e-03 1.887396e-03 1.850223e-03 1.777906e-03
 [61] 1.754101e-03 1.748754e-03 1.683781e-03 1.666419e-03 1.647284e-03
 [66] 1.635269e-03 1.635269e-03 1.618808e-03 1.601446e-03 1.582311e-03
 [71] 1.514665e-03 1.507321e-03 1.415869e-03 1.341555e-03 1.307056e-03
 [76] 1.268562e-03 1.265888e-03 1.242759e-03 1.232742e-03 1.208260e-03
 [81] 1.208260e-03 1.175113e-03 1.167769e-03 1.143287e-03 1.143287e-03
 [86] 1.143287e-03 1.135943e-03 1.133269e-03 1.102120e-03 1.097449e-03
 [91] 1.094776e-03 1.075641e-03 1.044491e-03 1.044491e-03 1.044491e-03
 [96] 1.032476e-03 1.032476e-03 1.010668e-03 1.010668e-03 1.010668e-03
[101] 1.005997e-03 9.986533e-04 9.456951e-04 9.456951e-04 9.118719e-04
[106] 9.072014e-04 8.780488e-04 8.780488e-04 8.707047e-04 8.368816e-04
[111] 8.322110e-04 8.084055e-04 8.030584e-04 8.030584e-04 7.745823e-04
[116] 7.692353e-04 7.645648e-04 7.407592e-04 7.407592e-04 7.380857e-04
[121] 7.354122e-04 7.354122e-04 7.334151e-04 7.334151e-04 7.334151e-04
[126] 7.307416e-04 7.307416e-04 7.022655e-04 6.969185e-04 6.969185e-04
[131] 6.942450e-04 6.711158e-04 6.711158e-04 6.704394e-04 6.684423e-04
[136] 6.657688e-04 6.657688e-04 6.657688e-04 6.657688e-04 6.630953e-04
[141] 6.630953e-04 6.630953e-04 6.372927e-04 6.366162e-04 6.346192e-04
[146] 6.319457e-04 6.319457e-04 6.081401e-04 6.054666e-04 6.054666e-04
[151] 6.034696e-04 5.981226e-04 5.981226e-04 5.716435e-04 5.716435e-04
[156] 5.696464e-04 5.669729e-04 5.669729e-04 5.642994e-04 5.616259e-04
[161] 5.616259e-04 5.378203e-04 5.304763e-04 5.066707e-04 5.066707e-04
[166] 5.020001e-04 4.993266e-04 4.966531e-04 4.735240e-04 4.728475e-04
[171] 4.728475e-04 4.728475e-04 4.708505e-04 4.681770e-04 4.681770e-04
[176] 4.681770e-04 4.390244e-04 4.390244e-04 4.390244e-04 4.316803e-04
[181] 4.290068e-04 4.032042e-04 4.032042e-04 4.005307e-04 4.005307e-04
[186] 3.667076e-04 3.667076e-04 3.667076e-04 3.640341e-04 3.640341e-04
[191] 3.328844e-04 3.328844e-04 3.328844e-04 3.302109e-04 3.017348e-04
[196] 2.990613e-04 2.963878e-04 2.963878e-04 2.705851e-04 2.705851e-04
[201] 2.652381e-04 2.652381e-04 2.652381e-04 2.340885e-04 2.340885e-04
[206] 2.340885e-04 2.314150e-04 2.314150e-04 2.314150e-04 2.314150e-04
[211] 2.314150e-04 2.314150e-04 2.314150e-04 2.314150e-04 2.314150e-04
[216] 2.002654e-04 2.002654e-04 2.002654e-04 2.002654e-04 2.002654e-04
[221] 1.975918e-04 1.975918e-04 1.975918e-04 1.975918e-04 1.975918e-04
[226] 1.975918e-04 1.975918e-04 1.664422e-04 1.664422e-04 1.664422e-04
[231] 1.664422e-04 1.352926e-04 1.326191e-04 1.326191e-04 1.326191e-04
[236] 1.326191e-04 1.326191e-04 1.326191e-04 1.326191e-04 1.326191e-04
[241] 1.014694e-04 1.014694e-04 1.014694e-04 1.014694e-04 1.014694e-04
[246] 9.879592e-05 9.879592e-05 9.879592e-05 9.879592e-05 9.879592e-05
[251] 9.879592e-05 9.879592e-05 9.879592e-05 9.879592e-05 9.879592e-05
[256] 9.879592e-05 9.879592e-05 9.879592e-05 9.879592e-05 9.879592e-05
[261] 9.879592e-05 6.764629e-05 6.764629e-05 6.764629e-05 3.382314e-05
[266] 3.382314e-05 3.382314e-05 3.382314e-05 3.382314e-05 3.382314e-05
[271] 3.382314e-05 3.382314e-05 3.382314e-05 3.382314e-05 3.382314e-05
[276] 3.382314e-05 3.382314e-05 3.382314e-05 3.382314e-05 3.382314e-05
[281] 3.382314e-05 3.382314e-05 3.382314e-05 0.000000e+00 0.000000e+00
[286] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[291] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[296] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[301] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[306] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[311] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[316] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[321] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[326] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[331] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[336] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[341] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[346] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[351] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[356] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[361] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[366] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[371] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[376] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[381] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[386] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[391] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[396] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[401] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[406] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[411] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[416] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[421] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[426] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[431] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[436] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[441] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[446] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[451] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[456] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[461] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[466] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
[471] 0.000000e+00 0.000000e+00 0.000000e+00

In [36]:
sorted_feature_importance = rev(sort(grf::variable_importance(GRF_object)))

In [42]:
sum(sorted_feature_importance[1:10])

[1] 0.4802782

### Time Invariant Features?

In [43]:
hhs_X_w_clusters = readr::read_csv("../benchmark_tcv_kmeans_code/hhs_X_w_clusters.csv")

Rows: 3136 Columns: 253
── Column specification ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr   (2): county, state
dbl (251): fips, LAT, LON, E_UNEMP, E_PCI, E_SNGPNT, E_MUNIT, E_CROWD, E_NOV...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [44]:
names(hhs_X_w_clusters)

  [1] "fips"
  [2] "county"
  [3] "state"
  [4] "LAT"
  [5] "LON"
  [6] "E_UNEMP"
  [7] "E_PCI"
  [8] "E_SNGPNT"
  [9] "E_MUNIT"
 [10] "E_CROWD"
 [11] "E_NOVEH"
 [12] "E_GROUPQ"
 [13] "EP_POV"
 [14] "MP_POV"
 [15] "EP_UNEMP"
 [16] "MP_UNEMP"
 [17] "EP_PCI"
 [18] "MP_PCI"
 [19] "EP_NOHSDP"
 [20] "MP_NOHSDP"
 [21] "EP_AGE65"
 [22] "MP_AGE65"
 [23] "EP_AGE17"
 [24] "MP_AGE17"
 [25] "EP_DISABL"
 [26] "MP_DISABL"
 [27] "EP_SNGPNT"
 [28] "MP_SNGPNT"
 [29] "EP_MINRTY"
 [30] "MP_MINRTY"
 [31] "EP_LIMENG"
 [32] "MP_LIMENG"
 [33] "EP_MUNIT"
 [34] "MP_MUNIT"
 [35] "EP_MOBILE"
 [36] "MP_MOBILE"
 [37] "EP_CROWD"
 [38] "MP_CROWD"
 [39] "EP_NOVEH"
 [40] "MP_NOVEH"
 [41] "EP_GROUPQ"
 [42] "MP_GROUPQ"
 [43] "EPL_POV"
 [44] "EPL_UNEMP"
 [45] "EPL_PCI"
 [46] "EPL_NOHSDP"
 [47] "SPL_THEME1"
 [48] "RPL_THEME1"
 [49] "EPL_AGE65"
 [50] "EPL_AGE17"
 [51] "EPL_DISABL"
 [52] "EPL_SNGPNT"
 [53] "SPL_THEME2"
 [54] "RPL_THEME2"
 [55] "EPL_MINRTY"
 [56] "EPL_LIMENG"
 [57] "SPL_THEME3"
 [58] "RPL_THEME3"
 [59] "EPL_MUNIT"
 [60] "EPL_MOBILE"
 [61] "EPL_CROWD"
 [62] "EPL_NOVEH"
 [63] "EPL_GROUPQ"
 [64] "SPL_THEME4"
 [65] "RPL_THEME4"
 [66] "SPL_THEMES"
 [67] "RPL_THEMES"
 [68] "F_POV"
 [69] "F_UNEMP"
 [70] "F_PCI"
 [71] "F_NOHSDP"
 [72] "F_THEME1"
 [73] "F_AGE65"
 [74] "F_AGE17"
 [75] "F_DISABL"
 [76] "F_SNGPNT"
 [77] "F_THEME2"
 [78] "F_MINRTY"
 [79] "F_LIMENG"
 [80] "F_THEME3"
 [81] "F_MUNIT"
 [82] "F_MOBILE"
 [83] "F_CROWD"
 [84] "F_NOVEH"
 [85] "F_GROUPQ"
 [86] "F_THEME4"
 [87] "F_TOTAL"
 [88] "E_UNINSUR"
 [89] "EP_UNINSUR"
 [90] "MP_UNINSUR"
 [91] "State_FIPS_Code"
 [92] "Closed_businesses_overnight"
 [93] "Religious_gatherings_exempt_without_clear_social_distance_mandate*"
 [94] "Face_mask_mandate_enforced_by_fines"
 [95] "Face_mask_mandate_enforced_by_criminal_charge/citation"
 [96] "No_legal_enforcement_of_face_mask_mandate"
 [97] "Liquor_stores_remained_open"
 [98] "Firearm_sellers_remained_open"
 [99] "Cannabis_dispensaries_considered_essential_business"
[100] "Initially_reopen_restaurants_for_outdoor_dining_only"
[101] "Vaccine_allocation_phase:_Frontline_Healthcare_Workers"
[102] "Vaccine_allocation_phase:_Healthcare_Service_Workers"
[103] "Vaccine_allocation_phase:_Home_Healthcare_Workers"
[104] "Vaccine_allocation_phase:_Additional_Healthcare_Workers"
[105] "Vaccine_allocation_phase:_Long-term_Care_Residents"
[106] "Vaccine_allocation_phase:_EMS_Providers"
[107] "Vaccine_allocation_phase:_Firefighters"
[108] "Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel"
[109] "Vaccine_allocation_phase:_Correctional_Staff"
[110] "Vaccine_allocation_phase:_People_who_are_Incarcerated"
[111] "Vaccine_allocation_phase:_Residents_of_Homeless_Shelters"
[112] "Vaccine_allocation_phase:_Adults_Ages_75+"
[113] "Vaccine_allocation_phase:_Adults_Ages_65+"
[114] "Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions"
[115] "Vaccine_allocation_phase:_Pre-K-12_School_Employees"
[116] "Vaccine_allocation_phase:_Higher_Education_Employees"
[117] "Vaccine_allocation_phase:_Public_Transit_Workers"
[118] "Vaccine_allocation_phase:_Food_Supply_Workers"
[119] "Vaccine_allocation_phase:_Grocery_Store_Workers"
[120] "Vaccine_allocation_phase:_Frontline_Essential_Workers"
[121] "Vaccine_allocation_phase:_Additional_Essential_Workers"
[122] "Vaccine_allocation_phase:_General_Public"
[123] "Adults_ages_65+_prioritized_ahead_of_essential_workers"
[124] "Prioritization_by_race/ethnicity"
[125] "Proof_of_work_eligibility_requirement_for_vaccination"
[126] "Proof_of_age_eligibility_requirement_for_vaccination"
[127] "Proof_of_residency_requirement_for_vaccination"
[128] "Penalty_for_failure_to_comply_with_vaccine_distribution_requirements"
[129] "Expanded_scope_of_practice_of_certain_health_providers_to_administer_vaccines"
[130] "State_previously_allowed_audio-only_telehealth"
[131] "State_had_CHIP_premium_non-payment_lock-out_period_as_of_January_2019"
[132] "Suspend_CHIP_premium_non-payment_lock-outs"
[133] "Report_COVID-19_testing_by_race/ethnicity"
[134] "Report_COVID-19_cases_by_race/ethnicity"
[135] "Report_COVID-19_hospitalizations_by_race"
[136] "Report_COVID-19_deaths_by_race/ethnicity"
[137] "Report_COVID-19_vaccinations_by_race/ethnicity"
[138] "Report_Indigenous_COVID-19_testing"
[139] "Report_Indigenous_COVID-19_cases"
[140] "Report_Indigenous_COVID-19_hospitalizations"
[141] "Report_Indigenous_COVID-19_deaths"
[142] "Report_Indigenous_COVID-19_vaccinations"
[143] "Does_not_charge_copays_for_incarcerated_individuals"
[144] "Waived_COVID/respiratory_illness-related_copays_during_pandemic_for_incarcerated_individuals"
[145] "Waived_all_copays_during_pandemic_for_incarcerated_individuals"
[146] "Did_not_waive_copays_for_incarcerated_individuals"
[147] "No_state_unemployment_waiting_period_prior_to_pandemic;_or_date_waiting_period_waived_not_found"
[148] "Reinstated_one_week_waiting_period_for_unemployment_insurance"
[149] "Waived_work_search_requirement_for_unemployment_insurance"
[150] "Reinstated_work_search_requirement_for_UI"
[151] "Expanded_eligibility_of_unemployment_insurance_to_anyone_who_is_quarantined_and/or_taking_care_of_someone_who_is_quarantined"
[152] "Expanded_eligibility_to_high-risk_individuals_in_preventative_quarantine"
[153] "Expanded_eligibility_of_unemployment_insurance_to_those_who_have_lost_childcare/school_closures"
[154] "Extended_the_amount_of_time_an_individual_can_be_on_unemployment_insurance"
[155] "Weekly_unemployment_insurance_maximum_amount_(dollars)"
[156] "Total_Unemployment_Rate_at_Extended_Benefits_program_shutoff"
[157] "Total_Unemployment_Rate_relative_to_prior_year_(%)"
[158] "Total_Unemployment_Rate_relative_to_second_prior_year_(%)"
[159] "Minimum_total_earnings_required_in_the_base_period_to_qualify_for_UI"
[160] "Number_of_calendar_quarters_with_earnings_in_the_base_period_needed_to_qualify_for_UI"
[161] "Minimum_total_earnings_required_outside_the_highest_earning_calendar_quarter_of_the_base_period_to_qualify_for_UI"
[162] "Require_earnings_in_the_last_two_calendar_quarters_of_the_base_period_in_order_to_qualify_for_UI"
[163] "Taxable_Wage_Amount"
[164] "Minimum_Tax_Rate_(%)"
[165] "Maximum_Tax_Rate_(%)"
[166] "Average_Benefit_Amount_(August)"
[167] "OSHA-approved_state_plan"
[168] "State_department_in_charge_of_enforcing_programs"
[169] "Aerosol_transmissable_diseases_standards"
[170] "Air_or_ventilation_standards"
[171] "Paid_sick_leave_prior_to_pandemic"
[172] "Paid_sick_leave_expansion_during_pandemic"
[173] "COVID-19_anti-retaliation_rules"
[174] "COVID-19_business_liability_protections"
[175] "COVID-19_liability_protections_for_healthcare_providers"
[176] "Branch_of_government_implementing_COVID-19_liability_rules"
[177] "COVID-19_workers'_compensation_expansion"
[178] "Types_of_workers_eligible_for_workers'_compensation_expansion"
[179] "Data_reporting_required_for_medical_treatment"
[180] "Minimum_number_of_work_days_missed_by_workers_to_require_data_reporting"
[181] "Occupational_injuries,_illnesses,_and_fatalities_reporting_prior_to_pandemic"
[182] "Made_Effort_to_Limit_Abortion_Access"
[183] "Medicaid_Expansion"
[184] "Population_density_per_square_miles"
[185] "Number_Homeless_(2019)"
[186] "Percent_Unemployed_(2018)"
[187] "Percent_living_under_the_federal_poverty_line_(2018)"
[188] "Percent_at_risk_for_serious_illness_due_to_COVID"
[189] "Mental_health_professionals_per_100,000_population_in_2019"
[190] "Were_there_casino(s)_in_State?_(Land_and_Non-Land_based)"
[191] "State_has_at_least_one_Indian/Alaska_Native_reservation"
[192] "Permanent_mail-in_ballot_system"
[193] "Automatic_mail-in_ballot_system_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)"
[194] "Automatic_applications_sent_for_mail-in_ballots_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)"
[195] "Last_date_of_receipt_of_mail-in_ballot_request_for_the_general_election_(by_mail_or_online)"
[196] "Mention_of_tribal_casinos"
[197] "Jan_1_2019_Minimum_Wage"
[198] "Mar_29_2019_Minimum_Wage"
[199] "Jul_1_2019_Minimum_Wage"
[200] "Oct_1_2019_Minimum_Wage"
[201] "Different_Minimum_Wage_for_Smaller_Businesses"
[202] "positiveScore"
[203] "hhs_region"
[204] "kmeans_k=10_labels"
[205] "kmeans_k=100_labels"
[206] "kmeans_k=1000_labels"
[207] "kmeans_k=11_labels"
[208] "kmeans_k=1100_labels"
[209] "kmeans_k=12_labels"
[210] "kmeans_k=1200_labels"
[211] "kmeans_k=13_labels"
[212] "kmeans_k=1300_labels"
[213] "kmeans_k=14_labels"
[214] "kmeans_k=1400_labels"
[215] "kmeans_k=15_labels"
[216] "kmeans_k=1500_labels"
[217] "kmeans_k=16_labels"
[218] "kmeans_k=1600_labels"
[219] "kmeans_k=17_labels"
[220] "kmeans_k=1700_labels"
[221] "kmeans_k=18_labels"
[222] "kmeans_k=1800_labels"
[223] "kmeans_k=19_labels"
[224] "kmeans_k=1900_labels"
[225] "kmeans_k=2_labels"
[226] "kmeans_k=20_labels"
[227] "kmeans_k=200_labels"
[228] "kmeans_k=2000_labels"
[229] "kmeans_k=2100_labels"
[230] "kmeans_k=2200_labels"
[231] "kmeans_k=2300_labels"
[232] "kmeans_k=2400_labels"
[233] "kmeans_k=2500_labels"
[234] "kmeans_k=2600_labels"
[235] "kmeans_k=2700_labels"
[236] "kmeans_k=2800_labels"
[237] "kmeans_k=2900_labels"
[238] "kmeans_k=3_labels"
[239] "kmeans_k=300_labels"
[240] "kmeans_k=3000_labels"
[241] "kmeans_k=3100_labels"
[242] "kmeans_k=4_labels"
[243] "kmeans_k=400_labels"
[244] "kmeans_k=5_labels"
[245] "kmeans_k=500_labels"
[246] "kmeans_k=6_labels"
[247] "kmeans_k=600_labels"
[248] "kmeans_k=7_labels"
[249] "kmeans_k=700_labels"
[250] "kmeans_k=8_labels"
[251] "kmeans_k=800_labels"
[252] "kmeans_k=9_labels"
[253] "kmeans_k=900_labels"

In [47]:
setdiff(names(GRF_object$X.orig), names(hhs_X_w_clusters))

  [1] "log_rolled_cases.y"
  [2] "AREA_SQMI"
  [3] "E_TOTPOP"
  [4] "E_HU"
  [5] "E_HH"
  [6] "E_POV"
  [7] "E_NOHSDP"
  [8] "E_AGE65"
  [9] "E_AGE17"
 [10] "E_DISABL"
 [11] "E_MINRTY"
 [12] "E_LIMENG"
 [13] "E_MOBILE"
 [14] "E_DAYPOP"
 [15] "State_of_emergency_issued"
 [16] "State_of_emergency_lifted"
 [17] "Date_closed_K.12_public_schools"
 [18] "Closed_day_cares"
 [19] "Reopen_day_cares"
 [20] "Date_banned_visitors_to_nursing_homes"
 [21] "Stay_at_home._shelter_in_place"
 [22] "Stay_at_home_order._issued_but_did_not_specifically_restrict_movement_of_the_general_public"
 [23] "End.relax_stay_at_home.shelter_in_place"
 [24] "Closed_other_non.essential_businesses"
 [25] "Began_to_reopen_businesses"
 [26] "Religious_gatherings_exempt_without_clear_social_distance_mandate."
 [27] "Face_mask_mandate_in_public_spaces"
 [28] "Face_mask_mandate_x2"
 [29] "Face_mask_mandate_enforced_by_criminal_charge.citation"
 [30] "Face_mask_mandate_for_employees_of_public.facing_businesses"
 [31] "Ended_face_mask_mandate"
 [32] "Ended_face_mask_mandate_x2"
 [33] "Attempted_to_prevent_local_governments_from_implementing_face_mask_orders"
 [34] "Banned_local_mask_mandates"
 [35] "Allowed_restaurants_to_sell_takeout_alcohol"
 [36] "Allowed_restaurants_to_deliver_alcohol"
 [37] "Closed_restaurants_except_take_out"
 [38] "Reopen_restaurants"
 [39] "Closed_gyms"
 [40] "Reopened_gyms"
 [41] "Closed_movie_theaters"
 [42] "Reopened_movie_theaters"
 [43] "Closed_Bars"
 [44] "Reopen_bars"
 [45] "Reopened_hair_salons.barber_shops"
 [46] "Reopened_religious_gatherings"
 [47] "Reopened_other_non.essential_retail"
 [48] "Allowed_businesses_to_reopen_overnight"
 [49] "Began_to_reclose_bars"
 [50] "Closed_bars_.x2."
 [51] "Closed_movie_theaters_.x2."
 [52] "Closed_hair_salons.barber_shops_.x2."
 [53] "Closed_gyms_.x2."
 [54] "Closed_restaurants_.x2."
 [55] "Reopened_restaurants_.x2."
 [56] "Reopened_bars_.x2."
 [57] "Reopened_gyms_.x2."
 [58] "Reopened_hair_salons.barber_shops_.x2."
 [59] "Reopened_movie_theaters_.x2."
 [60] "Closed_bars_.x3."
 [61] "Closed_restaurants_.x3."
 [62] "Reopened_bars_.x3."
 [63] "Reopened_restaurants_.x3."
 [64] "Mandate_quarantine_for_those_entering_the_state_from_specific_settings"
 [65] "Mandate_quarantine_for_all_individuals_entering_the_state"
 [66] "Date_all_mandated_quarantines_ended"
 [67] "Date_vaccine_allocation_plan_last_updated"
 [68] "Vaccine_allocation_phase._Frontline_Healthcare_Workers"
 [69] "Vaccine_allocation_phase._Healthcare_Service_Workers"
 [70] "Vaccine_allocation_phase._Home_Healthcare_Workers"
 [71] "Vaccine_allocation_phase._Additional_Healthcare_Workers"
 [72] "Vaccine_allocation_phase._Long.term_Care_Residents"
 [73] "Vaccine_allocation_phase._EMS_Providers"
 [74] "Vaccine_allocation_phase._Firefighters"
 [75] "Vaccine_allocation_phase._Law_Enforcement_._Public_Safety_Personnel"
 [76] "Vaccine_allocation_phase._Correctional_Staff"
 [77] "Vaccine_allocation_phase._People_who_are_Incarcerated"
 [78] "Vaccine_allocation_phase._Residents_of_Homeless_Shelters"
 [79] "Vaccine_allocation_phase._Adults_Ages_75."
 [80] "Vaccine_allocation_phase._Adults_Ages_65."
 [81] "Vaccine_allocation_phase._Adults_w._High.Risk_Medical_Conditions"
 [82] "Vaccine_allocation_phase._Pre.K.12_School_Employees"
 [83] "Vaccine_allocation_phase._Higher_Education_Employees"
 [84] "Vaccine_allocation_phase._Public_Transit_Workers"
 [85] "Vaccine_allocation_phase._Food_Supply_Workers"
 [86] "Vaccine_allocation_phase._Grocery_Store_Workers"
 [87] "Vaccine_allocation_phase._Frontline_Essential_Workers"
 [88] "Vaccine_allocation_phase._Additional_Essential_Workers"
 [89] "Vaccine_allocation_phase._General_Public"
 [90] "Date_adults_ages_80._became_eligible_for_COVID.19_vaccination"
 [91] "Date_adults_ages_75._became_eligible_for_COVID.19_vaccination"
 [92] "Date_adults_ages_70._became_eligible_for_COVID.19_vaccination"
 [93] "Date_adults_ages_65._became_eligible_for_COVID.19_vaccination"
 [94] "Date_adults_ages_60._became_eligible_for_COVID.19_vaccination"
 [95] "Date_adults_ages_55._became_eligible_for_COVID.19_vaccination"
 [96] "Date_adults_ages_50._became_eligible_for_COVID.19_vaccination"
 [97] "Date_adults_ages_45._became_eligible_for_COVID.19_vaccination"
 [98] "Date_adults_ages_40._became_eligible_for_COVID.19_vaccination"
 [99] "Date_adults_ages_30._became_eligible_for_COVID.19_vaccination"
[100] "Date_K.12_school_employees_became_eligible_for_COVID.19_vaccination"
[101] "Date_grocery_store_workers_became_eligible_for_COVID.19_vaccination"
[102] "Date_incarcerated_people_became_eligible_for_COVID.19_vaccination"
[103] "Date_general_public_became_eligible_for_COVID.19_vaccination"
[104] "Adults_ages_65._prioritized_ahead_of_essential_workers"
[105] "Prioritization_by_race.ethnicity"
[106] "First_overall_eviction_moratorium_start"
[107] "First_overall_eviction_moratorium_end"
[108] "Second_overall_eviction_moratorium_start"
[109] "Second_overall_eviction_moratorium_end"
[110] "Third_overall_eviction_moratorium_start"
[111] "Third_overall_eviction_moratorium_end"
[112] "First_eviction_initiation_ban_start"
[113] "First_eviction_initiation_ban_end"
[114] "Second_Eviction_Initiation_Ban_Start"
[115] "Second_Eviction_Initiation_Ban_End"
[116] "First_eviction_hearing_ban_start"
[117] "First_eviction_hearing_ban_end"
[118] "Second_Eviction_Hearing_Ban_Start"
[119] "Second_Eviction_Hearing_Ban_End"
[120] "First_eviction_enforcement_ban_start"
[121] "First_eviction_enforcement_ban_end"
[122] "Second_Eviction_Enforcement_Ban_Start"
[123] "Second_Eviction_Enforcement_Ban_End"
[124] "COVID.19_hardship_limitation_start"
[125] "COVID.19_hardship_limitation_end"
[126] "Second_COVID.19_hardship_limitation_start"
[127] "Second_COVID.19_hardship_limitation_end"
[128] "Non.payment_limitation_start"
[129] "Non.payment_limitation_end"
[130] "Second_non.payment_limitation_start"
[131] "Second_non.payment_limitation_end"
[132] "CARES_Act_pleading_start"
[133] "CARES_Act_pleading_end"
[134] "CDC_moratorium_start"
[135] "CDC_moratorium_end"
[136] "Late_Fee_Ban_Start"
[137] "Late_Fee_Ban_End"
[138] "Second_Late_Fee_Ban_Start"
[139] "Second_Late_Fee_Ban_End"
[140] "Utilities_shutoff_moratorium_start"
[141] "Utilities_shutoff_moratorium_expiration"
[142] "Second_utilities_shutoff_moratorium_start"
[143] "Utilities_reconnection_start"
[144] "Utilities_reconnection_end"
[145] "SNAP_Waiver_._Emergency_Allotments_to_Current_SNAP_Households"
[146] "SNAP_Waiver_._Pandemic_EBT_during_school_year_2019.2020"
[147] "SNAP_Waiver_._Pandemic_EBT_during_school_year_2020.2021"
[148] "SNAP_Waiver_._Pandemic_EBT_during_summer_2021"
[149] "SNAP_Waiver_._Temporary_Suspension_of_Claims_Collection"
[150] "X2020_Q1_SNAP_ABAWD_Time_Limit_Waiver"
[151] "Modify_Medicaid_requirements_with_1135_waivers_.date_of_CMS_approval."
[152] "Reopened_ACA_enrollment_using_a_special_enrollment_period"
[153] "State_previously_allowed_audio.only_telehealth"
[154] "Allow_audio.only_telehealth"
[155] "Allow.expand_Medicaid_telehealth_coverage"
[156] "State_had_CHIP_premium_non.payment_lock.out_period_as_of_January_2019"
[157] "Suspend_CHIP_premium_non.payment_lock.outs"
[158] "Report_COVID.19_testing_by_race.ethnicity"
[159] "Report_COVID.19_cases_by_race.ethnicity"
[160] "Report_COVID.19_hospitalizations_by_race"
[161] "Report_COVID.19_deaths_by_race.ethnicity"
[162] "Report_COVID.19_vaccinations_by_race.ethnicity"
[163] "Report_Indigenous_COVID.19_testing"
[164] "Report_Indigenous_COVID.19_cases"
[165] "Report_Indigenous_COVID.19_hospitalizations"
[166] "Report_Indigenous_COVID.19_deaths"
[167] "Report_Indigenous_COVID.19_vaccinations"
[168] "Stopped_personal_visitation_in_state_prisons"
[169] "Stopped_legal_visitation_in_state_prisons"
[170] "Resumed_visitation_in_state_prisons"
[171] "Stopped_visitation_in_state_prisons_x2"
[172] "Resumed_visitation_in_state_prisons_x2"
[173] "Waived_COVID.respiratory_illness.related_copays_during_pandemic_for_incarcerated_individuals"
[174] "Suspended_elective_medical_procedures"
[175] "Resumed_elective_medical_procedures"
[176] "No_order_to_suspend_elective_medical_procedures_but_did_release_guidance_or_orders_to_resume"
[177] "Suspended_elective_medical_procedures_x2"
[178] "Resumed_elective_medical_procedures_x2"
[179] "No_state_unemployment_waiting_period_prior_to_pandemic._or_date_waiting_period_waived_not_found"
[180] "Waived_one_week_waiting_period_for_unemployment_insurance"
[181] "Expanded_eligibility_of_unemployment_insurance_to_anyone_who_is_quarantined_and.or_taking_care_of_someone_who_is_quarantined"
[182] "Expanded_eligibility_to_high.risk_individuals_in_preventative_quarantine"
[183] "Expanded_eligibility_of_unemployment_insurance_to_those_who_have_lost_childcare.school_closures"
[184] "Weekly_unemployment_insurance_maximum_amount_.dollars."
[185] "Weekly_unemployment_insurance_maximum_amount_with_extra_stimulus_.through_July_31._2020._.dollars."
[186] "January_2020_unemployment_insurance_maximum_duration_.weeks."
[187] "July_2020_unemployment_insurance_maximum_duration_.weeks."
[188] "X2021_unemployment_insurance_maximum_duration_.weeks."
[189] "Extended_Benefits_program_activated"
[190] "Extended_Benefits_program_deactivated"
[191] "Extended_Benefits_program_activated_x2"
[192] "Total_Unemployment_Rate_relative_to_prior_year_..."
[193] "Total_Unemployment_Rate_relative_to_second_prior_year_..."
[194] "X20.week_Extended_Benefits_program_activated"
[195] "X20.week_Extended_Benefits_program_deactivated"
[196] "X20.week_Extended_Benefits_program_activated_x2"
[197] "Stopped_participating_in_pandemic.related_federal_unemployment_benefit_programs"
[198] "Earnings_in_base_period_required_to_receive_a_.300_weekly_benefit_amount_for_UI"
[199] "Minimum_Tax_Rate_..."
[200] "Maximum_Tax_Rate_..."
[201] "Average_Benefit_Amount_.August."
[202] "OSHA.approved_state_plan"
[203] "COVID.19_anti.retaliation_rules"
[204] "COVID.19_business_liability_protections"
[205] "COVID.19_liability_protections_for_healthcare_providers"
[206] "Branch_of_government_implementing_COVID.19_liability_rules"
[207] "COVID.19_workers._compensation_expansion"
[208] "Types_of_workers_eligible_for_workers._compensation_expansion"
[209] "Occupational_injuries._illnesses._and_fatalities_reporting_prior_to_pandemic"
[210] "Use_of_telemedicine.telephone_evaluations_to_initiate_buprenorphine_prescribing"
[211] "Patients_can_receive_14.28_take.home_doses_of_opioid_medication"
[212] "Home_delivery_of_take.home_medication_by_opioid_treatment_programs"
[213] "Use_of_telemedicine_for_schedule_II.V_prescriptions"
[214] "Exceptions_to_emergency_oral_prescriptions"
[215] "Waive_requirement_to_obtain_separate_DEA_registration_to_dispense_outside_home_state"
[216] "Population_2018"
[217] "Square_Miles"
[218] "Number_Homeless_.2019."
[219] "Percent_Unemployed_.2018."
[220] "Percent_living_under_the_federal_poverty_line_.2018."
[221] "All.cause_deaths_2018"
[222] "Mental_health_professionals_per_100.000_population_in_2019"
[223] "Were_there_casino.s._in_State._.Land_and_Non.Land_based."
[224] "State_has_at_least_one_Indian.Alaska_Native_reservation"
[225] "COVID.19_is_not_an_acceptable_reason_to_request_application_for_mail.in_ballot_unless_sick_or_exposed_.as_of_September_16._2020."
[226] "Witness_or_notary_signature_required_for_mail.in_ballot_.as_of_September_1._2020."
[227] "Permanent_mail.in_ballot_system"
[228] "Automatic_mail.in_ballot_system_in_response_to_COVID.19_.0.1.2_2_being_conditional._see_notes_for_details."
[229] "Automatic_applications_sent_for_mail.in_ballots_in_response_to_COVID.19_.0.1.2_2_being_conditional._see_notes_for_details."
[230] "Last_date_of_receipt_of_mail.in_ballot_request_for_the_general_election_.by_mail_or_online."
[231] "Closed_casinos"
[232] "Reopened_casinos"
[233] "Closed_casinos_.x2."
[234] "Reopened_casinos_.x2."
[235] "Jan_1_2020_Minimum_Wage"
[236] "Jul_1_2020_Minimum_Wage"
[237] "Sep_1_2020_Minimum_Wage"
[238] "Oct_1_2020_Minimum_Wage"
[239] "X2020_Minimum_Wage_for_Tipped_Workers"
[240] "X2021_Minimum_Wage"
[241] "death"
[242] "deathConfirmed"
[243] "deathIncrease"
[244] "deathProbable"
[245] "hospitalized"
[246] "hospitalizedCumulative"
[247] "hospitalizedCurrently"
[248] "hospitalizedIncrease"
[249] "inIcuCumulative"
[250] "inIcuCurrently"
[251] "negative"
[252] "negativeIncrease"
[253] "negativeTestsAntibody"
[254] "negativeTestsPeopleAntibody"
[255] "negativeTestsViral"
[256] "onVentilatorCumulative"
[257] "onVentilatorCurrently"
[258] "positive"
[259] "positiveCasesViral"
[260] "positiveIncrease"
[261] "positiveTestsAntibody"
[262] "positiveTestsAntigen"
[263] "positiveTestsPeopleAntibody"
[264] "positiveTestsPeopleAntigen"
[265] "positiveTestsViral"
[266] "recovered"
[267] "totalTestEncountersViral"
[268] "totalTestEncountersViralIncrease"
[269] "totalTestResults"
[270] "totalTestResultsIncrease"
[271] "totalTestsAntibody"
[272] "totalTestsAntigen"
[273] "totalTestsPeopleAntibody"
[274] "totalTestsPeopleAntigen"
[275] "totalTestsPeopleViral"
[276] "totalTestsPeopleViralIncrease"
[277] "totalTestsViral"
[278] "totalTestsViralIncrease"
[279] "metrics.testPositivityRatio"
[280] "metrics.vaccinationsInitiatedRatio"
[281] "metrics.vaccinationsCompletedRatio"
[282] "Variant...A.2.5"
[283] "Variant...AY.1"
[284] "Variant...AY.2"
[285] "Variant...AY.3"
[286] "Variant...B.1"
[287] "Variant...B.1.1"
[288] "Variant...B.1.1.194"
[289] "Variant...B.1.1.519"
[290] "Variant...B.1.1.529"
[291] "Variant...B.1.1.7"
[292] "Variant...B.1.2"
[293] "Variant...B.1.234"
[294] "Variant...B.1.243"
[295] "Variant...B.1.351"
[296] "Variant...B.1.427"
[297] "Variant...B.1.429"
[298] "Variant...B.1.525"
[299] "Variant...B.1.526"
[300] "Variant...B.1.526.1"
[301] "Variant...B.1.526.2"
[302] "Variant...B.1.596"
[303] "Variant...B.1.617"
[304] "Variant...B.1.617.1"
[305] "Variant...B.1.617.2"
[306] "Variant...B.1.617.3"
[307] "Variant...B.1.621"
[308] "Variant...B.1.621.1"
[309] "Variant...B.1.626"
[310] "Variant...B.1.628"
[311] "Variant...B.1.637"
[312] "Variant...BA.1.1"
[313] "Variant...BA.2"
[314] "Variant...BA.2.12.1"
[315] "Variant...BA.2.75"
[316] "Variant...BA.2.75.2"
[317] "Variant...BA.4"
[318] "Variant...BA.4.6"
[319] "Variant...BA.5"
[320] "Variant...BA.5.2.6"
[321] "Variant...BF.11"
[322] "Variant...BF.7"
[323] "Variant...BN.1"
[324] "Variant...BQ.1"
[325] "Variant...BQ.1.1"
[326] "Variant...CH.1.1"
[327] "Variant...FD.2"
[328] "Variant...Other"
[329] "Variant...P.1"
[330] "Variant...P.2"
[331] "Variant...R.1"
[332] "Variant...XBB"
[333] "Variant...XBB.1.16"
[334] "Variant...XBB.1.5"
[335] "Variant...XBB.1.5.1"
[336] "Variant...XBB.1.9.1"
[337] "Variant...XBB.1.9.2"
[338] "Variant...XBB.2.3"
[339] "cutoff"
[340] "t0.lm"
[341] "r.lm"

In [46]:
GRF_object$X.orig$Waived_all_copays_during_pandemic_for_incarcerated_individuals

   [1]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  [25]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  [49]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  [73]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  [97]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [121]  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [145]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [169]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [193]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [217]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [241]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [265]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [289]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [313]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [337]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [361]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [385]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [409]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [433]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [457]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [481]  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  1  1
 [505]  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [529]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [553]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [577]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [601]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [625]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [649]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [673]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [697]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [721]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [745]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [769]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [793]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [817]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [841]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [865]  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [889]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [913]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [937]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [961]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 [985]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1009]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1033]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1057]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1081]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1105]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1129]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1153]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1177]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1201]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1225]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1249]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1273]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1297]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1321]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1345]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1369]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1393]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1417]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1441]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1465]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1489]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1513]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1537]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1561]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1585]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1609]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1633]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1657]  0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1681]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1705]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1729]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1753]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0
[1777]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1
[1801]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1825]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1849]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1873]  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1897]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1921]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1945]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1969]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[1993]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2017]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1
[2041]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[2065]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[2089]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[2113]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[2137]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[2161]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[2185]  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2209]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2233]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2257]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2281]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2305]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2329]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2353]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2377]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2401]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2425]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2449]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2473]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2497]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2521]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2545]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2569]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2593]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2617]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2641]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2665]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2689]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2713]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2737]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2761]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2785]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2809]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2833]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2857]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2881]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2905]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2929]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2953]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2977]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3001]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3025]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3049]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3073]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3097]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3121]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3145]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3169]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3193]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3217]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3241]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3265]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3289]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3313]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3337]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3361]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3385]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3409]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3433]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3457]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3481]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3505]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3529]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3553]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3577]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1
[3601]  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3625]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3649]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3673]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3697]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3721]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1
[3745]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[3769]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[3793]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[3817]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[3841]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[3865]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[3889]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[3913]  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3937]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3961]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3985]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4009]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4033]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4057]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4081]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4105]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4129]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4153]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4177]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4201]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4225]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4249]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4273]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4297]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4321]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4345]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4369]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4393]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4417]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4441]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4465]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4489]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4513]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4537]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4561]  0  0  0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[4585]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[4609]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[4633]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[4657]  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4681]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4705]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4729]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4753]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4777]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4801]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[4825]  0  0  0  0  0  0  0  0  0  0  0  0  0  0 NA NA NA NA  0  0