## Import Dependencies

In [1]:
list.of.packages <- c("ggplot2", "Rcpp", "grf", "caret", "mltools", "rpart", "minpack.lm", "doParallel", "rattle", "anytime","rlist")
list.of.packages <- c(list.of.packages, "zoo", "dtw", "foreach", "evaluate","rlist","data.table","plyr","dplyr")


new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, lib='/home/zwang937/local/R_libs', repos="http://cran.us.r-project.org", dependencies = TRUE, INSTALL_opts = '--no-lock')


lapply(list.of.packages, require, character.only = TRUE)

Loading required package: ggplot2

Loading required package: Rcpp

Loading required package: grf

Loading required package: caret

Loading required package: lattice

Loading required package: mltools

Loading required package: rpart

Loading required package: minpack.lm

Loading required package: doParallel

Loading required package: foreach

Loading required package: iterators

Loading required package: parallel

Loading required package: rattle

Loading required package: tibble

Loading required package: bitops

Rattle: A free graphical interface for data science with R.
Version 5.5.1 Copyright (c) 2006-2021 Togaware Pty Ltd.
Type 'rattle()' to shake, rattle, and roll your data.

Loading required package: anytime

Loading required package: rlist

Loading required package: zoo


Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric


Loading required package: dtw

Loading required package: proxy


Attaching package: ‘proxy’


The following objects are masked from ‘package:stats’:

    as.dist, dist


The following object is masked from ‘package:base’:

    as.matrix


Loaded dtw v1.22-3. See ?dtw for help, citation("dtw") for use in publication.


Loading required package: evaluate

Loading required package: data.table

Loading required package: plyr

Loading required package: dplyr


Attaching package: ‘dplyr’


The following objects are masked from ‘package:plyr’:

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize


The following objects are masked from ‘package:data.table’:

    between, first, last


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[[1]]
[1] TRUE

[[2]]
[1] TRUE

[[3]]
[1] TRUE

[[4]]
[1] TRUE

[[5]]
[1] TRUE

[[6]]
[1] TRUE

[[7]]
[1] TRUE

[[8]]
[1] TRUE

[[9]]
[1] TRUE

[[10]]
[1] TRUE

[[11]]
[1] TRUE

[[12]]
[1] TRUE

[[13]]
[1] TRUE

[[14]]
[1] TRUE

[[15]]
[1] TRUE

[[16]]
[1] TRUE

[[17]]
[1] TRUE

[[18]]
[1] TRUE

[[19]]
[1] TRUE

### Read Data

### Transformation on Panel Data

In [2]:
# SET PARAMS
windowsize=2
num_trees = 100



# CREATE OUTPUT FOLDERS
mainDir = "./time_invariant_grf_results"
dir.create(mainDir, showWarnings = FALSE)

subDir = paste("time_invariant_grf_backtest_state_forests_windowsize=",toString(windowsize),"_numtrees=",toString(num_trees),sep="")
outputfolder = file.path(mainDir, subDir)


dir.create(outputfolder, showWarnings = FALSE)

grf.subfolder = paste("time_invariant_grf_grf_windowsize=",toString(windowsize),"_numtrees=",toString(num_trees),sep="")
grf.outputfolder = file.path(mainDir,grf.subfolder)
dir.create(grf.outputfolder, showWarnings = FALSE)

# READ DATA
destfile <- paste("../../data/augmented_us-counties-states_latest_variants",".csv",sep="")
augmented_panel_data <- as.data.frame(fread(file = destfile))
# Time Invariant
hhs_X_w_clusters_fpath = "../benchmark_tcv_kmeans_code/hhs_X_w_clusters.csv"
hhs_X_w_clusters = as.data.frame(fread(file = hhs_X_w_clusters_fpath))

augmented_panel_data <- augmented_panel_data[order(augmented_panel_data$fips, augmented_panel_data$days_from_start), ]
augmented_panel_data <- augmented_panel_data[augmented_panel_data$rolled_cases >= 20,]
augmented_panel_data$log_rolled_cases <- log(augmented_panel_data$rolled_cases + 1.1)
augmented_panel_data <- augmented_panel_data %>%
  group_by(fips) %>%
    mutate(log_rolled_cases_ratios = c(0, diff(log_rolled_cases)))
augmented_panel_data <- augmented_panel_data %>%
  group_by(fips) %>%
    mutate(shifted_days_from_start = days_from_start - first(days_from_start))
augmented_panel_data <- augmented_panel_data[, colSums(!is.na(augmented_panel_data)) > 0]


X_time_invariant <- (hhs_X_w_clusters[,intersect(names(augmented_panel_data), names(hhs_X_w_clusters))])
X_time_invariant <- X_time_invariant[,!names(X_time_invariant) %in% c("county","state")]

start_day = min(augmented_panel_data$days_from_start)
end_day = max(augmented_panel_data$days_from_start)

cutoff_list <- start_day:end_day

### Earlier Days

In [9]:
cutoff=100

check.file.name <- paste0("classical_grf_stateforest_cutoff=", toString(cutoff), ".rds")
check.file.full.name <- file.path(grf.outputfolder, check.file.name)
if (file.exists(check.file.full.name)){
    print(paste0(check.file.name, " exists, skipping"))
    #next
}
print(paste0("Computing Classical GRF for ", toString(cutoff)))
# START TRY

start_time <- Sys.time()
# Given my current cutoff, which block numbers should I use?
fname <- paste("time_invariant_grf_",toString(cutoff),".csv",sep="")        
# SLICE THE DATA ACCORDINGLY
early_data <- augmented_panel_data[augmented_panel_data$days_from_start <= cutoff, ]
case_number_columns <- c("fips","date","county","state","days_from_start","log_rolled_cases", "shifted_days_from_start")
early_data_case_numbers <- early_data[, names(early_data) %in% case_number_columns]
# Format data to be fed to GRF
WYX <- merge(early_data_case_numbers, X_time_invariant, by="fips", all.x=TRUE)
WYX <- WYX[order(WYX$fips, WYX$days_from_start),]

Y <- WYX$log_rolled_cases
W <- WYX$shifted_days_from_start
X <- WYX[, !names(WYX) %in% case_number_columns]

cf <- causal_forest(X,Y,as.numeric(W), num.trees=num_trees, seed = 1)
cf.fname <- check.file.name
cf.path <- file.path(grf.outputfolder, cf.fname)
print(paste0("Saving ", cf.fname))
#saveRDS(cf, cf.path)

# GENERATE r_GRF estimates
WYX_test <- WYX %>%
  group_by(fips) %>%
  filter(days_from_start == max(days_from_start))
X_test <- WYX_test[, !names(WYX_test) %in% case_number_columns]
r_GRF <- predict(cf, X_test)

# Generate predictions
indexing_columns <- c("fips","county","state","date", "days_from_start","shifted_days_from_start", "rolled_cases", "log_rolled_cases")
indexing <- WYX_test[, names(WYX) %in% indexing_columns]
indexing$r_GRF <- unlist(r_GRF)
indexing$predicted_log_rolled_cases_GRF <- indexing$r_GRF*7 + indexing$log_rolled_cases

[1] "classical_grf_stateforest_cutoff=100.rds exists, skipping"
[1] "Computing Classical GRF for 100"
[1] "Saving classical_grf_stateforest_cutoff=100.rds"

In [10]:

X

      LAT      LON       E_UNEMP E_PCI E_SNGPNT E_MUNIT E_CROWD E_NOVEH
8     32.53224 -86.64644 1065    29372 1586       886   299     1191
1     32.53224 -86.64644 1065    29372 1586       886   299     1191
2     32.53224 -86.64644 1065    29372 1586       886   299     1191
3     32.53224 -86.64644 1065    29372 1586       886   299     1191
7     32.53224 -86.64644 1065    29372 1586       886   299     1191
4     32.53224 -86.64644 1065    29372 1586       886   299     1191
5     32.53224 -86.64644 1065    29372 1586       886   299     1191
6     32.53224 -86.64644 1065    29372 1586       886   299     1191
12    32.53224 -86.64644 1065    29372 1586       886   299     1191
13    32.53224 -86.64644 1065    29372 1586       886   299     1191
10    32.53224 -86.64644 1065    29372 1586       886   299     1191
11    32.53224 -86.64644 1065    29372 1586       886   299     1191
14    32.53224 -86.64644 1065    29372 1586       886   299     1191
15    32.53224 -86.64644 1065    29372 1586       886   299     1191
9     32.53224 -86.64644 1065    29372 1586       886   299     1191
16    30.65922 -87.74607 4343    31203 4508     20492   991     2705
17    30.65922 -87.74607 4343    31203 4508     20492   991     2705
20    30.65922 -87.74607 4343    31203 4508     20492   991     2705
21    30.65922 -87.74607 4343    31203 4508     20492   991     2705
18    30.65922 -87.74607 4343    31203 4508     20492   991     2705
19    30.65922 -87.74607 4343    31203 4508     20492   991     2705
30    30.65922 -87.74607 4343    31203 4508     20492   991     2705
31    30.65922 -87.74607 4343    31203 4508     20492   991     2705
32    30.65922 -87.74607 4343    31203 4508     20492   991     2705
33    30.65922 -87.74607 4343    31203 4508     20492   991     2705
34    30.65922 -87.74607 4343    31203 4508     20492   991     2705
35    30.65922 -87.74607 4343    31203 4508     20492   991     2705
36    30.65922 -87.74607 4343    31203 4508     20492   991     2705
24    30.65922 -87.74607 4343    31203 4508     20492   991     2705
25    30.65922 -87.74607 4343    31203 4508     20492   991     2705
⋮     ⋮        ⋮         ⋮       ⋮     ⋮        ⋮       ⋮       ⋮
31486 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31487 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31488 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31489 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31490 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31491 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31492 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31493 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31494 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31495 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31496 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31497 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31498 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31499 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31500 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31501 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31502 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31503 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31504 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31505 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31506 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31507 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31508 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31509 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31510 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31511 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31512 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31513 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31514 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
31515 40.65857 -73.95064 70250   31984 60827    358674  61715   292462
      E_GROUPQ EP_POV ⋯
8      546     15.4   ⋯
1      546     15.4   ⋯
2      546     15.4   ⋯
3      546     15.4   ⋯
7      546     15.4   ⋯
4      546     15.4   ⋯
5      546     15.4   ⋯
6      546     15.4   ⋯
12     546     15.4   ⋯
13     546     15.4   ⋯
10     546     15.4   ⋯
11     546     15.4   ⋯
14     546     15.4   ⋯
15     546     15.4   ⋯
9      546     15.4   ⋯
16    3014     10.6   ⋯
17    3014     10.6   ⋯
20    3014     10.6   ⋯
21    3014     10.6   ⋯
18    3014     10.6   ⋯
19    3014     10.6   ⋯
30    3014     10.6   ⋯
31    3014     10.6   ⋯
32    3014     10.6   ⋯
33    3014     10.6   ⋯
34    3014     10.6   ⋯
35    3014     10.6   ⋯
36    3014     10.6   ⋯
24    3014     10.6   ⋯
25    3014     10.6   ⋯
⋮     ⋮        ⋮      ⋱
31486 40893    16.6   ⋯
31487 40893    16.6   ⋯
31488 40893    16.6   ⋯
31489 40893    16.6   ⋯
31490 40893    16.6   ⋯
31491 40893    16.6   ⋯
31492 40893    16.6   ⋯
31493 40893    16.6   ⋯
31494 40893    16.6   ⋯
31495 40893    16.6   ⋯
31496 40893    16.6   ⋯
31497 40893    16.6   ⋯
31498 40893    16.6   ⋯
31499 40893    16.6   ⋯
31500 40893    16.6   ⋯
31501 40893    16.6   ⋯
31502 40893    16.6   ⋯
31503 40893    16.6   ⋯
31504 40893    16.6   ⋯
31505 40893    16.6   ⋯
31506 40893    16.6   ⋯
31507 40893    16.6   ⋯
31508 40893    16.6   ⋯
31509 40893    16.6   ⋯
31510 40893    16.6   ⋯
31511 40893    16.6   ⋯
31512 40893    16.6   ⋯
31513 40893    16.6   ⋯
31514 40893    16.6   ⋯
31515 40893    16.6   ⋯
      Automatic_applications_sent_for_mail-in_ballots_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)
8     0
1     0
2     0
3     0
7     0
4     0
5     0
6     0
12    0
13    0
10    0
11    0
14    0
15    0
9     0
16    0
17    0
20    0
21    0
18    0
19    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
24    0
25    0
⋮     ⋮
31486 2
31487 2
31488 2
31489 2
31490 2
31491 2
31492 2
31493 2
31494 2
31495 2
31496 2
31497 2
31498 2
31499 2
31500 2
31501 2
31502 2
31503 2
31504 2
31505 2
31506 2
31507 2
31508 2
31509 2
31510 2
31511 2
31512 2
31513 2
31514 2
31515 2
      Last_date_of_receipt_of_mail-in_ballot_request_for_the_general_election_(by_mail_or_online)
8     44133
1     44133
2     44133
3     44133
7     44133
4     44133
5     44133
6     44133
12    44133
13    44133
10    44133
11    44133
14    44133
15    44133
9     44133
16    44133
17    44133
20    44133
21    44133
18    44133
19    44133
30    44133
31    44133
32    44133
33    44133
34    44133
35    44133
36    44133
24    44133
25    44133
⋮     ⋮
31486 44131
31487 44131
31488 44131
31489 44131
31490 44131
31491 44131
31492 44131
31493 44131
31494 44131
31495 44131
31496 44131
31497 44131
31498 44131
31499 44131
31500 44131
31501 44131
31502 44131
31503 44131
31504 44131
31505 44131
31506 44131
31507 44131
31508 44131
31509 44131
31510 44131
31511 44131
31512 44131
31513 44131
31514 44131
31515 44131
      Mention_of_tribal_casinos Jan_1_2019_Minimum_Wage
8     0                         7.25
1     0                         7.25
2     0                         7.25
3     0                         7.25
7     0                         7.25
4     0                         7.25
5     0                         7.25
6     0                         7.25
12    0                         7.25
13    0                         7.25
10    0                         7.25
11    0                         7.25
14    0                         7.25
15    0                         7.25
9     0                         7.25
16    0                         7.25
17    0                         7.25
20    0                         7.25
21    0                         7.25
18    0                         7.25
19    0                         7.25
30    0                         7.25
31    0                         7.25
32    0                         7.25
33    0                         7.25
34    0                         7.25
35    0                         7.25
36    0                         7.25
24    0                         7.25
25    0                         7.25
⋮     ⋮                         ⋮
31486 1                         11.1
31487 1                         11.1
31488 1                         11.1
31489 1                         11.1
31490 1                         11.1
31491 1                         11.1
31492 1                         11.1
31493 1                         11.1
31494 1                         11.1
31495 1                         11.1
31496 1                         11.1
31497 1                         11.1
31498 1                         11.1
31499 1                         11.1
31500 1                         11.1
31501 1                         11.1
31502 1                         11.1
31503 1                         11.1
31504 1                         11.1
31505 1                         11.1
31506 1                         11.1
31507 1                         11.1
31508 1                         11.1
31509 1                         11.1
31510 1                         11.1
31511 1                         11.1
31512 1                         11.1
31513 1                         11.1
31514 1                         11.1
31515 1                         11.1
      Mar_29_2019_Minimum_Wage Jul_1_2019_Minimum_Wage Oct_1_2019_Minimum_Wage
8     7.25                     7.25                    7.25
1     7.25                     7.25                    7.25
2     7.25                     7.25                    7.25
3     7.25                     7.25                    7.25
7     7.25                     7.25                    7.25
4     7.25                     7.25                    7.25
5     7.25                     7.25                    7.25
6     7.25                     7.25                    7.25
12    7.25                     7.25                    7.25
13    7.25                     7.25                    7.25
10    7.25                     7.25                    7.25
11    7.25                     7.25                    7.25
14    7.25                     7.25                    7.25
15    7.25                     7.25                    7.25
9     7.25                     7.25                    7.25
16    7.25                     7.25                    7.25
17    7.25                     7.25                    7.25
20    7.25                     7.25                    7.25
21    7.25                     7.25                    7.25
18    7.25                     7.25                    7.25
19    7.25                     7.25                    7.25
30    7.25                     7.25                    7.25
31    7.25                     7.25                    7.25
32    7.25                     7.25                    7.25
33    7.25                     7.25                    7.25
34    7.25                     7.25                    7.25
35    7.25                     7.25                    7.25
36    7.25                     7.25                    7.25
24    7.25                     7.25                    7.25
25    7.25                     7.25                    7.25
⋮     ⋮                        ⋮                       ⋮
31486 11.1                     11.1                    11.1
31487 11.1                     11.1                    11.1
31488 11.1                     11.1                    11.1
31489 11.1                     11.1                    11.1
31490 11.1                     11.1                    11.1
31491 11.1                     11.1                    11.1
31492 11.1                     11.1                    11.1
31493 11.1                     11.1                    11.1
31494 11.1                     11.1                    11.1
31495 11.1                     11.1                    11.1
31496 11.1                     11.1                    11.1
31497 11.1                     11.1                    11.1
31498 11.1                     11.1                    11.1
31499 11.1                     11.1                    11.1
31500 11.1                     11.1                    11.1
31501 11.1                     11.1                    11.1
31502 11.1                     11.1                    11.1
31503 11.1                     11.1                    11.1
31504 11.1                     11.1                    11.1
31505 11.1                     11.1                    11.1
31506 11.1                     11.1                    11.1
31507 11.1                     11.1                    11.1
31508 11.1                     11.1                    11.1
31509 11.1                     11.1                    11.1
31510 11.1                     11.1                    11.1
31511 11.1                     11.1                    11.1
31512 11.1                     11.1                    11.1
31513 11.1                     11.1                    11.1
31514 11.1                     11.1                    11.1
31515 11.1                     11.1                    11.1
      Different_Minimum_Wage_for_Smaller_Businesses positiveScore hhs_region
8     0                                             0             4
1     0                                             0             4
2     0                                             0             4
3     0                                             0             4
7     0                                             0             4
4     0                                             0             4
5     0                                             0             4
6     0                                             0             4
12    0                                             0             4
13    0                                             0             4
10    0                                             0             4
11    0                                             0             4
14    0                                             0             4
15    0                                             0             4
9     0                                             0             4
16    0                                             0             4
17    0                                             0             4
20    0                                             0             4
21    0                                             0             4
18    0                                             0             4
19    0                                             0             4
30    0                                             0             4
31    0                                             0             4
32    0                                             0             4
33    0                                             0             4
34    0                                             0             4
35    0                                             0             4
36    0                                             0             4
24    0                                             0             4
25    0                                             0             4
⋮     ⋮                                             ⋮             ⋮
31486 0                                             0             2
31487 0                                             0             2
31488 0                                             0             2
31489 0                                             0             2
31490 0                                             0             2
31491 0                                             0             2
31492 0                                             0             2
31493 0                                             0             2
31494 0                                             0             2
31495 0                                             0             2
31496 0                                             0             2
31497 0                                             0             2
31498 0                                             0             2
31499 0                                             0             2
31500 0                                             0             2
31501 0                                             0             2
31502 0                                             0             2
31503 0                                             0             2
31504 0                                             0             2
31505 0                                             0             2
31506 0                                             0             2
31507 0                                             0             2
31508 0                                             0             2
31509 0                                             0             2
31510 0                                             0             2
31511 0                                             0             2
31512 0                                             0             2
31513 0                                             0             2
31514 0                                             0             2
31515 0                                             0             2

In [11]:
Y

    [1]  3.062723  3.082565  3.082565  3.095578  3.114784  3.114784  3.121105
    [8]  3.133629  3.170286  3.205646  3.228543  3.256447  3.283593  3.315224
   [15]  3.350906  3.158215  3.261935  3.360871  3.464396  3.570337  3.694933
   [22]  3.796131  3.902550  4.001341  4.098384  4.195482  4.289872  4.365280
   [29]  4.435398  4.500920  4.554929  4.593242  4.623150  4.649460  4.679084
   [36]  4.710431  4.738327  4.772741  4.810673  4.842724  4.862798  4.868303
   [43]  3.089093  3.188122  3.283593  3.355901  3.409260  3.459915  3.486501
   [50]  3.508128  3.533478  3.062723  3.139833  3.228543  3.299534  3.360871
   [57]  3.390185  3.423332  3.446353  3.473297  3.486501  3.508128  3.520883
   [64]  3.533478  3.075995  3.121105  3.170286  3.211420  3.228543  3.239798
   [71]  3.245379  3.170286  3.335770  3.490864  3.621289  3.256447  3.459915
   [78]  3.628902  3.746811  3.858321  3.958634  4.016898  4.047303  4.067071
   [85]  4.086456  4.105473  4.121821  4.144721  4.182486  4.212551  4.245839
   [92]  4.278054  4.309264  4.322618  4.324511  4.303486  4.264087  4.199777
   [99]  4.119502  3.139833  3.335770  3.578347  3.812045  4.011739  4.162671
  [106]  4.287912  4.409677  4.562412  4.693573  4.803670  4.910236  5.018887
  [113]  5.121154  5.212370  5.274244  5.319310  5.355710  5.383643  5.403128
  [120]  5.415910  5.421609  5.429158  5.432911  5.427903  5.414003  5.394082
  [127]  5.373756  5.355035  5.325585  5.269109  3.095578  3.188122  3.256447
  [134]  3.325550  3.390185  3.459915  3.508128  3.533478  3.541787  3.562263
  [141]  3.570337  3.574350  3.566308  3.558201  3.566308  3.574350  3.578347
  [148]  3.570337  3.562263  3.554123  3.541787  3.049273  3.164269  3.261935
  [155]  3.340841  3.432604  3.075995  3.133629  3.164269  3.193997  3.211420
  [162]  3.228543  3.222868  3.211420  3.199839  3.164269  3.127387  3.095578
  [169]  3.069381  3.062723  3.199839  3.365817  3.529297  3.669769  3.792918
  [176]  3.876248  3.955903  4.039788  4.112512  4.180304  4.251959  4.303486
  [183]  4.357990  4.406196  4.455509  4.497744  4.527517  3.062723  3.095578
  [190]  3.114784  3.133629  3.152125  3.170286  3.182212  3.158215  3.056021
  [197]  3.102021  3.145998  3.199839  3.250928  3.299534  3.340841  3.370738
  [204]  3.399768  3.399768  3.133629  3.222868  3.340841  3.423332  3.495208
  [211]  3.558201  3.594176  3.658788  3.677024  3.669769  3.669769  3.666122
  [218]  3.662462  3.651400  3.617460  3.613617  3.613617  3.613617  3.594176
  [225]  3.582328  3.574350  3.075995  3.121105  3.139833  3.152125  3.152125
  [232]  3.145998  3.158215  3.075995  3.139833  3.176267  3.217160  3.267394
  [239]  3.294248  3.310022  3.340841  3.355901  3.365817  3.390185  3.127387
  [246]  3.228543  3.315224  3.390185  3.459915  3.512398  3.570337  3.640214
  [253]  3.722936  3.799334  3.861331  3.911165  3.964073  4.011739  4.049795
  [260]  4.071953  4.088853  3.062723  3.102021  3.139833  3.193997  3.261935
  [267]  3.345886  3.437208  3.525099  3.601998  3.684226  3.763523  3.840067
  [274]  3.908302  3.966782  4.003951  4.037270  4.067071  4.091245  4.103116
  [281]  4.107825  4.107825  4.114847  3.095578  3.139833  3.158215  3.158215
  [288]  3.350906  3.520883  3.677024  3.821473  3.958634  4.064621  4.149239
  [295]  4.225164  4.299615  4.357990  4.393920  4.418324  4.443827  4.470332
  [302]  4.511958  4.548902  4.587443  4.621746  4.641227  4.649460  4.643979
  [309]  4.621746  4.604742  4.578680  3.089093  3.217160  3.335770  3.441791
  [316]  3.525099  3.640214  3.089093  3.145998  3.211420  3.272823  3.365817
  [323]  3.437208  3.508128  3.554123  3.613617  3.655101  3.691376  3.702007
  [330]  3.722936  3.082565  3.182212  3.272823  3.350906  3.418663  3.490864
  [337]  3.550028  3.598095  3.625103  3.636458  3.640214  3.655101  3.062723
  [344]  3.069381  3.056021  3.049273  3.145998  3.267394  3.385358  3.495208
  [351]  3.590242  3.687807  3.779960  3.852273  3.933784  3.993471  4.039788
  [358]  4.076811  4.107825  4.137906  4.167108  4.180304  4.191169  4.193328
  [365]  4.186837  4.178117  4.167108  4.153736  3.075995  3.127387  3.188122
  [372]  3.239798  3.283593  3.315224  3.375635  3.418663  3.459915  3.486501
  [379]  3.508128  3.529297  3.562263  3.562263  3.558201  3.545916  3.525099
  [386]  3.503840  3.473297  3.211420  3.486501  3.712526  3.928178  4.107825
  [393]  4.326401  4.559425  4.735822  4.911288  5.080250  5.221668  5.359076
  [400]  5.470889  5.562164  5.661322  5.737816  5.811440  5.880812  5.943437
  [407]  6.003781  6.060691  6.110104  6.158098  6.194901  6.229553  6.254570
  [414]  6.272527  6.274412  6.261137  6.251546  6.232644  6.203027  6.176372
  [421]  6.153857  6.144094  6.141945  6.131133  6.129579  6.123025  6.116743
  [428]  6.103421  6.077872  3.239798  3.450894  3.632687  3.776694  3.942136
  [435]  4.069515  4.169320  4.262076  4.350647  4.435398  4.521323  4.585987
  [442]  4.665728  4.796617  4.916534  5.021717  5.116881  5.210032  5.297388
  [449]  5.375741  5.422240  5.456358  5.485212  5.510371  5.526420  5.537728
  [456]  5.537166  5.535477  5.537166  5.541095  5.544452  5.549465  5.551685
  [463]  5.559417  5.557765  5.526420  3.127387  3.211420  3.294248  3.355901
  [470]  3.399768  3.437208  3.477717  3.499533  3.520883  3.541787  3.558201
  [477]  3.578347  3.590242  3.582328  3.550028  3.503840  3.450894  3.394988
  [484]  3.315224  3.217160  3.127387  3.056021  3.095578  3.188122  3.267394
  [491]  3.330673  3.370738  3.409260  3.455415  3.499533  3.525099  3.537641
  [498]  3.601998  3.677024  3.750176  3.056021  3.127387  3.176267  3.217160
  [505]  3.256447  3.261935  3.267394  3.278222  3.299534  3.320400  3.340841
  [512]  3.360871  3.390185  3.127387  3.418663  3.640214  3.855301  4.059704
  [519]  4.237620  4.376116  4.499333  4.593242  4.681734  4.754452  4.808344
  [526]  4.865004  4.925907  4.986245  5.032956  5.081138  5.116881  5.143083
  [533]  5.159630  5.166988  5.156342  5.157165  5.121154  5.085566  5.040379
  [540]  4.980372  4.911288  4.840468  4.737075  4.673763  4.601879  4.535207
  [547]  4.494558  4.443827  4.381491  3.049273  3.114784  3.164269  3.188122
  [554]  3.205646  3.211420  3.256447  3.320400  3.365817  3.418663  3.459915
  [561]  3.499533  3.520883  3.520883  3.503840  3.512398  3.102021  3.239798
  [568]  3.370738  3.516650  3.662462  3.786460  3.890945  3.958634  4.001341
  [575]  4.029679  4.032216  4.024586  4.022030  4.019467  4.016898  4.024586
  [582]  4.034746  4.047303  4.054762  4.057236  4.052282  4.042299  3.095578
  [589]  3.320400  3.578347  3.776694  3.974864  4.153736  4.297674  4.414874
  [596]  4.519768  4.597570  4.664382  4.730795  4.788325  4.856151  4.945411
  [603]  5.065935  5.181543  5.288051  5.375741  5.466673  5.537728  5.587623
  [610]  5.609315  5.619728  3.288935  3.512398  3.694933  3.852273  4.069515
  [617]  4.247883  4.409677  4.574269  4.772741  4.981354  5.208471  5.405056
  [624]  5.588158  5.748346  5.892709  6.006248  6.108517  6.186414  6.250444
  [631]  6.300969  6.346313  6.383193  6.423177  6.457599  6.494769  6.530815
  [638]  6.565607  6.600007  6.633638  6.665083  6.689013  6.698744  3.102021
  [645]  3.234187  3.385358  3.574350  3.736649  3.888023  4.001341  4.103116
  [652]  4.201917  4.287912  4.341391  4.414874  4.492961  4.607596  4.721937
  [659]  4.842724  4.949469  5.046829  5.131335  5.205340  5.253544  5.296673
  [666]  5.326280  5.353684  5.379041  5.394731  5.406339  5.414003  5.423502
  [673]  5.437272  5.454527  3.089093  3.152125  3.217160  3.278222  3.350906
  [680]  3.418663  3.473297  3.529297  3.578347  3.621289  3.658788  3.687807
  [687]  3.698476  3.705526  3.687807  3.662462  3.625103  3.590242  3.541787
  [694]  3.503840  3.482119  3.486501  3.520883  3.550028  3.574350  3.598095
  [701]  3.613617  3.069381  3.164269  3.222868  3.288935  3.345886  3.418663
  [708]  3.486501  3.550028  3.590242  3.632687  3.651400  3.662462  3.658788
  [715]  3.647685  3.628902  3.605886  3.578347  3.075995  3.133629  3.188122
  [722]  3.256447  3.325550  3.404525  3.495208  3.586293  3.673403  3.756872
  [729]  3.815197  3.873282  3.914021  3.939360  3.950419  3.950419  3.082565
  [736]  3.250928  3.413973  3.545916  3.651400  3.753530  3.827709  3.873282
  [743]  3.914021  3.947666  3.982881  3.998725  4.006554  4.006554  4.001341
  [750]  3.990834  3.972177  3.947666  3.930985  3.152125  3.250928  3.335770
  [757]  3.404525  3.490864  3.566308  3.640214  3.702007  3.770130  3.827709
  [764]  3.879205  3.902550  3.916868  3.905430  3.899661  3.876248  3.849235
  [771]  3.056021  3.164269  3.250928  3.340841  3.423332  3.482119  3.537641
  [778]  3.590242  3.625103  3.669769  3.709032  3.733238  3.766832  3.786460
  [785]  3.796131  3.808882  3.818340  3.824596  3.830813  3.824596  3.812045
  [792]  3.796131  3.783215  3.763523  3.740048  3.712526  3.069381  3.325550
  [799]  3.594176  3.792918  3.974864  4.137906  4.264087  4.354325  4.438778
  [806]  4.511958  4.594687  4.685696  4.761808  4.843850  4.921752  4.999815
  [813]  5.056883  5.109144  5.153044  5.205340  5.249052  5.288051  5.303092
  [820]  5.316508  5.317209  5.317209  5.303802  5.284436  5.268373  5.263948
  [827]  5.262468  5.259502  5.249802  5.233931  5.220896  5.196680  5.165357
  [834]  3.049273  3.133629  3.217160  3.299534  3.380509  3.455415  3.529297
  [841]  3.598095  3.655101  3.702007  3.750176  3.779960  3.815197  3.840067
  [848]  3.846188  3.833907  3.843132  3.075995  3.193997  3.278222  3.345886
  [855]  3.427978  3.499533  3.550028  3.582328  3.609759  3.643957  3.677024
  [862]  3.698476  3.722936  3.746811  3.773418  3.799334  3.808882  3.805710
  [869]  3.789694  3.773418  3.750176  3.716008  3.082565  3.205646  3.360871
  [876]  3.503840  3.636458  3.783215  3.985539  4.169320  4.348802  4.524425
  [883]  4.679084  4.807178  4.931077  5.020774  5.091732  5.171052  5.235454
  [890]  5.297388  5.358404  5.405697  5.445937  5.482245  5.501083  5.511526
  [897]  5.512680  3.056021  3.176267  3.261935  3.350906  3.441791  3.529297
  [904]  3.666122  3.812045  3.950419  4.084054  4.189005  4.283981  4.383276
  [911]  4.476850  4.542839  4.597570  4.652190  4.697489  4.755682  4.783555
  [918]  4.794255  4.814157  4.832533  4.849460  4.878137  4.891101  4.917580
  [925]  4.944394  4.949469  4.945411  4.933137  4.912340  3.082565  3.245379
  [932]  3.365817  3.441791  3.550028  3.632687  3.702007  3.779960  3.879205
  [939]  3.980216  4.076811  4.128746  4.191169  4.260061  4.316917  4.348802
  [946]  4.370713  4.376116  4.365280  4.332048  4.283981  4.237620  4.193328
  [953]  4.144721  4.103116  4.079231  4.037270  4.001341  3.958634  3.902550
  [960]  3.815197  3.716008  3.069381  3.145998  3.095578  3.205646  3.340841
  [967]  3.446353  3.533478  3.605886  3.662462  3.719478  3.773418  3.802527
  [974]  3.833907  3.864332  3.876248  3.876248  3.873282  3.873282  3.879205
  [981]  3.890945  3.108423  3.380509  3.609759  3.766832  3.914021  4.019467
  [988]  4.100753  4.167108  4.223073  4.274083  4.324511  4.383276  4.442147
  [995]  4.505666  4.560920  4.614696  4.667071  4.716839  4.744559  4.770321
 [1002]  4.782360  4.793071  4.782360  4.755682  4.719391  4.693573  4.663035
 [1009]  4.641227  4.620340  4.601879  4.583071  4.568358  4.550412  4.522875
 [1016]  4.486548  3.188122  3.345886  3.473297  3.570337  3.658788  3.746811
 [1023]  3.821473  3.905430  3.982881  4.054762  4.124134  4.178117  4.218877
 [1030]  4.256018  4.274083  4.278054  4.274083  4.260061  4.239681  4.206184
 [1037]  4.160444  4.105473  4.042299  3.966782  3.890945  3.821473  3.750176
 [1044]  3.666122  3.586293  3.468856  3.330673  3.056021  3.049273  3.108423
 [1051]  3.211420  3.385358  3.554123  3.726382  3.873282  4.039788  4.191169
 [1058]  4.335796  4.440464  4.562412  4.690955  4.809509  4.922792  5.036674
 [1065]  5.136386  5.247550  5.350978  5.440994  5.530392  5.611928  5.685376
 [1072]  5.753343  5.825030  3.049273  3.133629  3.193997  3.261935  3.320400
 [1079]  3.360871  3.375635  3.390185  3.399768  3.413973  3.133629  3.380509
 [1086]  3.609759  3.805710  3.988190  4.140183  4.322618  4.471965  4.610442
 [1093]  4.727008  4.839338  4.944394  5.042226  5.124559  5.195097  5.256528
 [1100]  5.312291  5.361091  5.409539  5.448399  5.488761  5.525851  5.551685
 [1107]  5.576328  5.592957  5.601433  5.614014  5.619728  5.619210  5.620763
 [1114]  5.618691  5.619210  5.620763  5.621797  5.628494  3.423332  3.899661
 [1121]  4.337664  4.706566  5.011302  5.308763  5.559967  5.787204  6.003075
 [1128]  6.192567  6.359005  6.510407  6.639633  6.765154  6.885758  6.988505
 [1135]  7.076497  7.155474  7.232702  7.299865  7.364248  7.416181  7.459067
 [1142]  7.493850  7.524924  7.550413  7.579000  7.596012  7.611962  7.622573
 [1149]  7.631688  7.639141  7.645036  7.648447  7.654761  7.658342  7.661103
 [1156]  7.667606  7.679100  7.699629  3.114784  3.222868  3.299534  3.394988
 [1163]  3.495208  3.586293  3.677024  3.750176  3.808882  3.867324  3.896764
 [1170]  3.916868  3.944905  3.974864  4.016898  4.076811  4.140183  4.206184
 [1177]  4.260061  4.313098  4.372517  3.193997  3.432604  3.628902  3.799334
 [1184]  3.982881  4.128746  4.268098  4.426898  4.583071  4.744559  4.897520
 [1191]  5.019831  5.136386  5.245293  5.355710  5.443468  5.526988  5.598263
 [1198]  5.660825  5.713120  5.767740  5.806726  5.852079  5.886382  5.916472
 [1205]  5.946430  5.971153  5.999185  6.030239  6.051316  6.071628  6.086677
 [1212]  6.093795  6.112322  6.119889  6.123025  3.170286  3.512398  3.849235
 [1219]  4.133336  4.404452  4.654912  4.850578  5.021717  5.162907  5.298103
 [1226]  5.434782  5.561615  5.678074  5.775749  5.878416  5.981306  6.069979
 [1233]  6.151729  6.222208  6.287779  6.352057  6.400186  6.447464  6.493473
 [1240]  6.529773  6.567215  6.594355  6.616581  6.637951  6.656120  6.670531
 [1247]  6.680622  6.683665  6.684380  6.683844  6.689013  6.683307  3.193997
 [1254]  3.335770  3.486501  3.662462  3.789694  3.908302  3.988190  4.079231
 [1261]  4.180304  4.283981  4.361642  4.458822  4.548902  4.642604  4.716839
 [1268]  4.781162  4.840468  4.895385  4.940315  4.981354  5.024538  5.069533
 [1275]  5.124559  5.171863  5.213926  5.249052  5.293807  5.338705  5.386263
 [1282]  5.422240  5.451468  5.482245  5.513832  5.539974  5.559417  3.102021
 [1289]  3.182212  3.234187  3.278222  3.304791  3.304791  3.315224  3.182212
 [1296]  3.345886  3.499533  3.625103  3.743435  3.852273  3.933784  4.003951
 [1303]  4.052282  4.093630  4.121821  4.144721  4.155977  4.160444  4.167108
 [1310]  4.169320  4.162671  4.155977  4.124134  4.091245  4.059704  4.001341
 [1317]  3.942136  3.867324  3.783215  3.694933  3.594176  3.468856  3.089093
 [1324]  3.176267  3.267394  3.380509  3.516650  3.651400  3.779960  3.222868
 [1331]  3.404525  3.503840  3.582328  3.647685  3.687807  3.719478  3.733238
 [1338]  3.753530  3.773418  3.789694  3.805710  3.824596  3.840067  3.888023
 [1345]  3.930985  3.966782  3.955903  3.936576  3.914021  3.873282  3.783215
 [1352]  3.680631  3.574350  3.520883  3.503840  3.503840  3.586293  3.673403
 [1359]  3.753530  3.836992  3.914021  3.062723  3.133629  3.193997  3.245379
 [1366]  3.294248  3.310022  3.325550  3.330673  3.335770  3.330673  3.325550
 [1373]  3.320400  3.310022  3.299534  3.267394  3.193997  3.108423  3.170286
 [1380]  3.409260  3.574350  3.680631  3.786460  3.888023  3.964073  4.022030
 [1387]  4.067071  4.105473  4.140183  4.160444  4.175925  4.186837  4.199777
 [1394]  4.208311  4.214664  4.199777  4.162671  4.117177  4.067071  3.982881
 [1401]  3.873282  3.733238  3.598095  3.482119  3.340841  3.164269  3.133629
 [1408]  3.217160  3.288935  3.340841  3.404525  3.459915  3.499533  3.533478
 [1415]  3.558201  3.594176  3.628902  3.640214  3.658788  3.669769  3.691376
 [1422]  3.722936  3.746811  3.766832  3.799334  3.824596  3.861331  3.876248
 [1429]  3.133629  3.310022  3.450894  3.601998  3.750176  3.852273  3.950419
 [1436]  4.067071  4.171526  4.264087  4.339529  4.438778  4.525972  4.606170
 [1443]  4.658982  4.701389  4.749518  4.788325  4.801324  4.818783  4.817628
 [1450]  4.829113  4.846098  4.846098  4.849460  4.844974  4.832533  4.834807
 [1457]  4.831395  3.164269  3.325550  3.418663  3.477717  3.537641  3.586293
 [1464]  3.628902  3.691376  3.746811  3.808882  3.867324  3.916868  3.961357
 [1471]  4.003951  4.032216  4.029679  4.019467  3.985539  3.933784  3.873282
 [1478]  3.805710  3.722936  3.655101  3.562263  3.508128  3.486501  3.459915
 [1485]  3.441791  3.441791  3.423332  3.404525  3.365817  3.315224  3.082565
 [1492]  3.205646  3.288935  3.380509  3.473297  3.558201  3.617460  3.666122
 [1499]  3.729816  3.805710  3.888023  3.961357  4.029679  4.112512  4.220977
 [1506]  4.309264  4.379703  4.420045  4.457167  4.491361  4.510388  4.492961
 [1513]  4.468696  4.442147  4.423477  4.397443  4.368905  4.339529  4.322618
 [1520]  4.305416  4.278054  4.241738  3.049273  3.082565  3.108423  3.145998
 [1527]  3.182212  3.256447  3.350906  3.477717  3.582328  3.691376  3.783215
 [1534]  3.888023  3.972177  4.057236  4.131044  4.204053  4.245839  4.285948
 [1541]  4.316917  4.354325  4.376116  4.385058  4.395683  4.426898  4.465415
 [1548]  4.492961  4.519768  4.545875  4.562412  4.571318  4.580145  4.581609
 [1555]  4.591795  4.588896  4.577212  4.568358  4.554929  3.062723  3.075995
 [1562]  3.069381  3.056021  3.062723  3.069381  3.062723  3.069381  3.182212
 [1569]  3.315224  3.380509  3.450894  3.512398  3.574350  3.632687  3.684226
 [1576]  3.740048  3.158215  3.413973  3.617460  3.885092  4.133336  4.330169
 [1583]  4.645352  5.066836  5.405697  5.715946  5.968963  6.170119  6.339023
 [1590]  6.456702  6.523499  6.583943  6.618682  3.075995  3.145998  3.217160
 [1597]  3.288935  3.320400  3.350906  3.380509  3.399768  3.394988  3.370738
 [1604]  3.330673  3.294248  3.261935  3.217160  3.182212  3.133629  3.102021
 [1611]  3.108423  3.108423  3.069381  3.075995  3.152125  3.222868  3.272823
 [1618]  3.320400  3.355901  3.390185  3.404525  3.413973  3.413973  3.390185
 [1625]  3.365817  3.340841  3.315224  3.288935  3.234187  3.164269  3.121105
 [1632]  3.075995  3.176267  3.250928  3.304791  3.350906  3.385358  3.409260
 [1639]  3.441791  3.455415  3.459915  3.459915  3.459915  3.464396  3.459915
 [1646]  3.446353  3.450894  3.441791  3.418663  3.385358  3.340841  3.139833
 [1653]  3.380509  3.613617  3.840067  4.022030  4.178117  4.309264  4.386836
 [1660]  4.463771  4.525972  4.577212  4.638467  4.696185  4.748281  4.819936
 [1667]  4.891101  4.959542  5.034817  5.108280  5.179936  5.252049  5.305931
 [1674]  5.353684  5.402484  5.463650  5.503995  5.537728  5.571991  5.602488
 [1681]  5.634637  5.663803  5.674648  5.693107  5.710758  5.732277  5.756962
 [1688]  5.769971  5.777962  5.783693  5.785011  3.127387  3.288935  3.394988
 [1695]  3.520883  3.590242  3.643957  3.756872  3.858321  3.953165  4.037270
 [1702]  4.086456  4.133336  4.175925  4.184664  4.204053  4.223073  4.249923
 [1709]  4.260061  4.260061  4.241738  4.210433  3.089093  3.217160  3.299534
 [1716]  3.360871  3.409260  3.455415  3.464396  3.459915  3.459915  3.468856
 [1723]  3.477717  3.486501  3.520883  3.554123  3.586293  3.609759  3.632687
 [1730]  3.651400  3.662462  3.640214  3.621289  3.574350  3.516650  3.490864
 [1737]  3.490864  3.069381  3.108423  3.182212  3.250928  3.330673  3.049273
 [1744]  3.056021  3.075995  3.108423  3.145998  3.176267  3.205646  3.228543
 [1751]  3.250928  3.267394  3.234187  3.176267  3.102021  3.049273  3.121105
 [1758]  3.205646  3.267394  3.310022  3.380509  3.437208  3.486501  3.533478
 [1765]  3.562263  3.598095  3.628902  3.636458  3.628902  3.617460  3.601998
 [1772]  3.586293  3.590242  3.605886  3.609759  3.632687  3.684226  3.743435
 [1779]  3.808882  3.836992  3.855301  3.899661  3.928178  3.089093  3.188122
 [1786]  3.256447  3.283593  3.310022  3.335770  3.350906  3.355901  3.360871

In [12]:
indexing

     fips  date       county        state          days_from_start
1    1001  2020-04-30 Autauga       Alabama        100
2    1003  2020-04-30 Baldwin       Alabama        100
3    1005  2020-04-30 Barbour       Alabama        100
4    1007  2020-04-30 Bibb          Alabama        100
5    1009  2020-04-30 Blount        Alabama        100
6    1013  2020-04-30 Butler        Alabama        100
7    1015  2020-04-30 Calhoun       Alabama        100
8    1017  2020-04-30 Chambers      Alabama        100
9    1021  2020-04-30 Chilton       Alabama        100
10   1023  2020-04-30 Choctaw       Alabama        100
11   1025  2020-04-30 Clarke        Alabama        100
12   1031  2020-04-30 Coffee        Alabama        100
13   1037  2020-04-30 Coosa         Alabama        100
14   1039  2020-04-30 Covington     Alabama        100
15   1043  2020-04-30 Cullman       Alabama        100
16   1045  2020-04-30 Dale          Alabama        100
17   1047  2020-04-30 Dallas        Alabama        100
18   1049  2020-04-30 DeKalb        Alabama        100
19   1051  2020-04-30 Elmore        Alabama        100
20   1053  2020-04-30 Escambia      Alabama        100
21   1055  2020-04-30 Etowah        Alabama        100
22   1059  2020-04-30 Franklin      Alabama        100
23   1063  2020-04-30 Greene        Alabama        100
24   1065  2020-04-30 Hale          Alabama        100
25   1067  2020-04-29 Henry         Alabama         99
26   1069  2020-04-30 Houston       Alabama        100
27   1071  2020-04-30 Jackson       Alabama        100
28   1073  2020-04-30 Jefferson     Alabama        100
29   1081  2020-04-30 Lee           Alabama        100
30   1083  2020-04-24 Limestone     Alabama         94
⋮    ⋮     ⋮          ⋮             ⋮              ⋮
1298 54061 2020-04-30 Monongalia    West Virginia  100
1299 54069 2020-04-19 Ohio          West Virginia   89
1300 54099 2020-04-30 Wayne         West Virginia  100
1301 54107 2020-04-30 Wood          West Virginia  100
1302 55009 2020-04-30 Brown         Wisconsin      100
1303 55021 2020-04-21 Columbia      Wisconsin       91
1304 55025 2020-04-30 Dane          Wisconsin      100
1305 55035 2020-04-12 Eau Claire    Wisconsin       82
1306 55039 2020-04-30 Fond du Lac   Wisconsin      100
1307 55043 2020-04-30 Grant         Wisconsin      100
1308 55055 2020-04-30 Jefferson     Wisconsin      100
1309 55059 2020-04-30 Kenosha       Wisconsin      100
1310 55063 2020-04-15 La Crosse     Wisconsin       85
1311 55079 2020-04-30 Milwaukee     Wisconsin      100
1312 55087 2020-04-30 Outagamie     Wisconsin      100
1313 55089 2020-04-30 Ozaukee       Wisconsin      100
1314 55101 2020-04-30 Racine        Wisconsin      100
1315 55105 2020-04-30 Rock          Wisconsin      100
1316 55111 2020-04-30 Sauk          Wisconsin      100
1317 55117 2020-04-30 Sheboygan     Wisconsin      100
1318 55127 2020-04-30 Walworth      Wisconsin      100
1319 55131 2020-04-30 Washington    Wisconsin      100
1320 55133 2020-04-30 Waukesha      Wisconsin      100
1321 55139 2020-04-30 Winnebago     Wisconsin      100
1322 56013 2020-04-30 Fremont       Wyoming        100
1323 56021 2020-04-30 Laramie       Wyoming        100
1324 56025 2020-04-30 Natrona       Wyoming        100
1325 56039 2020-04-30 Teton         Wyoming        100
1326 78030 2020-04-30 St. Thomas    Virgin Islands 100
1327 99999 2020-04-30 New York City New York       100
     log_rolled_cases shifted_days_from_start r_GRF
1    3.350906         14                      0.030717198
2    4.868303         26                      0.058703279
3    3.533478          8                      0.064040805
4    3.533478         12                      0.042707133
5    3.245379          6                      0.037515252
6    3.621289          3                      0.046124857
7    4.119502         23                      0.037887214
8    5.269109         30                      0.063229034
9    3.541787         20                      0.027098959
10   3.432604          4                      0.045759606
11   3.062723         13                      0.025266362
12   4.527517         16                      0.065918725
13   3.158215          7                      0.041323415
14   3.399768          9                      0.037489299
15   3.574350         20                      0.020166935
16   3.158215          6                      0.041851191
17   3.390185         10                      0.050681887
18   4.088853         16                      0.072272860
19   4.114847         21                      0.051193462
20   3.158215          2                      0.043303096
21   4.578680         24                      0.051430555
22   3.640214          5                      0.059867831
23   3.722936         12                      0.053264110
24   3.655101         11                      0.052519679
25   3.049273          3                      0.043584764
26   4.153736         21                      0.054690671
27   3.473297         18                      0.026384787
28   6.077872         41                      0.065081568
29   5.526420         35                      0.061403324
30   3.056021         21                      0.009038488
⋮    ⋮                ⋮                       ⋮
1298  3.944905        32                      0.026852225
1299  3.062723         7                      0.030600477
1300  4.433704        15                      0.051077232
1301  3.375635        14                      0.027612860
1302  6.699799        24                      0.120144755
1303  3.062723        12                      0.018464629
1304  4.988195        40                      0.042682553
1305  3.069381         2                      0.036109861
1306  3.423332        29                      0.017741428
1307  3.404525         6                      0.034350558
1308  3.340841        16                      0.022202283
1309  5.520146        31                      0.071313205
1310  3.089093         9                      0.025615247
1311  7.332715        42                      0.078655533
1312  3.345886        22                      0.021700454
1313  3.335770        33                      0.009636799
1314  5.779287        28                      0.086344367
1315  4.907072        25                      0.057776172
1316  3.193997        19                      0.011504389
1317  3.170286        22                      0.015408373
1318  4.801324        21                      0.078307029
1319  3.687807        33                      0.015428814
1320  5.099605        37                      0.048052780
1321  3.375635        21                      0.026605863
1322  4.160444        29                      0.020769896
1323  4.481710        29                      0.040486177
1324  3.299534        23                      0.013698371
1325  4.084054        27                      0.037343633
1326  3.228543        18                      0.005346202
1327 11.476319        50                      0.142606878
     predicted_log_rolled_cases_GRF
1    3.565926
2    5.279226
3    3.981764
4    3.832428
5    3.507985
6    3.944163
7    4.384712
8    5.711712
9    3.731480
10   3.752921
11   3.239588
12   4.988949
13   3.447479
14   3.662193
15   3.715519
16   3.451174
17   3.744958
18   4.594763
19   4.473201
20   3.461337
21   4.938693
22   4.059289
23   4.095785
24   4.022739
25   3.354366
26   4.536571
27   3.657990
28   6.533443
29   5.956243
30   3.119290
⋮    ⋮
1298  4.132871
1299  3.276926
1300  4.791244
1301  3.568925
1302  7.540813
1303  3.191976
1304  5.286973
1305  3.322150
1306  3.547522
1307  3.644979
1308  3.496257
1309  6.019338
1310  3.268399
1311  7.883304
1312  3.497789
1313  3.403227
1314  6.383698
1315  5.311505
1316  3.274528
1317  3.278144
1318  5.349473
1319  3.795809
1320  5.435975
1321  3.561876
1322  4.305834
1323  4.765114
1324  3.395422
1325  4.345459
1326  3.265967
1327 12.474567

In [13]:
analysis_WYX <- WYX
analysis_WYX$r_tc_predictions <- unlist(cf$predictions)
analysis_WYX

      fips  date       county        state    days_from_start log_rolled_cases
8     1001  2020-04-16 Autauga       Alabama   86             3.062723
1     1001  2020-04-17 Autauga       Alabama   87             3.082565
2     1001  2020-04-18 Autauga       Alabama   88             3.082565
3     1001  2020-04-19 Autauga       Alabama   89             3.095578
7     1001  2020-04-20 Autauga       Alabama   90             3.114784
4     1001  2020-04-21 Autauga       Alabama   91             3.114784
5     1001  2020-04-22 Autauga       Alabama   92             3.121105
6     1001  2020-04-23 Autauga       Alabama   93             3.133629
12    1001  2020-04-24 Autauga       Alabama   94             3.170286
13    1001  2020-04-25 Autauga       Alabama   95             3.205646
10    1001  2020-04-26 Autauga       Alabama   96             3.228543
11    1001  2020-04-27 Autauga       Alabama   97             3.256447
14    1001  2020-04-28 Autauga       Alabama   98             3.283593
15    1001  2020-04-29 Autauga       Alabama   99             3.315224
9     1001  2020-04-30 Autauga       Alabama  100             3.350906
16    1003  2020-04-04 Baldwin       Alabama   74             3.158215
17    1003  2020-04-05 Baldwin       Alabama   75             3.261935
20    1003  2020-04-06 Baldwin       Alabama   76             3.360871
21    1003  2020-04-07 Baldwin       Alabama   77             3.464396
18    1003  2020-04-08 Baldwin       Alabama   78             3.570337
19    1003  2020-04-09 Baldwin       Alabama   79             3.694933
30    1003  2020-04-10 Baldwin       Alabama   80             3.796131
31    1003  2020-04-11 Baldwin       Alabama   81             3.902550
32    1003  2020-04-12 Baldwin       Alabama   82             4.001341
33    1003  2020-04-13 Baldwin       Alabama   83             4.098384
34    1003  2020-04-14 Baldwin       Alabama   84             4.195482
35    1003  2020-04-15 Baldwin       Alabama   85             4.289872
36    1003  2020-04-16 Baldwin       Alabama   86             4.365280
24    1003  2020-04-17 Baldwin       Alabama   87             4.435398
25    1003  2020-04-18 Baldwin       Alabama   88             4.500920
⋮     ⋮     ⋮          ⋮             ⋮        ⋮               ⋮
31486 99999 2020-04-01 New York City New York  71             10.45620
31487 99999 2020-04-02 New York City New York  72             10.56942
31488 99999 2020-04-03 New York City New York  73             10.68157
31489 99999 2020-04-04 New York City New York  74             10.78497
31490 99999 2020-04-05 New York City New York  75             10.88212
31491 99999 2020-04-06 New York City New York  76             10.97158
31492 99999 2020-04-07 New York City New York  77             11.05295
31493 99999 2020-04-08 New York City New York  78             11.12949
31494 99999 2020-04-09 New York City New York  79             11.20114
31495 99999 2020-04-10 New York City New York  80             11.26607
31496 99999 2020-04-11 New York City New York  81             11.32345
31497 99999 2020-04-12 New York City New York  82             11.37601
31498 99999 2020-04-13 New York City New York  83             11.41995
31499 99999 2020-04-14 New York City New York  84             11.45578
31500 99999 2020-04-15 New York City New York  85             11.49098
31501 99999 2020-04-16 New York City New York  86             11.51803
31502 99999 2020-04-17 New York City New York  87             11.53995
31503 99999 2020-04-18 New York City New York  88             11.55804
31504 99999 2020-04-19 New York City New York  89             11.56855
31505 99999 2020-04-20 New York City New York  90             11.57697
31506 99999 2020-04-21 New York City New York  91             11.58214
31507 99999 2020-04-22 New York City New York  92             11.57754
31508 99999 2020-04-23 New York City New York  93             11.57197
31509 99999 2020-04-24 New York City New York  94             11.56502
31510 99999 2020-04-25 New York City New York  95             11.55462
31511 99999 2020-04-26 New York City New York  96             11.54274
31512 99999 2020-04-27 New York City New York  97             11.52855
31513 99999 2020-04-28 New York City New York  98             11.51262
31514 99999 2020-04-29 New York City New York  99             11.49584
31515 99999 2020-04-30 New York City New York 100             11.47632
      shifted_days_from_start LAT      LON       E_UNEMP ⋯
8      0                      32.53224 -86.64644 1065    ⋯
1      1                      32.53224 -86.64644 1065    ⋯
2      2                      32.53224 -86.64644 1065    ⋯
3      3                      32.53224 -86.64644 1065    ⋯
7      4                      32.53224 -86.64644 1065    ⋯
4      5                      32.53224 -86.64644 1065    ⋯
5      6                      32.53224 -86.64644 1065    ⋯
6      7                      32.53224 -86.64644 1065    ⋯
12     8                      32.53224 -86.64644 1065    ⋯
13     9                      32.53224 -86.64644 1065    ⋯
10    10                      32.53224 -86.64644 1065    ⋯
11    11                      32.53224 -86.64644 1065    ⋯
14    12                      32.53224 -86.64644 1065    ⋯
15    13                      32.53224 -86.64644 1065    ⋯
9     14                      32.53224 -86.64644 1065    ⋯
16     0                      30.65922 -87.74607 4343    ⋯
17     1                      30.65922 -87.74607 4343    ⋯
20     2                      30.65922 -87.74607 4343    ⋯
21     3                      30.65922 -87.74607 4343    ⋯
18     4                      30.65922 -87.74607 4343    ⋯
19     5                      30.65922 -87.74607 4343    ⋯
30     6                      30.65922 -87.74607 4343    ⋯
31     7                      30.65922 -87.74607 4343    ⋯
32     8                      30.65922 -87.74607 4343    ⋯
33     9                      30.65922 -87.74607 4343    ⋯
34    10                      30.65922 -87.74607 4343    ⋯
35    11                      30.65922 -87.74607 4343    ⋯
36    12                      30.65922 -87.74607 4343    ⋯
24    13                      30.65922 -87.74607 4343    ⋯
25    14                      30.65922 -87.74607 4343    ⋯
⋮     ⋮                       ⋮        ⋮         ⋮       ⋱
31486 21                      40.65857 -73.95064 70250   ⋯
31487 22                      40.65857 -73.95064 70250   ⋯
31488 23                      40.65857 -73.95064 70250   ⋯
31489 24                      40.65857 -73.95064 70250   ⋯
31490 25                      40.65857 -73.95064 70250   ⋯
31491 26                      40.65857 -73.95064 70250   ⋯
31492 27                      40.65857 -73.95064 70250   ⋯
31493 28                      40.65857 -73.95064 70250   ⋯
31494 29                      40.65857 -73.95064 70250   ⋯
31495 30                      40.65857 -73.95064 70250   ⋯
31496 31                      40.65857 -73.95064 70250   ⋯
31497 32                      40.65857 -73.95064 70250   ⋯
31498 33                      40.65857 -73.95064 70250   ⋯
31499 34                      40.65857 -73.95064 70250   ⋯
31500 35                      40.65857 -73.95064 70250   ⋯
31501 36                      40.65857 -73.95064 70250   ⋯
31502 37                      40.65857 -73.95064 70250   ⋯
31503 38                      40.65857 -73.95064 70250   ⋯
31504 39                      40.65857 -73.95064 70250   ⋯
31505 40                      40.65857 -73.95064 70250   ⋯
31506 41                      40.65857 -73.95064 70250   ⋯
31507 42                      40.65857 -73.95064 70250   ⋯
31508 43                      40.65857 -73.95064 70250   ⋯
31509 44                      40.65857 -73.95064 70250   ⋯
31510 45                      40.65857 -73.95064 70250   ⋯
31511 46                      40.65857 -73.95064 70250   ⋯
31512 47                      40.65857 -73.95064 70250   ⋯
31513 48                      40.65857 -73.95064 70250   ⋯
31514 49                      40.65857 -73.95064 70250   ⋯
31515 50                      40.65857 -73.95064 70250   ⋯
      Last_date_of_receipt_of_mail-in_ballot_request_for_the_general_election_(by_mail_or_online)
8     44133
1     44133
2     44133
3     44133
7     44133
4     44133
5     44133
6     44133
12    44133
13    44133
10    44133
11    44133
14    44133
15    44133
9     44133
16    44133
17    44133
20    44133
21    44133
18    44133
19    44133
30    44133
31    44133
32    44133
33    44133
34    44133
35    44133
36    44133
24    44133
25    44133
⋮     ⋮
31486 44131
31487 44131
31488 44131
31489 44131
31490 44131
31491 44131
31492 44131
31493 44131
31494 44131
31495 44131
31496 44131
31497 44131
31498 44131
31499 44131
31500 44131
31501 44131
31502 44131
31503 44131
31504 44131
31505 44131
31506 44131
31507 44131
31508 44131
31509 44131
31510 44131
31511 44131
31512 44131
31513 44131
31514 44131
31515 44131
      Mention_of_tribal_casinos Jan_1_2019_Minimum_Wage
8     0                         7.25
1     0                         7.25
2     0                         7.25
3     0                         7.25
7     0                         7.25
4     0                         7.25
5     0                         7.25
6     0                         7.25
12    0                         7.25
13    0                         7.25
10    0                         7.25
11    0                         7.25
14    0                         7.25
15    0                         7.25
9     0                         7.25
16    0                         7.25
17    0                         7.25
20    0                         7.25
21    0                         7.25
18    0                         7.25
19    0                         7.25
30    0                         7.25
31    0                         7.25
32    0                         7.25
33    0                         7.25
34    0                         7.25
35    0                         7.25
36    0                         7.25
24    0                         7.25
25    0                         7.25
⋮     ⋮                         ⋮
31486 1                         11.1
31487 1                         11.1
31488 1                         11.1
31489 1                         11.1
31490 1                         11.1
31491 1                         11.1
31492 1                         11.1
31493 1                         11.1
31494 1                         11.1
31495 1                         11.1
31496 1                         11.1
31497 1                         11.1
31498 1                         11.1
31499 1                         11.1
31500 1                         11.1
31501 1                         11.1
31502 1                         11.1
31503 1                         11.1
31504 1                         11.1
31505 1                         11.1
31506 1                         11.1
31507 1                         11.1
31508 1                         11.1
31509 1                         11.1
31510 1                         11.1
31511 1                         11.1
31512 1                         11.1
31513 1                         11.1
31514 1                         11.1
31515 1                         11.1
      Mar_29_2019_Minimum_Wage Jul_1_2019_Minimum_Wage Oct_1_2019_Minimum_Wage
8     7.25                     7.25                    7.25
1     7.25                     7.25                    7.25
2     7.25                     7.25                    7.25
3     7.25                     7.25                    7.25
7     7.25                     7.25                    7.25
4     7.25                     7.25                    7.25
5     7.25                     7.25                    7.25
6     7.25                     7.25                    7.25
12    7.25                     7.25                    7.25
13    7.25                     7.25                    7.25
10    7.25                     7.25                    7.25
11    7.25                     7.25                    7.25
14    7.25                     7.25                    7.25
15    7.25                     7.25                    7.25
9     7.25                     7.25                    7.25
16    7.25                     7.25                    7.25
17    7.25                     7.25                    7.25
20    7.25                     7.25                    7.25
21    7.25                     7.25                    7.25
18    7.25                     7.25                    7.25
19    7.25                     7.25                    7.25
30    7.25                     7.25                    7.25
31    7.25                     7.25                    7.25
32    7.25                     7.25                    7.25
33    7.25                     7.25                    7.25
34    7.25                     7.25                    7.25
35    7.25                     7.25                    7.25
36    7.25                     7.25                    7.25
24    7.25                     7.25                    7.25
25    7.25                     7.25                    7.25
⋮     ⋮                        ⋮                       ⋮
31486 11.1                     11.1                    11.1
31487 11.1                     11.1                    11.1
31488 11.1                     11.1                    11.1
31489 11.1                     11.1                    11.1
31490 11.1                     11.1                    11.1
31491 11.1                     11.1                    11.1
31492 11.1                     11.1                    11.1
31493 11.1                     11.1                    11.1
31494 11.1                     11.1                    11.1
31495 11.1                     11.1                    11.1
31496 11.1                     11.1                    11.1
31497 11.1                     11.1                    11.1
31498 11.1                     11.1                    11.1
31499 11.1                     11.1                    11.1
31500 11.1                     11.1                    11.1
31501 11.1                     11.1                    11.1
31502 11.1                     11.1                    11.1
31503 11.1                     11.1                    11.1
31504 11.1                     11.1                    11.1
31505 11.1                     11.1                    11.1
31506 11.1                     11.1                    11.1
31507 11.1                     11.1                    11.1
31508 11.1                     11.1                    11.1
31509 11.1                     11.1                    11.1
31510 11.1                     11.1                    11.1
31511 11.1                     11.1                    11.1
31512 11.1                     11.1                    11.1
31513 11.1                     11.1                    11.1
31514 11.1                     11.1                    11.1
31515 11.1                     11.1                    11.1
      Different_Minimum_Wage_for_Smaller_Businesses positiveScore hhs_region
8     0                                             0             4
1     0                                             0             4
2     0                                             0             4
3     0                                             0             4
7     0                                             0             4
4     0                                             0             4
5     0                                             0             4
6     0                                             0             4
12    0                                             0             4
13    0                                             0             4
10    0                                             0             4
11    0                                             0             4
14    0                                             0             4
15    0                                             0             4
9     0                                             0             4
16    0                                             0             4
17    0                                             0             4
20    0                                             0             4
21    0                                             0             4
18    0                                             0             4
19    0                                             0             4
30    0                                             0             4
31    0                                             0             4
32    0                                             0             4
33    0                                             0             4
34    0                                             0             4
35    0                                             0             4
36    0                                             0             4
24    0                                             0             4
25    0                                             0             4
⋮     ⋮                                             ⋮             ⋮
31486 0                                             0             2
31487 0                                             0             2
31488 0                                             0             2
31489 0                                             0             2
31490 0                                             0             2
31491 0                                             0             2
31492 0                                             0             2
31493 0                                             0             2
31494 0                                             0             2
31495 0                                             0             2
31496 0                                             0             2
31497 0                                             0             2
31498 0                                             0             2
31499 0                                             0             2
31500 0                                             0             2
31501 0                                             0             2
31502 0                                             0             2
31503 0                                             0             2
31504 0                                             0             2
31505 0                                             0             2
31506 0                                             0             2
31507 0                                             0             2
31508 0                                             0             2
31509 0                                             0             2
31510 0                                             0             2
31511 0                                             0             2
31512 0                                             0             2
31513 0                                             0             2
31514 0                                             0             2
31515 0                                             0             2
      r_tc_predictions
8     0.03220264
1     0.03178858
2     0.03408014
3     0.02975961
7     0.02980316
4     0.02992165
5     0.03021922
6     0.02847353
12    0.03131413
13    0.02874512
10    0.03067547
11    0.03223757
14    0.03215873
15    0.02911215
9     0.03453413
16    0.05912778
17    0.05806478
20    0.05860773
21    0.05667253
18    0.05824731
19    0.05743970
30    0.05897801
31    0.05896233
32    0.05873367
33    0.05825608
34    0.05792191
35    0.05729647
36    0.05651743
24    0.05904741
25    0.05854681
⋮     ⋮
31486 0.1402567
31487 0.1453018
31488 0.1395732
31489 0.1398597
31490 0.1381288
31491 0.1431071
31492 0.1432176
31493 0.1425741
31494 0.1466458
31495 0.1415341
31496 0.1411076
31497 0.1395952
31498 0.1403501
31499 0.1422979
31500 0.1427338
31501 0.1419644
31502 0.1451157
31503 0.1403889

In [14]:
per_fips_mean_tau <- aggregate(analysis_WYX$r_tc_predictions, list(analysis_WYX$fips), mean)
names(per_fips_mean_tau) <- c("fips", "mean_tau_per_fips")
per_fips_mean_tau

     fips  mean_tau_per_fips
1    1001  0.031001721
2    1003  0.058257026
3    1005  0.063661846
4    1007  0.042525428
5    1009  0.037770027
6    1013  0.045424653
7    1015  0.037793837
8    1017  0.062984628
9    1021  0.027616586
10   1023  0.044817507
11   1025  0.025536667
12   1031  0.066395536
13   1037  0.042825367
14   1039  0.038039881
15   1043  0.020377389
16   1045  0.041816127
17   1047  0.050885372
18   1049  0.072953226
19   1051  0.051002931
20   1053  0.043841069
21   1055  0.051223339
22   1059  0.061109002
23   1063  0.053183411
24   1065  0.052855523
25   1067  0.041311049
26   1069  0.054775618
27   1071  0.026499401
28   1073  0.065111761
29   1081  0.061240358
30   1083  0.008973783
⋮    ⋮     ⋮
1298 54061 0.026888986
1299 54069 0.032983720
1300 54099 0.049739456
1301 54107 0.027738375
1302 55009 0.118896462
1303 55021 0.019438405
1304 55025 0.043027279
1305 55035 0.033332895
1306 55039 0.017534475
1307 55043 0.034715035
1308 55055 0.022848042
1309 55059 0.071335706
1310 55063 0.026314781
1311 55079 0.078493730
1312 55087 0.022166378
1313 55089 0.009936192
1314 55101 0.086081437
1315 55105 0.057670591
1316 55111 0.011765557
1317 55117 0.015787860
1318 55127 0.078134071
1319 55131 0.015442575
1320 55133 0.048281357
1321 55139 0.026815856
1322 56013 0.020908382
1323 56021 0.040342916
1324 56025 0.014345037
1325 56039 0.037413442
1326 78030 0.005162024
1327 99999 0.142407723

In [15]:
diff = as.vector(indexing$r_GRF) - as.vector(per_fips_mean_tau$mean_tau_per_fips)

In [16]:
sum(abs(diff))/length(diff)

[1] 0.0005874995

In [17]:
sum((diff)**2)/length(diff)

[1] 1.101476e-06

In [18]:
max(abs(diff))

[1] 0.01309921

In [19]:
2**2

[1] 4

In [20]:
analysis_WYX[, names(analysis_WYX) %in% c("fips","shifted_days_from_start","r_tc_predictions")]

      fips  shifted_days_from_start r_tc_predictions
8     1001   0                      0.03220264
1     1001   1                      0.03178858
2     1001   2                      0.03408014
3     1001   3                      0.02975961
7     1001   4                      0.02980316
4     1001   5                      0.02992165
5     1001   6                      0.03021922
6     1001   7                      0.02847353
12    1001   8                      0.03131413
13    1001   9                      0.02874512
10    1001  10                      0.03067547
11    1001  11                      0.03223757
14    1001  12                      0.03215873
15    1001  13                      0.02911215
9     1001  14                      0.03453413
16    1003   0                      0.05912778
17    1003   1                      0.05806478
20    1003   2                      0.05860773
21    1003   3                      0.05667253
18    1003   4                      0.05824731
19    1003   5                      0.05743970
30    1003   6                      0.05897801
31    1003   7                      0.05896233
32    1003   8                      0.05873367
33    1003   9                      0.05825608
34    1003  10                      0.05792191
35    1003  11                      0.05729647
36    1003  12                      0.05651743
24    1003  13                      0.05904741
25    1003  14                      0.05854681
⋮     ⋮     ⋮                       ⋮
31486 99999 21                      0.1402567
31487 99999 22                      0.1453018
31488 99999 23                      0.1395732
31489 99999 24                      0.1398597
31490 99999 25                      0.1381288
31491 99999 26                      0.1431071
31492 99999 27                      0.1432176
31493 99999 28                      0.1425741
31494 99999 29                      0.1466458
31495 99999 30                      0.1415341
31496 99999 31                      0.1411076
31497 99999 32                      0.1395952
31498 99999 33                      0.1403501
31499 99999 34                      0.1422979
31500 99999 35                      0.1427338
31501 99999 36                      0.1419644
31502 99999 37                      0.1451157
31503 99999 38                      0.1403889
31504 99999 39                      0.1414917
31505 99999 40                      0.1398354
31506 99999 41                      0.1410749
31507 99999 42                      0.1435583
31508 99999 43                      0.1437231
31509 99999 44                      0.1417024
31510 99999 45                      0.1467238
31511 99999 46                      0.1397783
31512 99999 47                      0.1474264
31513 99999 48                      0.1419098
31514 99999 49                      0.1443156
31515 99999 50                      0.1442193

In [21]:
predict(cf)$predictions - cf$predictions # These gives a tau(x) per fips x time combination
# predict(cf, X_test) # This gives a single tau(x)

      [,1]
 [1,] 0
 [2,] 0
 [3,] 0
 [4,] 0
 [5,] 0
 [6,] 0
 [7,] 0
 [8,] 0
 [9,] 0
[10,] 0
[11,] 0
[12,] 0
[13,] 0
[14,] 0
[15,] 0
[16,] 0
[17,] 0
[18,] 0
[19,] 0
[20,] 0
[21,] 0
[22,] 0
[23,] 0
[24,] 0
[25,] 0
[26,] 0
[27,] 0
[28,] 0
[29,] 0
[30,] 0
[31,] ⋮
[32,] 0
[33,] 0
[34,] 0
[35,] 0
[36,] 0
[37,] 0
[38,] 0
[39,] 0
[40,] 0
[41,] 0
[42,] 0
[43,] 0
[44,] 0
[45,] 0
[46,] 0
[47,] 0
[48,] 0
[49,] 0
[50,] 0
[51,] 0
[52,] 0
[53,] 0
[54,] 0
[55,] 0
[56,] 0
[57,] 0
[58,] 0
[59,] 0
[60,] 0
[61,] 0

In [22]:
predict(cf, X_test)

     predictions
1    0.030717198
2    0.058703279
3    0.064040805
4    0.042707133
5    0.037515252
6    0.046124857
7    0.037887214
8    0.063229034
9    0.027098959
10   0.045759606
11   0.025266362
12   0.065918725
13   0.041323415
14   0.037489299
15   0.020166935
16   0.041851191
17   0.050681887
18   0.072272860
19   0.051193462
20   0.043303096
21   0.051430555
22   0.059867831
23   0.053264110
24   0.052519679
25   0.043584764
26   0.054690671
27   0.026384787
28   0.065081568
29   0.061403324
30   0.009038488
⋮    ⋮
1298 0.026852225
1299 0.030600477
1300 0.051077232
1301 0.027612860
1302 0.120144755
1303 0.018464629
1304 0.042682553
1305 0.036109861
1306 0.017741428
1307 0.034350558
1308 0.022202283
1309 0.071313205
1310 0.025615247
1311 0.078655533
1312 0.021700454
1313 0.009636799
1314 0.086344367
1315 0.057776172
1316 0.011504389
1317 0.015408373
1318 0.078307029
1319 0.015428814
1320 0.048052780
1321 0.026605863
1322 0.020769896
1323 0.040486177
1324 0.013698371
1325 0.037343633
1326 0.005346202
1327 0.142606878

In [ ]:
help(predict)

In [29]:
cf_single <- causal_forest(as.matrix(X$LAT),Y, W, num.trees=100, seed=1)

In [30]:
cf_single$predictions

      [,1]
 [1,] 0.06024304
 [2,] 0.05849363
 [3,] 0.05827931
 [4,] 0.05917859
 [5,] 0.05969659
 [6,] 0.06041000
 [7,] 0.05852497
 [8,] 0.05787173
 [9,] 0.06033763
[10,] 0.06135448
[11,] 0.05927999
[12,] 0.06146934
[13,] 0.05824439
[14,] 0.06229364
[15,] 0.06042659
[16,] 0.05238845
[17,] 0.05350652
[18,] 0.05527430
[19,] 0.05422822
[20,] 0.05467910
[21,] 0.05407505
[22,] 0.05434783
[23,] 0.05618252
[24,] 0.05254662
[25,] 0.05775686
[26,] 0.05414532
[27,] 0.05469972
[28,] 0.05542681
[29,] 0.05539178
[30,] 0.05383217
[31,] ⋮
[32,] 0.1424478
[33,] 0.1455585
[34,] 0.1424512
[35,] 0.1423492
[36,] 0.1426483
[37,] 0.1443433
[38,] 0.1463644
[39,] 0.1440852
[40,] 0.1477642
[41,] 0.1446248
[42,] 0.1406930
[43,] 0.1406207
[44,] 0.1436679
[45,] 0.1427942
[46,] 0.1425103
[47,] 0.1494940
[48,] 0.1475082
[49,] 0.1433450
[50,] 0.1430486
[51,] 0.1420157
[52,] 0.1463331
[53,] 0.1467495
[54,] 0.1471961
[55,] 0.1446315
[56,] 0.1479678
[57,] 0.1433869
[58,] 0.1485852
[59,] 0.1434695
[60,] 0.1434986
[61,] 0.1447539

In [32]:
predict(cf_single, as.matrix(X$LAT))

      predictions
1     0.05985108
2     0.05985108
3     0.05985108
4     0.05985108
5     0.05985108
6     0.05985108
7     0.05985108
8     0.05985108
9     0.05985108
10    0.05985108
11    0.05985108
12    0.05985108
13    0.05985108
14    0.05985108
15    0.05985108
16    0.05497233
17    0.05497233
18    0.05497233
19    0.05497233
20    0.05497233
21    0.05497233
22    0.05497233
23    0.05497233
24    0.05497233
25    0.05497233
26    0.05497233
27    0.05497233
28    0.05497233
29    0.05497233
30    0.05497233
⋮     ⋮
31486 0.1440456
31487 0.1440456
31488 0.1440456
31489 0.1440456
31490 0.1440456
31491 0.1440456
31492 0.1440456
31493 0.1440456
31494 0.1440456
31495 0.1440456
31496 0.1440456
31497 0.1440456
31498 0.1440456
31499 0.1440456
31500 0.1440456
31501 0.1440456
31502 0.1440456
31503 0.1440456
31504 0.1440456
31505 0.1440456
31506 0.1440456
31507 0.1440456
31508 0.1440456
31509 0.1440456
31510 0.1440456
31511 0.1440456
31512 0.1440456
31513 0.1440456
31514 0.1440456
31515 0.1440456