### Import Dependencies

In [1]:
list.of.packages <- c("ggplot2", "Rcpp", "grf", "caret", "mltools", "rpart", "minpack.lm", "doParallel", "rattle", "anytime","rlist")
list.of.packages <- c(list.of.packages, "zoo", "dtw", "foreach", "evaluate","rlist","data.table","plyr","dplyr")


new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, lib='/home/zwang937/local/R_libs', repos="http://cran.us.r-project.org", dependencies = TRUE, INSTALL_opts = '--no-lock')


lapply(list.of.packages, require, character.only = TRUE)

Loading required package: ggplot2

Loading required package: Rcpp

Loading required package: grf

Loading required package: caret

Loading required package: lattice

Loading required package: mltools

Loading required package: rpart

Loading required package: minpack.lm

Loading required package: doParallel

Loading required package: foreach

Loading required package: iterators

Loading required package: parallel

Loading required package: rattle

Loading required package: tibble

Loading required package: bitops

Rattle: A free graphical interface for data science with R.
Version 5.5.1 Copyright (c) 2006-2021 Togaware Pty Ltd.
Type 'rattle()' to shake, rattle, and roll your data.

Loading required package: anytime

Loading required package: rlist

Loading required package: zoo


Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric


Loading required package: dtw

Loading required package: proxy


Attaching package: ‘proxy’


The following objects are masked from ‘package:stats’:

    as.dist, dist


The following object is masked from ‘package:base’:

    as.matrix


Loaded dtw v1.22-3. See ?dtw for help, citation("dtw") for use in publication.


Loading required package: evaluate

Loading required package: data.table

Loading required package: plyr

Loading required package: dplyr


Attaching package: ‘dplyr’


The following objects are masked from ‘package:plyr’:

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize


The following objects are masked from ‘package:data.table’:

    between, first, last


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[[1]]
[1] TRUE

[[2]]
[1] TRUE

[[3]]
[1] TRUE

[[4]]
[1] TRUE

[[5]]
[1] TRUE

[[6]]
[1] TRUE

[[7]]
[1] TRUE

[[8]]
[1] TRUE

[[9]]
[1] TRUE

[[10]]
[1] TRUE

[[11]]
[1] TRUE

[[12]]
[1] TRUE

[[13]]
[1] TRUE

[[14]]
[1] TRUE

[[15]]
[1] TRUE

[[16]]
[1] TRUE

[[17]]
[1] TRUE

[[18]]
[1] TRUE

[[19]]
[1] TRUE

In [2]:
# SET PARAMS
windowsize=2
num_trees = 100



# CREATE OUTPUT FOLDERS
mainDir = "./time_variant_grf_results"
dir.create(mainDir, showWarnings = FALSE)

subDir = paste("time_variant_grf_backtest_state_forests_windowsize=",toString(windowsize),"_numtrees=",toString(num_trees),sep="")
outputfolder = file.path(mainDir, subDir)


dir.create(outputfolder, showWarnings = FALSE)

grf.subfolder = paste("time_variant_grf_grf_windowsize=",toString(windowsize),"_numtrees=",toString(num_trees),sep="")
grf.outputfolder = file.path(mainDir,grf.subfolder)
dir.create(grf.outputfolder, showWarnings = FALSE)

### Read in Panel Data

In [3]:
# READ DATA
print("Reading in data")
destfile <- paste("../../data/augmented_us-counties-states_latest_variants",".csv",sep="")
augmented_panel_data <- as.data.frame(fread(file = destfile))
# Time variant
#hhs_X_w_clusters_fpath = "../benchmark_tcv_kmeans_code/hhs_X_w_clusters.csv"
#hhs_X_w_clusters = as.data.frame(fread(file = hhs_X_w_clusters_fpath))

print("Transforming augmented_panel_data")
augmented_panel_data <- augmented_panel_data[order(augmented_panel_data$fips, augmented_panel_data$days_from_start), ]
augmented_panel_data <- augmented_panel_data[augmented_panel_data$rolled_cases >= 20,]
augmented_panel_data$log_rolled_cases <- log(augmented_panel_data$rolled_cases + 1.1)
augmented_panel_data <- augmented_panel_data %>%
  group_by(fips) %>%
    mutate(log_rolled_cases_ratios = c(0, diff(log_rolled_cases)))
augmented_panel_data <- augmented_panel_data %>%
  group_by(fips) %>%
    mutate(shifted_days_from_start = days_from_start - first(days_from_start))
augmented_panel_data <- augmented_panel_data[, colSums(!is.na(augmented_panel_data)) > 0]

# Obtain the time invariant data specific to each fips
#X_time_invariant <- (hhs_X_w_clusters[,intersect(names(augmented_panel_data), names(hhs_X_w_clusters))])
#X_time_invariant <- X_time_invariant[,!names(X_time_invariant) %in% c("county","state")]



# SET START AND END
start_day = min(augmented_panel_data$days_from_start)
end_day = max(augmented_panel_data$days_from_start)

cutoff_list <- start_day:end_day

[1] "Reading in data"
[1] "Transforming augmented_panel_data"

In [6]:
cutoff = 564
check.file.name <- paste0("classical_grf_stateforest_cutoff=", toString(cutoff), ".rds")
check.file.full.name <- file.path(grf.outputfolder, check.file.name)
if (file.exists(check.file.full.name)){
    print(paste0(check.file.name, " exists, skipping"))
    #next
}
print(paste0("Computing Classical GRF for ", toString(cutoff)))
try({ # START TRY
    start_time <- Sys.time()
    # Given my current cutoff, which block numbers should I use?
    fname <- paste("time_variant_grf_",toString(cutoff),".csv",sep="")        
    # SLICE THE DATA ACCORDINGLY
    early_data <- augmented_panel_data[augmented_panel_data$days_from_start <= cutoff, ]
    case_number_columns <- c("fips","date","county","state","days_from_start","log_rolled_cases", "shifted_days_from_start")
    early_data_case_numbers <- early_data[, names(early_data) %in% case_number_columns]
    # Format data to be fed to GRF
    #WYX <- merge(early_data_case_numbers, X_time_invariant, by="fips", all.x=TRUE)
    WYX <- early_data
    WYX <- WYX[order(WYX$fips, WYX$days_from_start),]

    Y <- WYX$log_rolled_cases
    W <- WYX$shifted_days_from_start
    X <- WYX[, !names(WYX) %in% case_number_columns]
    X <- X %>%
      select_if(is.numeric)

    cf <- causal_forest(X,Y,as.numeric(W), num.trees=num_trees)
    cf.fname <- check.file.name
    cf.path <- file.path(grf.outputfolder, cf.fname)
    print(paste0("Saving ", cf.fname))
    #saveRDS(cf, cf.path)

    # GENERATE r_GRF estimates
    WYX_test <- WYX %>%
      group_by(fips) %>%
      filter(days_from_start == cutoff)
    X_test <- WYX_test[, !names(WYX_test) %in% case_number_columns]
    X_test <- X_test %>%
      select_if(is.numeric)
    r_GRF <- predict(cf, X_test)

    # Generate predictions
    indexing_columns <- c("fips","county","state","date", "days_from_start","shifted_days_from_start", "rolled_cases", "log_rolled_cases")
    indexing <- WYX_test[, names(WYX) %in% indexing_columns]
    indexing$r_GRF <- unlist(r_GRF)
    indexing$GRF_predicted_log_rolled_cases <- indexing$r_GRF*7 + indexing$log_rolled_cases

    output.fname = paste("time_variant_grf_block_results_",toString(cutoff),".csv",sep="")
    destpath = file.path(outputfolder,output.fname)
    #fwrite(indexing, destpath, row.names=FALSE)
    end_time <- Sys.time()
} # END TRY
) # END TRY

[1] "Computing Classical GRF for 564"
[1] "Saving classical_grf_stateforest_cutoff=564.rds"

In [7]:
indexing

     fips  date       county        state          days_from_start rolled_cases
1    1001  2021-08-07 Autauga       Alabama        564              329.57143
2    1003  2021-08-07 Baldwin       Alabama        564             3789.00000
3    1005  2021-08-07 Barbour       Alabama        564              180.85714
4    1007  2021-08-07 Bibb          Alabama        564              235.57143
5    1009  2021-08-07 Blount        Alabama        564              421.00000
6    1013  2021-08-07 Butler        Alabama        564              156.71429
7    1015  2021-08-07 Calhoun       Alabama        564              708.28571
8    1017  2021-08-07 Chambers      Alabama        564              244.85714
9    1019  2021-08-07 Cherokee      Alabama        564              121.14286
10   1021  2021-08-07 Chilton       Alabama        564              304.28571
11   1025  2021-08-07 Clarke        Alabama        564              196.57143
12   1027  2021-08-07 Clay          Alabama        564               67.85714
13   1029  2021-08-07 Cleburne      Alabama        564               69.28571
14   1031  2021-08-07 Coffee        Alabama        564              751.71429
15   1033  2021-08-07 Colbert       Alabama        564              312.57143
16   1035  2021-08-07 Conecuh       Alabama        564               73.14286
17   1037  2021-08-07 Coosa         Alabama        564               68.00000
18   1039  2021-08-07 Covington     Alabama        564              465.00000
19   1041  2021-08-07 Crenshaw      Alabama        564              111.28571
20   1043  2021-08-07 Cullman       Alabama        564              581.85714
21   1045  2021-08-07 Dale          Alabama        564              752.85714
22   1047  2021-08-07 Dallas        Alabama        564              125.42857
23   1049  2021-08-07 DeKalb        Alabama        564              542.71429
24   1051  2021-08-07 Elmore        Alabama        564              623.85714
25   1053  2021-08-07 Escambia      Alabama        564              497.00000
26   1055  2021-08-07 Etowah        Alabama        564              797.42857
27   1057  2021-08-07 Fayette       Alabama        564               74.28571
28   1059  2021-08-07 Franklin      Alabama        564              305.71429
29   1061  2021-08-07 Geneva        Alabama        564              296.85714
30   1063  2021-08-07 Greene        Alabama        564               53.71429
⋮    ⋮     ⋮          ⋮             ⋮              ⋮               ⋮
2433 55125 2021-08-07 Vilas         Wisconsin      564                25.85714
2434 55127 2021-08-07 Walworth      Wisconsin      564               171.57143
2435 55129 2021-08-07 Washburn      Wisconsin      564                21.00000
2436 55131 2021-08-07 Washington    Wisconsin      564               307.28571
2437 55133 2021-08-07 Waukesha      Wisconsin      564              1254.14286
2438 55135 2021-08-07 Waupaca       Wisconsin      564                78.85714
2439 55137 2021-08-07 Waushara      Wisconsin      564                24.14286
2440 55139 2021-08-07 Winnebago     Wisconsin      564               292.28571
2441 55141 2021-08-07 Wood          Wisconsin      564               123.28571
2442 56001 2021-08-07 Albany        Wyoming        564               122.71429
2443 56003 2021-08-07 Big Horn      Wyoming        564                46.57143
2444 56005 2021-08-07 Campbell      Wyoming        564               194.57143
2445 56007 2021-08-07 Carbon        Wyoming        564               119.28571
2446 56009 2021-08-07 Converse      Wyoming        564               114.00000
2447 56013 2021-08-07 Fremont       Wyoming        564               196.00000
2448 56015 2021-08-07 Goshen        Wyoming        564                52.71429
2449 56021 2021-08-07 Laramie       Wyoming        564               690.71429
2450 56023 2021-08-07 Lincoln       Wyoming        564                84.57143
2451 56025 2021-08-07 Natrona       Wyoming        564               227.42857
2452 56029 2021-08-07 Park          Wyoming        564                94.42857
2453 56031 2021-08-07 Platte        Wyoming        564                72.28571
2454 56033 2021-08-07 Sheridan      Wyoming        564                87.42857
2455 56035 2021-08-07 Sublette      Wyoming        564                58.57143
2456 56037 2021-08-07 Sweetwater    Wyoming        564               176.85714
2457 56039 2021-08-07 Teton         Wyoming        564               109.71429
2458 56041 2021-08-07 Uinta         Wyoming        564               130.57143
2459 56045 2021-08-07 Weston        Wyoming        564                25.14286
2460 78010 2021-08-07 St. Croix     Virgin Islands 564               235.00000
2461 78030 2021-08-07 St. Thomas    Virgin Islands 564               425.42857
2462 99999 2021-08-07 New York City New York       564             21914.71429
     log_rolled_cases shifted_days_from_start r_GRF
1    5.801125         478                     0.0016938048
2    8.240148         490                     0.0001241522
3    5.203771         472                     0.0008860441
4    5.466673         476                     0.0008393291
5    6.045242         470                     0.0011102096
6    5.061419         467                     0.0001363751
7    6.564399         487                     0.0008190283
8    5.505157         494                     0.0013789374
9    4.806010         414                     0.0009236261
10   5.721576         484                     0.0003397878
11   5.286606         477                     0.0005116210
12   4.233485         400                     0.0007816071
13   4.253990         390                     0.0005931062
14   6.623819         480                     0.0014041792
15   5.748346         463                     0.0018696578
16   4.307342         435                     0.0013465021
17   4.235555         471                     0.0004550689
18   6.144400         473                     0.0010824091
19   4.721937         458                     0.0007012902
20   6.368114         484                     0.0016844412
21   6.625336         470                     0.0001025810
22   4.840468         474                     0.0008113799
23   6.298608         480                     0.0009745123
24   6.437683         485                     0.0013970791
25   6.210801         466                     0.0001238559
26   6.682771         488                     0.0012842550
27   4.322618         419                     0.0008604522
28   5.726243         469                     0.0003233798
29   5.696950         439                     0.0000674708
30   4.003951         476                     0.0016921674
⋮    ⋮                ⋮                       ⋮
2433 3.294248         366                     0.0012462823
2434 5.151391         485                     0.0019407885
2435 3.095578         368                     0.0005701276
2436 5.731351         497                     0.0023810007
2437 7.135084         501                     0.0028193620
2438 4.381491         432                     0.0015831926
2439 3.228543         391                     0.0014718247
2440 5.681488         485                     0.0020803084
2441 4.823387         410                     0.0020879027
2442 4.818783         388                     0.0014439079
2443 3.864332         305                     0.0012542211
2444 5.276437         406                     0.0012681227
2445 4.790701         379                     0.0010026666
2446 4.745801         329                     0.0007248446
2447 5.283711         493                     0.0010422190
2448 3.985539         359                     0.0016965410
2449 6.539318         493                     0.0011633008
2450 4.450519         394                     0.0011372419
2451 5.431661         487                     0.0016884999
2452 4.559425         405                     0.0021108321
2453 4.295729         312                     0.0013424846
2454 4.483325         371                     0.0031594894
2455 4.088853         374                     0.0012362234
2456 5.181543         411                     0.0014812971
2457 4.707856         491                     0.0014040926
2458 4.880310         422                     0.0014679271
2459 3.267394         304                     0.0009216831
2460 5.464255         398                     0.0007957637
2461 6.055679         482                     0.0012370691
2462 9.994964         514                     0.0012957497
     GRF_predicted_log_rolled_cases
1    5.812982
2    8.241017
3    5.209973
4    5.472548
5    6.053014
6    5.062374
7    6.570133
8    5.514810
9    4.812475
10   5.723954
11   5.290188
12   4.238956
13   4.258142
14   6.633648
15   5.761434
16   4.316767
17   4.238740
18   6.151977
19   4.726846
20   6.379905
21   6.626054
22   4.846148
23   6.305429
24   6.447463
25   6.211668
26   6.691761
27   4.328641
28   5.728506
29   5.697422
30   4.015796
⋮    ⋮
2433  3.302972
2434  5.164976
2435  3.099569
2436  5.748018
2437  7.154820
2438  4.392573
2439  3.238846
2440  5.696050
2441  4.838003
2442  4.828890
2443  3.873112
2444  5.285314
2445  4.797720
2446  4.750875
2447  5.291007
2448  3.997415
2449  6.547461
2450  4.458480
2451  5.443481
2452  4.574201
2453  4.305127
2454  4.505442
2455  4.097507
2456  5.191912
2457  4.717684
2458  4.890585
2459  3.273846
2460  5.469826
2461  6.064339
2462 10.004034

In [8]:
X_test

     cases deaths rolled_cases LAT      LON        AREA_SQMI   E_TOTPOP E_HU
1     404  114     329.57143   32.53224 -86.64644   594.4435    55200    23315
2    4456  330    3789.00000   30.65922 -87.74607  1589.7930   208107   111945
3     224   63     180.85714   31.87025 -85.40510   885.0016    25782    11937
4     271   66     235.57143   33.01589 -87.12715   622.4611    22527     9161
5     494  140     421.00000   33.97736 -86.56644   644.8305    57645    24222
6     189   72     156.71429   31.75167 -86.68197   776.8382    20025    10026
7     862  336     708.28571   33.77052 -85.82791   605.8673   115098    53682
8     307  125     244.85714   32.91550 -85.39403   596.5606    33826    16981
9     149   48     121.14286   34.06952 -85.65424   553.5248    25853    16531
10    341  117     304.28571   32.85405 -86.72661   692.8512    43930    19586
11    242   63     196.57143   31.68552 -87.81862  1238.4199    24387    12741
12     85   59      67.85714   33.27040 -85.86352   603.9608    13378     6802
13     78   45      69.28571   33.67196 -85.51613   560.1042    14938     6806
14    923  132     751.71429   31.40226 -85.98960   678.9858    51288    23088
15    398  142     312.57143   34.70311 -87.80146   592.7447    54495    26466
16     94   33      73.14286   31.43093 -86.98872   850.1996    12514     7143
17     81   29      68.00000   32.93144 -86.24348   650.9104    10855     6558
18    548  126     465.00000   31.24399 -86.44872  1030.5561    37351    18907
19    132   59     111.28571   31.73283 -86.31922   608.8646    13865     6790
20    679  209     581.85714   34.13192 -86.86927   734.7803    82313    37652
21    900  121     752.85714   31.43065 -85.60948   561.1006    49255    23065
22    150  164     125.42857   32.33354 -87.11436   978.7375    40029    20336
23    647  195     542.71429   34.46093 -85.80399   777.0984    71200    31462
24    722  220     623.85714   32.59723 -86.14274   618.4463    81212    34004
25    629   83     497.00000   31.12229 -87.16841   945.2221    37328    16595
26    937  372     797.42857   34.04764 -86.03426   535.2816   102939    47705
27     83   65      74.28571   33.71616 -87.76429   627.6834    16585     8470
28    371   81     305.71429   34.44199 -87.84281   633.9183    31542    14152
29    368   85     296.85714   31.09238 -85.82102   574.4803    26491    12768
30     56   38      53.71429   32.84450 -87.96420   647.0228     8426     5075
⋮    ⋮     ⋮      ⋮            ⋮        ⋮          ⋮           ⋮        ⋮
2433    33    45     25.85714  46.04985  -89.50125   857.70755   21593   25691
2434   219   169    171.57143  42.66811  -88.54173   555.43411  103013   52177
2435    24    24     21.00000  45.89249  -91.79642   797.11292   15689   13229
2436   387   204    307.28571  43.39116  -88.23292   430.64357  134535   56328
2437  1561   652   1254.14286  43.01837  -88.30424   549.72013  398879  164619
2438    96   167     78.85714  44.47800  -88.96701   747.69159   51444   25717
2439    24    38     24.14286  44.11282  -89.23979   626.15784   24116   15060
2440   358   230    292.28571  44.08571  -88.66815   434.69144  169926   75203
2441   152   111    123.28571  44.46141  -90.03883   793.01333   73274   34868
2442   132    18    122.71429  41.66551 -105.72188  4274.32501   38102   19162
2443    55    36     46.57143  44.52512 -107.99485  3136.95587   11901    5461
2444   235    64    194.57143  44.19200 -105.51701  4802.06327   47708   20158
2445   126    25    119.28571  41.70359 -106.93315  7897.79941   15477    8755
2446   117    20    114.00000  42.98462 -105.52475  4254.96140   13997    6654
2447   221    88    196.00000  43.05483 -108.60894  9183.58620   40076   17983
2448    56    24     52.71429  42.08946 -104.35354  2225.61217   13438    6031
2449   682   134    690.71429  41.29283 -104.66039  2685.86256   97692   42922
2450    89    14     84.57143  42.22999 -110.68296  4075.33508   19011    9319
2451   293   141    227.42857  42.97765 -106.76822  5340.52241   80610   36703
2452   109    34     94.42857  44.49239 -109.59360  6939.03584   29121   14324
2453    74    15     72.28571  42.13159 -104.95396  2081.44756    8673    4822
2454   116    31     87.42857  44.78137 -106.88121  2523.36001   30012   14779
2455    55     9     58.57143  42.76793 -109.91617  4886.47950    9951    5989
2456   174    45    176.85714  41.66033 -108.87568 10426.97573   44117   19628
2457   125    11    109.71429  44.04866 -110.42609  3996.84462   23059   13680
2458   163    14    130.57143  41.28473 -110.55895  2081.71981   20609    8972
2459    30     6     25.14286  43.84621 -104.57002  2398.00389    7100    3565
2460   256    16    235.00000  17.74600  -64.70330          NA      NA      NA
2461   511    23    425.42857  18.33333  -64.91667          NA      NA      NA
2462 26154 33578  21914.71429  40.65857  -73.95064    57.51865 1632480  855716
     E_HH   E_POV  ⋯ Variant % P.2 Variant % R.1 Variant % XBB
1    21115   8422  ⋯ 0             0             0
2    78622  21653  ⋯ 0             0             0
3     9186   6597  ⋯ 0             0             0
4     6840   2863  ⋯ 0             0             0
5    20600   8220  ⋯ 0             0             0
6     6708   4640  ⋯ 0             0             0
7    45033  20819  ⋯ 0             0             0
8    13516   5531  ⋯ 0             0             0
9    10606   3827  ⋯ 0             0             0
10   16751   8034  ⋯ 0             0             0
11    9358   6088  ⋯ 0             0             0
12    5236   2405  ⋯ 0             0             0
13    5726   2719  ⋯ 0             0             0
14   19789   7604  ⋯ 0             0             0
15   21799   8785  ⋯ 0             0             0
16    4574   2752  ⋯ 0             0             0
17    4103   1459  ⋯ 0             0             0
18   15008   6702  ⋯ 0             0             0
19    5025   2148  ⋯ 0             0             0
20   30730  12831  ⋯ 0             0             0
21   18670   8798  ⋯ 0             0             0
22   16336  12247  ⋯ 0             0             0
23   26132  15500  ⋯ 0             0             0
24   29143   9462  ⋯ 0             0             0
25   13428   8268  ⋯ 0             0             0
26   38777  17524  ⋯ 0             0             0
27    6947   3258  ⋯ 0             0             0
28   11210   6299  ⋯ 0             0             0
29   10479   6282  ⋯ 0             0             0
30    2955   3225  ⋯ 0             0             0
⋮    ⋮      ⋮      ⋱ ⋮             ⋮             ⋮
2433  10914   2910 ⋯ 0             0             0
2434  40372  11689 ⋯ 0             0             0
2435   7062   2050 ⋯ 0             0             0
2436  54138   6465 ⋯ 0             0             0
2437 157548  19190 ⋯ 0             0             0
2438  22024   5303 ⋯ 0             0             0
2439   9869   2580 ⋯ 0             0             0
2440  70173  19184 ⋯ 0             0             0
2441  32245   7488 ⋯ 0             0             0
2442  16027   8114 ⋯ 0             0             0
2443   4494   1446 ⋯ 0             0             0
2444  17488   5203 ⋯ 0             0             0
2445   6341   1929 ⋯ 0             0             0
2446   5429   1145 ⋯ 0             0             0
2447  15003   5352 ⋯ 0             0             0
2448   5209   1485 ⋯ 0             0             0
2449  39179   9540 ⋯ 0             0             0
2450   7075   1710 ⋯ 0             0             0
2451  32851   7568 ⋯ 0             0             0
2452  11977   2180 ⋯ 0             0             0
2453   3936    998 ⋯ 0             0             0
2454  13159   1797 ⋯ 0             0             0
2455   3275    828 ⋯ 0             0             0
2456  15871   5237 ⋯ 0             0             0
2457   9158   1619 ⋯ 0             0             0
2458   7735   2552 ⋯ 0             0             0
2459   3062   1171 ⋯ 0             0             0
2460     NA     NA ⋯ 0             0             0
2461     NA     NA ⋯ 0             0             0
2462 758133 295165 ⋯ 0             0             0
     Variant % XBB.1.16 Variant % XBB.1.5 Variant % XBB.1.5.1
1    0                  0                 0
2    0                  0                 0
3    0                  0                 0
4    0                  0                 0
5    0                  0                 0
6    0                  0                 0
7    0                  0                 0
8    0                  0                 0
9    0                  0                 0
10   0                  0                 0
11   0                  0                 0
12   0                  0                 0
13   0                  0                 0
14   0                  0                 0
15   0                  0                 0
16   0                  0                 0
17   0                  0                 0
18   0                  0                 0
19   0                  0                 0
20   0                  0                 0
21   0                  0                 0
22   0                  0                 0
23   0                  0                 0
24   0                  0                 0
25   0                  0                 0
26   0                  0                 0
27   0                  0                 0
28   0                  0                 0
29   0                  0                 0
30   0                  0                 0
⋮    ⋮                  ⋮                 ⋮
2433 0                  0                 0
2434 0                  0                 0
2435 0                  0                 0
2436 0                  0                 0
2437 0                  0                 0
2438 0                  0                 0
2439 0                  0                 0
2440 0                  0                 0
2441 0                  0                 0
2442 0                  0                 0
2443 0                  0                 0
2444 0                  0                 0
2445 0                  0                 0
2446 0                  0                 0
2447 0                  0                 0
2448 0                  0                 0
2449 0                  0                 0
2450 0                  0                 0
2451 0                  0                 0
2452 0                  0                 0
2453 0                  0                 0
2454 0                  0                 0
2455 0                  0                 0
2456 0                  0                 0
2457 0                  0                 0
2458 0                  0                 0
2459 0                  0                 0
2460 0                  0                 0
2461 0                  0                 0
2462 0                  0                 0
     Variant % XBB.1.9.1 Variant % XBB.1.9.2 Variant % XBB.2.3
1    0                   0                   0
2    0                   0                   0
3    0                   0                   0
4    0                   0                   0
5    0                   0                   0
6    0                   0                   0
7    0                   0                   0
8    0                   0                   0
9    0                   0                   0
10   0                   0                   0
11   0                   0                   0
12   0                   0                   0
13   0                   0                   0
14   0                   0                   0
15   0                   0                   0
16   0                   0                   0
17   0                   0                   0
18   0                   0                   0
19   0                   0                   0
20   0                   0                   0
21   0                   0                   0
22   0                   0                   0
23   0                   0                   0
24   0                   0                   0
25   0                   0                   0
26   0                   0                   0
27   0                   0                   0
28   0                   0                   0
29   0                   0                   0
30   0                   0                   0
⋮    ⋮                   ⋮                   ⋮
2433 0                   0                   0
2434 0                   0                   0
2435 0                   0                   0
2436 0                   0                   0
2437 0                   0                   0
2438 0                   0                   0
2439 0                   0                   0
2440 0                   0                   0
2441 0                   0                   0
2442 0                   0                   0
2443 0                   0                   0
2444 0                   0                   0
2445 0                   0                   0
2446 0                   0                   0
2447 0                   0                   0
2448 0                   0                   0
2449 0                   0                   0
2450 0                   0                   0
2451 0                   0                   0
2452 0                   0                   0
2453 0                   0                   0
2454 0                   0                   0
2455 0                   0                   0
2456 0                   0                   0
2457 0                   0                   0
2458 0                   0                   0
2459 0                   0                   0
2460 0                   0                   0
2461 0                   0                   0
2462 0                   0                   0
     log_rolled_cases_ratios
1    0.07209280
2    0.05696177
3    0.06403094
4    0.04506379
5    0.05567236
6    0.05680171
7    0.06188783
8    0.07725382
9    0.06893444
10   0.04106177
11   0.06108997
12   0.07974926
13   0.03301311
14   0.06204055
15   0.07320802
16   0.08846432
17   0.05963018
18   0.05286410
19   0.06838473
20   0.05542003
21   0.05952744
22   0.04503185
23   0.05591216
24   0.04655594
25   0.08433725
26   0.05459711
27   0.04258433
28   0.06641204
29   0.07463551
30   0.01311666
⋮    ⋮
2433 0.106126280
2434 0.108241951
2435 0.032854466
2436 0.091624942
2437 0.087480170
2438 0.074149204
2439 0.017123706
2440 0.077420805
2441 0.100180179
2442 0.036423199
2443 0.052287432
2444 0.078176644
2445 0.027672603
2446 0.023864483
2447 0.055892955
2448 0.032374017
2449 0.009752733
2450 0.032195258
2451 0.093642508
2452 0.063273184
2453 0.015695829
2454 0.118045294
2455 0.000000000
2456 0.007251079
2457 0.058395254
2458 0.088422810
2459 0.073396362
2460 0.043910096
2461 0.068617342
2462 0.055835392

In [9]:
X <- WYX[, !names(WYX) %in% case_number_columns]

In [10]:
X <- X[, !names(X) %in% c("cases","deaths","datetime","rolled_cases")]

In [11]:
dim(X)

[1] 1095276     470

In [12]:
X_numeric <- X %>%
  select_if(is.numeric)

In [13]:
as.numeric(X_numeric)

ERROR: Error in eval(expr, envir, enclos): 'list' object cannot be coerced to type 'double'

In [19]:
for (i in seq_along(colnames(X))) {
  cat("Column ", i, " (", colnames(X)[i], ")\n")
}

Column  1  ( LAT )
Column  2  ( LON )
Column  3  ( AREA_SQMI )
Column  4  ( E_TOTPOP )
Column  5  ( E_HU )
Column  6  ( E_HH )
Column  7  ( E_POV )
Column  8  ( E_UNEMP )
Column  9  ( E_PCI )
Column  10  ( E_NOHSDP )
Column  11  ( E_AGE65 )
Column  12  ( E_AGE17 )
Column  13  ( E_DISABL )
Column  14  ( E_SNGPNT )
Column  15  ( E_MINRTY )
Column  16  ( E_LIMENG )
Column  17  ( E_MUNIT )
Column  18  ( E_MOBILE )
Column  19  ( E_CROWD )
Column  20  ( E_NOVEH )
Column  21  ( E_GROUPQ )
Column  22  ( EP_POV )
Column  23  ( MP_POV )
Column  24  ( EP_UNEMP )
Column  25  ( MP_UNEMP )
Column  26  ( EP_PCI )
Column  27  ( MP_PCI )
Column  28  ( EP_NOHSDP )
Column  29  ( MP_NOHSDP )
Column  30  ( EP_AGE65 )
Column  31  ( MP_AGE65 )
Column  32  ( EP_AGE17 )
Column  33  ( MP_AGE17 )
Column  34  ( EP_DISABL )
Column  35  ( MP_DISABL )
Column  36  ( EP_SNGPNT )
Column  37  ( MP_SNGPNT )
Column  38  ( EP_MINRTY )
Column  39  ( MP_MINRTY )
Column  40  ( EP_LIMENG )
Column  41  ( MP_LIMENG )
Column  42  ( EP_MUNIT )
Column  43  ( MP_MUNIT )
Column  44  ( EP_MOBILE )
Column  45  ( MP_MOBILE )
Column  46  ( EP_CROWD )
Column  47  ( MP_CROWD )
Column  48  ( EP_NOVEH )
Column  49  ( MP_NOVEH )
Column  50  ( EP_GROUPQ )
Column  51  ( MP_GROUPQ )
Column  52  ( EPL_POV )
Column  53  ( EPL_UNEMP )
Column  54  ( EPL_PCI )
Column  55  ( EPL_NOHSDP )
Column  56  ( SPL_THEME1 )
Column  57  ( RPL_THEME1 )
Column  58  ( EPL_AGE65 )
Column  59  ( EPL_AGE17 )
Column  60  ( EPL_DISABL )
Column  61  ( EPL_SNGPNT )
Column  62  ( SPL_THEME2 )
Column  63  ( RPL_THEME2 )
Column  64  ( EPL_MINRTY )
Column  65  ( EPL_LIMENG )
Column  66  ( SPL_THEME3 )
Column  67  ( RPL_THEME3 )
Column  68  ( EPL_MUNIT )
Column  69  ( EPL_MOBILE )
Column  70  ( EPL_CROWD )
Column  71  ( EPL_NOVEH )
Column  72  ( EPL_GROUPQ )
Column  73  ( SPL_THEME4 )
Column  74  ( RPL_THEME4 )
Column  75  ( SPL_THEMES )
Column  76  ( RPL_THEMES )
Column  77  ( F_POV )
Column  78  ( F_UNEMP )
Column  79  ( F_PCI )
Column  80  ( F_NOHSDP )
Column  81  ( F_THEME1 )
Column  82  ( F_AGE65 )
Column  83  ( F_AGE17 )
Column  84  ( F_DISABL )
Column  85  ( F_SNGPNT )
Column  86  ( F_THEME2 )
Column  87  ( F_MINRTY )
Column  88  ( F_LIMENG )
Column  89  ( F_THEME3 )
Column  90  ( F_MUNIT )
Column  91  ( F_MOBILE )
Column  92  ( F_CROWD )
Column  93  ( F_NOVEH )
Column  94  ( F_GROUPQ )
Column  95  ( F_THEME4 )
Column  96  ( F_TOTAL )
Column  97  ( E_UNINSUR )
Column  98  ( EP_UNINSUR )
Column  99  ( MP_UNINSUR )
Column  100  ( E_DAYPOP )
Column  101  ( State_FIPS_Code )
Column  102  ( State_of_emergency_issued )
Column  103  ( State_of_emergency_lifted )
Column  104  ( Date_closed_K-12_public_schools )
Column  105  ( Closed_day_cares )
Column  106  ( Reopen_day_cares )
Column  107  ( Date_banned_visitors_to_nursing_homes )
Column  108  ( Stay_at_home/_shelter_in_place )
Column  109  ( Stay_at_home_order'_issued_but_did_not_specifically_restrict_movement_of_the_general_public )
Column  110  ( End/relax_stay_at_home/shelter_in_place )
Column  111  ( Closed_other_non-essential_businesses )
Column  112  ( Closed_businesses_overnight )
Column  113  ( Began_to_reopen_businesses )
Column  114  ( Religious_gatherings_exempt_without_clear_social_distance_mandate* )
Column  115  ( Face_mask_mandate_in_public_spaces )
Column  116  ( Face_mask_mandate_x2 )
Column  117  ( Face_mask_mandate_enforced_by_fines )
Column  118  ( Face_mask_mandate_enforced_by_criminal_charge/citation )
Column  119  ( No_legal_enforcement_of_face_mask_mandate )
Column  120  ( Face_mask_mandate_for_employees_of_public-facing_businesses )
Column  121  ( Ended_face_mask_mandate )
Column  122  ( Ended_face_mask_mandate_x2 )
Column  123  ( Attempted_to_prevent_local_governments_from_implementing_face_mask_orders )
Column  124  ( Banned_local_mask_mandates )
Column  125  ( Liquor_stores_remained_open )
Column  126  ( Allowed_restaurants_to_sell_takeout_alcohol )
Column  127  ( Allowed_restaurants_to_deliver_alcohol )
Column  128  ( Firearm_sellers_remained_open )
Column  129  ( Cannabis_dispensaries_considered_essential_business )
Column  130  ( Closed_restaurants_except_take_out )
Column  131  ( Reopen_restaurants )
Column  132  ( Initially_reopen_restaurants_for_outdoor_dining_only )
Column  133  ( Closed_gyms )
Column  134  ( Reopened_gyms )
Column  135  ( Closed_movie_theaters )
Column  136  ( Reopened_movie_theaters )
Column  137  ( Closed_Bars )
Column  138  ( Reopen_bars )
Column  139  ( Reopened_hair_salons/barber_shops )
Column  140  ( Reopened_religious_gatherings )
Column  141  ( Reopened_other_non-essential_retail )
Column  142  ( Allowed_businesses_to_reopen_overnight )
Column  143  ( Began_to_reclose_bars )
Column  144  ( Closed_bars_(x2) )
Column  145  ( Closed_movie_theaters_(x2) )
Column  146  ( Closed_hair_salons/barber_shops_(x2) )
Column  147  ( Closed_gyms_(x2) )
Column  148  ( Closed_restaurants_(x2) )
Column  149  ( Reopened_restaurants_(x2) )
Column  150  ( Reopened_bars_(x2) )
Column  151  ( Reopened_gyms_(x2) )
Column  152  ( Reopened_hair_salons/barber_shops_(x2) )
Column  153  ( Reopened_movie_theaters_(x2) )
Column  154  ( Closed_bars_(x3) )
Column  155  ( Closed_restaurants_(x3) )
Column  156  ( Reopened_bars_(x3) )
Column  157  ( Reopened_restaurants_(x3) )
Column  158  ( Mandate_quarantine_for_those_entering_the_state_from_specific_settings )
Column  159  ( Mandate_quarantine_for_all_individuals_entering_the_state )
Column  160  ( Date_all_mandated_quarantines_ended )
Column  161  ( Date_vaccine_allocation_plan_last_updated )
Column  162  ( Vaccine_allocation_phase:_Frontline_Healthcare_Workers )
Column  163  ( Vaccine_allocation_phase:_Healthcare_Service_Workers )
Column  164  ( Vaccine_allocation_phase:_Home_Healthcare_Workers )
Column  165  ( Vaccine_allocation_phase:_Additional_Healthcare_Workers )
Column  166  ( Vaccine_allocation_phase:_Long-term_Care_Residents )
Column  167  ( Vaccine_allocation_phase:_EMS_Providers )
Column  168  ( Vaccine_allocation_phase:_Firefighters )
Column  169  ( Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel )
Column  170  ( Vaccine_allocation_phase:_Correctional_Staff )
Column  171  ( Vaccine_allocation_phase:_People_who_are_Incarcerated )
Column  172  ( Vaccine_allocation_phase:_Residents_of_Homeless_Shelters )
Column  173  ( Vaccine_allocation_phase:_Adults_Ages_75+ )
Column  174  ( Vaccine_allocation_phase:_Adults_Ages_65+ )
Column  175  ( Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions )
Column  176  ( Vaccine_allocation_phase:_Pre-K-12_School_Employees )
Column  177  ( Vaccine_allocation_phase:_Higher_Education_Employees )
Column  178  ( Vaccine_allocation_phase:_Public_Transit_Workers )
Column  179  ( Vaccine_allocation_phase:_Food_Supply_Workers )
Column  180  ( Vaccine_allocation_phase:_Grocery_Store_Workers )
Column  181  ( Vaccine_allocation_phase:_Frontline_Essential_Workers )
Column  182  ( Vaccine_allocation_phase:_Additional_Essential_Workers )
Column  183  ( Vaccine_allocation_phase:_General_Public )
Column  184  ( Date_adults_ages_80+_became_eligible_for_COVID-19_vaccination )
Column  185  ( Date_adults_ages_75+_became_eligible_for_COVID-19_vaccination )
Column  186  ( Date_adults_ages_70+_became_eligible_for_COVID-19_vaccination )
Column  187  ( Date_adults_ages_65+_became_eligible_for_COVID-19_vaccination )
Column  188  ( Date_adults_ages_60+_became_eligible_for_COVID-19_vaccination )
Column  189  ( Date_adults_ages_55+_became_eligible_for_COVID-19_vaccination )
Column  190  ( Date_adults_ages_50+_became_eligible_for_COVID-19_vaccination )
Column  191  ( Date_adults_ages_45+_became_eligible_for_COVID-19_vaccination )
Column  192  ( Date_adults_ages_40+_became_eligible_for_COVID-19_vaccination )
Column  193  ( Date_adults_ages_30+_became_eligible_for_COVID-19_vaccination )
Column  194  ( Date_K-12_school_employees_became_eligible_for_COVID-19_vaccination )
Column  195  ( Date_grocery_store_workers_became_eligible_for_COVID-19_vaccination )
Column  196  ( Date_incarcerated_people_became_eligible_for_COVID-19_vaccination )
Column  197  ( Date_general_public_became_eligible_for_COVID-19_vaccination )
Column  198  ( Adults_ages_65+_prioritized_ahead_of_essential_workers )
Column  199  ( Prioritization_by_race/ethnicity )
Column  200  ( Proof_of_work_eligibility_requirement_for_vaccination )
Column  201  ( Proof_of_age_eligibility_requirement_for_vaccination )
Column  202  ( Proof_of_residency_requirement_for_vaccination )
Column  203  ( Penalty_for_failure_to_comply_with_vaccine_distribution_requirements )
Column  204  ( Expanded_scope_of_practice_of_certain_health_providers_to_administer_vaccines )
Column  205  ( First_overall_eviction_moratorium_start )
Column  206  ( First_overall_eviction_moratorium_end )
Column  207  ( Second_overall_eviction_moratorium_start )
Column  208  ( Second_overall_eviction_moratorium_end )
Column  209  ( Third_overall_eviction_moratorium_start )
Column  210  ( Third_overall_eviction_moratorium_end )
Column  211  ( First_eviction_initiation_ban_start )
Column  212  ( First_eviction_initiation_ban_end )
Column  213  ( Second_Eviction_Initiation_Ban_Start )
Column  214  ( Second_Eviction_Initiation_Ban_End )
Column  215  ( First_eviction_hearing_ban_start )
Column  216  ( First_eviction_hearing_ban_end )
Column  217  ( Second_Eviction_Hearing_Ban_Start )
Column  218  ( Second_Eviction_Hearing_Ban_End )
Column  219  ( First_eviction_enforcement_ban_start )
Column  220  ( First_eviction_enforcement_ban_end )
Column  221  ( Second_Eviction_Enforcement_Ban_Start )
Column  222  ( Second_Eviction_Enforcement_Ban_End )
Column  223  ( COVID-19_hardship_limitation_start )
Column  224  ( COVID-19_hardship_limitation_end )
Column  225  ( Second_COVID-19_hardship_limitation_start )
Column  226  ( Second_COVID-19_hardship_limitation_end )
Column  227  ( Non-payment_limitation_start )
Column  228  ( Non-payment_limitation_end )
Column  229  ( Second_non-payment_limitation_start )
Column  230  ( Second_non-payment_limitation_end )
Column  231  ( CARES_Act_pleading_start )
Column  232  ( CARES_Act_pleading_end )
Column  233  ( CDC_moratorium_start )
Column  234  ( CDC_moratorium_end )
Column  235  ( Late_Fee_Ban_Start )
Column  236  ( Late_Fee_Ban_End )
Column  237  ( Second_Late_Fee_Ban_Start )
Column  238  ( Second_Late_Fee_Ban_End )
Column  239  ( Utilities_shutoff_moratorium_start )
Column  240  ( Utilities_shutoff_moratorium_expiration )
Column  241  ( Second_utilities_shutoff_moratorium_start )
Column  242  ( Utilities_reconnection_start )
Column  243  ( Utilities_reconnection_end )
Column  244  ( SNAP_Waiver_-_Emergency_Allotments_to_Current_SNAP_Households )
Column  245  ( SNAP_Waiver_-_Pandemic_EBT_during_school_year_2019-2020 )
Column  246  ( SNAP_Waiver_-_Pandemic_EBT_during_school_year_2020-2021 )
Column  247  ( SNAP_Waiver_-_Pandemic_EBT_during_summer_2021 )
Column  248  ( SNAP_Waiver_-_Temporary_Suspension_of_Claims_Collection )
Column  249  ( 2020_Q1_SNAP_ABAWD_Time_Limit_Waiver )
Column  250  ( Modify_Medicaid_requirements_with_1135_waivers_(date_of_CMS_approval) )
Column  251  ( Reopened_ACA_enrollment_using_a_special_enrollment_period )
Column  252  ( State_previously_allowed_audio-only_telehealth )
Column  253  ( Allow_audio-only_telehealth )
Column  254  ( Allow/expand_Medicaid_telehealth_coverage )
Column  255  ( State_had_CHIP_premium_non-payment_lock-out_period_as_of_January_2019 )
Column  256  ( Suspend_CHIP_premium_non-payment_lock-outs )
Column  257  ( Report_COVID-19_testing_by_race/ethnicity )
Column  258  ( Report_COVID-19_cases_by_race/ethnicity )
Column  259  ( Report_COVID-19_hospitalizations_by_race )
Column  260  ( Report_COVID-19_deaths_by_race/ethnicity )
Column  261  ( Report_COVID-19_vaccinations_by_race/ethnicity )
Column  262  ( Report_Indigenous_COVID-19_testing )
Column  263  ( Report_Indigenous_COVID-19_cases )
Column  264  ( Report_Indigenous_COVID-19_hospitalizations )
Column  265  ( Report_Indigenous_COVID-19_deaths )
Column  266  ( Report_Indigenous_COVID-19_vaccinations )
Column  267  ( Stopped_personal_visitation_in_state_prisons )
Column  268  ( Stopped_legal_visitation_in_state_prisons )
Column  269  ( Resumed_visitation_in_state_prisons )
Column  270  ( Stopped_visitation_in_state_prisons_x2 )
Column  271  ( Resumed_visitation_in_state_prisons_x2 )
Column  272  ( Does_not_charge_copays_for_incarcerated_individuals )
Column  273  ( Waived_COVID/respiratory_illness-related_copays_during_pandemic_for_incarcerated_individuals )
Column  274  ( Waived_all_copays_during_pandemic_for_incarcerated_individuals )
Column  275  ( Did_not_waive_copays_for_incarcerated_individuals )
Column  276  ( Suspended_elective_medical_procedures )
Column  277  ( Resumed_elective_medical_procedures )
Column  278  ( No_order_to_suspend_elective_medical_procedures_but_did_release_guidance_or_orders_to_resume )
Column  279  ( Suspended_elective_medical_procedures_x2 )
Column  280  ( Resumed_elective_medical_procedures_x2 )
Column  281  ( No_state_unemployment_waiting_period_prior_to_pandemic;_or_date_waiting_period_waived_not_found )
Column  282  ( Waived_one_week_waiting_period_for_unemployment_insurance )
Column  283  ( Reinstated_one_week_waiting_period_for_unemployment_insurance )
Column  284  ( Waived_work_search_requirement_for_unemployment_insurance )
Column  285  ( Reinstated_work_search_requirement_for_UI )
Column  286  ( Expanded_eligibility_of_unemployment_insurance_to_anyone_who_is_quarantined_and/or_taking_care_of_someone_who_is_quarantined )
Column  287  ( Expanded_eligibility_to_high-risk_individuals_in_preventative_quarantine )
Column  288  ( Expanded_eligibility_of_unemployment_insurance_to_those_who_have_lost_childcare/school_closures )
Column  289  ( Extended_the_amount_of_time_an_individual_can_be_on_unemployment_insurance )
Column  290  ( Weekly_unemployment_insurance_maximum_amount_(dollars) )
Column  291  ( Weekly_unemployment_insurance_maximum_amount_with_extra_stimulus_(through_July_31,_2020)_(dollars) )
Column  292  ( January_2020_unemployment_insurance_maximum_duration_(weeks) )
Column  293  ( July_2020_unemployment_insurance_maximum_duration_(weeks) )
Column  294  ( 2021_unemployment_insurance_maximum_duration_(weeks) )
Column  295  ( Extended_Benefits_program_activated )
Column  296  ( Extended_Benefits_program_deactivated )
Column  297  ( Extended_Benefits_program_activated_x2 )
Column  298  ( Total_Unemployment_Rate_at_Extended_Benefits_program_shutoff )
Column  299  ( Total_Unemployment_Rate_relative_to_prior_year_(%) )
Column  300  ( Total_Unemployment_Rate_relative_to_second_prior_year_(%) )
Column  301  ( 20-week_Extended_Benefits_program_activated )
Column  302  ( 20-week_Extended_Benefits_program_deactivated )
Column  303  ( 20-week_Extended_Benefits_program_activated_x2 )
Column  304  ( Stopped_participating_in_pandemic-related_federal_unemployment_benefit_programs )
Column  305  ( Minimum_total_earnings_required_in_the_base_period_to_qualify_for_UI )
Column  306  ( Number_of_calendar_quarters_with_earnings_in_the_base_period_needed_to_qualify_for_UI )
Column  307  ( Minimum_total_earnings_required_outside_the_highest_earning_calendar_quarter_of_the_base_period_to_qualify_for_UI )
Column  308  ( Require_earnings_in_the_last_two_calendar_quarters_of_the_base_period_in_order_to_qualify_for_UI )
Column  309  ( Earnings_in_base_period_required_to_receive_a_$300_weekly_benefit_amount_for_UI )
Column  310  ( Taxable_Wage_Amount )
Column  311  ( Minimum_Tax_Rate_(%) )
Column  312  ( Maximum_Tax_Rate_(%) )
Column  313  ( Average_Benefit_Amount_(August) )
Column  314  ( OSHA-approved_state_plan )
Column  315  ( State_department_in_charge_of_enforcing_programs )
Column  316  ( Aerosol_transmissable_diseases_standards )
Column  317  ( Air_or_ventilation_standards )
Column  318  ( Paid_sick_leave_prior_to_pandemic )
Column  319  ( Paid_sick_leave_expansion_during_pandemic )
Column  320  ( COVID-19_anti-retaliation_rules )
Column  321  ( COVID-19_business_liability_protections )
Column  322  ( COVID-19_liability_protections_for_healthcare_providers )
Column  323  ( Branch_of_government_implementing_COVID-19_liability_rules )
Column  324  ( COVID-19_workers'_compensation_expansion )
Column  325  ( Types_of_workers_eligible_for_workers'_compensation_expansion )
Column  326  ( Data_reporting_required_for_medical_treatment )
Column  327  ( Minimum_number_of_work_days_missed_by_workers_to_require_data_reporting )
Column  328  ( Occupational_injuries,_illnesses,_and_fatalities_reporting_prior_to_pandemic )
Column  329  ( Made_Effort_to_Limit_Abortion_Access )
Column  330  ( Use_of_telemedicine/telephone_evaluations_to_initiate_buprenorphine_prescribing )
Column  331  ( Patients_can_receive_14-28_take-home_doses_of_opioid_medication )
Column  332  ( Home_delivery_of_take-home_medication_by_opioid_treatment_programs )
Column  333  ( Use_of_telemedicine_for_schedule_II-V_prescriptions )
Column  334  ( Exceptions_to_emergency_oral_prescriptions )
Column  335  ( Waive_requirement_to_obtain_separate_DEA_registration_to_dispense_outside_home_state )
Column  336  ( Medicaid_Expansion )
Column  337  ( Population_density_per_square_miles )
Column  338  ( Population_2018 )
Column  339  ( Square_Miles )
Column  340  ( Number_Homeless_(2019) )
Column  341  ( Percent_Unemployed_(2018) )
Column  342  ( Percent_living_under_the_federal_poverty_line_(2018) )
Column  343  ( Percent_at_risk_for_serious_illness_due_to_COVID )
Column  344  ( All-cause_deaths_2018 )
Column  345  ( Mental_health_professionals_per_100,000_population_in_2019 )
Column  346  ( Were_there_casino(s)_in_State?_(Land_and_Non-Land_based) )
Column  347  ( State_has_at_least_one_Indian/Alaska_Native_reservation )
Column  348  ( COVID-19_is_not_an_acceptable_reason_to_request_application_for_mail-in_ballot_unless_sick_or_exposed_(as_of_September_16,_2020) )
Column  349  ( Witness_or_notary_signature_required_for_mail-in_ballot_(as_of_September_1,_2020) )
Column  350  ( Permanent_mail-in_ballot_system )
Column  351  ( Automatic_mail-in_ballot_system_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details) )
Column  352  ( Automatic_applications_sent_for_mail-in_ballots_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details) )
Column  353  ( Last_date_of_receipt_of_mail-in_ballot_request_for_the_general_election_(by_mail_or_online) )
Column  354  ( Closed_casinos )
Column  355  ( Reopened_casinos )
Column  356  ( Closed_casinos_(x2) )
Column  357  ( Reopened_casinos_(x2) )
Column  358  ( Mention_of_tribal_casinos )
Column  359  ( Jan_1_2019_Minimum_Wage )
Column  360  ( Mar_29_2019_Minimum_Wage )
Column  361  ( Jul_1_2019_Minimum_Wage )
Column  362  ( Oct_1_2019_Minimum_Wage )
Column  363  ( Jan_1_2020_Minimum_Wage )
Column  364  ( Jul_1_2020_Minimum_Wage )
Column  365  ( Sep_1_2020_Minimum_Wage )
Column  366  ( Oct_1_2020_Minimum_Wage )
Column  367  ( 2020_Minimum_Wage_for_Tipped_Workers )
Column  368  ( 2021_Minimum_Wage )
Column  369  ( Different_Minimum_Wage_for_Smaller_Businesses )
Column  370  ( death )
Column  371  ( deathConfirmed )
Column  372  ( deathIncrease )
Column  373  ( deathProbable )
Column  374  ( hospitalized )
Column  375  ( hospitalizedCumulative )
Column  376  ( hospitalizedCurrently )
Column  377  ( hospitalizedIncrease )
Column  378  ( inIcuCumulative )
Column  379  ( inIcuCurrently )
Column  380  ( negative )
Column  381  ( negativeIncrease )
Column  382  ( negativeTestsAntibody )
Column  383  ( negativeTestsPeopleAntibody )
Column  384  ( negativeTestsViral )
Column  385  ( onVentilatorCumulative )
Column  386  ( onVentilatorCurrently )
Column  387  ( positive )
Column  388  ( positiveCasesViral )
Column  389  ( positiveIncrease )
Column  390  ( positiveScore )
Column  391  ( positiveTestsAntibody )
Column  392  ( positiveTestsAntigen )
Column  393  ( positiveTestsPeopleAntibody )
Column  394  ( positiveTestsPeopleAntigen )
Column  395  ( positiveTestsViral )

In [20]:
# 102 State_of_emergency_issued
# 358 Mention_of_tribal_casinos

In [24]:
X_removed <- X[, -(102:358)]
for (i in seq_along(colnames(X_removed))) {
  cat("Column ", i, " (", colnames(X_removed)[i], ")\n")
}

Column  1  ( LAT )
Column  2  ( LON )
Column  3  ( AREA_SQMI )
Column  4  ( E_TOTPOP )
Column  5  ( E_HU )
Column  6  ( E_HH )
Column  7  ( E_POV )
Column  8  ( E_UNEMP )
Column  9  ( E_PCI )
Column  10  ( E_NOHSDP )
Column  11  ( E_AGE65 )
Column  12  ( E_AGE17 )
Column  13  ( E_DISABL )
Column  14  ( E_SNGPNT )
Column  15  ( E_MINRTY )
Column  16  ( E_LIMENG )
Column  17  ( E_MUNIT )
Column  18  ( E_MOBILE )
Column  19  ( E_CROWD )
Column  20  ( E_NOVEH )
Column  21  ( E_GROUPQ )
Column  22  ( EP_POV )
Column  23  ( MP_POV )
Column  24  ( EP_UNEMP )
Column  25  ( MP_UNEMP )
Column  26  ( EP_PCI )
Column  27  ( MP_PCI )
Column  28  ( EP_NOHSDP )
Column  29  ( MP_NOHSDP )
Column  30  ( EP_AGE65 )
Column  31  ( MP_AGE65 )
Column  32  ( EP_AGE17 )
Column  33  ( MP_AGE17 )
Column  34  ( EP_DISABL )
Column  35  ( MP_DISABL )
Column  36  ( EP_SNGPNT )
Column  37  ( MP_SNGPNT )
Column  38  ( EP_MINRTY )
Column  39  ( MP_MINRTY )
Column  40  ( EP_LIMENG )
Column  41  ( MP_LIMENG )
Column  42  ( EP_MUNIT )
Column  43  ( MP_MUNIT )
Column  44  ( EP_MOBILE )
Column  45  ( MP_MOBILE )
Column  46  ( EP_CROWD )
Column  47  ( MP_CROWD )
Column  48  ( EP_NOVEH )
Column  49  ( MP_NOVEH )
Column  50  ( EP_GROUPQ )
Column  51  ( MP_GROUPQ )
Column  52  ( EPL_POV )
Column  53  ( EPL_UNEMP )
Column  54  ( EPL_PCI )
Column  55  ( EPL_NOHSDP )
Column  56  ( SPL_THEME1 )
Column  57  ( RPL_THEME1 )
Column  58  ( EPL_AGE65 )
Column  59  ( EPL_AGE17 )
Column  60  ( EPL_DISABL )
Column  61  ( EPL_SNGPNT )
Column  62  ( SPL_THEME2 )
Column  63  ( RPL_THEME2 )
Column  64  ( EPL_MINRTY )
Column  65  ( EPL_LIMENG )
Column  66  ( SPL_THEME3 )
Column  67  ( RPL_THEME3 )
Column  68  ( EPL_MUNIT )
Column  69  ( EPL_MOBILE )
Column  70  ( EPL_CROWD )
Column  71  ( EPL_NOVEH )
Column  72  ( EPL_GROUPQ )
Column  73  ( SPL_THEME4 )
Column  74  ( RPL_THEME4 )
Column  75  ( SPL_THEMES )
Column  76  ( RPL_THEMES )
Column  77  ( F_POV )
Column  78  ( F_UNEMP )
Column  79  ( F_PCI )
Column  80  ( F_NOHSDP )
Column  81  ( F_THEME1 )
Column  82  ( F_AGE65 )
Column  83  ( F_AGE17 )
Column  84  ( F_DISABL )
Column  85  ( F_SNGPNT )
Column  86  ( F_THEME2 )
Column  87  ( F_MINRTY )
Column  88  ( F_LIMENG )
Column  89  ( F_THEME3 )
Column  90  ( F_MUNIT )
Column  91  ( F_MOBILE )
Column  92  ( F_CROWD )
Column  93  ( F_NOVEH )
Column  94  ( F_GROUPQ )
Column  95  ( F_THEME4 )
Column  96  ( F_TOTAL )
Column  97  ( E_UNINSUR )
Column  98  ( EP_UNINSUR )
Column  99  ( MP_UNINSUR )
Column  100  ( E_DAYPOP )
Column  101  ( State_FIPS_Code )
Column  102  ( Jan_1_2019_Minimum_Wage )
Column  103  ( Mar_29_2019_Minimum_Wage )
Column  104  ( Jul_1_2019_Minimum_Wage )
Column  105  ( Oct_1_2019_Minimum_Wage )
Column  106  ( Jan_1_2020_Minimum_Wage )
Column  107  ( Jul_1_2020_Minimum_Wage )
Column  108  ( Sep_1_2020_Minimum_Wage )
Column  109  ( Oct_1_2020_Minimum_Wage )
Column  110  ( 2020_Minimum_Wage_for_Tipped_Workers )
Column  111  ( 2021_Minimum_Wage )
Column  112  ( Different_Minimum_Wage_for_Smaller_Businesses )
Column  113  ( death )
Column  114  ( deathConfirmed )
Column  115  ( deathIncrease )
Column  116  ( deathProbable )
Column  117  ( hospitalized )
Column  118  ( hospitalizedCumulative )
Column  119  ( hospitalizedCurrently )
Column  120  ( hospitalizedIncrease )
Column  121  ( inIcuCumulative )
Column  122  ( inIcuCurrently )
Column  123  ( negative )
Column  124  ( negativeIncrease )
Column  125  ( negativeTestsAntibody )
Column  126  ( negativeTestsPeopleAntibody )
Column  127  ( negativeTestsViral )
Column  128  ( onVentilatorCumulative )
Column  129  ( onVentilatorCurrently )
Column  130  ( positive )
Column  131  ( positiveCasesViral )
Column  132  ( positiveIncrease )
Column  133  ( positiveScore )
Column  134  ( positiveTestsAntibody )
Column  135  ( positiveTestsAntigen )
Column  136  ( positiveTestsPeopleAntibody )
Column  137  ( positiveTestsPeopleAntigen )
Column  138  ( positiveTestsViral )
Column  139  ( recovered )
Column  140  ( totalTestEncountersViral )
Column  141  ( totalTestEncountersViralIncrease )
Column  142  ( totalTestResults )
Column  143  ( totalTestResultsIncrease )
Column  144  ( totalTestsAntibody )
Column  145  ( totalTestsAntigen )
Column  146  ( totalTestsPeopleAntibody )
Column  147  ( totalTestsPeopleAntigen )
Column  148  ( totalTestsPeopleViral )
Column  149  ( totalTestsPeopleViralIncrease )
Column  150  ( totalTestsViral )
Column  151  ( totalTestsViralIncrease )
Column  152  ( metrics.testPositivityRatio )
Column  153  ( metrics.vaccinationsInitiatedRatio )
Column  154  ( metrics.vaccinationsCompletedRatio )
Column  155  ( hhs_region )
Column  156  ( Variant % A.2.5 )
Column  157  ( Variant % AY.1 )
Column  158  ( Variant % AY.2 )
Column  159  ( Variant % AY.3 )
Column  160  ( Variant % B.1 )
Column  161  ( Variant % B.1.1 )
Column  162  ( Variant % B.1.1.194 )
Column  163  ( Variant % B.1.1.519 )
Column  164  ( Variant % B.1.1.529 )
Column  165  ( Variant % B.1.1.7 )
Column  166  ( Variant % B.1.2 )
Column  167  ( Variant % B.1.234 )
Column  168  ( Variant % B.1.243 )
Column  169  ( Variant % B.1.351 )
Column  170  ( Variant % B.1.427 )
Column  171  ( Variant % B.1.429 )
Column  172  ( Variant % B.1.525 )
Column  173  ( Variant % B.1.526 )
Column  174  ( Variant % B.1.526.1 )
Column  175  ( Variant % B.1.526.2 )
Column  176  ( Variant % B.1.596 )
Column  177  ( Variant % B.1.617 )
Column  178  ( Variant % B.1.617.1 )
Column  179  ( Variant % B.1.617.2 )
Column  180  ( Variant % B.1.617.3 )
Column  181  ( Variant % B.1.621 )
Column  182  ( Variant % B.1.621.1 )
Column  183  ( Variant % B.1.626 )
Column  184  ( Variant % B.1.628 )
Column  185  ( Variant % B.1.637 )
Column  186  ( Variant % BA.1.1 )
Column  187  ( Variant % BA.2 )
Column  188  ( Variant % BA.2.12.1 )
Column  189  ( Variant % BA.2.75 )
Column  190  ( Variant % BA.2.75.2 )
Column  191  ( Variant % BA.4 )
Column  192  ( Variant % BA.4.6 )
Column  193  ( Variant % BA.5 )
Column  194  ( Variant % BA.5.2.6 )
Column  195  ( Variant % BF.11 )
Column  196  ( Variant % BF.7 )
Column  197  ( Variant % BN.1 )
Column  198  ( Variant % BQ.1 )
Column  199  ( Variant % BQ.1.1 )
Column  200  ( Variant % CH.1.1 )
Column  201  ( Variant % FD.2 )
Column  202  ( Variant % Other )
Column  203  ( Variant % P.1 )
Column  204  ( Variant % P.2 )
Column  205  ( Variant % R.1 )
Column  206  ( Variant % XBB )
Column  207  ( Variant % XBB.1.16 )
Column  208  ( Variant % XBB.1.5 )
Column  209  ( Variant % XBB.1.5.1 )
Column  210  ( Variant % XBB.1.9.1 )
Column  211  ( Variant % XBB.1.9.2 )
Column  212  ( Variant % XBB.2.3 )
Column  213  ( log_rolled_cases_ratios )