In [1]:
import numpy as np
import pandas as pd
import requests

from itertools import product

### Overall Code Logic

Data comes in as `bi_weekly_dates x hhs_region x variant`, with the corresponding `share`

End goal is to transform this into:
`daily_dates x fips` with `variant_1, variant_2, ..., variant_n` as features with their corresponding `shares` adding up to `1`

Where the `dates` will range from the beginning of the TLGRF project till now (when data gets updated)

### Import CDC's CSV File of COVID 19 Proportions

In [2]:
url = "https://data.cdc.gov/api/views/jr58-6ysp/rows.csv?accessType=DOWNLOAD"
data_path = "../data/SARS-CoV-2_Variant_Proportions.csv"
UPDATE_DATA = True

if (UPDATE_DATA):
    response = requests.get(url)
    with open(data_path, "wb") as f:
        f.write(response.content)

df = pd.read_csv(data_path, low_memory=False)
df["week_ending"] = pd.to_datetime(df["week_ending"])
df["published_date"] = pd.to_datetime(df["published_date"])

df["variant"] = df["variant"].apply(str)
#df["share"] = df["share"].astype('int64')


df.sort_values(by=["week_ending","usa_or_hhsregion","variant"], inplace=True, ascending=[True,True,True])
df.head(30)

,usa_or_hhsregion,week_ending,variant,share,share_hi,share_lo,nchs_or_count_flag,modeltype,time_interval,published_date
21875,1,2021-01-02,B.1,0.215363,0.519812,0.065066,NaN,weighted,biweekly,2021-05-04
21876,1,2021-01-02,B.1.1.519,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
21871,1,2021-01-02,B.1.1.7,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
21870,1,2021-01-02,B.1.2,0.286312,0.422580,0.180268,NaN,weighted,biweekly,2021-05-04
21879,1,2021-01-02,B.1.234,0.031440,0.112799,0.008219,NaN,weighted,biweekly,2021-05-04
21878,1,2021-01-02,B.1.243,0.076162,0.154845,0.035769,NaN,weighted,biweekly,2021-05-04
21881,1,2021-01-02,B.1.351,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
21874,1,2021-01-02,B.1.427,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
21872,1,2021-01-02,B.1.429,0.001683,0.035162,0.000078,NaN,weighted,biweekly,2021-05-04
21882,1,2021-01-02,B.1.525,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
21877,1,2021-01-02,B.1.526,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
21873,1,2021-01-02,B.1.596,0.051787,0.118745,0.021658,NaN,weighted,biweekly,2021-05-04
36187,1,2021-01-02,Other,0.337252,0.435615,0.251213,NaN,weighted,biweekly,2021-05-04
21883,1,2021-01-02,P.1,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
21880,1,2021-01-02,P.2,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
21884,1,2021-01-02,R.1,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
36064,10,2021-01-02,B.1,0.011769,0.101699,0.001251,NaN,weighted,biweekly,2021-05-04
36065,10,2021-01-02,B.1.1.519,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
36060,10,2021-01-02,B.1.1.7,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
36059,10,2021-01-02,B.1.2,0.479575,0.899642,0.086531,NaN,weighted,biweekly,2021-05-04
36068,10,2021-01-02,B.1.234,0.011645,0.101950,0.001221,NaN,weighted,biweekly,2021-05-04
36067,10,2021-01-02,B.1.243,0.034636,0.291921,0.003113,NaN,weighted,biweekly,2021-05-04
36070,10,2021-01-02,B.1.351,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
36063,10,2021-01-02,B.1.427,0.020096,0.215470,0.001529,NaN,weighted,biweekly,2021-05-04
36061,10,2021-01-02,B.1.429,0.040242,0.272556,0.004670,NaN,weighted,biweekly,2021-05-04
36071,10,2021-01-02,B.1.525,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
36066,10,2021-01-02,B.1.526,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
36062,10,2021-01-02,B.1.596,0.023636,0.201160,0.002322,NaN,weighted,biweekly,2021-05-04
36259,10,2021-01-02,Other,0.378402,0.643827,0.170132,NaN,weighted,biweekly,2021-05-04
36072,10,2021-01-02,P.1,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04

In [3]:
unique_dates = pd.unique(df["week_ending"])
unique_dates

array(['2021-01-02T00:00:00.000000000', '2021-01-16T00:00:00.000000000',
       '2021-01-30T00:00:00.000000000', '2021-02-06T00:00:00.000000000',
       '2021-02-13T00:00:00.000000000', '2021-02-20T00:00:00.000000000',
       '2021-02-27T00:00:00.000000000', '2021-03-06T00:00:00.000000000',
       '2021-03-13T00:00:00.000000000', '2021-03-20T00:00:00.000000000',
       '2021-03-27T00:00:00.000000000', '2021-04-03T00:00:00.000000000',
       '2021-04-10T00:00:00.000000000', '2021-04-17T00:00:00.000000000',
       '2021-04-24T00:00:00.000000000', '2021-05-01T00:00:00.000000000',
       '2021-05-08T00:00:00.000000000', '2021-05-15T00:00:00.000000000',
       '2021-05-22T00:00:00.000000000', '2021-05-29T00:00:00.000000000',
       '2021-06-05T00:00:00.000000000', '2021-06-12T00:00:00.000000000',
       '2021-06-19T00:00:00.000000000', '2021-06-26T00:00:00.000000000',
       '2021-07-03T00:00:00.000000000', '2021-07-10T00:00:00.000000000',
       '2021-07-17T00:00:00.000000000', '2021-07-24T00:00:00.000000000',
       '2021-07-31T00:00:00.000000000', '2021-08-07T00:00:00.000000000',
       '2021-08-14T00:00:00.000000000', '2021-08-21T00:00:00.000000000',
       '2021-08-28T00:00:00.000000000', '2021-09-04T00:00:00.000000000',
       '2021-09-11T00:00:00.000000000', '2021-09-18T00:00:00.000000000',
       '2021-09-25T00:00:00.000000000', '2021-10-02T00:00:00.000000000',
       '2021-10-09T00:00:00.000000000', '2021-10-16T00:00:00.000000000',
       '2021-10-23T00:00:00.000000000', '2021-10-30T00:00:00.000000000',
       '2021-11-06T00:00:00.000000000', '2021-11-13T00:00:00.000000000',
       '2021-11-20T00:00:00.000000000', '2021-11-27T00:00:00.000000000',
       '2021-12-04T00:00:00.000000000', '2021-12-11T00:00:00.000000000',
       '2021-12-18T00:00:00.000000000', '2021-12-25T00:00:00.000000000',
       '2022-01-01T00:00:00.000000000', '2022-01-08T00:00:00.000000000',
       '2022-01-15T00:00:00.000000000', '2022-01-22T00:00:00.000000000',
       '2022-01-29T00:00:00.000000000', '2022-02-05T00:00:00.000000000',
       '2022-02-12T00:00:00.000000000', '2022-02-19T00:00:00.000000000',
       '2022-02-26T00:00:00.000000000', '2022-03-05T00:00:00.000000000',
       '2022-03-12T00:00:00.000000000', '2022-03-19T00:00:00.000000000',
       '2022-03-26T00:00:00.000000000', '2022-04-02T00:00:00.000000000',
       '2022-04-09T00:00:00.000000000', '2022-04-16T00:00:00.000000000',
       '2022-04-23T00:00:00.000000000', '2022-04-30T00:00:00.000000000',
       '2022-05-07T00:00:00.000000000', '2022-05-14T00:00:00.000000000',
       '2022-05-21T00:00:00.000000000', '2022-05-28T00:00:00.000000000',
       '2022-06-04T00:00:00.000000000', '2022-06-11T00:00:00.000000000',
       '2022-06-18T00:00:00.000000000', '2022-06-25T00:00:00.000000000',
       '2022-07-02T00:00:00.000000000', '2022-07-09T00:00:00.000000000',
       '2022-07-16T00:00:00.000000000', '2022-07-23T00:00:00.000000000',
       '2022-07-30T00:00:00.000000000', '2022-08-06T00:00:00.000000000',
       '2022-08-13T00:00:00.000000000', '2022-08-20T00:00:00.000000000',
       '2022-08-27T00:00:00.000000000', '2022-09-03T00:00:00.000000000',
       '2022-09-10T00:00:00.000000000', '2022-09-17T00:00:00.000000000',
       '2022-09-24T00:00:00.000000000', '2022-10-01T00:00:00.000000000',
       '2022-10-08T00:00:00.000000000', '2022-10-15T00:00:00.000000000',
       '2022-10-22T00:00:00.000000000', '2022-10-29T00:00:00.000000000',
       '2022-11-05T00:00:00.000000000', '2022-11-12T00:00:00.000000000',
       '2022-11-19T00:00:00.000000000', '2022-11-26T00:00:00.000000000',
       '2022-12-03T00:00:00.000000000', '2022-12-10T00:00:00.000000000',
       '2022-12-17T00:00:00.000000000', '2022-12-24T00:00:00.000000000',
       '2022-12-31T00:00:00.000000000'], dtype='datetime64[ns]')

In [4]:
unique_regions = pd.unique(df["usa_or_hhsregion"])
unique_regions

array(['1', '10', '2', '3', '4', '5', '6', '7', '8', '9', 'USA'],
      dtype=object)

In [5]:
unique_variants = sorted(pd.unique(df["variant"]))
unique_variants

['A.2.5',
 'AY.1',
 'AY.2',
 'AY.3',
 'B.1',
 'B.1.1',
 'B.1.1.194',
 'B.1.1.519',
 'B.1.1.529',
 'B.1.1.7',
 'B.1.2',
 'B.1.234',
 'B.1.243',
 'B.1.351',
 'B.1.427',
 'B.1.429',
 'B.1.525',
 'B.1.526',
 'B.1.526.1',
 'B.1.526.2',
 'B.1.596',
 'B.1.617',
 'B.1.617.1',
 'B.1.617.2',
 'B.1.617.3',
 'B.1.621',
 'B.1.621.1',
 'B.1.626',
 'B.1.628',
 'B.1.637',
 'BA.1.1',
 'BA.2',
 'BA.2.12.1',
 'BA.2.75',
 'BA.2.75.2',
 'BA.4',
 'BA.4.6',
 'BA.5',
 'BA.5.2.6',
 'BF.11',
 'BF.7',
 'BN.1',
 'BQ.1',
 'BQ.1.1',
 'Other',
 'P.1',
 'P.2',
 'R.1',
 'XBB',
 'XBB.1.5']

### Multiple Published Reports of `share` per `date`, `hhs_region`, `variant`. Keep by latest `publication_date`

In [6]:
df_latest = df.sort_values('published_date', ascending=False).groupby(["week_ending","usa_or_hhsregion","variant"]).first().reset_index()
df_latest

,week_ending,usa_or_hhsregion,variant,share,share_hi,share_lo,nchs_or_count_flag,modeltype,time_interval,published_date
0,2021-01-02,1,B.1,0.215363,0.519812,0.065066,NaN,weighted,biweekly,2021-05-04
1,2021-01-02,1,B.1.1.519,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
2,2021-01-02,1,B.1.1.7,0.000000,NaN,NaN,NaN,weighted,biweekly,2021-05-04
3,2021-01-02,1,B.1.2,0.286312,0.422580,0.180268,NaN,weighted,biweekly,2021-05-04
4,2021-01-02,1,B.1.234,0.031440,0.112799,0.008219,NaN,weighted,biweekly,2021-05-04
...,...,...,...,...,...,...,...,...,...,...
27110,2022-12-31,USA,BQ.1,0.183221,0.258504,0.125420,NaN,smoothed,weekly,2022-12-30
27111,2022-12-31,USA,BQ.1.1,0.268548,0.364878,0.189282,NaN,smoothed,weekly,2022-12-30
27112,2022-12-31,USA,Other,0.000245,0.000462,0.000127,NaN,smoothed,weekly,2022-12-30
27113,2022-12-31,USA,XBB,0.035711,0.049730,0.025421,NaN,smoothed,weekly,2022-12-30
27114,2022-12-31,USA,XBB.1.5,0.405490,0.609860,0.227259,NaN,smoothed,weekly,2022-12-30

### Impute missing variants for each date and region, setting their share to 0

In [7]:
#df_imputed = pd.DataFrame(columns=["date", "hhs_region", "variant"])

df_weekly_dates = pd.DataFrame({"date":unique_dates})
df_regions = pd.DataFrame({"hhs_region": unique_regions})
df_variants = pd.DataFrame({"variant": unique_variants})

df_imputed = pd.merge(left=df_weekly_dates, right=df_regions, how="cross")
df_imputed = pd.merge(left=df_imputed, right=df_variants, how="cross")

#for date, region, variant in product(unique_dates, unique_regions, unique_variants):
#    df_imputed = df_imputed.append({"date": date, "hhs_region": region, "variant": variant}, ignore_index=True)

df_imputed = df_imputed.merge(df_latest, how="left", left_on=["date", "hhs_region", "variant"], right_on=["week_ending","usa_or_hhsregion", "variant"])
df_imputed.fillna(0, inplace=True)
df_imputed

,date,hhs_region,variant,week_ending,usa_or_hhsregion,share,share_hi,share_lo,nchs_or_count_flag,modeltype,time_interval,published_date
0,2021-01-02,1,A.2.5,0,0,0.000000,0.000000,0.000000,0.0,0,0,0
1,2021-01-02,1,AY.1,0,0,0.000000,0.000000,0.000000,0.0,0,0,0
2,2021-01-02,1,AY.2,0,0,0.000000,0.000000,0.000000,0.0,0,0,0
3,2021-01-02,1,AY.3,0,0,0.000000,0.000000,0.000000,0.0,0,0,0
4,2021-01-02,1,B.1,2021-01-02 00:00:00,1,0.215363,0.519812,0.065066,0.0,weighted,biweekly,2021-05-04 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
56645,2022-12-31,USA,P.1,0,0,0.000000,0.000000,0.000000,0.0,0,0,0
56646,2022-12-31,USA,P.2,0,0,0.000000,0.000000,0.000000,0.0,0,0,0
56647,2022-12-31,USA,R.1,0,0,0.000000,0.000000,0.000000,0.0,0,0,0
56648,2022-12-31,USA,XBB,2022-12-31 00:00:00,USA,0.035711,0.049730,0.025421,0.0,smoothed,weekly,2022-12-30 00:00:00
56649,2022-12-31,USA,XBB.1.5,2022-12-31 00:00:00,USA,0.405490,0.609860,0.227259,0.0,smoothed,weekly,2022-12-30 00:00:00

### Normalize the shares

In [8]:
df_imputed_select = df_imputed[["date", "hhs_region", "variant", "share"]]
def normalize(x):
    return (x) / (x.sum())
df_grouped = df_imputed_select.groupby(["date","hhs_region"])
df_normalized = df_grouped["share"].transform(normalize)
df_imputed_select["normalized_share"] = df_normalized
df_imputed_select = df_imputed_select[~(df_imputed_select["hhs_region"] == "USA")]
df_imputed_select["hhs_region"] = df_imputed_select["hhs_region"].astype(int)
df_imputed_select

/home/zwang937/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/zwang937/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

            date  hhs_region  variant     share  normalized_share
0     2021-01-02           1    A.2.5  0.000000          0.000000
1     2021-01-02           1     AY.1  0.000000          0.000000
2     2021-01-02           1     AY.2  0.000000          0.000000
3     2021-01-02           1     AY.3  0.000000          0.000000
4     2021-01-02           1      B.1  0.215363          0.215363
...          ...         ...      ...       ...               ...
56595 2022-12-31           9      P.1  0.000000          0.000000
56596 2022-12-31           9      P.2  0.000000          0.000000
56597 2022-12-31           9      R.1  0.000000          0.000000
56598 2022-12-31           9      XBB  0.075548          0.075548
56599 2022-12-31           9  XBB.1.5  0.091676          0.091676

[51500 rows x 5 columns]

### Verify that for each date, all the present variants sum up to 100%

In [9]:
for date in unique_dates:
    df_segmented_by_date = df_imputed[df_imputed["date"] == date]
    for region in pd.unique(df_segmented_by_date["hhs_region"]):
        df_segmented_by_date_and_region = df_segmented_by_date[df_segmented_by_date["hhs_region"]==region]
        sum_of_variant_shares = df_segmented_by_date_and_region["share"].sum()
        print("Date: {}, Region: {}, Total Sum of Normalized Shares {}".format(date, region, sum_of_variant_shares))
    print("\n")

Date: 2021-01-02T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000000013620594
Date: 2021-01-02T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000016763808
Date: 2021-01-02T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.999999996274711
Date: 2021-01-02T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999976134859
Date: 2021-01-02T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000027939668
Date: 2021-01-02T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000164145608
Date: 2021-01-02T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.999999988824127
Date: 2021-01-02T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000000004074537
Date: 2021-01-02T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000000009313226
Date: 2021-01-02T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000011175871
Date: 2021-01-02T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.000000009225916


Date: 2021-01-16T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.999999987194315
Date: 2021-01-16T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999862338871
Date: 2021-01-16T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.99999999173451
Date: 2021-01-16T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999825377001
Date: 2021-01-16T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000000008847565
Date: 2021-01-16T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.999999968102202
Date: 2021-01-16T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000027939682
Date: 2021-01-16T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000274740168
Date: 2021-01-16T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999997671692
Date: 2021-01-16T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000013038516
Date: 2021-01-16T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.9999999825085979


Date: 2021-01-30T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.572708071558737
Date: 2021-01-30T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.7802995806559918
Date: 2021-01-30T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.547318851109593
Date: 2021-01-30T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.772835647367176
Date: 2021-01-30T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.847807396610733
Date: 2021-01-30T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.9111418966203928
Date: 2021-01-30T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.85130840796046
Date: 2021-01-30T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.898825344629587
Date: 2021-01-30T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.830218374030666
Date: 2021-01-30T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.8153978912159778
Date: 2021-01-30T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.802398898580577


Date: 2021-02-06T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.022592179477214
Date: 2021-02-06T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.2636462710797791
Date: 2021-02-06T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.058407435193659
Date: 2021-02-06T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0427255867980418
Date: 2021-02-06T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.052847055485473
Date: 2021-02-06T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0488032763823871
Date: 2021-02-06T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.066383285215124
Date: 2021-02-06T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.102080771699548
Date: 2021-02-06T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.1364775588735931
Date: 2021-02-06T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.496139578637666
Date: 2021-02-06T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.131778116163332


Date: 2021-02-13T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.5399801009334602
Date: 2021-02-13T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.899626704864202
Date: 2021-02-13T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.599749704822895
Date: 2021-02-13T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.7864172866102312
Date: 2021-02-13T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.787851100089027
Date: 2021-02-13T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.8873822045279671
Date: 2021-02-13T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.85786870663287
Date: 2021-02-13T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.808224888984114
Date: 2021-02-13T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.805497026536615
Date: 2021-02-13T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.8699016452010238
Date: 2021-02-13T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.79361407129909


Date: 2021-02-20T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0428683762438589
Date: 2021-02-20T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.345573037862778
Date: 2021-02-20T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0718958722427478
Date: 2021-02-20T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.069696634076536
Date: 2021-02-20T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.076095756608993
Date: 2021-02-20T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0668855624971911
Date: 2021-02-20T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.091369320871308
Date: 2021-02-20T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.130229707807302
Date: 2021-02-20T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.165221206843853
Date: 2021-02-20T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.512415464036168
Date: 2021-02-20T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.1386189791955983


Date: 2021-02-27T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.520514840842224
Date: 2021-02-27T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.792630134150386
Date: 2021-02-27T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.508085548295639
Date: 2021-02-27T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.678144165780395
Date: 2021-02-27T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.7014036468171958
Date: 2021-02-27T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.874733196018496
Date: 2021-02-27T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.735309199983022
Date: 2021-02-27T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.867590845562518
Date: 2021-02-27T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.863800660939889
Date: 2021-02-27T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.826026482565795
Date: 2021-02-27T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.714324082175154


Date: 2021-03-06T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.076624943641945
Date: 2021-03-06T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.4371782443486159
Date: 2021-03-06T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.036107676336541
Date: 2021-03-06T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.075142879039048
Date: 2021-03-06T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0859565563587241
Date: 2021-03-06T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.1101805057842289
Date: 2021-03-06T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.102741542039439
Date: 2021-03-06T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.098538235295565
Date: 2021-03-06T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.2572668287903073
Date: 2021-03-06T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.538598868384726
Date: 2021-03-06T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.138954167243355


Date: 2021-03-13T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.4515349442372112
Date: 2021-03-13T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.787322340183891
Date: 2021-03-13T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.397368799312971
Date: 2021-03-13T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.508460850454866
Date: 2021-03-13T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.488114488223802
Date: 2021-03-13T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.6457971034978989
Date: 2021-03-13T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.565767598163805
Date: 2021-03-13T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.7329235221259291
Date: 2021-03-13T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.7566263902699557
Date: 2021-03-13T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.733624317683283
Date: 2021-03-13T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.5498134753997888


Date: 2021-03-20T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0496560588944712
Date: 2021-03-20T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.332360357278957
Date: 2021-03-20T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.035339260619367
Date: 2021-03-20T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.049115591624286
Date: 2021-03-20T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0581880433601318
Date: 2021-03-20T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0943771747406568
Date: 2021-03-20T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0740876373602068
Date: 2021-03-20T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0814038724638522
Date: 2021-03-20T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.308035437017679
Date: 2021-03-20T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.474692327261435
Date: 2021-03-20T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.107417722188983


Date: 2021-03-27T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.31809628161136
Date: 2021-03-27T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.610995307797567
Date: 2021-03-27T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.2563065475260382
Date: 2021-03-27T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.312040869932388
Date: 2021-03-27T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.285754758311668
Date: 2021-03-27T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.395995582643081
Date: 2021-03-27T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.3941183695569639
Date: 2021-03-27T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.4899551076814528
Date: 2021-03-27T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.520552942878569
Date: 2021-03-27T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.6109034980181611
Date: 2021-03-27T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.359453095850766


Date: 2021-04-03T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.035103907081065
Date: 2021-04-03T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.266077608335764
Date: 2021-04-03T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.021841757712536
Date: 2021-04-03T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0284167272038751
Date: 2021-04-03T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.040836556028806
Date: 2021-04-03T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.058502013027466
Date: 2021-04-03T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0718039700295792
Date: 2021-04-03T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.102306937333196
Date: 2021-04-03T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.200865786755457
Date: 2021-04-03T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.3041975793894358
Date: 2021-04-03T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.072581234046083


Date: 2021-04-10T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.2254329362767749
Date: 2021-04-10T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.4828667128458621
Date: 2021-04-10T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.198463965178237
Date: 2021-04-10T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.17825443507172
Date: 2021-04-10T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.1466798593028211
Date: 2021-04-10T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.2036017672071462
Date: 2021-04-10T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.192632416903508
Date: 2021-04-10T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.2568726042518379
Date: 2021-04-10T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.350748853175899
Date: 2021-04-10T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.368306831136579
Date: 2021-04-10T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.213546475166368


Date: 2021-04-17T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.024707463264349
Date: 2021-04-17T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.222345305141062
Date: 2021-04-17T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.012308773584663
Date: 2021-04-17T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0135910176322789
Date: 2021-04-17T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.018825402265066
Date: 2021-04-17T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.030380019336008
Date: 2021-04-17T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.044107125548181
Date: 2021-04-17T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.038996905786918
Date: 2021-04-17T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.119222289184109
Date: 2021-04-17T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.146072696865304
Date: 2021-04-17T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.041098424329903


Date: 2021-04-24T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.2378015564172522
Date: 2021-04-24T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.368921396730003
Date: 2021-04-24T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.188725271684235
Date: 2021-04-24T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.151928501582006
Date: 2021-04-24T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0975585307751319
Date: 2021-04-24T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.1250911366660141
Date: 2021-04-24T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.1096166734350832
Date: 2021-04-24T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.119979472729029
Date: 2021-04-24T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.224125604785514
Date: 2021-04-24T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.2329478063038561
Date: 2021-04-24T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.1560076183623091


Date: 2021-05-01T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.017270936310522
Date: 2021-05-01T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.1248320961603868
Date: 2021-05-01T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0328996658790859
Date: 2021-05-01T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.004042057553306
Date: 2021-05-01T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0144780013652042
Date: 2021-05-01T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0243406309746201
Date: 2021-05-01T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0458106934674989
Date: 2021-05-01T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.008269051788375
Date: 2021-05-01T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.034496936015785
Date: 2021-05-01T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0780351187568151
Date: 2021-05-01T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.030553303279702


Date: 2021-05-08T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 2.0591676906915373
Date: 2021-05-08T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.9834082429879363
Date: 2021-05-08T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 2.0148486933903778
Date: 2021-05-08T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 2.0174657625029804
Date: 2021-05-08T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.981930408612242
Date: 2021-05-08T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.998685064259917
Date: 2021-05-08T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.943459406029433
Date: 2021-05-08T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.9880801143590352
Date: 2021-05-08T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 2.00062782378518
Date: 2021-05-08T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.9394797735149019
Date: 2021-05-08T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.9895962969385441


Date: 2021-05-15T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.916058349306696
Date: 2021-05-15T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.8818276466336121
Date: 2021-05-15T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.9481331806164222
Date: 2021-05-15T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.9508761454490011
Date: 2021-05-15T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.9447665778570808
Date: 2021-05-15T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.952139221102696
Date: 2021-05-15T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.909751700703056
Date: 2021-05-15T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.9334558765403922
Date: 2021-05-15T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.8552122412947951
Date: 2021-05-15T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.875826534349472
Date: 2021-05-15T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.9284353608782099


Date: 2021-05-22T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 2.098543783911735
Date: 2021-05-22T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.969154443300796
Date: 2021-05-22T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 2.0588726428031823
Date: 2021-05-22T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 2.034712581487838
Date: 2021-05-22T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.9977606075408412
Date: 2021-05-22T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.99450757121667

Date: 2021-07-31T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.177163247097269
Date: 2021-07-31T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.1746681902267269
Date: 2021-07-31T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.33717579054172
Date: 2021-07-31T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.080765366050174
Date: 2021-07-31T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.094520850212573
Date: 2021-07-31T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.1567898894481912


Date: 2021-08-07T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.128993288161694
Date: 2021-08-07T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.07524733643774
Date: 2021-08-07T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.1762843919319141
Date: 2021-08-07T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.177325129477878
Date: 2021-08-07T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.14596820843394
Date: 2021-08-07T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.139754761332257
Date: 2021-08-07T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.1791644458598398
Date: 2021-08-07T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.3855572738492568
Date: 2021-08-07T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0451627003110748
Date: 2021-08-07T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.073767865219452
Date: 2021-08-07T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.1504311429137029


Date: 2021-08-14T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.122024976182728
Date: 2021-08-14T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0653239999444248
Date: 2021-08-14T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.156513517573331
Date: 2021-08-14T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.178359251587609
Date: 2021-08-14T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.135484408474439
Date: 2021-08-14T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.13277247614731
Date: 2021-08-14T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.164840441104901
Date: 2021-08-14T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.387946206551875
Date: 2021-08-14T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.057306514504831
Date: 2021-08-14T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.061735444434815
Date: 2021-08-14T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.138213699869085


Date: 2021-08-21T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.01035935030086
Date: 2021-08-21T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.009077507362236
Date: 2021-08-21T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0091555914259511
Date: 2021-08-21T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.004015384620287
Date: 2021-08-21T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.010407764770206
Date: 2021-08-21T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.006363910128129
Date: 2021-08-21T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0101581418712149
Date: 2021-08-21T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.008945758454502
Date: 2021-08-21T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.005570332810748
Date: 2021-08-21T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.014730058406712
Date: 2021-08-21T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.00962578439521


Date: 2021-08-28T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.010414770338685
Date: 2021-08-28T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.006153500246001
Date: 2021-08-28T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.014806595339905
Date: 2021-08-28T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.006335083424346
Date: 2021-08-28T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.010129527974639
Date: 2021-08-28T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0108239104738461
Date: 2021-08-28T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0203233279316921
Date: 2021-08-28T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.012988951239093
Date: 2021-08-28T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.007061610660458
Date: 2021-08-28T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.013079884229228
Date: 2021-08-28T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.011994617689196


Date: 2021-09-04T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.004671138303821
Date: 2021-09-04T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.00216642068699
Date: 2021-09-04T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0102251298085312
Date: 2021-09-04T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.001558788695546
Date: 2021-09-04T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.009560119477101
Date: 2021-09-04T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.007885837578215
Date: 2021-09-04T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.005261108679408
Date: 2021-09-04T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0041189400835728
Date: 2021-09-04T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.004921002138872
Date: 2021-09-04T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.011044008468161
Date: 2021-09-04T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.007121250257115


Date: 2021-09-11T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.001607865394987
Date: 2021-09-11T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0035343974456792
Date: 2021-09-11T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0100528970662261
Date: 2021-09-11T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.005240205755001
Date: 2021-09-11T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0060150971783712
Date: 2021-09-11T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.005919594557431
Date: 2021-09-11T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.005883986751269
Date: 2021-09-11T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0044911181321359
Date: 2021-09-11T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.007982900896082
Date: 2021-09-11T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.010492473972707
Date: 2021-09-11T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.006285623061842


Date: 2021-09-18T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.002588595903945
Date: 2021-09-18T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0011568350601021
Date: 2021-09-18T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0087876957841222
Date: 2021-09-18T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.002821307105477
Date: 2021-09-18T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.006329482152069
Date: 2021-09-18T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.007039832111331
Date: 2021-09-18T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.007733303442364
Date: 2021-09-18T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.004146612249314
Date: 2021-09-18T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.003391425212613
Date: 2021-09-18T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.007798711696524
Date: 2021-09-18T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.0058932143215318


Date: 2021-09-25T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0003405738328122
Date: 2021-09-25T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000598169916536
Date: 2021-09-25T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.002759883257375
Date: 2021-09-25T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000451290129426
Date: 2021-09-25T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0020605785437249
Date: 2021-09-25T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.000246493754461
Date: 2021-09-25T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0004251166694058
Date: 2021-09-25T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000010133306837
Date: 2021-09-25T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0009258640631709
Date: 2021-09-25T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0026986158482138
Date: 2021-09-25T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.001185380370055


Date: 2021-10-02T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000038151959992
Date: 2021-10-02T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0029745654541
Date: 2021-10-02T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000269569043299
Date: 2021-10-02T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000716907355597
Date: 2021-10-02T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000339381651059
Date: 2021-10-02T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.001381015201963
Date: 2021-10-02T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000311010727899
Date: 2021-10-02T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000804499539937
Date: 2021-10-02T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000777622680952
Date: 2021-10-02T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0018185899768761
Date: 2021-10-02T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.00092844718508


Date: 2021-10-09T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0003399856959738
Date: 2021-10-09T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0026646809928939
Date: 2021-10-09T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000272727238553
Date: 2021-10-09T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0002530906658649
Date: 2021-10-09T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000325885619533
Date: 2021-10-09T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0008718650406088
Date: 2021-10-09T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000883776501721
Date: 2021-10-09T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000018475809156
Date: 2021-10-09T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.001676508310766
Date: 2021-10-09T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.002005919626754
Date: 2021-10-09T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.0007945961197031


Date: 2021-10-16T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0001479570137242
Date: 2021-10-16T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.001576175769513
Date: 2021-10-16T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0005491854367379
Date: 2021-10-16T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000698983394614
Date: 2021-10-16T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000920186230349
Date: 2021-10-16T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.000966974233961
Date: 2021-10-16T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000885599847152
Date: 2021-10-16T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000011504854456
Date: 2021-10-16T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0020190403475908
Date: 2021-10-16T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.001814620145523
Date: 2021-10-16T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.0008883731525209


Date: 2021-10-23T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000001511763343
Date: 2021-10-23T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.001385673307596
Date: 2021-10-23T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.001242805492779
Date: 2021-10-23T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0000033590702049
Date: 2021-10-23T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000495740636325
Date: 2021-10-23T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0008544461184101
Date: 2021-10-23T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000002364528427
Date: 2021-10-23T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000005308266962
Date: 2021-10-23T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.002375942655248
Date: 2021-10-23T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0017265081977489
Date: 2021-10-23T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.0008060018640208


Date: 2021-10-30T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000000714168096
Date: 2021-10-30T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.001484826081878
Date: 2021-10-30T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0005713920456851
Date: 2021-10-30T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000356533377157
Date: 2021-10-30T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0005484857161941
Date: 2021-10-30T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.001293959388477
Date: 2021-10-30T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000355755975534
Date: 2021-10-30T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000535956468382
Date: 2021-10-30T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.00187606295981
Date: 2021-10-30T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0026226901759971
Date: 2021-10-30T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.001095902676637


Date: 2021-11-06T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000000002793968
Date: 2021-11-06T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000955674040597
Date: 2021-11-06T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.001373310340568
Date: 2021-11-06T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000271695753326
Date: 2021-11-06T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0007514620665459
Date: 2021-11-06T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.000398457486881
Date: 2021-11-06T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000380963552743
Date: 2021-11-06T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.00045229398529
Date: 2021-11-06T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0032991084735852
Date: 2021-11-06T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0017867538408611
Date: 2021-11-06T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.000910770845621


Date: 2021-11-13T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.00009348866297
Date: 2021-11-13T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0007147085270849
Date: 2021-11-13T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.001685694616754
Date: 2021-11-13T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0003779984253909
Date: 2021-11-13T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.99999998981366
Date: 2021-11-13T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.001694020116702
Date: 2021-11-13T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000342656800058
Date: 2021-11-13T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000333550793584
Date: 2021-11-13T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.001003517536447
Date: 2021-11-13T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.001458207203542
Date: 2021-11-13T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.000962743873969


Date: 2021-11-20T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000582708053118
Date: 2021-11-20T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000011641532
Date: 2021-11-20T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0007747976342218
Date: 2021-11-20T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000014901161
Date: 2021-11-20T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999970546923
Date: 2021-11-20T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.001319769071415
Date: 2021-11-20T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000018626451
Date: 2021-11-20T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.001406102441252
Date: 2021-11-20T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000000012019883
Date: 2021-11-20T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.001368218901916
Date: 2021-11-20T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.0006752333017621


Date: 2021-11-27T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999876745279
Date: 2021-11-27T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.001564210513606
Date: 2021-11-27T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000015017576
Date: 2021-11-27T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999727588149
Date: 2021-11-27T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000537609041202
Date: 2021-11-27T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.002240506611998
Date: 2021-11-27T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.001183054526336
Date: 2021-11-27T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.00000001268927
Date: 2021-11-27T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999993946404
Date: 2021-11-27T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.001717121434922
Date: 2021-11-27T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.001055304011969


Date: 2021-12-04T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000156808479916
Date: 2021-12-04T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000539098823537
Date: 2021-12-04T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000451537169738
Date: 2021-12-04T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000380790384043
Date: 2021-12-04T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000173780789738
Date: 2021-12-04T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0006770934778622
Date: 2021-12-04T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000137220135912
Date: 2021-12-04T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0002083874111352
Date: 2021-12-04T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000824944138003
Date: 2021-12-04T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0023840715002732
Date: 2021-12-04T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.000656226869977



Date: 2022-02-19T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.999999984633177
Date: 2022-02-19T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.999999997089617
Date: 2022-02-19T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.00000000061118
Date: 2022-02-19T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000010360964
Date: 2022-02-19T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000000014348188
Date: 2022-02-19T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.000000003346941
Date: 2022-02-19T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000005908077
Date: 2022-02-19T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999906867739
Date: 2022-02-19T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999976949766
Date: 2022-02-19T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000020285369
Date: 2022-02-19T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.9999999793581069


Date: 2022-02-26T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000000008265488
Date: 2022-02-26T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.999999974563252
Date: 2022-02-26T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000312284112
Date: 2022-02-26T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999991501681
Date: 2022-02-26T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999858264339
Date: 2022-02-26T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.999999998020939
Date: 2022-02-26T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.999999972176738
Date: 2022-02-26T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000000028405339
Date: 2022-02-26T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999975552783
Date: 2022-02-26T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.999999989347999
Date: 2022-02-26T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.000000023072063


Date: 2022-03-05T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000000023399479
Date: 2022-03-05T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.999999998137355
Date: 2022-03-05T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999732244749
Date: 2022-03-05T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999995052349
Date: 2022-03-05T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999973777448
Date: 2022-03-05T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.999999979510903
Date: 2022-03-05T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000035506673
Date: 2022-03-05T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000000030267984
Date: 2022-03-05T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999870778989
Date: 2022-03-05T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.999999991501682
Date: 2022-03-05T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.0000000210711728


Date: 2022-03-12T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.999999962834409
Date: 2022-03-12T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000014668331
Date: 2022-03-12T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.999999996565749
Date: 2022-03-12T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000010710209
Date: 2022-03-12T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999994994141
Date: 2022-03-12T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000097788861
Date: 2022-03-12T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000029802323
Date: 2022-03-12T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000009
Date: 2022-03-12T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.99999997910345
Date: 2022-03-12T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000014901161
Date: 2022-03-12T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.0000000300933611


Date: 2022-03-19T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999948195181
Date: 2022-03-19T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999961582939
Date: 2022-03-19T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000019063008
Date: 2022-03-19T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999998137354
Date: 2022-03-19T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999970896171
Date: 2022-03-19T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999700812611
Date: 2022-03-19T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000029802322
Date: 2022-03-19T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.999999978579581
Date: 2022-03-19T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000000010826624
Date: 2022-03-19T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000001309672
Date: 2022-03-19T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999982654117


Date: 2022-03-26T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.999999987077899
Date: 2022-03-26T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000013969839
Date: 2022-03-26T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000025494956
Date: 2022-03-26T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999975494575
Date: 2022-03-26T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000000020489097
Date: 2022-03-26T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.000000024912879
Date: 2022-03-26T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000046566129
Date: 2022-03-26T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000000002328305
Date: 2022-03-26T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000000003376043
Date: 2022-03-26T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000016763807
Date: 2022-03-26T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.000000021100278


Date: 2022-04-02T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999715946619
Date: 2022-04-02T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.999999978695996
Date: 2022-04-02T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.999999996391125
Date: 2022-04-02T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999975843821
Date: 2022-04-02T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999715946619
Date: 2022-04-02T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.999999962979926
Date: 2022-04-02T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999977881089
Date: 2022-04-02T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.999999962048604
Date: 2022-04-02T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999962747099
Date: 2022-04-02T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000009953509
Date: 2022-04-02T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999995598045


Date: 2022-04-09T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000000003492458
Date: 2022-04-09T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999785795809
Date: 2022-04-09T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000012514647
Date: 2022-04-09T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.00000002644083
Date: 2022-04-09T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999891733742
Date: 2022-04-09T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999747378752
Date: 2022-04-09T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000023748726
Date: 2022-04-09T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000000001164153
Date: 2022-04-09T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999989988282
Date: 2022-04-09T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999921856221
Date: 2022-04-09T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999978725101


Date: 2022-04-16T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000000021318556
Date: 2022-04-16T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000019208521
Date: 2022-04-16T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000010375516
Date: 2022-04-16T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0000000270083549
Date: 2022-04-16T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999972264051
Date: 2022-04-16T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.000000019557774
Date: 2022-04-16T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000018859283
Date: 2022-04-16T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.999999985098839
Date: 2022-04-16T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999990453944
Date: 2022-04-16T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000027081114
Date: 2022-04-16T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999975872924


Date: 2022-04-23T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.999999987951016
Date: 2022-04-23T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999724095681
Date: 2022-04-23T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000077998261
Date: 2022-04-23T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000028463547
Date: 2022-04-23T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000000019237632
Date: 2022-04-23T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.00000001816079
Date: 2022-04-23T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000000349245
Date: 2022-04-23T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999962165029
Date: 2022-04-23T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999982188456
Date: 2022-04-23T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999757856131
Date: 2022-04-23T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.000000007392372


Date: 2022-04-30T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999656574798
Date: 2022-04-30T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000025611371
Date: 2022-04-30T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000376894609
Date: 2022-04-30T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000003259629
Date: 2022-04-30T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999977531844
Date: 2022-04-30T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000047730269
Date: 2022-04-30T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.999999971245415
Date: 2022-04-30T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999967403701
Date: 2022-04-30T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000267755231
Date: 2022-04-30T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0000000211875881
Date: 2022-04-30T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999994819518


Date: 2022-05-07T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.999999991327059
Date: 2022-05-07T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000024447217
Date: 2022-05-07T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000017229469
Date: 2022-05-07T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999995226971
Date: 2022-05-07T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999992724043
Date: 2022-05-07T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.999999978026608
Date: 2022-05-07T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.999999983119779
Date: 2022-05-07T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.999999984225723
Date: 2022-05-07T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999979045243
Date: 2022-05-07T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000004947651
Date: 2022-05-07T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.000000006344635


Date: 2022-05-14T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.999999991618096
Date: 2022-05-14T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000024563634
Date: 2022-05-14T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.999999961277354
Date: 2022-05-14T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999770661829
Date: 2022-05-14T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000000020430888
Date: 2022-05-14T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999769206631
Date: 2022-05-14T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999998253759
Date: 2022-05-14T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.999999997555278
Date: 2022-05-14T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000000033352991
Date: 2022-05-14T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0000000021245792
Date: 2022-05-14T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.9999999928404579


Date: 2022-05-21T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999960418791
Date: 2022-05-21T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.999999988795027
Date: 2022-05-21T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000017171261
Date: 2022-05-21T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.00000001222361
Date: 2022-05-21T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.99999997249688
Date: 2022-05-21T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.000000003841706
Date: 2022-05-21T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999913852671
Date: 2022-05-21T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000000007334164
Date: 2022-05-21T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999942956481
Date: 2022-05-21T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000011059456
Date: 2022-05-21T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.9999999947322071


Date: 2022-05-28T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000000016298146
Date: 2022-05-28T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000011059451
Date: 2022-05-28T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.999999985273461
Date: 2022-05-28T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999992840457
Date: 2022-05-28T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999973457306
Date: 2022-05-28T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.999999999359715
Date: 2022-05-28T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.999999999417925
Date: 2022-05-28T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000258442
Date: 2022-05-28T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000000018626451
Date: 2022-05-28T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.999999997075065
Date: 2022-05-28T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.000000017433195


Date: 2022-06-04T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000000020721929
Date: 2022-06-04T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000020256265
Date: 2022-06-04T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000003085006
Date: 2022-06-04T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000000422005
Date: 2022-06-04T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999837018541
Date: 2022-06-04T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.000000034895495
Date: 2022-06-04T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000071158859
Date: 2022-06-04T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.999999984167516
Date: 2022-06-04T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999632127579
Date: 2022-06-04T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000024680048
Date: 2022-06-04T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.9999999889259921


Date: 2022-06-11T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000000028172507
Date: 2022-06-11T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000009429641
Date: 2022-06-11T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.999999999825377
Date: 2022-06-11T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000019092112
Date: 2022-06-11T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999832507469
Date: 2022-06-11T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999920255499
Date: 2022-06-11T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.999999999417924
Date: 2022-06-11T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000219442868
Date: 2022-06-11T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999994673998
Date: 2022-06-11T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.999999995809048
Date: 2022-06-11T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999998377461


Date: 2022-06-18T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.99999999080319
Date: 2022-06-18T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999823048701
Date: 2022-06-18T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.00000000768341
Date: 2022-06-18T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999907449819
Date: 2022-06-18T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999999097781
Date: 2022-06-18T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999881547419
Date: 2022-06-18T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000013038517
Date: 2022-06-18T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000093423291
Date: 2022-06-18T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999991443473
Date: 2022-06-18T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.999999993029633
Date: 2022-06-18T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999996121915


Date: 2022-06-25T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000013969839
Date: 2022-06-25T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999889405451
Date: 2022-06-25T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999966530599
Date: 2022-06-25T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000024068867
Date: 2022-06-25T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999811116149
Date: 2022-06-25T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999839637899

Date: 2022-09-03T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.99999998608837
Date: 2022-09-03T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999972875232
Date: 2022-09-03T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.99999999461579
Date: 2022-09-03T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.9999999709252712


Date: 2022-09-10T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.00000001816079
Date: 2022-09-10T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.999999977182598
Date: 2022-09-10T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999941210268
Date: 2022-09-10T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999755527831
Date: 2022-09-10T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000000008469216
Date: 2022-09-10T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.999999994528479
Date: 2022-09-10T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999798601479
Date: 2022-09-10T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000000011874364
Date: 2022-09-10T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000189756961
Date: 2022-09-10T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000007305059
Date: 2022-09-10T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.9999999698375172


Date: 2022-09-17T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.999999979976564
Date: 2022-09-17T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.999999994179233
Date: 2022-09-17T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000016996637
Date: 2022-09-17T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999965657478
Date: 2022-09-17T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999996332918
Date: 2022-09-17T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.000000022584572
Date: 2022-09-17T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000004889444
Date: 2022-09-17T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999814899639
Date: 2022-09-17T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999844585551
Date: 2022-09-17T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000017927961
Date: 2022-09-17T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.000000011314115


Date: 2022-09-24T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.99999998183921
Date: 2022-09-24T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000024039764
Date: 2022-09-24T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000011932571
Date: 2022-09-24T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000015832484
Date: 2022-09-24T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000000022817404
Date: 2022-09-24T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.000000019092111
Date: 2022-09-24T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.999999968276825
Date: 2022-09-24T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000000016822013
Date: 2022-09-24T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000000013737008
Date: 2022-09-24T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999732826831
Date: 2022-09-24T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999974686943


Date: 2022-10-01T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000057043512
Date: 2022-10-01T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000022584572
Date: 2022-10-01T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.999999996391123
Date: 2022-10-01T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000016298146
Date: 2022-10-01T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000231666468
Date: 2022-10-01T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999930732901
Date: 2022-10-01T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000016880221
Date: 2022-10-01T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.999999975785613
Date: 2022-10-01T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999985448069
Date: 2022-10-01T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.999999970197676
Date: 2022-10-01T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.0000000269792502


Date: 2022-10-08T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.99999998882413
Date: 2022-10-08T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.999999988242054
Date: 2022-10-08T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.999999989173374
Date: 2022-10-08T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0000000229338202
Date: 2022-10-08T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999980907888
Date: 2022-10-08T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999918509259
Date: 2022-10-08T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.999999982770533
Date: 2022-10-08T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999809078871
Date: 2022-10-08T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999977764672
Date: 2022-10-08T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000023865141
Date: 2022-10-08T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.00000000333239


Date: 2022-10-15T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.000000028754584
Date: 2022-10-15T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.999999983003363
Date: 2022-10-15T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000009487848
Date: 2022-10-15T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0000000173458832
Date: 2022-10-15T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999977531843
Date: 2022-10-15T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.000000024330802
Date: 2022-10-15T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.999999996740371
Date: 2022-10-15T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.999999992316588
Date: 2022-10-15T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000199070191
Date: 2022-10-15T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000013387763
Date: 2022-10-15T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.000000015003025


Date: 2022-10-22T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.999999978113919
Date: 2022-10-22T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.999999974388627
Date: 2022-10-22T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000009895304
Date: 2022-10-22T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000011816156
Date: 2022-10-22T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999774154299
Date: 2022-10-22T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999708961691
Date: 2022-10-22T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000020489097
Date: 2022-10-22T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000000014202669
Date: 2022-10-22T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999767169351
Date: 2022-10-22T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.999999993946403
Date: 2022-10-22T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999985862813


Date: 2022-10-29T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000053551041
Date: 2022-10-29T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000028638169
Date: 2022-10-29T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.999999993247913
Date: 2022-10-29T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999789288271
Date: 2022-10-29T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000076543072
Date: 2022-10-29T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999758729249
Date: 2022-10-29T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999763676889
Date: 2022-10-29T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999860301629
Date: 2022-10-29T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000000000000002
Date: 2022-10-29T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.999999977648258
Date: 2022-10-29T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.9999999884894348


Date: 2022-11-05T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999857973321
Date: 2022-11-05T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000016298146
Date: 2022-11-05T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999991559869
Date: 2022-11-05T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000010681108
Date: 2022-11-05T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999990686774
Date: 2022-11-05T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999962165019
Date: 2022-11-05T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999908031899
Date: 2022-11-05T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000000001164153
Date: 2022-11-05T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999970081261
Date: 2022-11-05T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999913852661
Date: 2022-11-05T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999992336597


Date: 2022-11-12T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.999999995459803
Date: 2022-11-12T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000000931325
Date: 2022-11-12T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.00000000145519
Date: 2022-11-12T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999991152436
Date: 2022-11-12T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.00000001047738
Date: 2022-11-12T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000084983172
Date: 2022-11-12T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000019790605
Date: 2022-11-12T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000000028871001
Date: 2022-11-12T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000000021304003
Date: 2022-11-12T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.999999997409758
Date: 2022-11-12T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.00000000135333


Date: 2022-11-19T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999846331771
Date: 2022-11-19T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000004656608
Date: 2022-11-19T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000039581198
Date: 2022-11-19T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999986437614
Date: 2022-11-19T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000000002066372
Date: 2022-11-19T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.00000000046566
Date: 2022-11-19T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.999999987892809
Date: 2022-11-19T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.999999999534338
Date: 2022-11-19T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000000010477381
Date: 2022-11-19T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999883002589
Date: 2022-11-19T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999992436641


Date: 2022-11-26T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000137370082
Date: 2022-11-26T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000139698402
Date: 2022-11-26T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000007275959
Date: 2022-11-26T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999997438863
Date: 2022-11-26T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000137079041
Date: 2022-11-26T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.000000011263181
Date: 2022-11-26T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000003492459
Date: 2022-11-26T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.999999986554031
Date: 2022-11-26T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000183936222
Date: 2022-11-26T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000002095475
Date: 2022-11-26T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999988151104


Date: 2022-12-03T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000180443769
Date: 2022-12-03T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000003725291
Date: 2022-12-03T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000016996638
Date: 2022-12-03T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999912106421
Date: 2022-12-03T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000000014144462
Date: 2022-12-03T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000127183728
Date: 2022-12-03T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999965657481
Date: 2022-12-03T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.999999995459802
Date: 2022-12-03T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.99999999301508
Date: 2022-12-03T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.999999977415429
Date: 2022-12-03T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999998723067


Date: 2022-12-10T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.00000001268927
Date: 2022-12-10T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999972060301
Date: 2022-12-10T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000026775542
Date: 2022-12-10T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0000000145519161
Date: 2022-12-10T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999832361941
Date: 2022-12-10T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.999999982770533
Date: 2022-12-10T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999918509271
Date: 2022-12-10T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000023283078
Date: 2022-12-10T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.999999991152436
Date: 2022-12-10T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000023283063
Date: 2022-12-10T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999974501407


Date: 2022-12-17T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999990707731
Date: 2022-12-17T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.000000006726737
Date: 2022-12-17T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.000000016135781
Date: 2022-12-17T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0000000078738789
Date: 2022-12-17T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.000000003538148
Date: 2022-12-17T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999765689289
Date: 2022-12-17T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.99999998491775
Date: 2022-12-17T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999944701301
Date: 2022-12-17T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000123129251
Date: 2022-12-17T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999826029801
Date: 2022-12-17T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 1.0000000130182531


Date: 2022-12-24T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.999999984978922
Date: 2022-12-24T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.999999994015227
Date: 2022-12-24T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000220713479
Date: 2022-12-24T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.999999993523198
Date: 2022-12-24T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999994237421
Date: 2022-12-24T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.999999988848202
Date: 2022-12-24T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.000000020722341
Date: 2022-12-24T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999962189889
Date: 2022-12-24T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000000010098255
Date: 2022-12-24T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.000000004844142
Date: 2022-12-24T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.9999999977708369


Date: 2022-12-31T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999923211951
Date: 2022-12-31T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.999999985908591
Date: 2022-12-31T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999948850089
Date: 2022-12-31T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.000000004493499
Date: 2022-12-31T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.999999995528983
Date: 2022-12-31T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.00000001273085
Date: 2022-12-31T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.999999995063217
Date: 2022-12-31T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.000000006003112
Date: 2022-12-31T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.000000002375425
Date: 2022-12-31T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.999999998002108
Date: 2022-12-31T00:00:00.000000000, Region: USA, Total Sum of Normalized Shares 0.999999980228486

### For each date, for each HHS region, take the latest `published_date` if there are duplicates of a variant

In [10]:
for date in unique_dates:
    df_segmented_by_date = df_imputed_select[df_imputed_select["date"] == date]
    for region in pd.unique(df_segmented_by_date["hhs_region"]):
        df_segmented_by_date_and_region = df_segmented_by_date[df_segmented_by_date["hhs_region"]==region]
        sum_of_variant_shares = df_segmented_by_date_and_region["normalized_share"].sum()
        print("Date: {}, Region: {}, Total Sum of Normalized Shares {}".format(date, region, sum_of_variant_shares))
    print("\n")

Date: 2021-01-02T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-01-02T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-01-02T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-01-02T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-01-02T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-01-02T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-01-02T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-01-02T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-01-02T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-01-02T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-01-16T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-01-16T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-01-16T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-01-16T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-01-16T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-01-16T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-01-16T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-01-16T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-01-16T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-01-16T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2021-01-30T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-01-30T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-01-30T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-01-30T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-01-30T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-01-30T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-01-30T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-01-30T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-01-30T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-01-30T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-02-06T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-02-06T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-02-06T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-02-06T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-02-06T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-02-06T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-02-06T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-02-06T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-02-06T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-02-06T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-02-13T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-02-13T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-02-13T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-02-13T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-02-13T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-02-13T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-02-13T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-02-13T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-02-13T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-02-13T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0000000000000002


Date: 2021-02-20T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-02-20T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-02-20T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-02-20T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-02-20T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-02-20T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-02-20T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-02-20T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-02-20T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-02-20T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2021-02-27T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-02-27T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-02-27T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-02-27T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-02-27T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-02-27T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-02-27T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-02-27T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-02-27T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-02-27T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-03-06T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-03-06T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-03-06T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-03-06T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-03-06T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-03-06T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-03-06T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-03-06T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-03-06T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-03-06T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0000000000000002


Date: 2021-03-13T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-03-13T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-03-13T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-03-13T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-03-13T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-03-13T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-03-13T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-03-13T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-03-13T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-03-13T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-03-20T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-03-20T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-03-20T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-03-20T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-03-20T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-03-20T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-03-20T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-03-20T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-03-20T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-03-20T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2021-03-27T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-03-27T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-03-27T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-03-27T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-03-27T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-03-27T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-03-27T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-03-27T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-03-27T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-03-27T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-04-03T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-04-03T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-04-03T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-04-03T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-04-03T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-04-03T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-04-03T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-04-03T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-04-03T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-04-03T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0

Date: 2021-04-10T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-04-10T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-04-10T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-04-10T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-04-10T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-04-10T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-04-10T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-04-10T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-04-10T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-04-10T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-04-17T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-04-17T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-04-17T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-04-17T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-04-17T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-04-17T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-04-17T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-04-17T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-04-17T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-04-17T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2021-04-24T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-04-24T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-04-24T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-04-24T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-04-24T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-04-24T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-04-24T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-04-24T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-04-24T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-04-24T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-05-01T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-05-01T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-05-01T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-05-01T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-05-01T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-05-01T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-05-01T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-05-01T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-05-01T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-05-01T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999998


Date: 2021-05-08T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-05-08T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-05-08T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-05-08T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-05-08T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-05-08T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-05-08T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-05-08T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-05-08T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-05-08T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-05-15T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-05-15T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-05-15T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-05-15T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-05-15T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-05-15T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-05-15T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-05-15T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-05-15T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-05-15T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-05-22T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-05-22T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-05-22T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-05-22T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-05-22T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-05-22T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-05-22T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-05-22T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-05-22T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-05-22T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2021-05-29T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-05-29T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-05-29T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-05-29T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-05-29T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-05-29T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-05-29T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-05-29T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-05-29T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-05-29T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-06-05T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-06-05T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-06-05T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-06-05T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-06-05T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-06-05T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-06-05T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-06-05T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-06-05T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-06-05T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-06-12T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-06-12T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-06-12T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-06-12T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-06-12T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-06-12T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-06-12T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-06-12T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-06-12T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-06-12T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-06-19T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-06-19T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-06-19T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-06-19T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-06-19T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-06-19T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-06-19T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-06-19T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-06-19T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-06-19T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-06-26T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-06-26T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-06-26T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-06-26T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-06-26T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-06-26T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-06-26T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-06-26T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-06-26T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-06-26T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-07-03T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-07-03T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-07-03T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-07-03T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-07-03T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-07-03T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-07-03T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-07-03T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-07-03T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-07-03T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-07-10T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-07-10T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-07-10T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-07-10T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-07-10T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-07-10T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-07-10T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-07-10T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-07-10T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-07-10T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-07-17T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-07-17T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-07-17T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-07-17T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-07-17T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-07-17T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-07-17T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-07-17T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-07-17T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-07-17T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-07-24T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-07-24T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-07-24T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-07-24T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-07-24T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-07-24T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-07-24T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-07-24T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-07-24T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-07-24T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-07-31T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-07-31T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-07-31T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-07-31T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-07-31T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-07-31T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-07-31T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-07-31T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-07-31T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-07-31T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-08-07T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-08-07T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-08-07T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-08-07T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-08-07T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-08-07T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-08-07T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-08-07T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-08-07T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-08-07T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-08-14T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-08-14T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-08-14T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-08-14T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-08-14T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-08-14T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-08-14T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-08-14T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-08-14T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-08-14T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2021-08-21T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-08-21T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-08-21T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-08-21T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-08-21T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-08-21T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-08-21T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-08-21T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-08-21T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-08-21T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2021-08-28T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-08-28T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-08-28T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-08-28T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999

Date: 2021-08-28T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-08-28T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-08-28T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-08-28T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-08-28T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-08-28T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0000000000000002


Date: 2021-09-04T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-09-04T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-09-04T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-09-04T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-09-04T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-09-04T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-09-04T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-09-04T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-09-04T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-09-04T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0000000000000002


Date: 2021-09-11T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-09-11T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-09-11T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-09-11T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-09-11T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-09-11T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-09-11T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-09-11T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-09-11T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-09-11T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-09-18T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-09-18T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-09-18T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-09-18T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-09-18T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-09-18T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-09-18T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-09-18T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-09-18T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-09-18T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0000000000000002


Date: 2021-09-25T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-09-25T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-09-25T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-09-25T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-09-25T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-09-25T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-09-25T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-09-25T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-09-25T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-09-25T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-10-02T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-10-02T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-02T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-10-02T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-10-02T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-02T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-02T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-02T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-10-02T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-10-02T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2021-10-09T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-10-09T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-10-09T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-10-09T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-10-09T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-10-09T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-10-09T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-09T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-10-09T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-10-09T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-10-16T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-16T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-16T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-10-16T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-16T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-10-16T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-16T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-10-16T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-10-16T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-10-16T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-10-23T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-10-23T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-23T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-23T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-10-23T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-23T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-23T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-10-23T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-23T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-10-23T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-10-30T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-10-30T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-30T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-10-30T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-10-30T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-30T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-10-30T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-10-30T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-10-30T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-10-30T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999998


Date: 2021-11-06T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-11-06T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-11-06T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-11-06T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-11-06T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-11-06T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-11-06T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-11-06T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-11-06T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-11-06T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2021-11-13T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-11-13T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-11-13T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-11-13T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-11-13T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-11-13T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-11-13T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-11-13T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-11-13T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-11-13T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2021-11-20T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-11-20T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000000000002

Date: 2021-11-20T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-11-20T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-11-20T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-11-20T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-11-20T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-11-20T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-11-20T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-11-20T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-11-27T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-11-27T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-11-27T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-11-27T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-11-27T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-11-27T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-11-27T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-11-27T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-11-27T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-11-27T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2021-12-04T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-12-04T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-12-04T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-12-04T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2021-12-04T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-12-04T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-12-04T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-12-04T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-12-04T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-12-04T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999998


Date: 2021-12-11T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-12-11T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-12-11T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-12-11T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0000000000000002
Date: 2021-12-11T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-12-11T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-12-11T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-12-11T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-12-11T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-12-11T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2021-12-18T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-12-18T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-12-18T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-12-18T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-12-18T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-12-18T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-12-18T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-12-18T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-12-18T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2021-12-18T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2021-12-25T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2021-12-25T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2021-12-25T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2021-12-25T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2021-12-25T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2021-12-25T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2021-12-25T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2021-12-25T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2021-12-25T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999998
Date: 2021-12-25T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-01-01T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-01-01T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-01-01T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-01-01T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-01-01T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-01-01T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-01-01T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-01-01T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-01-01T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-01-01T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-01-08T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-01-08T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-01-08T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-01-08T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-01-08T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-01-08T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-01-08T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-01-08T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-01-08T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-01-08T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-01-15T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-01-15T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-01-15T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-01-15T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-01-15T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-01-15T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-01-15T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-01-15T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-01-15T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-01-15T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-01-22T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-01-22T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-01-22T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-01-22T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-01-22T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-01-22T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-01-22T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-01-22T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-01-22T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-01-22T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-01-29T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-01-29T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-01-29T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-01-29T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-01-29T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-01-29T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-01-29T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-01-29T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-01-29T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-01-29T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-02-05T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-02-05T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-02-05T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-02-05T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-02-05T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-02-05T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-02-05T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-02-05T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-02-05T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-02-05T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-02-12T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-02-12T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-02-12T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-02-12T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-02-12T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-02-12T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-02-12T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-02-12T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-02-12T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-02-12T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-02-19T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-02-19T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-02-19T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-02-19T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-02-19T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-02-19T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-02-19T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-02-19T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-02-19T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-02-19T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-02-26T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-02-26T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-02-26T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-02-26T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-02-26T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-02-26T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-02-26T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-02-26T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-02-26T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-02-26T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-03-05T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-03-05T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-03-05T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-03-05T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-03-05T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-03-05T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-03-05T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-03-05T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-03-05T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-03-05T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-03-12T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-03-12T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-03-12T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-03-12T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-03-12T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-03-12T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-03-12T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-03-12T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-03-12T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-03-12T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-03-19T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-03-19T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-03-19T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-03-19T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-03-19T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-03-19T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-03-19T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-03-19T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-03-19T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-03-19T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-03-26T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-03-26T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-03-26T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-03-26T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-03-26T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-03-26T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-03-26T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-03-26T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-03-26T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-03-26T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-04-02T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-04-02T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-04-02T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-04-02T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-04-02T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-04-02T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-04-02T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-04-02T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-04-02T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-04-02T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-04-09T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-04-09T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-04-09T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-04-09T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-04-09T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-04-09T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-04-09T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-04-09T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-04-09T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0

Date: 2022-04-09T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-04-16T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-04-16T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-04-16T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-04-16T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-04-16T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-04-16T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-04-16T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-04-16T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-04-16T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-04-16T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-04-23T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-04-23T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-04-23T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-04-23T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-04-23T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-04-23T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-04-23T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-04-23T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-04-23T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-04-23T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-04-30T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-04-30T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-04-30T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-04-30T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-04-30T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-04-30T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-04-30T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-04-30T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-04-30T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-04-30T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999998


Date: 2022-05-07T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-05-07T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-05-07T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-05-07T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-05-07T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-05-07T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-05-07T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-05-07T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-05-07T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-05-07T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-05-14T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-05-14T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-05-14T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-05-14T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-05-14T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-05-14T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-05-14T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-05-14T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-05-14T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-05-14T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999998


Date: 2022-05-21T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-05-21T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-05-21T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-05-21T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-05-21T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-05-21T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-05-21T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-05-21T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-05-21T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-05-21T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-05-28T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-05-28T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-05-28T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-05-28T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-05-28T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-05-28T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-05-28T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-05-28T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-05-28T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-05-28T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-06-04T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-06-04T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-06-04T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-06-04T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-06-04T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-06-04T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-06-04T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-06-04T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-06-04T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-06-04T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-06-11T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-06-11T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-06-11T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-06-11T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-06-11T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-06-11T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-06-11T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-06-11T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-06-11T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-06-11T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-06-18T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-06-18T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-06-18T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-06-18T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-06-18T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-06-18T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-06-18T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-06-18T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-06-18T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-06-18T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-06-25T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-06-25T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-06-25T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-06-25T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-06-25T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-06-25T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-06-25T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-06-25T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-06-25T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-06-25T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-07-02T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-07-02T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-07-02T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-07-02T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-07-02T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-07-02T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0

Date: 2022-07-02T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-07-02T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-07-02T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-07-02T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-07-09T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-07-09T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-07-09T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-07-09T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-07-09T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-07-09T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-07-09T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-07-09T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-07-09T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-07-09T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-07-16T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-07-16T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-07-16T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-07-16T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-07-16T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-07-16T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-07-16T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-07-16T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-07-16T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-07-16T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-07-23T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-07-23T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-07-23T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-07-23T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-07-23T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-07-23T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-07-23T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-07-23T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-07-23T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-07-23T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-07-30T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-07-30T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-07-30T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-07-30T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-07-30T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-07-30T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-07-30T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-07-30T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-07-30T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-07-30T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0000000000000002


Date: 2022-08-06T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-08-06T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-08-06T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-08-06T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-08-06T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-08-06T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-08-06T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-08-06T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-08-06T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-08-06T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-08-13T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-08-13T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-08-13T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-08-13T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-08-13T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-08-13T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-08-13T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-08-13T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-08-13T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-08-13T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-08-20T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-08-20T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-08-20T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-08-20T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-08-20T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-08-20T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-08-20T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-08-20T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-08-20T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-08-20T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-08-27T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-08-27T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-08-27T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-08-27T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-08-27T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-08-27T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-08-27T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-08-27T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-08-27T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-08-27T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-09-03T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-09-03T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-09-03T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-09-03T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-09-03T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-09-03T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-09-03T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-09-03T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-09-03T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-09-03T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-09-10T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-09-10T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-09-10T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-09-10T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-09-10T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-09-10T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-09-10T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-09-10T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-09-10T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-09-10T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-09-17T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-09-17T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-09-17T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-09-17T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-09-17T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-09-17T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-09-17T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-09-17T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-09-17T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-09-17T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-09-24T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-09-24T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-09-24T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-09-24T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-09-24T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-09-24T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-09-24T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-09-24T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-09-24T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-09-24T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-10-01T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-01T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-10-01T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-10-01T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-10-01T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-10-01T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-10-01T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-10-01T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-10-01T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-10-01T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-10-08T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-10-08T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-10-08T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-08T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-08T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-10-08T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-10-08T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-08T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-08T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-08T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-10-15T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-10-15T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-10-15T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-10-15T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-15T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-10-15T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-15T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-10-15T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-10-15T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-15T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0000000000000002


Date: 2022-10-22T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-10-22T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-10-22T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-10-22T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-22T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-10-22T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-10-22T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-22T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-22T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-10-22T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-10-29T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-10-29T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-10-29T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-10-29T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-10-29T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-10-29T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-10-29T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-10-29T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-10-29T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-10-29T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-11-05T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-11-05T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-11-05T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-11-05T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-11-05T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-11-05T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-11-05T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-11-05T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-11-05T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-11-05T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-11-12T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-11-12T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-11-12T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-11-12T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-11-12T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-11-12T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-11-12T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-11-12T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-11-12T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-11-12T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-11-19T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-11-19T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-11-19T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-11-19T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-11-19T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-11-19T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-11-19T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-11-19T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-11-19T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-11-19T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0000000000000002


Date: 2022-11-26T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-11-26T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-11-26T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-11-26T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0

Date: 2022-11-26T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-11-26T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-11-26T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-11-26T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-11-26T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-11-26T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-12-03T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-12-03T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-12-03T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-12-03T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-12-03T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-12-03T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-12-03T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-12-03T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-12-03T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-12-03T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-12-10T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-12-10T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-12-10T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-12-10T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-12-10T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-12-10T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-12-10T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-12-10T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-12-10T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-12-10T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-12-17T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-12-17T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-12-17T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-12-17T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-12-17T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-12-17T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-12-17T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-12-17T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-12-17T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 0.9999999999999998
Date: 2022-12-17T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999


Date: 2022-12-24T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-12-24T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-12-24T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-12-24T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-12-24T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-12-24T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-12-24T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-12-24T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 1.0
Date: 2022-12-24T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0
Date: 2022-12-24T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 1.0


Date: 2022-12-31T00:00:00.000000000, Region: 1, Total Sum of Normalized Shares 1.0
Date: 2022-12-31T00:00:00.000000000, Region: 10, Total Sum of Normalized Shares 1.0
Date: 2022-12-31T00:00:00.000000000, Region: 2, Total Sum of Normalized Shares 1.0
Date: 2022-12-31T00:00:00.000000000, Region: 3, Total Sum of Normalized Shares 1.0
Date: 2022-12-31T00:00:00.000000000, Region: 4, Total Sum of Normalized Shares 1.0
Date: 2022-12-31T00:00:00.000000000, Region: 5, Total Sum of Normalized Shares 1.0
Date: 2022-12-31T00:00:00.000000000, Region: 6, Total Sum of Normalized Shares 1.0
Date: 2022-12-31T00:00:00.000000000, Region: 7, Total Sum of Normalized Shares 0.9999999999999999
Date: 2022-12-31T00:00:00.000000000, Region: 8, Total Sum of Normalized Shares 1.0000000000000002
Date: 2022-12-31T00:00:00.000000000, Region: 9, Total Sum of Normalized Shares 0.9999999999999999

### HHS to State Mapping

In [11]:
df_imputed_select

            date  hhs_region  variant     share  normalized_share
0     2021-01-02           1    A.2.5  0.000000          0.000000
1     2021-01-02           1     AY.1  0.000000          0.000000
2     2021-01-02           1     AY.2  0.000000          0.000000
3     2021-01-02           1     AY.3  0.000000          0.000000
4     2021-01-02           1      B.1  0.215363          0.215363
...          ...         ...      ...       ...               ...
56595 2022-12-31           9      P.1  0.000000          0.000000
56596 2022-12-31           9      P.2  0.000000          0.000000
56597 2022-12-31           9      R.1  0.000000          0.000000
56598 2022-12-31           9      XBB  0.075548          0.075548
56599 2022-12-31           9  XBB.1.5  0.091676          0.091676

[51500 rows x 5 columns]

In [12]:
hhs_data_path = "../data/hhs_regions.csv"
hhs_df = pd.read_csv(hhs_data_path, low_memory=False)
hhs_region_state_df = hhs_df[["region_number", "state_or_territory"]]

In [13]:
df_variant_share_by_state = pd.merge(left=df_imputed_select, right=hhs_region_state_df, how='left', left_on="hhs_region", right_on="region_number")
df_variant_share_by_state = df_variant_share_by_state[["date","hhs_region", "state_or_territory", "variant", "normalized_share"]]
df_variant_share_by_state = df_variant_share_by_state.rename(columns={"state_or_territory":"state", "normalized_share":"normalized_variant_share"})
df_variant_share_by_state["variant"] = "Variant % " + df_variant_share_by_state["variant"]
df_variant_share_by_state = df_variant_share_by_state.pivot_table(index=["date","hhs_region","state"], columns="variant", values="normalized_variant_share").reset_index()
df_variant_share_by_state.to_csv("../data/normalized_variant_share_by_date_and_state.csv", index=False)

In [14]:
df_variant_share_by_state

variant,date,hhs_region,state,Variant % A.2.5,Variant % AY.1,Variant % AY.2,Variant % AY.3,Variant % B.1,Variant % B.1.1,Variant % B.1.1.194,...,Variant % BF.7,Variant % BN.1,Variant % BQ.1,Variant % BQ.1.1,Variant % Other,Variant % P.1,Variant % P.2,Variant % R.1,Variant % XBB,Variant % XBB.1.5
0,2021-01-02,1,Connecticut,0.0,0.0,0.0,0.0,0.215363,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.337252,0.0,0.0,0.0,0.000000,0.000000
1,2021-01-02,1,Maine,0.0,0.0,0.0,0.0,0.215363,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.337252,0.0,0.0,0.0,0.000000,0.000000
2,2021-01-02,1,Massachusetts,0.0,0.0,0.0,0.0,0.215363,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.337252,0.0,0.0,0.0,0.000000,0.000000
3,2021-01-02,1,New Hampshire,0.0,0.0,0.0,0.0,0.215363,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.337252,0.0,0.0,0.0,0.000000,0.000000
4,2021-01-02,1,Rhode Island,0.0,0.0,0.0,0.0,0.215363,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.337252,0.0,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6072,2022-12-31,9,Republic of Palau,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.025809,0.041958,0.309209,0.370465,0.000470,0.0,0.0,0.0,0.075548,0.091676
6073,2022-12-31,10,Alaska,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.034255,0.039383,0.222777,0.386609,0.000484,0.0,0.0,0.0,0.035565,0.182380
6074,2022-12-31,10,Idaho,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.034255,0.039383,0.222777,0.386609,0.000484,0.0,0.0,0.0,0.035565,0.182380
6075,2022-12-31,10,Oregon,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.034255,0.039383,0.222777,0.386609,0.000484,0.0,0.0,0.0,0.035565,0.182380
6076,2022-12-31,10,Washington,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.034255,0.039383,0.222777,0.386609,0.000484,0.0,0.0,0.0,0.035565,0.182380

### State to County Mapping

In [15]:
fips_list_path = "../data/fips-list.csv"
fips_list = pd.read_csv(fips_list_path, low_memory=False)
fips_list

       fips         county           state
0      1001        Autauga         Alabama
1      1003        Baldwin         Alabama
2      1005        Barbour         Alabama
3      1007           Bibb         Alabama
4      1009         Blount         Alabama
...     ...            ...             ...
3231  72153          Yauco     Puerto Rico
3232  78010      St. Croix  Virgin Islands
3233  78020       St. John  Virgin Islands
3234  78030     St. Thomas  Virgin Islands
3235  99999  New York City        New York

[3236 rows x 3 columns]

In [16]:
df_variant_share_by_fips = pd.merge(left=fips_list, right=df_variant_share_by_state, how='left', on="state")
df_variant_share_by_fips.to_csv("../data/df_variant_share_by_fips.csv", index=False)
df_variant_share_by_fips

,fips,county,state,date,hhs_region,Variant % A.2.5,Variant % AY.1,Variant % AY.2,Variant % AY.3,Variant % B.1,...,Variant % BF.7,Variant % BN.1,Variant % BQ.1,Variant % BQ.1.1,Variant % Other,Variant % P.1,Variant % P.2,Variant % R.1,Variant % XBB,Variant % XBB.1.5
0,1001,Autauga,Alabama,2021-01-02,4.0,0.000000,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.000000,0.000000,0.240098,0.00000,0.010343,0.00000,0.000000,0.000000
1,1001,Autauga,Alabama,2021-01-16,4.0,0.000000,0.0,0.0,0.0,0.052789,...,0.000000,0.000000,0.000000,0.000000,0.235318,0.00000,0.007352,0.00000,0.000000,0.000000
2,1001,Autauga,Alabama,2021-01-30,4.0,0.003891,0.0,0.0,0.0,0.026768,...,0.000000,0.000000,0.000000,0.000000,0.479922,0.00000,0.002132,0.00080,0.000000,0.000000
3,1001,Autauga,Alabama,2021-02-06,4.0,0.001265,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.858039,0.00000,0.000000,0.00000,0.000000,0.000000
4,1001,Autauga,Alabama,2021-02-13,4.0,0.000843,0.0,0.0,0.0,0.024583,...,0.000000,0.000000,0.000000,0.000000,0.501443,0.00035,0.005559,0.00205,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332895,99999,New York City,New York,2022-12-03,2.0,0.000000,0.0,0.0,0.0,0.000000,...,0.037494,0.022823,0.339862,0.306883,0.000642,0.00000,0.000000,0.00000,0.041575,0.067101
332896,99999,New York City,New York,2022-12-10,2.0,0.000000,0.0,0.0,0.0,0.000000,...,0.024744,0.024744,0.270167,0.349265,0.002942,0.00000,0.000000,0.00000,0.068348,0.133780
332897,99999,New York City,New York,2022-12-17,2.0,0.000000,0.0,0.0,0.0,0.000000,...,0.021161,0.016263,0.238384,0.278654,0.000370,0.00000,0.000000,0.00000,0.050601,0.314298
332898,99999,New York City,New York,2022-12-24,2.0,0.000000,0.0,0.0,0.0,0.000000,...,0.012052,0.011100,0.163023,0.205172,0.000180,0.00000,0.000000,0.00000,0.039109,0.523029
332899,99999,New York City,New York,2022-12-31,2.0,0.000000,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.092470,0.125267,0.000072,0.00000,0.000000,0.00000,0.025083,0.721664

### Fill in the missing days in between every 2 weeks with the previous week's values

In [17]:
date_range = pd.date_range(unique_dates[0],unique_dates[-1])
unique_fips = pd.unique(df_variant_share_by_fips["fips"])

In [18]:
df_dates = pd.DataFrame({"date":date_range})
df_fips = pd.DataFrame({"fips":unique_fips})
df_all_dates_fips = pd.merge(left=df_dates, right=df_fips, how="cross")
df_all_dates_fips_imputted = pd.merge(left=df_all_dates_fips, right=df_variant_share_by_fips, how="left", on=["date","fips"])
df_all_dates_fips_imputted = df_all_dates_fips_imputted.sort_values(by=["date", "fips"], ascending=[True,True])

# Group by FIPS, while being sorted by dates, and then forward fill
COVID_Variants_Normalized_Share_All_Dates_FIPS = df_all_dates_fips_imputted.fillna(df_all_dates_fips_imputted.groupby(["fips"]).ffill())

COVID_Variants_Normalized_Share_All_Dates_FIPS.to_csv("../data/COVID_Variants_Normalized_Share_All_Dates_FIPS.csv", index=False)
COVID_Variants_Normalized_Share_All_Dates_FIPS

,date,fips,county,state,hhs_region,Variant % A.2.5,Variant % AY.1,Variant % AY.2,Variant % AY.3,Variant % B.1,...,Variant % BF.7,Variant % BN.1,Variant % BQ.1,Variant % BQ.1.1,Variant % Other,Variant % P.1,Variant % P.2,Variant % R.1,Variant % XBB,Variant % XBB.1.5
0,2021-01-02,1001,Autauga,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
1,2021-01-02,1003,Baldwin,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
2,2021-01-02,1005,Barbour,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
3,2021-01-02,1007,Bibb,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
4,2021-01-02,1009,Blount,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2359039,2022-12-31,72153,Yauco,Puerto Rico,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664
2359040,2022-12-31,78010,St. Croix,Virgin Islands,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664
2359041,2022-12-31,78020,St. John,Virgin Islands,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664
2359042,2022-12-31,78030,St. Thomas,Virgin Islands,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664
2359043,2022-12-31,99999,New York City,New York,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664

### Obtain Dates of Project

In [19]:
dataF_path = "../data/augmented_us-counties-states_latest.csv"
dataF = pd.read_csv(dataF_path, low_memory=False)
dataF["date"] = pd.to_datetime(dataF["date"])
dataF

,fips,date,county,state,cases,deaths,datetime,days_from_start,rolled_cases,LAT,...,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease,metrics.testPositivityRatio,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio
0,1001,2022-11-25,Autauga,Alabama,101,230,2022-11-25,1039,89.571429,32.532237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1001,2020-12-20,Autauga,Alabama,1006,44,2020-12-20,334,881.142857,32.532237,...,NaN,82020.0,NaN,1783890.0,8462.0,NaN,0.0,0.256,0.000,0.000
2,1001,2021-02-05,Autauga,Alabama,749,76,2021-02-05,381,802.571429,32.532237,...,NaN,140376.0,NaN,2149684.0,0.0,NaN,0.0,0.156,0.043,0.010
3,1001,2021-10-03,Autauga,Alabama,534,142,2021-10-03,621,620.285714,32.532237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.118,0.431,0.340
4,1001,2022-01-08,Autauga,Alabama,1195,162,2022-01-08,718,880.428571,32.532237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.435,0.487,0.388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3132585,99999,2021-04-28,New York City,New York,56198,32461,2021-04-28,463,62164.428571,40.658566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3132586,99999,2022-04-27,New York City,New York,48728,40184,2022-04-27,827,46966.142857,40.658566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3132587,99999,2022-08-14,New York City,New York,78078,41322,2022-08-14,936,84349.571429,40.658566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3132588,99999,2022-09-03,New York City,New York,49884,41616,2022-09-03,956,56297.571429,40.658566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3132589,99999,2022-03-19,New York City,New York,15729,40022,2022-03-19,788,16636.714286,40.658566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Back Fill from Beginning of Variants Dataset to Start of Project Date

In [20]:
project_start_date = dataF["date"].min()
COVID_variants_end_date = date_range[-1]
print("project_start_date: {}, COVID_variants_end_date: {}".format(project_start_date, COVID_variants_end_date))

backfill_date_range = pd.date_range(project_start_date, COVID_variants_end_date)
backfill_date_range

project_start_date: 2020-01-27 00:00:00, COVID_variants_end_date: 2022-12-31 00:00:00

DatetimeIndex(['2020-01-27', '2020-01-28', '2020-01-29', '2020-01-30',
               '2020-01-31', '2020-02-01', '2020-02-02', '2020-02-03',
               '2020-02-04', '2020-02-05',
               ...
               '2022-12-22', '2022-12-23', '2022-12-24', '2022-12-25',
               '2022-12-26', '2022-12-27', '2022-12-28', '2022-12-29',
               '2022-12-30', '2022-12-31'],
              dtype='datetime64[ns]', length=1070, freq='D')

In [21]:
df_backfill_dates = pd.DataFrame({"date":backfill_date_range})
df_fips = pd.DataFrame({"fips":unique_fips})
df_backfill_dates_fips = pd.merge(left=df_backfill_dates, right=df_fips, how="cross")
df_backfilled_COVID_Variants_Normalized_Share_All_Dates_FIPS = pd.merge(left=df_backfill_dates_fips, right=COVID_Variants_Normalized_Share_All_Dates_FIPS, how="left", on=["date","fips"])
df_backfilled_COVID_Variants_Normalized_Share_All_Dates_FIPS = df_backfilled_COVID_Variants_Normalized_Share_All_Dates_FIPS.sort_values(by=["date", "fips"], ascending=[True,True])

df_backfilled_COVID_Variants_Normalized_Share_All_Dates_FIPS = df_backfilled_COVID_Variants_Normalized_Share_All_Dates_FIPS.fillna(df_backfilled_COVID_Variants_Normalized_Share_All_Dates_FIPS.groupby(["fips"]).bfill())
df_backfilled_COVID_Variants_Normalized_Share_All_Dates_FIPS

,date,fips,county,state,hhs_region,Variant % A.2.5,Variant % AY.1,Variant % AY.2,Variant % AY.3,Variant % B.1,...,Variant % BF.7,Variant % BN.1,Variant % BQ.1,Variant % BQ.1.1,Variant % Other,Variant % P.1,Variant % P.2,Variant % R.1,Variant % XBB,Variant % XBB.1.5
0,2020-01-27,1001,Autauga,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
1,2020-01-27,1003,Baldwin,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
2,2020-01-27,1005,Barbour,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
3,2020-01-27,1007,Bibb,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
4,2020-01-27,1009,Blount,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3462515,2022-12-31,72153,Yauco,Puerto Rico,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664
3462516,2022-12-31,78010,St. Croix,Virgin Islands,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664
3462517,2022-12-31,78020,St. John,Virgin Islands,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664
3462518,2022-12-31,78030,St. Thomas,Virgin Islands,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664
3462519,2022-12-31,99999,New York City,New York,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664

### Forward Fill from End of Variants Dataset to Current Date

In [22]:
current_date = dataF["date"].max()
print("Project Start Date: {}, Current Date for Update: {}".format(project_start_date, current_date))

forwardfill_date_range = pd.date_range(project_start_date, current_date)
forwardfill_date_range

Project Start Date: 2020-01-27 00:00:00, Current Date for Update: 2022-12-31 00:00:00

DatetimeIndex(['2020-01-27', '2020-01-28', '2020-01-29', '2020-01-30',
               '2020-01-31', '2020-02-01', '2020-02-02', '2020-02-03',
               '2020-02-04', '2020-02-05',
               ...
               '2022-12-22', '2022-12-23', '2022-12-24', '2022-12-25',
               '2022-12-26', '2022-12-27', '2022-12-28', '2022-12-29',
               '2022-12-30', '2022-12-31'],
              dtype='datetime64[ns]', length=1070, freq='D')

In [23]:
df_forwardfill_dates = pd.DataFrame({"date":forwardfill_date_range})
df_fips = pd.DataFrame({"fips":unique_fips})
df_forwardfill_dates_fips = pd.merge(left=df_forwardfill_dates, right=df_fips, how="cross")
df_ffill_bfill_COVID_Variants_Normalized_Share_All_Dates_FIPS = pd.merge(left=df_forwardfill_dates_fips, right=df_backfilled_COVID_Variants_Normalized_Share_All_Dates_FIPS, how="left", on=["date","fips"])
df_ffill_bfill_COVID_Variants_Normalized_Share_All_Dates_FIPS = df_ffill_bfill_COVID_Variants_Normalized_Share_All_Dates_FIPS.sort_values(by=["date", "fips"], ascending=[True,True])

df_ffill_bfill_COVID_Variants_Normalized_Share_All_Dates_FIPS = df_ffill_bfill_COVID_Variants_Normalized_Share_All_Dates_FIPS.fillna(df_ffill_bfill_COVID_Variants_Normalized_Share_All_Dates_FIPS.groupby(["fips"]).ffill())
df_ffill_bfill_COVID_Variants_Normalized_Share_All_Dates_FIPS.to_csv("../data/df_ffill_bfill_COVID_Variants_Normalized_Share_All_Dates_FIPS.csv", index=False)
df_ffill_bfill_COVID_Variants_Normalized_Share_All_Dates_FIPS

,date,fips,county,state,hhs_region,Variant % A.2.5,Variant % AY.1,Variant % AY.2,Variant % AY.3,Variant % B.1,...,Variant % BF.7,Variant % BN.1,Variant % BQ.1,Variant % BQ.1.1,Variant % Other,Variant % P.1,Variant % P.2,Variant % R.1,Variant % XBB,Variant % XBB.1.5
0,2020-01-27,1001,Autauga,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
1,2020-01-27,1003,Baldwin,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
2,2020-01-27,1005,Barbour,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
3,2020-01-27,1007,Bibb,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
4,2020-01-27,1009,Blount,Alabama,4.0,0.0,0.0,0.0,0.0,0.053232,...,0.000000,0.000000,0.00000,0.000000,0.240098,0.0,0.010343,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3462515,2022-12-31,72153,Yauco,Puerto Rico,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664
3462516,2022-12-31,78010,St. Croix,Virgin Islands,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664
3462517,2022-12-31,78020,St. John,Virgin Islands,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664
3462518,2022-12-31,78030,St. Thomas,Virgin Islands,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664
3462519,2022-12-31,99999,New York City,New York,2.0,0.0,0.0,0.0,0.0,0.000000,...,0.005696,0.006282,0.09247,0.125267,0.000072,0.0,0.000000,0.0,0.025083,0.721664

### Merge with `augmented_us-counties-states_latest.csv`

In [24]:
augmented_us = pd.merge(left=dataF, right=df_ffill_bfill_COVID_Variants_Normalized_Share_All_Dates_FIPS, on=["date","fips"], how="left")
augmented_us.to_csv(dataF_path, index=False)
augmented_us

,fips,date,county_x,state_x,cases,deaths,datetime,days_from_start,rolled_cases,LAT,...,Variant % BF.7,Variant % BN.1,Variant % BQ.1,Variant % BQ.1.1,Variant % Other,Variant % P.1,Variant % P.2,Variant % R.1,Variant % XBB,Variant % XBB.1.5
0,1001,2022-11-25,Autauga,Alabama,101,230,2022-11-25,1039,89.571429,32.532237,...,0.082753,0.030092,0.189461,0.246416,0.000000,0.000000,0.000000,0.000000,0.011752,0.000476
1,1001,2020-12-20,Autauga,Alabama,1006,44,2020-12-20,334,881.142857,32.532237,...,0.000000,0.000000,0.000000,0.000000,0.240098,0.000000,0.010343,0.000000,0.000000,0.000000
2,1001,2021-02-05,Autauga,Alabama,749,76,2021-02-05,381,802.571429,32.532237,...,0.000000,0.000000,0.000000,0.000000,0.479922,0.000000,0.002132,0.000800,0.000000,0.000000
3,1001,2021-10-03,Autauga,Alabama,534,142,2021-10-03,621,620.285714,32.532237,...,0.000000,0.000000,0.000000,0.000000,0.012255,0.000000,0.000000,0.000000,0.000000,0.000000
4,1001,2022-01-08,Autauga,Alabama,1195,162,2022-01-08,718,880.428571,32.532237,...,0.000000,0.000000,0.000000,0.000000,0.003592,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3132585,99999,2021-04-28,New York City,New York,56198,32461,2021-04-28,463,62164.428571,40.658566,...,0.000000,0.000000,0.000000,0.000000,0.116236,0.021284,0.000000,0.004324,0.000000,0.000000
3132586,99999,2022-04-27,New York City,New York,48728,40184,2022-04-27,827,46966.142857,40.658566,...,0.000000,0.000000,0.000000,0.000000,0.000934,0.000000,0.000000,0.000000,0.000000,0.000000
3132587,99999,2022-08-14,New York City,New York,78078,41322,2022-08-14,936,84349.571429,40.658566,...,0.003231,0.000000,0.000000,0.000000,0.001408,0.000000,0.000000,0.000000,0.000000,0.000000
3132588,99999,2022-09-03,New York City,New York,49884,41616,2022-09-03,956,56297.571429,40.658566,...,0.011722,0.000000,0.001689,0.000000,0.001727,0.000000,0.000000,0.000000,0.000000,0.000000
3132589,99999,2022-03-19,New York City,New York,15729,40022,2022-03-19,788,16636.714286,40.658566,...,0.000000,0.000000,0.000000,0.000000,0.000849,0.000000,0.000000,0.000000,0.000000,0.000000